import {digest,canonical} from '../../vendor/dynamic-assets/runtime/core.mjs';
import {encodePackage,decodePackage} from '../../src/dynamic-assets/wire.mjs';
import {fail} from './policy.mjs';
export const WORLD='e78df027-7ef4-4d49-82eb-ea91f03d9fb3';
const prefix='kit_harbor.';
export function createPgAssetStore({pool,policy,now=Date.now}){
 const params=k=>[WORLD,k.owner,k.sessionId,k.roomId];
 async function transaction(key,fn){const c=await pool.connect();try{await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='2s'");await c.query("SET LOCAL statement_timeout='5s'");const w=(await c.query(`SELECT id FROM ${prefix}worlds WHERE world_id=$1 AND game_id=$1 AND environment='test'`,[WORLD])).rows[0];if(!w)fail('ASSET_WORLD_SCOPE');await c.query('SELECT pg_advisory_xact_lock($1::bigint)',[w.id]);const e=policy.assert(key.owner,key.sessionId);const j=(await c.query(`SELECT * FROM ${prefix}async_journeys WHERE world=$1 AND owner=$2 AND id=$3 FOR UPDATE`,[WORLD,key.owner,key.sessionId])).rows[0];if(!j||j.enrollment!==e.enrollment)fail('ASSET_OWNER_DENIED');const h=JSON.parse(j.data);if(h.scene!==key.roomId)fail('ROOM_ASSET_SCOPE_DENIED');const out=await fn(c,h);await c.query('COMMIT');return out}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e}finally{c.release()}}
 const load=async(q,k)=>{const r=(await q.query(`SELECT g.*,p.body FROM ${prefix}harbor_asset_grants g JOIN ${prefix}harbor_asset_packages p USING(package_hash) WHERE g.world=$1 AND g.owner=$2 AND g.session=$3 AND g.room=$4`,params(k))).rows[0];if(!r)return null;if(r.revoked_at)fail('ASSET_GRANT_REVOKED');const record=decodePackage({...r.body,grant:r.grant,grantHash:r.grant_hash});return {...record,packageHash:r.package_hash,leaseRevision:Number(r.lease_revision)}};
 const attachment=r=>({format:'harbor-dynamic-attachment-v1',packageHash:r.packageHash,roomHash:r.grant.room.hash,templateHash:r.grant.template.hash,consumerId:r.grant.scope.consumerId,grantHash:r.grantHash,leaseRevision:r.leaseRevision,scope:r.grant.scope});
 async function sidecar(c,k,r){await c.query(`INSERT INTO ${prefix}async_media(world,session,slot,data) VALUES($1,$2,$3,$4) ON CONFLICT(world,session,slot) DO UPDATE SET data=EXCLUDED.data`,[WORLD,k.sessionId,'library:'+k.roomId,JSON.stringify(attachment(r))])}
 return Object.freeze({attachment,
  get:async k=>{policy.assert(k.owner,k.sessionId);return load(pool,k)},
  async putIfAbsent(k,r){return transaction(k,async c=>{const old=await load(c,k);if(old)return old;const wire=encodePackage(r),{grant,grantHash,...body}=wire;const packageHash=await digest({...body,room:grant.room,template:grant.template});const byteCount=r.packaged.reduce((n,[,b])=>n+b.length,0)+r.manifests.reduce((n,[,b])=>n+b.length,0);await c.query(`INSERT INTO ${prefix}harbor_asset_packages(package_hash,room_hash,template_hash,profile_hash,template_id,template_version,body,byte_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(package_hash) DO NOTHING`,[packageHash,grant.room.hash,grant.template.hash,grant.scope.profile.hash,grant.scope.templateId,grant.scope.templateVersion,body,byteCount]);const saved=(await c.query(`SELECT body FROM ${prefix}harbor_asset_packages WHERE package_hash=$1`,[packageHash])).rows[0];if(canonical(saved.body)!==canonical(body))fail('ASSET_PACKAGE_CONFLICT',409);await c.query(`INSERT INTO ${prefix}harbor_asset_grants(world,owner,session,room,consumer_id,package_hash,"grant",grant_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[...params(k),grant.scope.consumerId,packageHash,grant,grantHash,grant.expiresAt]);const result={...r,packageHash,leaseRevision:1};await sidecar(c,k,result);return result})},
  async renew(k,previous,r){return transaction(k,async c=>{const old=await load(c,k);if(!old)fail('ROOM_ASSETS_NOT_PREPARED',404);if(old.grantHash!==previous)return old;const result={...r,packageHash:old.packageHash,leaseRevision:old.leaseRevision+1};await c.query(`UPDATE ${prefix}harbor_asset_grants SET "grant"=$5,grant_hash=$6,lease_revision=$7,expires_at=$8,updated_at=now() WHERE world=$1 AND owner=$2 AND session=$3 AND room=$4`,[...params(k),r.grant,r.grantHash,result.leaseRevision,r.grant.expiresAt]);await sidecar(c,k,result);return result})},
  async attachments(owner,id){const rows=(await pool.query(`SELECT m.data FROM ${prefix}async_media m JOIN ${prefix}async_journeys j ON j.world=m.world AND j.id=m.session WHERE m.world=$1 AND m.session=$2 AND j.owner=$3 AND m.slot LIKE 'library:%'`,[WORLD,id,owner])).rows;return rows.map(r=>JSON.parse(r.data))}
 });
}
