/** Paired StoryCartridge source. Spatial transactions remain in the audited adapter;
 * importing this into the text shell alone is intentionally not supported. */
import type {StoryCartridge,Locale} from './cartridge-types';
import {rooms,people,tx} from '../world/data';import {GAME_UUID} from '../game-id';
const opening=[['你刚下长途汽车，肩上只有一只旅行包。上一份工作告一段落，你给自己留了一个夏天，来到这个从没住过的海湾小镇。没有紧急任务，也没有人等着你拯救什么。先安顿下来，认识几个人，看看自己想把日子过成什么样。','The bus pulls away. You have one bag and a whole summer between jobs. You have never lived in this little harbor town before. Nothing urgent is waiting for you. Find a room, meet a few people, and see what kind of days you want to make.'],['你提前租了一间小屋。约好的房东正在街边等你，手里晃着一串钥匙。用左下角的摇杆走过去，也可以点地面行走。靠近她以后，右下角会出现谈话按钮。','You arranged a room before arriving. Your landlady is waiting along the street, turning a key in her hand. Use the round stick at the bottom left, or tap the ground to walk. When you are close enough, the action button will let you say hello.']] as const;
function make(locale:Locale):StoryCartridge{return {
 schemaVersion:1,id:GAME_UUID,locale,coverImage:'./poster.png',entryImage:'./poster.png',
 copy:{title:tx(['海湾新生活','A Summer in Harbor'],locale),subtitle:tx(['第一个夏天','Your first summer'],locale),promise:tx(['认识海湾，也找到自己的节奏。','Get to know the bay, and find your own pace.'],locale),enter:tx(['走进小镇','Step into town'],locale),continue:tx(['继续这个夏天','Continue your summer'],locale),customAction:tx(['自由询问','Ask a question'],locale),itemImagingTitle:tx(['细节正在显现','The details are taking shape'],locale),itemImagingBody:tx(['可以先查看线索。','You can read the clues now.'],locale)},
 theme:{outer:'#183f40',surface:'#2d4a46',paper:'#fff5df',ink:'#183f40',muted:'#64726e',accent:'#327e91',danger:'#bc674c',gold:'#e7bb70',material:'harbor'},
 audioTheme:{material:'harbor',bpm:76,rootHz:130.81,scale:[0,2,4,7,9],levels:{music:1,ambient:0,sfx:.7,master:.22},tension:[],recorded:{music:{src:'./audio/town-a.mp3',gain:1},ambienceByLocationId:{harbor:{src:'./audio/coast.mp3',gain:1},coast:{src:'./audio/coast.mp3',gain:1},hill:{src:'./audio/hill.mp3',gain:1}}}},
 statDefinitions:[{id:'energy',label:tx(['体力','Energy'],locale),min:0,max:100,initial:100,display:'bar',maxDelta:100,description:tx(['修桥和垂钓消耗体力；家中休息免费恢复。低于10不能修桥，仍可走动。','Repairs and fishing use energy. Rest at home for free. Below ten, bridge repairs wait; walking remains free.'],locale)},{id:'cash',label:tx(['现金','Cash'],locale),min:0,max:999,initial:25,display:'number',unit:'$',maxDelta:999,description:tx(['美元。点心4元，卖鱼6元；主线不要求付费。','US dollars. A snack costs four; a fish earns six. The main route never requires payment.'],locale)},{id:'standing',label:tx(['口碑','Reputation'],locale),min:0,max:100,initial:0,display:'bar',maxDelta:100,description:tx(['帮助街坊与完成练习后提高，不决定是否可以探索。','Grows by helping neighbors and completing practice. It never blocks exploration.'],locale)}],
 drawerLabels:{party:tx(['认识的人','People you know'],locale),map:tx(['海湾地图','Around the bay'],locale),inventory:tx(['行囊','Your bag'],locale),log:tx(['旅行手记','Your journal'],locale)},
 opening:{location:tx(rooms.station.title,locale),time:tx(['夏初 · 午后','Early summer · Afternoon'],locale),objective:tx(['和提着钥匙的女士打个招呼。','Say hello to the woman with the keys.'],locale),imagePrompt:'A newcomer arrives on a modest North American coastal street in summer.',blocks:opening.map((pair,i)=>({id:'arrival-'+i,kind:'narration',text:pair[locale==='zh'?0:1]})),choices:[{id:'meet-mara',label:tx(['走过去打个招呼','Go and say hello'],locale)}]},
 characters:Object.entries(people).map(([id,p])=>({id,name:tx(p.name,locale),role:tx(p.unknown,locale),detail:tx(p.intro,locale),vitality:100,stress:0,skills:[],hiddenUntilIntroduced:true})),initialMap:Object.values(rooms).map(r=>({id:r.id,label:tx(r.title,locale),current:r.id==='station',visited:r.id==='station',connectedTo:r.area===r.id?undefined:r.area})),initialInventory:[],initialFacts:{key:false,unpacked:false,'market-open':false},demoTurns:[],
 director:{mode:'open-world',maxActiveThreads:3,choiceIntents:locale==='zh'?['了解身边的人','亲手尝试一件事','走向另一个地方']:['Get to know someone','Try something hands-on','Explore another place'],fixedWorldRules:locale==='zh'?['现代北美海湾小镇。美元经济。','先在可见对话登场，再显示角色名字。','任务结果只由空间适配器和权威状态确认。']:['A modern North American harbor town, using US dollars.','Introduce people visibly before showing their names.','Only the spatial adapter and authority confirm persistent outcomes.'],generationRules:locale==='zh'?['只从已读线索生成两代补充观察地点。','不得发物品、改变主线或创造未知角色。']:['Generate at most two side spaces from already read evidence.','No item awards, mainline changes or unseen named people.']},
 domainRules:{rules:Object.values(rooms).flatMap(r=>r.entities.filter(e=>e.destination).map(e=>({id:r.id+'/'+e.id+'/travel',intent:tx(e.label,locale),match:[r.id+'/'+e.id+'/travel'],matchMode:'exact' as const,requirements:[{type:'map' as const,nodeId:r.id,reason:tx(['先走到入口所在地点。','Walk to the place containing the entrance.'],locale)}],effects:[{type:'map' as const,nodeId:e.destination!}],successText:tx(['你从入口前往下一处。','You pass through to the next place.'],locale),successChoices:[]})))},
}}
export const harborZh=make('zh'),harborEn=make('en');
export const cartridge=(locale:Locale)=>locale==='zh'?harborZh:harborEn;
export const spatialAdapterContract={version:1,required:true,authority:'Story Session',mainTransactions:'src/story/state.ts',binding:'src/story/binding.ts',generatedRules:'server/fieldnotes.ts',movementEngine:'RPGJS 5 beta34',chapterCompletion:'market-open',finalEnding:false,notes:'Cartridge map rules describe physical links. Do not execute them without proximity, admission, journey flags and the server adapter.'};
