import {nextRoles} from '../world/next-residents';
import {nextStoryLeads} from './next-neighbors';
import {residentRoutes,openingNotice} from '../world/residents';
import {newsMemory} from './town-news';
import {people,rooms,type Words} from '../world/data';
import type {Save} from './state';
import {questProgress} from './progress';

export type StoryLead={id:string;title:Words;people:string[];state:'active'|'done'|'upcoming'|'available'|'return-later';summary:Words;next?:Words;place?:string};
const roles:Record<string,Words>={...nextRoles,mara:['你的房东，住在海湾多年。','Your landlady, a longtime local.'],theo:['潮间咖啡馆的店员。','Works at Tide & Table.'],june:['经营修理铺，熟悉镇上的修修补补。','Runs the workshop and knows the town’s repairs.'],idris:['港口拳馆的教练。','Coach at Harbor Boxing Club.'],ruth:['常在码头钓鱼。','An angler at the pier.'],luis:['街角杂货铺的店主。','Runs the Corner Grocer.'],nell:['经营旧物店，保存老照片。','Keeps old photographs at Second Chances.'],elena:['庭院的住户，照顾花草和家人。','A courtyard resident who cares for the garden and her family.'],arthur:['曾在气象站工作。','Formerly worked at the weather station.'],avery:['送包裹之余，喜欢随手画画。','Delivers parcels and sketches in their spare time.'],samira:['在学校食堂工作，喜欢轻声哼歌。','Works in the school kitchen and enjoys humming.'],owen:['退休的公交车修理工，喜欢听海鸟。','A retired bus mechanic who listens for seabirds.'],dani:['在图书馆工作，记录街坊的花园故事。','Works at the library and collects neighbors’ garden stories.']};
/** No migration writes. Only encountered identities and explicit interaction facts count. */
export function knownPeople(s:Save,registry=people){
 const ids=new Set(s.known);
 for(const entry of s.history)if(entry.person)ids.add(entry.person);
 for(const flag of s.flags){const match=/^talk:([^:]+):/.exec(flag);if(match)ids.add(match[1]);}
 if(s.flags.includes('key')||s.flags.includes('bag-returned'))ids.add('mara');
 if(s.items.toolkit>0)ids.add('june');
 if(s.flags.includes('garden-agreed'))ids.add('elena');
 return Object.keys(registry).filter(id=>ids.has(id));
}
/** Shares completion precedence with dialogue. No UI-only quest completion flags. */
export function relationshipStory(s:Save,registry=people){
 const known=knownPeople(s,registry),k=new Set(known),f=(v:string)=>s.flags.includes(v),q=questProgress(s),leads:StoryLead[]=[];
 const add=(v:StoryLead)=>{if(v.place&&v.next&&openingNotice(v.place,s)){const n=openingNotice(v.place,s)!;v.next=[v.next[0]+' '+n[0],v.next[1]+' '+n[1]]}v.people=v.people.filter(id=>k.has(id));if(v.people.length)leads.push(v)};
 if(k.has('mara'))add({id:'arrival',people:['mara'],title:['在海湾安顿下来','Settle into the bay'],state:q.arrival==='settled'?'done':'active',summary:q.arrival==='settled'?['你已经拿到钥匙，放下了行李。','You have your key and have put your bag down.']:['玛拉为你留了一间夏天的租屋。','Mara has a room for your summer here.'],...(q.arrival==='settled'?{}:{next:q.arrival==='key-collected'?['去租屋放下行李。','Put your bag down in your room.']:['向玛拉领取钥匙。','Ask Mara for your key.'],place:q.arrival==='key-collected'?'home':'station'})});
 if(q.toolbag!=='not-requested')add({id:'toolbag',people:['mara','theo'],title:['玛拉的工具袋','Mara’s tool bag'],state:q.toolbag==='returned'?'done':'active',summary:q.toolbag==='returned'?['工具袋已经交还玛拉。','You returned the tool bag to Mara.']:['玛拉把工具袋落在咖啡馆。','Mara left her tool bag at the café.'],...(q.toolbag==='returned'?{}:{next:q.toolbag==='carried'||q.toolbag==='collected'?['回车站街，把工具袋交还玛拉。','Return the tool bag to Mara on Station Street.']:['去咖啡馆，向西奥取回工具袋。','Collect the tool bag from Theo at the café.'],place:q.toolbag==='carried'||q.toolbag==='collected'?'station':'cafe'})});
 if(q.terrace==='repaired'||q.terrace==='in-progress'||f('talk:theo:bag')||f('talk:theo:repair'))add({id:'lantern',people:['theo'],title:['露台上的灯','The terrace lantern'],state:q.terrace==='repaired'?'done':'active',summary:q.terrace==='repaired'?['灯已经亮了，西奥请你喝过咖啡。','The lantern is lit. Theo thanked you with coffee.']:['西奥提到露台灯的接头松了。','Theo mentioned the lantern’s loose connectors.'],...(q.terrace==='repaired'?{}:{next:['去咖啡馆检查露台灯。','Check the lantern at the café.'],place:'cafe'})});
 if(q.bridge!=='uninspected'||f('talk:june:bridge'))add({id:'bridge',people:['june'],title:['海岸小桥','The coast footbridge'],state:q.bridge==='repaired'?'done':'active',summary:q.bridge==='repaired'?['小桥已经修好。','The footbridge is repaired.']:['桥板坏了，桥基仍然牢固。','The boards are damaged, but the supports are sound.'],...(q.bridge==='repaired'?{}:{next:!s.items.toolkit?['去修理铺向琼借工具。','Borrow June’s toolkit at the workshop.']:(s.items.wood??0)<2?['去贝壳海滩找两块结实的木板。','Find two sound planks on Shell Beach.']:['带工具和木板去滨海道修桥。','Take the tools and planks to Coastal Path.'],place:!s.items.toolkit?'workshop':(s.items.wood??0)<2?'beach':'path'})});
 if(f('talk:nell:photo')||f('talk:arthur:trail')||q.trail==='mapped')add({id:'trail',people:['nell','arthur'],title:['公共绕行小路','The public trail'],state:q.trail==='mapped'?'done':'active',summary:q.trail==='mapped'?['你已经拼好公共小路的地图。','You pieced together the public trail map.']:['老照片与旧地图留下了一条绕行线索。','An old photograph and map offer another way around.'],...(q.trail==='mapped'?{}:{next:f('talk:arthur:trail')?['去松林营地拼合旧地图。','Piece together the old map at Pine Camp.']:['去旧气象站问问那里的老人。','Ask at the Weather Station.'],place:f('talk:arthur:trail')?'camp':'weather'})});
 if(f('talk:elena:quiet')||q.garden==='agreed-10-to-12')add({id:'garden',people:['elena'],title:['庭院借道的约定','Courtyard access'],state:q.garden==='agreed-10-to-12'?'done':'active',summary:q.garden==='agreed-10-to-12'?['你们同意试行上午10点到12点借道，尊重住户的安静。','You agreed to try access from 10:00 to 12:00, respecting the residents’ quiet.']:['埃琳娜希望来往的人尊重这里是她的家。','Elena wants passersby to respect her home.'],...(q.garden==='agreed-10-to-12'?{}:{next:q.bridge==='uninspected'?['先去滨海道查看小桥，再商量通行时间。','Inspect the bridge on Coastal Path before discussing access hours.']:['回住户庭院，与埃琳娜商量通行时间。','Discuss access hours with Elena in the courtyard.'],place:q.bridge==='uninspected'?'path':'courtyard'})});
 if(q.market!=='unknown'||q.access!=='not-ready')add({id:'coast-access',people:['theo','june','nell','arthur','elena'],title:['让海岸重新通行','Reopen coast access'],state:q.market==='open'?'done':'active',summary:q.market==='open'?['路线已经开放，集市也收到了消息。','The route is open and the market has the news.']:q.access==='open'?['海岸通行已经安排好，还可以把消息带去集市。','Access is arranged. You can share the news at the market.']:q.access==='ready'?['已有可行路线，可以确认通行安排。','A route is ready for its access arrangements.']:['你可以修桥、找公共小路，或与住户商量借道。','Repair the bridge, find the public trail, or agree access with the resident.'],...(q.market==='open'?{}:q.access==='ready'?{next:['去灯塔确认通行安排。','Confirm access at the Lighthouse.'],place:'lighthouse'}:q.access==='open'?{next:['去集市广场告诉大家。','Share the news in Market Square.'],place:'bazaar'}:{})});
 if(newsMemory(s))add({id:'visitor-news',people:['dani'],title:['游客的一个小试验','A visitor’s small experiment'],state:s.flags.some(f=>['news:checked','news:needs','news:later'].includes(f))?'done':'active',summary:newsMemory(s)!});
 if(f('battle:class:accepted'))add({id:'open-class',people:['idris'],title:['开课前的彩排','Before the Open Class'],state:f('battle:class:done')?'done':'active',summary:f('battle:class:done')?['你已陪教练彩排，并留下节奏感受。','You rehearsed with the coach and shared feedback.']:['陪教练完成一场回合练习，之后告诉他节奏感受；输赢都可以。','Finish one turn-based rehearsal and share feedback, win or lose.'],...(!f('battle:class:done')?{next:['港口拳馆 · 06:00–17:00找伊德里斯；暂停后可继续小镇生活。','Harbor Boxing Club · Meet Idris 06:00–17:00; pause any time for town life.'] as Words,place:'gym'}:{})});
 // Optional resident extension: facts are read only when the identities exist and are known.
 if(f('residents:invited')||f('residents:song-shared')){
  const done=f('residents:song-shared'),minutes=(s as Save&{townMinutes?:number}).townMinutes,m=typeof minutes==='number'?minutes%1440:undefined;
  add({id:'quiet-song',people:['avery','samira'],title:['码头边的一小段歌','A quiet tune at the pier'],state:done?'done':m===undefined||m<1020&&m>=360?'upcoming':m>=1020&&m<1260?'available':'return-later',summary:done?['你们曾一起在码头听歌、听水声。','You shared a tune and listened to the water together.']:['萨米拉约你们在钓鱼码头相聚，17:00–21:00；另一个傍晚也可以。','Samira invited you to the Fishing Pier, 17:00–21:00. Another evening is fine too.'],...(done?{}:{next:m!==undefined&&m>=1020&&m<1260?['去钓鱼码头，找萨米拉听那段歌。','Find Samira at the Fishing Pier to hear the tune.']:['另一个傍晚也可以，不需要赶时间。','Come another evening if you like. There is no rush.'],place:'dock'})});
 }
 for(const lead of nextStoryLeads(s))add(lead);
 return {leads,people:known.map(id=>{const history=s.history.filter(h=>h.person===id),related=leads.filter(l=>l.people.includes(id));return {id,...registry[id],role:roles[id]??['海湾里认识的人。','Someone you met in the bay.'],stage:related.some(l=>l.state==='done')?['有共同经历','Shared experiences'] as Words:history.length>1?['聊过一些事情','We have talked'] as Words:['已相识','We have met'] as Words,history,related,places:!!residentRoutes[id]&&!f(`talk:${id}:routine`)?[]:Object.values(rooms).filter(r=>s.visited.includes(r.id)&&r.entities.some(e=>e.person===id)).map(r=>r.id)};})};
}
