import type {Words} from '../world/data';
/** Frozen development sample. Never presented as a live feed or model retrieval. */
export const newsRecord={id:'academy-20261002-v1',revision:1,canonicalURL:'https://www.anthropic.com/news/claude-frontier-academy',title:'Claude Frontier Academy',source:'Anthropic',publishedAt:'2026-10-02',publishedPrecision:'date',publishedTimezone:null,fetchedAt:'2026-10-04',expiresAt:'2026-10-11',status:'frozen-local-sample',summary:['Anthropic于2026年10月2日宣布投入1亿美元，目标到2027年底培养一万名工程师。这是宣布的计划，尚不是完成的成果。','On October 2, 2026, Anthropic announced a $100 million commitment with a goal of training 10,000 engineers by the end of 2027. This is an announced plan, not a completed result.'] as Words};
type S={flags:string[];known:string[]};
export const newsTopicIds=['visitor-news','visitor-test','visitor-needs','visitor-later','visitor-hours','visitor-reminder','visitor-private','visitor-recall'];
const f=(s:S,id:string)=>s.flags.includes('news:'+id);
export function newsTopics(s:S,p:string):import('./resident-life').LifeTopic[]{
 if(p!=='dani'||!s.known.includes(p))return [];
 const t=(id:string,label:Words,reply:Words)=>({id,label,reply,once:true});
 if(!f(s,'heard'))return [t('visitor-news',['游客留言里有什么新鲜事？','Anything new in the visitor notebook?'],['丹妮翻出一张留言：“Casey是来休假的软件工程师。读到这则培训新闻后，她想试试：技术能不能帮小店少出错？不是大项目，先核对三条营业提示。”这是虚构游客的提议，不是新闻里公司的活动。','Dani opens a note. “Casey is a software engineer on holiday. That training announcement made her wonder: could technology help a small shop make fewer mistakes? She suggests checking three opening-hours notices.” This fictional visitor’s idea is not an activity run by the company in the news.'])];
 if(!f(s,'test')&&!f(s,'needs')&&!f(s,'later'))return [t('visitor-test',['我来核对一个小例子','Try checking a small example'],['“先看事实。”留言里给出的杂货铺营业时间是06:00–17:00。三张草稿，哪一张没有把休息时间说错？','“Start with the facts.” The grocer opens from 06:00 to 17:00. Which of the three drafts gets the closing time right?']),t('visitor-needs',['先问店主究竟需要什么','Ask what the shopkeeper actually needs'],['你写下：先征得店主同意，再试一项小改进，不拿顾客资料练习。丹妮把它留在留言本首页：“这个顺序值得记住。”这是你给虚构故事留下的建议，不代表店主已经答应。','You write: ask the shopkeeper first, try one small improvement, and leave customer information out of experiments. Dani keeps it at the front. “Worth remembering that order.” Your suggestion remains in this fictional story; it does not mean the shopkeeper has agreed.']),t('visitor-later',['今天先不参与，保留这则消息','Not today; keep the note'],['丹妮把留言收好。你可以继续小镇的其他事情，这则消息也留在手记里。','Dani saves the note. The rest of town is yours to explore; the source stays in your journal.'])];
 if(f(s,'test')&&!f(s,'checked'))return [t('visitor-hours',['06:00–17:00营业；关店后请明天再来','Open 06:00–17:00; return tomorrow after closing'],['你划出营业时段，并留下关店后的去向。丹妮在便条上写了“已核对”，没有让一句漂亮但错误的介绍替代事实。','You underline the opening hours and explain what to do after closing. Dani marks the note checked. A polished but wrong sentence does not get to replace the facts.']),t('visitor-reminder',['写成全天营业比较方便','Call it open all day'],['“那会让人白跑一趟。”丹妮指回06:00–17:00的记录。你们先留下草稿，重新核对。','“That sends someone on a wasted trip.” Dani points back to 06:00–17:00. You keep the draft and check again.']),t('visitor-private',['先收集顾客资料，再决定','Collect customer details first'],['“核对营业时间用不到这些。”丹妮把私人资料那一栏划掉，留下公开的营业记录。再看一次吧。','“Checking opening hours does not need that.” Dani crosses out the request for private details and leaves the public schedule. Have another look.'])];
 return !s.flags.includes('talk:dani:visitor-recall')?[t('visitor-recall',['那张游客便条后来怎样了？','What happened to the visitor note?'],f(s,'checked')?['“你核对过的那张还在本子里。”丹妮翻到打勾的一页，“先试小例子，把休息时间也写清楚。”','“Your checked note is still here.” Dani turns to the marked page. “A small test, with the closing time made clear.”']:f(s,'needs')?['“先问店主需要什么，那句我留着了。”丹妮没有把建议写成已经实现的计划。','“I kept your line about asking what the shopkeeper needs.” Dani has not turned your suggestion into a claim that it already happened.']:['“我留着了。你不必参加每一件事。”丹妮合上本子。','“Still here. You needn’t join every activity.” Dani closes the book.'])]:[];
}
export function applyNewsTopic(s:S,p:string,id:string){if(p!=='dani'||!newsTopicIds.includes(id))return;const names:Record<string,string>={'visitor-news':'heard','visitor-test':'test','visitor-needs':'needs','visitor-later':'later','visitor-hours':'checked'};const key=names[id];if(key&&!f(s,key))s.flags.push('news:'+key);if(key==='heard'&&!s.flags.includes('news:record:'+newsRecord.id))s.flags.push('news:record:'+newsRecord.id)}
export function newsMemory(s:S):Words|undefined{return !f(s,'heard')?undefined:f(s,'checked')?['游客留言 · 你核对了营业便条，丹妮保存了结果。','Visitor notebook · You checked the hours; Dani saved your note.']:f(s,'needs')?['游客留言 · 你建议先询问店主的需求与同意。','Visitor notebook · You suggested asking the shopkeeper first.']:f(s,'later')?['游客留言 · 你暂未参与，来源仍可查看。','Visitor notebook · You passed for now; the source remains available.']:['游客留言 · 丹妮还留着一个待核对的小例子。','Visitor notebook · Dani has a small example ready to check.']}
