import type {Words} from '../world/data';
/** Frozen development sample. Never presented as a live feed or model retrieval. */
export const newsRecord={id:'academy-20261002-v1',revision:1,canonicalURL:'https://www.anthropic.com/news/claude-frontier-academy',title:'Claude Frontier Academy',source:'Anthropic',publishedAt:'2026-10-02',publishedPrecision:'date',publishedTimezone:null,fetchedAt:'2026-10-04',expiresAt:'2026-10-11',status:'frozen-local-sample',summary:['Anthropic于2026年10月2日宣布投入1亿美元，目标到2027年底培养一万名工程师。这是宣布的计划，尚不是完成的成果。','On October 2, 2026, Anthropic announced a $100 million commitment with a goal of training 10,000 engineers by the end of 2027. This is an announced plan, not a completed result.'] as Words};
import {editionSummary,type NewsState} from './news-edition';
type S=NewsState&{flags:string[];known:string[]};
export const sourceFor=(s:S)=>s.newsEdition?{...s.newsEdition,summary:editionSummary(s.newsEdition)}:newsRecord;
export const newsTopicIds=['visitor-news','visitor-test','visitor-needs','visitor-later','visitor-hours','visitor-reminder','visitor-private','visitor-recall','visitor-budget','visitor-no-reserve'];
const f=(s:S,id:string)=>s.flags.includes('news:'+id);
export function newsTopics(s:S,p:string):import('./resident-life').LifeTopic[]{
 if(p!=='dani'||!s.known.includes(p))return [];
 if(s.newsMode==='live'){if(!s.newsEdition||['changed','unavailable'].includes(s.newsAvailability??'')||s.newsAvailability==='expired'&&!f(s,'heard'))return [];return financeTopics(s);}
 const t=(id:string,label:Words,reply:Words)=>({id,label,reply,once:true});
 if(!f(s,'heard'))return [t('visitor-news',['游客留言里有什么新鲜事？','Anything new in the visitor notebook?'],['丹妮翻出一张留言：“Casey是来休假的软件工程师。读到这则培训新闻后，她想试试：技术能不能帮小店少出错？不是大项目，先核对三条营业提示。”这是虚构游客的提议，不是新闻里公司的活动。','Dani opens a note. “Casey is a software engineer on holiday. That training announcement made her wonder: could technology help a small shop make fewer mistakes? She suggests checking three opening-hours notices.” This fictional visitor’s idea is not an activity run by the company in the news.'])];
 if(!f(s,'test')&&!f(s,'needs')&&!f(s,'later'))return [t('visitor-test',['我来核对一个小例子','Try checking a small example'],['“先看事实。”留言里给出的杂货铺营业时间是06:00–17:00。三张草稿，哪一张没有把休息时间说错？','“Start with the facts.” The grocer opens from 06:00 to 17:00. Which of the three drafts gets the closing time right?']),t('visitor-needs',['先问店主究竟需要什么','Ask what the shopkeeper actually needs'],['你写下：先征得店主同意，再试一项小改进，不拿顾客资料练习。丹妮把它留在留言本首页：“这个顺序值得记住。”这是你给虚构故事留下的建议，不代表店主已经答应。','You write: ask the shopkeeper first, try one small improvement, and leave customer information out of experiments. Dani keeps it at the front. “Worth remembering that order.” Your suggestion remains in this fictional story; it does not mean the shopkeeper has agreed.']),t('visitor-later',['今天先不参与，保留这则消息','Not today; keep the note'],['丹妮把留言收好。你可以继续小镇的其他事情，这则消息也留在手记里。','Dani saves the note. The rest of town is yours to explore; the source stays in your journal.'])];
 if(f(s,'test')&&!f(s,'checked'))return [t('visitor-hours',['06:00–17:00营业；关店后请明天再来','Open 06:00–17:00; return tomorrow after closing'],['你划出营业时段，并留下关店后的去向。丹妮在便条上写了“已核对”，没有让一句漂亮但错误的介绍替代事实。','You underline the opening hours and explain what to do after closing. Dani marks the note checked. A polished but wrong sentence does not get to replace the facts.']),t('visitor-reminder',['写成全天营业比较方便','Call it open all day'],['“那会让人白跑一趟。”丹妮指回06:00–17:00的记录。你们先留下草稿，重新核对。','“That sends someone on a wasted trip.” Dani points back to 06:00–17:00. You keep the draft and check again.']),t('visitor-private',['先收集顾客资料，再决定','Collect customer details first'],['“核对营业时间用不到这些。”丹妮把私人资料那一栏划掉，留下公开的营业记录。再看一次吧。','“Checking opening hours does not need that.” Dani crosses out the request for private details and leaves the public schedule. Have another look.'])];
 return !s.flags.includes('talk:dani:visitor-recall')?[t('visitor-recall',['那张游客便条后来怎样了？','What happened to the visitor note?'],f(s,'checked')?['“你核对过的那张还在本子里。”丹妮翻到打勾的一页，“先试小例子，把休息时间也写清楚。”','“Your checked note is still here.” Dani turns to the marked page. “A small test, with the closing time made clear.”']:f(s,'needs')?['“先问店主需要什么，那句我留着了。”丹妮没有把建议写成已经实现的计划。','“I kept your line about asking what the shopkeeper needs.” Dani has not turned your suggestion into a claim that it already happened.']:['“我留着了。你不必参加每一件事。”丹妮合上本子。','“Still here. You needn’t join every activity.” Dani closes the book.'])]:[];
}
export function applyNewsTopic(s:S,p:string,id:string){if(p!=='dani'||!newsTopicIds.includes(id))return;const names:Record<string,string>={'visitor-news':'heard','visitor-test':'test','visitor-needs':'needs','visitor-later':'later','visitor-hours':'checked','visitor-budget':'checked'};const key=names[id];if(key&&!f(s,key))s.flags.push('news:'+key);if(key==='heard'&&!s.flags.includes('news:record:'+sourceFor(s).id))s.flags.push('news:record:'+sourceFor(s).id)}
export function newsMemory(s:S):Words|undefined{if(s.newsEdition)return !f(s,'heard')?undefined:f(s,'checked')?['游客留言 · 你核对了$10试验预算，留出$3备用。','Visitor notebook · You checked the $10 trial budget and kept $3 in reserve.']:f(s,'needs')?['游客留言 · 你选择先询问摊主的需求。','Visitor notebook · You chose to ask the stallholder first.']:f(s,'later')?['游客留言 · 你暂不参加，保留来源。','Visitor notebook · You passed for now and kept the source.']:['游客留言 · 一份待核对的小集市试验预算。','Visitor notebook · A small market trial budget awaits a check.'];return !f(s,'heard')?undefined:f(s,'checked')?['游客留言 · 你核对了营业便条，丹妮保存了结果。','Visitor notebook · You checked the hours; Dani saved your note.']:f(s,'needs')?['游客留言 · 你建议先询问店主的需求与同意。','Visitor notebook · You suggested asking the shopkeeper first.']:f(s,'later')?['游客留言 · 你暂未参与，来源仍可查看。','Visitor notebook · You passed for now; the source remains available.']:['游客留言 · 丹妮还留着一个待核对的小例子。','Visitor notebook · Dani has a small example ready to check.']}

function financeTopics(s:S):import('./resident-life').LifeTopic[]{
 const t=(id:string,label:Words,reply:Words)=>({id,label,reply,once:true});
 if(!f(s,'heard'))return [t('visitor-news',['游客留言里有什么新鲜事？','Anything new in the visitor notebook?'],['丹妮说：“Alex是来休假的金融从业者，读到这则政策公告，又想起工作里最常见的错误：把不确定的事当成保证。她想帮小集市先算一份试验预算，再问摊主愿不愿意做。”这是虚构游客的联想，不是美联储对小镇的安排，也没有推断新闻会改变这里的物价。','Dani says, “Alex works in finance and is here on holiday. This policy announcement reminded her of a familiar mistake at work: treating uncertainty as a promise. She suggests checking a small market trial budget before asking a stallholder whether they want to try it.” This is a fictional visitor’s reaction, not a Federal Reserve project or a claim that this news changes town prices.'])];
 if(!f(s,'test')&&!f(s,'needs')&&!f(s,'later'))return [t('visitor-test',['核对小集市的试验预算','Check the market trial budget'],['纸上写着：试验预算$10，纸板$3，夹子$4，装饰$3。不必全花掉。你会给摊主哪一份建议？这里的数字只是虚构预算，不扣你的钱包。','The note lists a $10 trial budget: card $3, clips $4, decorations $3. There is no need to spend it all. What would you suggest? These are fictional planning figures; your wallet is not charged.']),t('visitor-needs',['先问摊主需要什么','Ask what the stallholder needs first'],['你写下：先问要解决什么问题，再决定是否花钱。丹妮留下这句建议，没有替摊主答应。','You write: first ask what problem needs solving, then decide whether to spend. Dani keeps the suggestion without agreeing on the stallholder’s behalf.']),t('visitor-later',['今天先不参与，保留这则消息','Not today; keep the note'],['丹妮收好来源和便条。你可以继续自己的旅程。','Dani keeps the source and the note. Your own journey can continue.'])];
 if(f(s,'test')&&!f(s,'checked'))return [t('visitor-budget',['纸板和夹子$7，留下$3备用','Card and clips: $7; keep $3 in reserve'],['你把必要材料和备用金分开。丹妮把预算便条留在花园告示处；Alex的试验仍是建议，尚未变成承诺或采购。你的钱包没有变化。','You separate necessary materials from the reserve. Dani keeps the budget note at the garden noticeboard. Alex’s trial remains a suggestion, not a promise or a purchase. Your wallet is unchanged.']),t('visitor-no-reserve',['花完$10，并保证不会有意外','Spend all $10 and promise no surprises'],['丹妮摇头：“预算加起来没错，但谁能保证没有意外？”你们保留草稿，重新想想。','Dani shakes her head. “The sum works, but who can promise there will be no surprises?” You keep the draft and reconsider.'])];
 return !s.flags.includes('talk:dani:visitor-recall')?[t('visitor-recall',['那张游客便条后来怎样了？','What happened to the visitor note?'],f(s,'checked')?['“留出$3备用的建议还在。”丹妮指向预算便条。没有因此自动举办集市或花掉任何人的钱。','“Your suggestion to keep $3 in reserve is still here.” Dani points to the budget note. No market was automatically arranged, and nobody’s money was spent.']:f(s,'needs')?['“先问需求，那句我留着了。”','“I kept your line about asking what is needed first.”']:['“便条还在。你不必参与每件事。”','“Still here. You need not join every activity.”'])]:[];
}
