import {mintItem,type PlantUseVerb} from '../life/plant-uses';
import {useRef,useState} from 'react';
import {items,type Save} from '../story/state';
import {rooms,tx,type Locale,type Words} from '../world/data';
import type {Command,LifeSave} from '../life/types';
import snapPea from '../life/snap-pea-v2.json';
import {observationRecordLabel} from '../animal-life/labels';
import {batchArt,itemArt} from './bag-art';
import {CropImage} from './CropImage';
import {Icon} from './icons';
import {gameMinuteLabel,type LifeView} from './LifeBag';
import {AnimalPages} from './AnimalNotebook';
import {useView} from './PlantUsesPanel';
type Category='all'|'seed'|'produce'|'tools'|'objects'|'notes';
export type BagState={tab:'goods'|'records'|'keepsakes';category:Category;selected?:string;search:string;last?:BagRow};
export const emptyBagState:BagState={tab:'goods',category:'all',search:''};
export type BagRow={id:string;name:Words;quantity:number;category:Exclude<Category,'all'>;description:Words;image?:string;transparent?:boolean;batch?:LifeView['batches'][number];item?:string};
const categories:Record<Category,Words>={all:['全部','All'],seed:['种子','Seeds'],produce:['收成','Harvest'],tools:['工具','Tools'],objects:['物件','Objects'],notes:['资料','Documents']};
const gifts:Record<string,Words>={'life-gift:theo-menu':['第一篮收成的菜单小卡','A menu card for my first delivery'],'life-gift:dani-page':['我的菜园与车站猫','My garden and the station cat']};
/** Quantity has one owner: authoritative batches replace legacy crop counters. */
export function bagRows(save:Save,view:LifeView|null):BagRow[]{
 const fallback:BagRow[]=view?[]:((save as LifeSave).lifeV1?.lots??[]).filter(l=>l.quantity>0).map(l=>{const item=(['radish','basil','tomato'].includes(l.ref.id.slice(5))?(l.kind==='seed'?'seed-':'crop-'):'life-'+l.kind+':')+l.ref.id.slice(5),name:Words=items[item]?.name??(l.ref.id===snapPea.id?snapPea.name as Words:['旧批次物品','Archived batch']);return {id:l.ref.id+'@'+l.ref.revision+':'+l.kind,item,name,quantity:l.quantity,category:l.kind==='seed'?'seed':'produce',description:['数量来自已存进度；详情读取成功后才能使用，实物仍保留。','Quantity from your saved progress. Read the details before using it; your goods remain.'],image:batchArt(l.ref,l.kind),transparent:true}});
 const covered=new Set(fallback.map(l=>l.item));
 const batches=(view?.batches??[]).filter(b=>b.quantity>0).map(b=>({id:b.id,name:b.name,quantity:b.quantity,category:b.kind==='seed'?'seed' as const:'produce' as const,description:b.kind==='seed'?b.startAvailable?['带到菜畦播种；原有作物使用花园固定畦。','Take to a bed to plant. Original crops use the garden beds.']:['此旧批次停止新播种，持有量与记录保留。','New planting is closed for this archived batch. Its goods and records remain.']:['可到杂货柜台出售，或消耗1份收成留种。订单须当面交货。','Sell at the grocer, or use one harvest unit to save a seed. Orders are delivered in person.'],image:batchArt(b.ref,b.kind),transparent:true,batch:b} satisfies BagRow));
 const legacy=Object.entries(save.items).filter(([id,n])=>n>0&&items[id]&&!covered.has(id)&&(!view||!id.startsWith('seed-')&&!id.startsWith('crop-'))).map(([id,n])=>({id:'item:'+id,item:id,name:items[id].name,quantity:n,category:id.startsWith('seed-')?'seed' as const:id.startsWith('crop-')?'produce' as const:items[id].kind,description:items[id].description,image:itemArt(id),transparent:true}));
 const mint:BagRow[]=(save.items[mintItem]??0)>0?[{id:'item:'+mintItem,item:mintItem,name:['野薄荷叶','Wild mint leaves'],quantity:save.items[mintItem],category:'produce',description:['采下的叶片；株丛留在山坡。可消耗一份收入我的记录。','Collected leaves; the clump stays on the hill. Use one portion to add to my notebook.'],image:itemArt(mintItem),transparent:true}]:[];
 const order:Category[]=['seed','produce','tools','objects','notes'];
 return [...batches,...fallback,...legacy,...mint].sort((a,b)=>order.indexOf(a.category)-order.indexOf(b.category)||(a.id<b.id?-1:a.id>b.id?1:0));
}
export function Bag({save,view,current,locale,busy,retry,error,feedback,pending,onReconnect,state,setState,onCommand,onEat,onPortrait,onPlace,onAnimal,onPlantUse}:{save:Save;view:LifeView|null;current:boolean;locale:Locale;busy:boolean;retry:()=>void;error:Words|null;feedback:Words|null;pending:boolean;onReconnect:()=>void;state:BagState;setState:(s:BagState)=>void;onCommand:(c:Command)=>Promise<unknown>;onEat:()=>Promise<unknown>;onPortrait:(id:string)=>void;onPlace:(id:string)=>void;onAnimal:(c:import('../animal-life/types').AnimalCommand)=>void;onPlantUse?:(v:PlantUseVerb)=>Promise<unknown>}){
 const rows=bagRows(save,view),selected=rows.find(r=>r.id===state.selected),detail=useRef<HTMLElement>(null),[working,setWorking]=useState(false),lock=useRef(false);
 const row=selected??(state.last&&state.last.id===state.selected?{...state.last,quantity:0}:undefined);
 const update=(patch:Partial<BagState>)=>setState({...state,...patch,...(patch.category&&patch.category!==state.category||patch.search!==undefined&&patch.search!==state.search?{selected:undefined}:{})});
 const run=async(fn:()=>Promise<unknown>)=>{if(lock.current||busy||pending||!current)return;lock.current=true;setWorking(true);try{await fn()}finally{lock.current=false;setWorking(false)}};
 const filtered=rows.filter(r=>(state.category==='all'||r.category===state.category)&&tx(r.name,locale).toLowerCase().includes(state.search.toLowerCase()));
 const ownedGifts=view?.gifts.filter(g=>g.quantity>0)??Object.entries(save.items).filter(([id,n])=>id.startsWith('life-gift:')&&n>0).map(([id,quantity])=>({id,quantity}));
 const records=!!view&&(view.collections.length>0||!!view.animals?.pages.length),p=useView(view),locked=busy||working||pending||!current;
 const effectiveTab=state.tab==='records'&&!records||state.tab==='keepsakes'&&!ownedGifts.length?'goods':state.tab,showGoods=effectiveTab==='goods',detailShown=showGoods&&!!row;
 return <div className="harbor-bag">
 <div className="harbor-subnav" aria-label={tx(['行囊分类','Bag sections'],locale)}>{(['goods',...(records?['records']:[]),...(ownedGifts.length?['keepsakes']:[])] as BagState['tab'][]).map(tab=><button key={tab} aria-pressed={effectiveTab===tab} onClick={()=>update({tab})}>{tx(tab==='goods'?['随身物品','Goods']:tab==='records'?['发现记录','Records']:['纪念物','Keepsakes'],locale)}</button>)}</div>
 {!detailShown&&feedback&&<p className="harbor-life-feedback" role="status">{tx(feedback,locale)}</p>}{!detailShown&&error&&<p className="harbor-error" role="alert">{tx(error,locale)}</p>}{!detailShown&&pending&&!busy&&<button onClick={onReconnect}>{tx(['重新连接，确认进度','Reconnect and check progress'],locale)}</button>}
 <div className="harbor-stats"><span>{tx(['精力','Energy'],locale)} {save.energy}/100</span><span>${save.cash}</span><span>{tx(['口碑','Reputation'],locale)} {save.standing}</span></div>
 {!view&&<p role="status">{tx(['种子与记录暂未读到；现有物品仍可查看。','Seeds and records could not be read. Existing goods remain visible.'],locale)}<button onClick={retry}>{tx(['重试读取','Try again'],locale)}</button></p>}
 {view&&!current&&<p role="status">{tx(['正在核对新数量。确认后可使用物品。','Checking updated quantities. Use items after they are confirmed.'],locale)}<button disabled={busy} onClick={retry}>{tx(['重试读取','Try again'],locale)}</button></p>}
 {showGoods&&<>
 <label className="harbor-bag__category">{tx(['类型','Type'],locale)}<select aria-label={tx(['物品类型','Item type'],locale)} value={state.category} onChange={e=>update({category:e.target.value as Category,search:''})}>{(['all',...Object.keys(categories).filter(c=>c!=='all'&&(c===state.category||rows.some(r=>r.category===c)))] as Category[]).map(c=><option key={c} value={c}>{tx(categories[c],locale)}</option>)}</select></label>
 <div className="harbor-bag__filters">{(['all',...Object.keys(categories).filter(c=>c!=='all'&&(c===state.category||rows.some(r=>r.category===c)))] as Category[]).map(c=><button key={c} aria-pressed={state.category===c} onClick={()=>update({category:c,search:''})}>{tx(categories[c],locale)}</button>)}</div>
 {(rows.length>12||state.search)&&<label className="harbor-bag__search">{tx(['查找物品','Find an item'],locale)}<input type="search" value={state.search} onChange={e=>update({search:e.target.value})}/></label>}
 <div className="harbor-bag__layout"><div className="harbor-bag__list" aria-label={tx(['物品与数量','Items and quantities'],locale)}>{filtered.map(r=><button key={r.id} data-bag-item={r.id} aria-pressed={state.selected===r.id} onClick={()=>{update({selected:r.id,last:r});requestAnimationFrame(()=>{detail.current?.scrollIntoView({block:'nearest'});detail.current?.querySelector<HTMLElement>('h3')?.focus({preventScroll:true})})}}><span className="harbor-bag__art" data-item-art={r.image?'available':'missing'}>{r.image?<CropImage image={r.image} transparent={r.transparent} alt=""/>:<small>{tx(['暂无图片','No image yet'],locale)}</small>}</span><span><strong>{tx(r.name,locale)}</strong><small>{tx(categories[r.category],locale)}{r.batch&&r.batch.ref.revision>1?` · v${r.batch.ref.revision}`:''}</small></span><strong className="harbor-bag__quantity">×{r.quantity}</strong></button>)}{!filtered.length&&<p>{tx(rows.length?['此分类没有物品。','No items in this category.']:['行囊还是空的。发现的记录会另行保留。','Your bag is empty. Discovery records are kept separately.'],locale)}</p>}</div>
 {row&&<section className="harbor-bag__detail" ref={detail} data-bag-detail={row.id} aria-label={tx(['选中物品','Selected item'],locale)}><button className="harbor-link" onClick={()=>{const el=document.querySelector(`[data-bag-item="${state.selected}"]`);update({selected:undefined});requestAnimationFrame(()=>{el?.scrollIntoView({block:'nearest'});(el as HTMLElement|null)?.focus({preventScroll:true})})}}>{tx(['返回物品列表','Back to items'],locale)}</button><div className="harbor-bag__detail-art" data-item-art={row.image?'available':'missing'}>{row.image?<CropImage image={row.image} transparent={row.transparent} alt={tx(row.name,locale)}/>:<p>{tx(['此物品暂无对应图片','No corresponding image for this item yet'],locale)}</p>}</div><h3 tabIndex={-1}>{tx(row.name,locale)} <span>×{row.quantity}</span></h3>{feedback&&<p className="harbor-life-feedback" role="status">{tx(feedback,locale)}</p>}{error&&<p className="harbor-error" role="alert">{tx(error,locale)}</p>}{pending&&!busy&&<button onClick={onReconnect}>{tx(['重新连接，确认进度','Reconnect and check progress'],locale)}</button>}<p>{tx(row.description,locale)}</p>{row.quantity===0?<p role="status">{tx(['这一份已经用完。分类与记录仍保留，可直接选下一件。','This item is used up. Your category and records remain; choose another item.'],locale)}</p>:<>
 {row.batch?.saveSeedAvailable&&<button disabled={locked} onClick={()=>void run(()=>onCommand({verb:'save-seed',ref:row.batch!.ref}))}>{tx(['留种 · 消耗1份收成','Save seed · use 1 harvest unit'],locale)}</button>}
 {row.item===mintItem&&p?.mintEnabled&&!p.mint.archived&&onPlantUse&&<button disabled={locked} onClick={()=>void run(()=>onPlantUse('archive-mint'))}>{tx(['收入记录 · 消耗一份叶','Add to my notebook · use one portion'],locale)}</button>}
 {row.item==='packed-snack'&&<button disabled={locked||save.energy>=100} onClick={()=>void run(onEat)}>{tx(['吃1份 · 精力+30','Eat 1 · +30 energy'],locale)}</button>}
 {row.category==='seed'&&<button disabled={busy} onClick={()=>onPlace('garden')}>{tx(['查看菜畦地点','Find the garden beds'],locale)}<Icon name="map"/></button>}
 {row.category==='produce'&&<button disabled={busy} onClick={()=>onPlace('grocery')}>{tx(['查看出售地点','Find the grocer'],locale)}<Icon name="map"/></button>}
 {['photo','route'].includes(row.item??'')&&<button onClick={()=>onPortrait('asset:'+(row.item==='photo'?'bridge-photo':'trail-map-closeup'))}>{tx(['放大查看','View closely'],locale)}</button>}
 </>}</section>}</div>
 {(view?.order||p?.order)&&<section className="harbor-item"><h3>{tx(['交货安排','Delivery plans'],locale)}</h3><p>{tx(['去人物的「事情」查看需求与交货地点；交货保留原现场条件。','See People → Matters for requirements and delivery locations. Deliveries keep their original in-person conditions.'],locale)}</p><button onClick={()=>onPlace('cafe')}>{tx(rooms.cafe.title,locale)}<Icon name="map"/></button></section>}
 </>}
 {effectiveTab==='records'&&records&&<><p>{tx(['这是发现与知识，不是额外库存，也不表示拥有动物。','Discoveries and knowledge, not extra inventory or ownership of animals.'],locale)}</p>{view!.collections.map(c=><article className="harbor-item" key={c.record.id} data-life-record={c.record.id}><h3>{tx(c.name??observationRecordLabel(c.record.id)??gifts[c.record.id.slice(5)]??['小镇经历','A town memory'],locale)}</h3><p>{tx(['已登记','Recorded'],locale)} · {gameMinuteLabel(c.record.minute,locale)}</p>{c.physicalSeedQuantity!==undefined&&<p>{tx([`持有种子 ${c.physicalSeedQuantity} 颗`,`Seeds owned: ${c.physicalSeedQuantity}`],locale)}</p>}{c.physicalGiftQuantity!==undefined&&<p>{tx([`持有纪念物 ${c.physicalGiftQuantity} 件`,`Keepsakes owned: ${c.physicalGiftQuantity}`],locale)}</p>}</article>)}<AnimalPages save={save} view={view?.animals} locale={locale} projectionCurrent={current} busy={busy||pending} onCommand={onAnimal}/></>}
 {effectiveTab==='keepsakes'&&!!ownedGifts.length&&<><p>{tx(['这些是实际持有的纪念物，不与随身物品重复计数。','Keepsakes you own. They are counted here once.'],locale)}</p>{ownedGifts.map(g=><article key={g.id} className="harbor-item"><h3>{tx(gifts[g.id]??['街坊的赠礼','A neighbor’s gift'],locale)} ×{g.quantity}</h3><p>{tx(['一起经历过的事留下的礼物。原有陈列功能尚未开放。','A gift from a shared experience. Display is not available yet.'],locale)}</p></article>)}</>}
 </div>;
}
