import {summerAudio} from '../audio';
import dimensions from '../world/combat-dimensions.json';
import {useEffect,useRef,useState} from 'react';import {Application,Assets,Sprite,Texture,Rectangle,Graphics,TilingSprite} from 'pixi.js';
import {beginEncounter,stepEncounter,FixedClock,appendInput,type InputRun,type CombatState} from '../combat/core';import {encounterPresets} from '../combat/presets';import {tx,type Locale} from '../world/data';import {Joystick} from './Joystick';import {Icon} from './icons';
export function Combat({kind,locale,onFinish,onLeave}:{kind:string;locale:Locale;onFinish:(runs:InputRun[])=>void;onLeave:()=>void}){
 const [started,setStarted]=useState(false);const startedRef=useRef(false);
 const mount=useRef<HTMLDivElement>(null),inputs=useRef({x:0,y:0,attack:false,defend:false}),runs=useRef<InputRun[]>([]),current=useRef<CombatState|null>(null);const [hud,setHud]=useState({hp:5,enemy:4,result:'playing',tick:0}),[ready,setReady]=useState(false),[loadError,setLoadError]=useState(false);
 useEffect(()=>{const c=encounterPresets[kind],s=beginEncounter(c);current.current=s;const app=new Application(),clock=new FixedClock();let stopped=false;const sprites:Sprite[]=[],graphics=new Graphics();
 void(async()=>{await app.init({width:c.width,height:c.height,background:'#d9c9a4',antialias:false,resolution:Math.min(2,devicePixelRatio),autoDensity:true});if(stopped){app.destroy(true);return}mount.current!.appendChild(app.canvas);const assets:Record<string,Texture>={};
 const keys=Object.keys(dimensions);await Promise.all(keys.map(async key=>assets[key]=await Assets.load('./art/'+key+'.png')));
 const walks=await Promise.all(['hero','npc-idris'].map(async key=>{const tex=await Assets.load('./art/'+key+'.png');return Array.from({length:12},(_,i)=>new Texture({source:tex.source,frame:new Rectangle(i%3*128,Math.floor(i/3)*128,128,128)}))}));
 const floor=new TilingSprite({texture:await Assets.load('./art/floor-wood.png'),width:c.width,height:c.height});floor.tileScale.set(.16);app.stage.addChild(floor);
 app.stage.addChild(graphics);app.stage.sortableChildren=true;graphics.zIndex=-1;floor.zIndex=-2;
 for(const a of [s.player,...s.enemies]){const sprite=new Sprite(walks[a.id===s.player.id?0:1][1]);sprite.anchor.set(.5,122/128);sprite.scale.set(56/108);app.stage.addChild(sprite);sprites.push(sprite)}
 const previous=[s.player,...s.enemies].map(a=>({...a.position})),strides=previous.map(()=>0);
 let count=0;app.ticker.add(t=>{if(stopped||document.hidden)return;clock.update(t.deltaMS/1000,()=>{if(s.result!=='playing'||!startedRef.current)return;appendInput(runs.current,inputs.current);stepEncounter(c,s,inputs.current);if(s.events.some(e=>e.type==='hit'))summerAudio.effect('hit');inputs.current.attack=false;inputs.current.defend=false});graphics.clear();graphics.rect(8,8,c.width-16,c.height-16).stroke({color:0x887658,width:3});
 for(const o of c.obstacles)graphics.roundRect(o.x,o.y,o.w,o.h,3).fill(0x547d7c);
 if(c.objective.kind==='reach'){const z=c.objective.zone;graphics.rect(z.x,z.y,z.w,z.h).fill({color:0x4f9083,alpha:.5})}
 [s.player,...s.enemies].forEach((a,i)=>{const sprite=sprites[i],dx=a.position.x-previous[i].x,dy=a.position.y-previous[i].y,distance=Math.hypot(dx,dy);strides[i]+=distance;previous[i]={...a.position};const direction=Math.abs(a.facing.x)>=Math.abs(a.facing.y)?(a.facing.x<0?'left':'right'):(a.facing.y<0?'up':'down');
 if(a.phase!=='idle'||distance<.01){const key=(i===0?'hero':'idris')+'-combat-'+(['left','right'].includes(direction)?'':direction+'-')+(a.phase==='active'?'punch':'guard'),d=dimensions[key as keyof typeof dimensions];if(d&&assets[key]){sprite.texture=assets[key];sprite.anchor.set(d.anchorX,1);sprite.scale.set((direction==='right'?-1:1)*56/d.height,56/d.height)}}else{const row={down:0,left:1,right:2,up:3}[direction],col=[0,1,2,1][Math.floor(strides[i]/12)%4];sprite.texture=walks[i===0?0:1][row*3+col];sprite.anchor.set(.5,122/128);sprite.scale.set(56/108)}
 sprite.position.set(a.position.x,a.position.y);sprite.zIndex=a.position.y;sprite.alpha=a.hp<=0?.25:a.hurtTicks?.55:1;if(a.phase==='windup'||a.phase==='active'){const angle=Math.atan2(a.facing.y,a.facing.x),arc=a.attack.arc/2;graphics.moveTo(a.position.x,a.position.y).arc(a.position.x,a.position.y,a.attack.reach,angle-arc,angle+arc).closePath().fill({color:a.phase==='active'?0xb04d35:0xddae4c,alpha:.5})}});
 for(const b of s.projectiles)graphics.circle(b.position.x,b.position.y,b.radius).fill(0x9b4738);
 if(++count%6===0||s.result!=='playing')setHud({hp:s.player.hp,enemy:s.enemies.reduce((n,e)=>n+e.hp,0),result:s.result,tick:s.tick});});setReady(true);
 })().catch(()=>{if(!stopped){setReady(false);setLoadError(true)}});const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if([' ','j','k','shift','w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='j'||k===' ')inputs.current.attack=true;if(k==='k'||k==='shift')inputs.current.defend=true;if(k==='w'||k==='arrowup')inputs.current.y=-1;if(k==='s'||k==='arrowdown')inputs.current.y=1;if(k==='a'||k==='arrowleft')inputs.current.x=-1;if(k==='d'||k==='arrowright')inputs.current.x=1};const up=(e:KeyboardEvent)=>{if(['w','s','arrowup','arrowdown'].includes(e.key.toLowerCase()))inputs.current.y=0;if(['a','d','arrowleft','arrowright'].includes(e.key.toLowerCase()))inputs.current.x=0};const clear=()=>{inputs.current={x:0,y:0,attack:false,defend:false};clock.reset()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);return()=>{stopped=true;window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);if(app.renderer)app.destroy(true,{children:true})};
 },[kind]);
 return <section className="harbor-combat" aria-label={tx(['练习','Practice'],locale)}><div className="harbor-combat__heading"><div><small>{tx(['港口拳馆','HARBOR BOXING CLUB'],locale)}</small><h2>{tx(kind==='footwork'?['抵达另一端','Reach the far end']:kind==='endurance'?['保持二十秒','Keep moving for twenty seconds']:['友好切磋','A friendly spar'],locale)}</h2></div><button onClick={onLeave}>{tx(['停下来','Stop'],locale)}</button></div><p>{tx(kind==='footwork'?['绕开垫子和来球，走进另一头的绿色区域。不需要打倒教练。','Avoid the pads and balls. Reach the green area at the far end; no need to defeat the coach.']:kind==='endurance'?['保持移动二十秒，看到提示就闪开。可以随时停下。','Keep moving for twenty seconds. Dodge the windup; stop whenever you need.']:['看到出招提示就躲开，等对方收招再还击。','Move away from a windup. Counter while your partner recovers.'],locale)}</p><div className="harbor-combat__status"><span>{tx(['状态','Condition'],locale)} {hud.hp}/5</span><span>{kind==='sparring'?tx(['对手','Partner'],locale)+' '+hud.enemy+'/4':Math.floor(hud.tick/60)+'s'}</span></div><div ref={mount} className="harbor-arena"/>{loadError?<p role="alert">{tx(['练习场暂时没能准备好。可以先停下来，再重新进入。','The practice floor could not load. Stop and enter again when you are ready.'],locale)}</p>:!ready?<p>{tx(['准备练习场…','Preparing the practice floor…'],locale)}</p>:!started?<button className="harbor-primary harbor-wide" onClick={()=>{startedRef.current=true;setStarted(true)}}>{tx(['准备好了，开始','Ready—begin'],locale)}</button>:hud.result==='playing'?<div className="harbor-combat__controls"><Joystick label={tx(['移动','Move'],locale)} onMove={(x,y)=>{inputs.current.x=x;inputs.current.y=y}}/><button onPointerDown={()=>inputs.current.defend=true}><Icon name="shield"/>{tx(['闪避','Dodge'],locale)}</button><button className="harbor-primary" onPointerDown={()=>inputs.current.attack=true}><Icon name="attack"/>{tx(['出手','Strike'],locale)}</button></div>:<div className="harbor-result"><h3>{tx(hud.result==='won'?['完成了','Nicely done']:['先歇一下','Take a breath'],locale)}</h3><button className="harbor-primary" onClick={()=>onFinish(runs.current)}>{tx(['回到拳馆','Back to the club'],locale)}</button></div>}</section>
}
