import {relationshipStory,type StoryLead} from '../story/relationships';
import {relationshipNext,relationshipProfiles} from '../story/relationship-growth';
import {plotIds,plotDescription} from '../story/crops';
import {has,type Save} from '../story/state';
import {rooms,people,tx,type Locale,type Words} from '../world/data';
import {gameMinuteLabel,type LifeView} from './LifeBag';
import {useView} from './PlantUsesPanel';
import {fernDescription} from '../world/residents';
import {Icon} from './icons';
const labels:Record<StoryLead['state'],Words>={active:['进行中','In progress'],done:['已发生','Completed'],upcoming:['已约好','Planned'],available:['可以赴约','Time to meet'],'return-later':['改日也可以','Another day is fine']};
export function StoryCards({save,locale,onPlace,onPerson,limit,place}:{save:Save;locale:Locale;onPlace:(id:string)=>void;onPerson:(id:string)=>void;limit?:number;place?:string}){
 const model=relationshipStory(save),leads=model.leads.filter(l=>!place||l.place===place).sort((a,b)=>Number(a.state==='done')-Number(b.state==='done'));
 return <>{(limit?leads.filter(l=>l.state!=='done').slice(0,limit):leads).map((lead:StoryLead)=><article className="harbor-rel__story" key={lead.id} data-story={lead.id}><small>{tx(labels[lead.state],locale)}</small><h4>{tx(lead.title,locale)}</h4><p>{tx(lead.summary,locale)}</p>{lead.next&&<p>{tx(lead.next,locale)}</p>}{lead.place&&<button onClick={()=>onPlace(lead.place!)}><Icon name="map"/>{tx(rooms[lead.place].title,locale)}</button>}<div className="harbor-rel__links">{lead.people.map(id=><button key={id} onClick={()=>onPerson(id)}>{tx(people[id].name,locale)}<Icon name="people"/></button>)}</div></article>)}</>;
}
export function Matters({save,view,locale,busy,current,onPlace,onPerson,onAction,place}:{save:Save;view:LifeView|null;locale:Locale;busy:boolean;current:boolean;onPlace:(id:string)=>void;onPerson:(id:string)=>void;onAction:(action:string,payload?:unknown,target?:string)=>void;place?:string}){
 const p=useView(view),model=relationshipStory(save);
 return <div className="harbor-matters">
 <StoryCards save={save} locale={locale} onPlace={onPlace} onPerson={onPerson} place={place}/>
 {!place&&model.people.filter(p=>relationshipProfiles[p.id]).map(person=>{const next=relationshipNext(save,person.id);return next&&<article className="harbor-item" key={person.id}><h3>{tx(person.name,locale)}</h3><p>{tx(next.text,locale)}</p><button onClick={()=>onPerson(person.id)}>{tx(['查看你们之间的事','See your story together'],locale)}</button>{next.place&&<button onClick={()=>onPlace(next.place!)}><Icon name="map"/>{tx(rooms[next.place].title,locale)}</button>}</article>})}
 {(!place||place==='gym')&&save.turnBattle?.phase==='paused'&&<article className="harbor-item"><h3>{tx(['暂停的对练','Paused bout'],locale)}</h3><p>{tx(['回拳馆找伊德里斯，06:00–17:00可继续。','Return to Idris at the gym, 06:00–17:00, to resume.'],locale)}</p><button onClick={()=>onPlace('gym')}>{tx(['查看拳馆','Find the gym'],locale)}</button><button disabled={busy} onClick={()=>onAction('battle-end',undefined,save.turnBattle!.id)}>{tx(['结束暂停练习 · 无报酬','End paused practice · no payment'],locale)}</button></article>}
 {(!place||place==='gym')&&has(save,'battle:class:pay-pending')&&!has(save,'battle:class:paid')&&<button disabled={busy||save.cash>993} onClick={()=>onAction('battle-claim',undefined,'idris')}>{tx(['领取彩排谢礼 · $6','Collect rehearsal thanks · $6'],locale)}</button>}
 {(!place||place==='cafe')&&view?.order&&<article className="harbor-item" data-life-order><h3>{tx(['西奥的脆荚订单','Theo’s snap pea order'],locale)}</h3><p>{tx([`需要2份，可用${view.order.availablePinnedProduce}份。`,`Needs 2 units; ${view.order.availablePinnedProduce} available.`],locale)} {gameMinuteLabel(view.order.definition.dueMinute,locale)}</p><button onClick={()=>onPlace('cafe')}>{tx(['去咖啡馆当面交货','Find the café for delivery'],locale)}</button>{view.order.closeAvailable&&<button disabled={busy||!current} onClick={()=>onAction('life:close-order',{command:{verb:'close-order'}},'life-bag')}>{tx(['关闭过期订单 · 保留产物','Close expired order · keep produce'],locale)}</button>}</article>}
 {(!place||place==='cafe')&&p?.order&&<article className="harbor-item" data-plant-use-bag><h3>{tx(['厨房的罗勒订单','Basil for the kitchen'],locale)}</h3><p>{tx([`需要2份，可用${p.availableBasil}份，交货+$7。`,`Needs 2 portions; ${p.availableBasil} available, delivery +$7.`],locale)} {gameMinuteLabel(p.order.dueMinute,locale)}</p><button onClick={()=>onPlace('cafe')}>{tx(['去咖啡馆当面交货','Find the café for delivery'],locale)}</button>{(save.townMinutes??540)>=p.order.dueMinute&&<button disabled={busy||!current} onClick={()=>onAction('plant-use:close-basil',undefined,'life-bag')}>{tx(['关闭过期订单 · 保留产物','Close expired order · keep produce'],locale)}</button>}</article>}
 {view?.animals?.commissions.filter(c=>c.active&&save.known.includes(c.definition.resident)).map(c=><article className="harbor-item" key={c.ref.id}><h3>{tx(c.definition.title,locale)}</h3><p>{tx(['没有期限；记录仍保留，分享需要在对方身边。','No deadline. Your records remain; share when you meet the neighbor.'],locale)}</p><button onClick={()=>onPerson(c.definition.resident)}>{tx(people[c.definition.resident].name,locale)}</button><button disabled={busy||!current} onClick={()=>onAction('animal-life:cancel',{command:{verb:'cancel',ref:c.ref}},'animal-notebook')}>{tx(['收起约定 · 保留发现','Set aside · keep discoveries'],locale)}</button></article>)}
 {(!place||place==='garden')&&has(save,'unpacked')&&<article className="harbor-item"><h3>{tx(['花园里的作物','Crops in the garden'],locale)}</h3>{plotIds.map(id=><p key={id}>{id.slice(-1)} · {tx(plotDescription(save,id),locale)}</p>)}{save.fernStartedAt!==undefined&&<p>{tx(fernDescription(save),locale)}</p>}<button onClick={()=>onPlace('garden')}>{tx(['查看花园','Find the garden'],locale)}</button></article>}
 {view?.plants?.plots.filter(b=>!place||b.scene===place).map(b=><article className="harbor-item" key={b.id}><h3>{tx(rooms[b.scene].title,locale)} · {tx(['新菜畦','New bed'],locale)}</h3><p>{b.status?tx(b.status.name,locale)+' · '+tx(b.status.ready?['可收成','Ready to harvest']:b.status.needsWater?['需要浇水','Needs water']:['正在生长','Growing'],locale):tx(['空畦','Empty bed'],locale)}</p><button onClick={()=>onPlace(b.scene)}>{tx(['查看地点','View location'],locale)}<Icon name="map"/></button></article>)}
 {save.fieldNotes?.rooms.filter(r=>!place||r.id===place).map(r=><article className="harbor-item" key={r.id}><h3>{tx(r.title,locale)}</h3><p>{tx([`已查看${r.observations.filter(o=>o.read).length}/${r.observations.length}条线索。`,`Clues read: ${r.observations.filter(o=>o.read).length}/${r.observations.length}.`],locale)}</p><button onClick={()=>onPlace(r.id)}>{tx(['查看地点','View location'],locale)}</button></article>)}
 {place&&<p>{tx(['此页只列出已知且有记录的事情，不表示已探索此地的全部内容。','Only known, recorded matters appear here. There may be more to discover.'],locale)}</p>}
 {!model.leads.length&&!has(save,'unpacked')&&!view?.order&&!p?.order&&<p>{tx(['先认识小镇里的人。已有约定与探索会留在这里。','Meet someone in town. Plans and explorations will appear here.'],locale)}</p>}
 </div>;
}
