import {useEffect,useRef,useState} from 'react';
import {residentGuide} from '../story/resident-guide';
import {relationshipStory,type StoryLead} from '../story/relationships';
import type {Save} from '../story/state';
import {rooms,tx,type Locale,type Words} from '../world/data';
import {Icon} from './icons';
import './relationships.css';

const status:Record<StoryLead['state'],Words>={active:['进行中','In progress'],done:['已发生','Completed'],upcoming:['已约好','Planned'],available:['现在可以赴约','Time to meet'], 'return-later':['另一个傍晚也可以','Another evening is fine']};
export function Relationships({save,locale,initialPerson,onMap,onPortrait}:{save:Save;locale:Locale;initialPerson?:string;onMap:(place:string,person?:string)=>void;onPortrait:(person:string)=>void}){
 const model=relationshipStory(save),[selected,setSelected]=useState(initialPerson),[tab,setTab]=useState<'people'|'stories'>('people'),[showHistory,setShowHistory]=useState(false),heading=useRef<HTMLHeadingElement>(null);
 const person=model.people.find(p=>p.id===selected);
 const open=(id:string)=>{setSelected(id);setShowHistory(false)};
 useEffect(()=>{heading.current?.focus();heading.current?.closest('.harbor-panel__body')?.scrollTo(0,0)},[selected,tab]);
 const card=(lead:StoryLead)=><article className="harbor-rel__story" key={lead.id} data-story={lead.id}><small>{tx(status[lead.state],locale)}</small><h4>{tx(lead.title,locale)}</h4><p>{tx(lead.summary,locale)}</p>{lead.next&&<p className="harbor-rel__next">{tx(lead.next,locale)}</p>}{lead.place&&<button className="harbor-rel__place" onClick={()=>onMap(lead.place!,person?.id)}><Icon name="map"/>{tx(rooms[lead.place].title,locale)} · {tx(['查看地图','View map'],locale)}</button>}<div className="harbor-rel__links">{lead.people.filter(id=>id!==person?.id).map(id=><button key={id} onClick={()=>open(id)}>{tx(model.people.find(p=>p.id===id)!.name,locale)}<Icon name="arrow"/></button>)}</div></article>;
 return <div className="harbor-rel">
 {person?<><button className="harbor-link" onClick={()=>{setSelected(undefined);setShowHistory(false)}}>{tx(['返回列表','Back to list'],locale)}</button><div className="harbor-rel__identity"><button aria-label={tx(['放大人物肖像','Enlarge portrait'],locale)} onClick={()=>onPortrait(person.id)}><img src={`./art/${person.art}-root-v2.png`} alt={tx(person.name,locale)} draggable={false}/></button><div><h3 ref={heading} tabIndex={-1}>{tx(person.name,locale)}</h3><small>{tx(person.stage,locale)}</small><p>{tx(person.role,locale)}</p></div></div>
 {(()=>{const g=residentGuide(save,person.id);return g?<section className="harbor-resident-guide"><p>{tx(g.now,locale)}</p><p>{tx(g.then,locale)}</p>{g.mapScene&&<button onClick={()=>onMap(g.mapScene!,person.id)}>{tx(['查看日程地点','View routine location'],locale)}</button>}</section>:null})()}
 <h3>{tx(['相关事情' ,'Stories together'],locale)}</h3>{person.related.length?person.related.slice().sort((a,b)=>Number(a.state==='done')-Number(b.state==='done')).map(card):<p>{tx(['还没有一起处理的事情。见面时，可以聊聊彼此的生活。','No shared errands yet. You can simply talk about life when you meet.'],locale)}</p>}
 {person.places.length>0&&<section><h3>{tx(['熟悉的去处','Familiar places'],locale)}</h3><p>{tx(['这些是熟悉的去处，不表示对方此刻一定在这里。','These are familiar places, not a live location.'],locale)}</p><div className="harbor-rel__links">{person.places.map(id=><button key={id} onClick={()=>onMap(id,person.id)}>{tx(rooms[id].title,locale)}<Icon name="map"/></button>)}</div></section>}
 <button className="harbor-rel__history" aria-expanded={showHistory} onClick={()=>setShowHistory(!showHistory)}>{tx(showHistory?['收起谈话记录','Hide conversations']:['查看谈话记录','Read conversations'],locale)} ({person.history.length})</button>{showHistory&&<section aria-label={tx(['谈话记录','Conversations'],locale)}><p className="harbor-rel__muted">{tx(['这是当时的记录；眼前的进展以“相关事情”为准。','These are earlier conversations. Stories together shows your current progress.'],locale)}</p>{person.history.length?person.history.map(h=><article className="harbor-item" key={h.id}>{h.question&&<p className="harbor-question">{h.question}</p>}<p>{tx(h.text,locale)}</p></article>):<p>{tx(['旧存档没有保留具体谈话，已认识的人仍会留在这里。','This older save has no conversation text. People you met remain here.'],locale)}</p>}</section>}
 </>:<><div className="harbor-rel__tabs" role="group" aria-label={tx(['人物与事情','People and stories'],locale)}><button aria-pressed={tab==='people'} onClick={()=>setTab('people')}>{tx(['认识的人','People you know'],locale)}</button><button aria-pressed={tab==='stories'} onClick={()=>setTab('stories')}>{tx(['相关事情','Shared stories'],locale)}</button></div><h3 ref={heading} tabIndex={-1}>{tx(tab==='people'?['相识从一句问候开始','It starts with hello']:['从一段相识，找到下一步','Find your next step together'],locale)}</h3>{tab==='people'?<div className="harbor-rel__list">{model.people.length?model.people.map(p=><button className="harbor-rel__person" key={p.id} onClick={()=>open(p.id)}><img src={`./art/${p.art}-root-v2.png`} alt="" draggable={false}/><span><strong>{tx(p.name,locale)}</strong><small>{tx(p.stage,locale)}</small><span>{tx(p.role,locale)}</span></span><Icon name="arrow"/></button>):<p>{tx(['打过招呼的人会出现在这里。先去车站街，和提钥匙的女士聊聊吧。','People appear here after you meet. Start with the woman holding the keys on Station Street.'],locale)}</p>}</div>:model.leads.length?model.leads.slice().sort((a,b)=>Number(a.state==='done')-Number(b.state==='done')).map(card):<p>{tx(['还没有共同的事情。先认识一个人，慢慢了解海湾。','No shared stories yet. Meet someone and get to know the bay at your own pace.'],locale)}</p>}</>}
 </div>;
}
