import React,{useState} from 'react';
import {tx,type Words,type Locale} from '../world/data';import {boutConfigs,type TurnBattle as Battle} from '../story/turn-battle';import {intent,type Move,type Turn} from '../turn-combat/core';import {Icon} from './icons';
const moveLabels:Record<Move,Words>={strike:['出招','Strike'],guard:['防守','Guard'],recover:['调整','Recover'],supply:['吃打包点心','Eat packed snack']};
const intentLabels={heavy:['重击','Heavy strike'],light:['轻击','Light strike'],rest:['休整','Rest']} satisfies Record<string,Words>;
export function TurnBattle({battle,locale,busy,error,snacks,completed,onAction,onRetry}:{battle:Battle;locale:Locale;busy:boolean;error:Words|null;snacks:number;completed:boolean;onAction:(a:string,p?:unknown)=>void;onRetry:()=>void}){
 const [bag,setBag]=useState(false),[confirmEnd,setConfirmEnd]=useState(false);const b=battle.bout,c=boutConfigs[battle.encounter],next=intent(c,b),result=battle.phase==='result';
 const row=(t:Turn)=>`${tx(['第','Round '],locale)}${t.round}${locale==='zh'?'轮':''} · ${tx(moveLabels[t.move],locale)} · ${tx(['对方','Opponent'],locale)} −${t.dealt} · ${tx(['你','You'],locale)} −${t.taken}${t.healed?' +'+t.healed:''}`;
 return <div className="harbor-backdrop"><section className="harbor-panel harbor-turn" aria-label={tx(['回合对练','Turn-based practice'],locale)}><header><div><small>{tx(['港口拳馆 · 伊德里斯','Harbor Boxing Club · Idris'],locale)}</small><h2>{tx(battle.encounter==='training'?['看清动作，再应对','Read the move, then respond']:['开课前的彩排','Before the Open Class'],locale)}</h2></div>{!result&&<button disabled={busy} onClick={()=>onAction('battle-pause')} aria-label={tx(['暂停并返回小镇','Pause and return to town'],locale)}><Icon name="close"/></button>}</header>
 <div className="harbor-panel__body">
 <p>{tx(['本场状态归零只结束这次练习。随时暂停，可以去收菜或见邻居。','Zero condition ends only this bout. Pause any time to tend crops or visit a neighbor.'],locale)}</p>
 <div className="harbor-turn__condition"><div><span>{tx(['你的本场状态','Your bout condition'],locale)}</span><strong>{b.player} / {c.playerMax}</strong><meter min={0} max={c.playerMax} value={b.player}/></div><div><span>{tx(['教练本场状态','Coach’s bout condition'],locale)}</span><strong>{b.opponent} / {c.opponentMax}</strong><meter min={0} max={c.opponentMax} value={b.opponent}/></div></div>
 {!result&&<div className="harbor-turn__intent"><small>{tx(['下一轮预告','Next intent'],locale)} · {b.round+1} / {c.maxRounds}</small><h3>{tx(intentLabels[next.id],locale)} · {next.damage}</h3><p>{tx(next.id==='heavy'?['防守能减轻重击，让紧接的出招更有力。','Guard reduces the heavy hit and strengthens your next strike.']:next.id==='rest'?['教练这轮不出招，可以进攻或恢复状态。','The coach will not attack this round. Strike or recover.']:['轻击也会消耗状态，想好下一步再出手。','A light hit still costs condition. Choose with the next move in mind.'],locale)}</p>{b.counter&&<strong>{tx(['防守后紧接出招：5','Strike immediately after guarding: 5'],locale)}</strong>}</div>}
 {b.log.length>0&&<p className="harbor-turn__receipt" key={b.round} aria-live="polite">{row(b.log.at(-1)!)}</p>}
 {busy&&<p role="status">{tx(['正在确认这一轮…','Confirming this turn…'],locale)}</p>}
 {error&&<div role="alert"><p className="harbor-error">{tx(error,locale)}</p><button disabled={busy} onClick={onRetry}>{tx(['重新读取并确认结果','Reload and confirm the result'],locale)}</button></div>}
 {result?<><h3>{tx(b.outcome==='won'?['这次练习完成了','Practice complete']:b.outcome==='lost'?['先喘口气','Take a breath']:['这次先练到这里','That is enough for now'],locale)}</h3><p>{tx(['输赢都不会让你失去旅程。','Your journey is safe whatever the result.'],locale)}</p>{battle.encounter==='open-class'&&!completed?<><p>{tx(['伊德里斯问：“这个节奏，新手跟得上吗？”选择感受后领取首次彩排谢礼。','Idris asks, “Could a newcomer follow that pace?” Share your feedback to collect the first rehearsal payment.'],locale)}</p><div className="harbor-choices"><button disabled={busy} onClick={()=>onAction('battle-feedback',{feedback:'clear'})}>{tx(['预告很清楚，能提前准备','The cues gave me time to prepare'],locale)}</button><button disabled={busy} onClick={()=>onAction('battle-feedback',{feedback:'slower'})}>{tx(['我希望第一轮讲得再慢一点','I would explain the first round more slowly'],locale)}</button></div></>:<button className="harbor-primary" disabled={busy} onClick={()=>onAction('battle-close')}>{tx(['收好记录，返回小镇','Keep the record and return'],locale)}</button>}</>:<>
 <div className="harbor-turn__actions">{(['strike','guard','recover'] as Move[]).map(move=><button className="harbor-primary" key={move} disabled={busy||!!error} onClick={()=>onAction('battle-move',{round:b.round,move})}><strong>{tx(moveLabels[move],locale)}</strong><small>{tx(move==='strike'?[`对方 −${b.counter?5:3}`,`Opponent −${b.counter?5:3}`]:move==='guard'?['本轮减伤，下次反击','Reduce this hit; counter next']:['恢复2，仍会受击','Recover 2; still take the hit'],locale)}</small></button>)}<button disabled={busy||battle.encounter==='training'||b.supplyUsed>0} onClick={()=>setBag(!bag)}><strong>{tx(['行囊','Bag'],locale)}</strong><small>{tx(battle.encounter==='training'?['免费训练无需补给','No supplies in free training']:b.supplyUsed?['本场已经用过','Used this bout']:[`可用点心 ${snacks}`,`Packed snacks: ${snacks}`],locale)}</small></button></div>
 {bag&&<div className="harbor-turn__intent"><p>{tx(snacks?['使用1份点心，恢复4本场状态并占一轮。','Use one snack to recover 4 condition. This takes a turn.']:['暂无本场可用补给。杂货铺出售打包点心。','No supplies for this bout. The grocer sells packed snacks.'],locale)}</p>{snacks>0&&<button disabled={busy||!!error} onClick={()=>{setBag(false);onAction('battle-move',{round:b.round,move:'supply'})}}>{tx(['确认使用一份','Use one snack'],locale)}</button>}</div>}
 <button className="harbor-link" disabled={busy} onClick={()=>onAction('battle-pause')}>{tx(['暂停并返回小镇','Pause and return to town'],locale)}</button><details><summary>{tx(['结束本次练习','End this bout'],locale)}</summary><p>{tx(['不领取本场报酬。用掉的点心和时间保留。','No payment for this bout. Used snacks and time stay spent.'],locale)}</p><button disabled={busy} onClick={()=>setConfirmEnd(true)}>{tx(['我要结束本次','End this attempt'],locale)}</button>{confirmEnd&&<button disabled={busy} onClick={()=>onAction('battle-end')}>{tx(['确认结束','Confirm end'],locale)}</button>}</details></>}
 {b.log.length>0&&<details><summary>{tx(['查看逐轮记录','Review each round'],locale)}</summary>{b.log.map(t=><p key={t.round}>{row(t)}</p>)}</details>}
 </div></section></div>;
}
