import {outdoors} from './outdoors';import {roadBoundaries,terrainAt} from './road-boundaries';import {globalPoint,zonesFor} from '../candidate/continuity';import type {Rect,Point} from '../engine/world';
export type GroundEdge={rect:Rect;material:'sand'|'stone'|'wood';phase:number};
const cache=new Map<string,GroundEdge[]>();
const visible=(id:string,p:Point)=>id==='coast'?!(p.x>=1235&&p.x<2035&&p.y>=260&&p.y<820)&&p.y<805:id==='beach'?p.y>=805:id==='path'?p.x>=1235:id==='market'?p.y>=650:id==='bazaar'?p.y<650:true;
/** Native floor pixels only; irregular 18–30px soil shoulders, no collision or layout mutation. */
export function strongGroundEdges(scene:string):GroundEdge[]{const old=cache.get(scene);if(old)return old;const out:GroundEdge[]=[];for(const id of zonesFor(scene)){const layout=outdoors[id];if(!layout)continue;for(const e of roadBoundaries(layout)){const v=e.from.x===e.to.x,len=v?e.to.y-e.from.y:e.to.x-e.from.x,dir=e.side==='E'||e.side==='S'?1:-1;for(let t=0,i=0;t<len;t+=32,i++){const n=Math.min(32,len-t),depth=[22,30,26,18,28][i%5],p={x:e.from.x+(v?0:t),y:e.from.y+(v?t:0)},g=globalPoint(id,p);if(!visible(id,{x:g.x+(v?0:n/2),y:g.y+(v?n/2:0)}))continue;const local={x:v?p.x+(dir>0?-6:6-depth):p.x,y:v?p.y:p.y+(dir>0?-6:6-depth),w:v?depth:n,h:v?n:depth};let safe=true;for(let y=local.y+2;y<local.y+local.h;y+=4)for(let x=local.x+2;x<local.x+local.w;x+=4)if(!['grass','stone','sand'].includes(terrainAt(layout,{x,y})??''))safe=false;if(!safe)continue;out.push({rect:{...globalPoint(id,local),w:local.w,h:local.h},material:'sand',phase:i%4});
 // A darker native stone lip on the road side gives the wider earth shoulder depth.
 if(e.road==='stone'){const lip={x:v?p.x+(dir>0?-6:0):p.x,y:v?p.y:p.y+(dir>0?-6:0),w:v?6:n,h:v?n:6};out.push({rect:{...globalPoint(id,lip),w:lip.w,h:lip.h},material:'stone',phase:(i+2)%4})}
 }}}
 for(const id of zonesFor(scene))for(const e of waterBanks(id)){const v=e.from.x===e.to.x,len=v?e.to.y-e.from.y:e.to.x-e.from.x,dir=e.side==='E'||e.side==='S'?1:-1;for(let t=0,i=0;t<len;t+=32,i++){const n=Math.min(32,len-t),depth=[14,22,18,26][i%4],p={x:e.from.x+(v?0:t),y:e.from.y+(v?t:0)},r={x:v?p.x+(dir>0?-depth:0):p.x,y:v?p.y:p.y+(dir>0?-depth:0),w:v?depth:n,h:v?n:depth};let dry=true;for(let y=r.y+2;y<r.y+r.h;y+=4)for(let x=r.x+2;x<r.x+r.w;x+=4)if(!['wood','stone'].includes(terrainAt(outdoors[id],{x,y})??''))dry=false;if(dry)out.push({rect:{...globalPoint(id,r),w:r.w,h:r.h},material:'wood',phase:i%4})}}cache.set(scene,out);return out;}
export type WaterBank={from:Point;to:Point;side:'N'|'E'|'S'|'W';dry:'stone'|'wood'};
export function waterBanks(id:string):WaterBank[]{const l=outdoors[id];if(!l||!['harbor','dock'].includes(id))return [];const b=l.bounds,xs=[...new Set([b.x,b.x+b.w,...l.patches.flatMap(p=>[Math.max(b.x,Math.min(b.x+b.w,p.x)),Math.max(b.x,Math.min(b.x+b.w,p.x+p.w))])])].sort((a,b)=>a-b),ys=[...new Set([b.y,b.y+b.h,...l.patches.flatMap(p=>[Math.max(b.y,Math.min(b.y+b.h,p.y)),Math.max(b.y,Math.min(b.y+b.h,p.y+p.h))])])].sort((a,b)=>a-b),out:WaterBank[]=[];const add=(a:any,c:any,from:Point,to:Point,s:WaterBank['side'],r:WaterBank['side'])=>{if(c==='water'&&['stone','wood'].includes(a))out.push({from,to,side:s,dry:a});else if(a==='water'&&['stone','wood'].includes(c))out.push({from,to,side:r,dry:c})};for(let j=0;j<ys.length-1;j++)for(let i=1;i<xs.length-1;i++){const x=xs[i],y=(ys[j]+ys[j+1])/2;add(terrainAt(l,{x:(xs[i-1]+x)/2,y}),terrainAt(l,{x:(x+xs[i+1])/2,y}),{x,y:ys[j]},{x,y:ys[j+1]},'E','W')}for(let j=1;j<ys.length-1;j++)for(let i=0;i<xs.length-1;i++){const x=(xs[i]+xs[i+1])/2,y=ys[j];add(terrainAt(l,{x,y:(ys[j-1]+y)/2}),terrainAt(l,{x,y:(y+ys[j+1])/2}),{x:xs[i],y},{x:xs[i+1],y},'S','N')}return out;}
