// @ts-nocheck -- actual compiled Main/View/RPGJS; isolated synthetic local accounts only.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync,existsSync,mkdtempSync,rmSync} from 'node:fs';import {mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';
import {makeDemoServer} from './temporary-account-server';import {afterRainSeed,afterRainAssembly} from './after-rain-integration-fixture';
import {GAME_UUID} from '../src/game-id';import {legacyMintDefinitionHash} from '../server/plant-uses-rules';
const out=resolve(process.env.HARBOR_AFTER_RAIN_UI_DIR??'../evidence/ui/round1');await mkdir(out,{recursive:true});
const dir=mkdtempSync('/tmp/harbor-after-rain-ui-'),shell='/Users/yin/code/games/harbor-animal-ai-owner-aba82cc-20261009/evidence';
const loader=readFileSync(shell+'/guest-shell-public-20261009.js'),impl=readFileSync(shell+'/guest-shell-impl-public-20261009.js');
let spec,seed,cookie='',models=0;const assembly=afterRainAssembly(afterRainSeed(),{initial:(locale,id)=>({...structuredClone(seed),id,locale}),resolveDialogue:async()=>{models++;throw Error('MODEL_CLOSED')}});
const legacy=afterRainAssembly(afterRainSeed(),{afterRain:false,weather:{enabled:true,ecology:false,newStarts:false},initial:(locale,id)=>({...structuredClone(seed),id,locale})});
const server=await makeDemoServer({directory:dir,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,newsProject:assembly.newsProject,decorateAuthority:assembly.decorateAuthority,accountOnly:true});
const api=server.url+'/'+GAME_UUID+'/api';
async function call(account,path,body){const r=await fetch(api+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,'X-Harbor-Telegram-Id':account,'X-Harbor-Identity-Mode':'temporary-unverified','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data}
const report={scope:'Actual compiled independent candidate Main/View/RPGJS and original local temporary-account transport + SQLite; all identities and saves synthetic, external services blocked. Not production/normal login/physical/Telegram/comprehension evidence.',cases:[],pageErrors:[],missing:[],blocked:[],modelCalls:0,productionWrites:0};
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.wav':'audio/wav','.mp3':'audio/mpeg'};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
let specs=[];for(const [width,height] of [[320,568],[390,844],[1280,800]])for(const locale of ['en','zh'])specs.push({width,height,locale,kind:'ready'});
specs.push({width:390,height:844,locale:'en',kind:'lost-reply'},{width:320,height:568,locale:'en',kind:'stale-fact'},{width:390,height:844,locale:'en',kind:'expired'},{width:320,height:568,locale:'zh',kind:'old-unpinned'},{width:390,height:844,locale:'zh',kind:'legacy-mint'});
if(process.env.HARBOR_AFTER_RAIN_UI_CASES)specs=specs.filter(s=>process.env.HARBOR_AFTER_RAIN_UI_CASES.split(',').includes(`${s.width}-${s.locale}-${s.kind}`));
async function snap(p,label){await p.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.screenshot({path:out+'/'+label+'-platform-layout.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'document overflow')}
async function ready(p){await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));while(await p.locator('.harbor-opening button').isVisible())await p.locator('.harbor-opening button').click();await p.waitForTimeout(150)}
try{for(let index=0;index<specs.length;index++){
 spec=specs[index];const label=`${spec.width}-${spec.locale}-${spec.kind}`,account=String(736000+index),result={...spec,label};
 seed=afterRainSeed(randomUUID(),spec.kind==='expired'?780:740);if(spec.kind==='old-unpinned'){delete seed.weatherV1;delete seed.weatherEcologyV1}if(spec.kind==='legacy-mint')seed.plantUsesV1.mint.definitionHash=legacyMintDefinitionHash;
 await call(account,'/bootstrap',{});const initial=assembly.runtime.initial;if(spec.kind==='old-unpinned')assembly.runtime.initial=legacy.runtime.initial;let s;try{s=await call(account,'/sessions',{enrollment_id:randomUUID(),locale:spec.locale})}finally{assembly.runtime.initial=initial}
 const head=()=>call(account,'/sessions/'+s.id),c=await browser.newContext({viewport:{width:spec.width,height:spec.height},locale:spec.locale==='zh'?'zh-CN':'en-US',serviceWorkers:'block'});
 await c.addInitScript(({account,id,locale})=>{window.__name=f=>f;window.Aigram={isInAigram:true,telegramId:account,callAigramAPI:()=>Promise.resolve({retcode:0})};addEventListener('DOMContentLoaded',()=>{for(const [k,v] of [['harbor-locale',locale],['harbor-muted','1'],['harbor-opening:'+id,'3']])window.alteruLocalStorage.setItem(k,v)})},{account,id:s.id,locale:spec.locale});
 let lost=false;const weatherAttempts=[];
 await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.js'))return r.fulfill({contentType:'text/javascript',body:loader});if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.impl.js'))return r.fulfill({contentType:'text/javascript',body:impl});if(u.hostname!=='127.0.0.1'){report.blocked.push(u.origin+u.pathname);return r.abort()}
  if(u.pathname.includes('/api/')){const body=r.request().postDataJSON();if(body?.action==='weather-after-rain'){weatherAttempts.push(body);if(spec.kind==='stale-fact'&&weatherAttempts.length===1)return r.continue({postData:JSON.stringify({...body,payload:{...body.payload,factId:'expired-local-synthetic-fact'}})});if(spec.kind==='lost-reply'&&!lost){lost=true;await r.fetch();return r.abort('failed')}}return r.continue()}
  const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file)){report.missing.push(u.pathname);return r.fulfill({status:404,body:'Missing'})}return r.fulfill({contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
 const p=await c.newPage();result.actionReplies=[];p.on('response',async r=>{if(r.request().method()==='POST'&&r.url().endsWith('/action')){const body=r.request().postDataJSON();if(body?.action==='weather-after-rain')result.actionReplies.push({status:r.status(),body:await r.json()})}});p.setDefaultTimeout(20000);p.on('pageerror',e=>report.pageErrors.push({label,error:String(e)}));
 try{
  await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:spec.locale==='zh'?'继续':'Continue',exact:true}).click();await ready(p);await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await snap(p,label+'-world');
  await p.keyboard.press('e');await p.locator('.harbor-panel--entity').waitFor();await p.getByRole('heading',{name:spec.locale==='zh'?'自由对话':'Ask in your own words',exact:true}).waitFor();
  if(['expired','old-unpinned'].includes(spec.kind)){
   await p.waitForTimeout(250);assert.equal(await p.locator('[data-after-rain]').count(),0);await snap(p,label+'-no-cue');result.noInventedPastRain=true;
  }else{
   const box=p.locator('[data-after-rain="resident"]');await box.waitFor();assert.equal(await box.locator('[data-after-rain-clue]').count(),spec.kind==='legacy-mint'?0:1);
   const button=p.getByRole('button',{name:spec.locale==='zh'?'聊聊刚过的小雨':'Talk about the recent rain',exact:true});await button.waitFor();await button.scrollIntoViewIfNeeded();await p.waitForFunction(()=>!document.querySelector('[data-after-rain] button')?.disabled);await snap(p,label+'-cue');
   const bounds=await button.boundingBox();assert.ok(bounds.width>=44&&bounds.height>=44);result.target=bounds;const before=await head();
   await button.click();
   if(spec.kind==='stale-fact'){
    await p.getByText(spec.locale==='zh'?'雨段记录已变化，请重新查看当前进度。':'The rain record changed. Check your current progress again.',{exact:true}).waitFor();const after=await head();assert.equal(after.history.length,before.history.length);assert.deepEqual(after.items,before.items);assert.equal(await p.getByRole('button',{name:'Reconnect and check progress',exact:true}).count(),0);assert.equal(result.actionReplies.at(-1).status,409);assert.equal(result.actionReplies.at(-1).body.terminal,true);await p.getByText('The rain record changed. Check your current progress again.',{exact:true}).scrollIntoViewIfNeeded();await snap(p,label+'-failure');result.staleRejected=true;
    // Follow the original close/reopen route, then make a new explicit request.
    await p.getByRole('button',{name:'Close',exact:true}).click();await p.keyboard.press('e');const retry=p.getByRole('button',{name:'Talk about the recent rain',exact:true});await retry.scrollIntoViewIfNeeded();await p.waitForFunction(()=>!document.querySelector('[data-after-rain] button')?.disabled);await retry.click();await p.locator('.harbor-reply').waitFor();await p.locator('.harbor-reply').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished.catch(()=>{}))));const recovered=await head();assert.equal(recovered.history.length,before.history.length+1);assert.deepEqual(recovered.items,before.items);assert.equal(weatherAttempts.length,2);assert.notEqual(weatherAttempts[0].action_id,weatherAttempts[1].action_id);assert.equal(result.actionReplies.at(-1).status,200);await p.locator('.harbor-reply').scrollIntoViewIfNeeded();await snap(p,label+'-recovered');result.staleRecoveryNewExplicitRequest=true;
   }else{
    if(spec.kind==='lost-reply'){await p.waitForTimeout(250);await p.reload();await p.getByRole('button',{name:'Continue',exact:true}).click();await ready(p);await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await p.keyboard.press('e');assert.equal(weatherAttempts.length,2);assert.deepEqual(weatherAttempts[0],weatherAttempts[1]);result.lostReplySameOriginalRequest=true}
    await p.locator('.harbor-reply').waitFor();await p.locator('.harbor-reply').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished.catch(()=>{}))));await snap(p,label+'-reply');const after=await head();assert.equal(after.history.length,before.history.length+1);assert.deepEqual(after.items,before.items);assert.equal(after.cash,before.cash);assert.equal(after.flags.includes('free-dialogue-experienced'),false);assert.equal(after.history.at(-1).question,undefined);result.authoredHistoryId=after.history.at(-1).id;result.replyText=after.history.at(-1).text;result.noFakeAIFirstSuccess=true;
    await p.getByRole('button',{name:spec.locale==='zh'?'关闭':'Close',exact:true}).click();await p.keyboard.press('e');await p.locator('.harbor-reply').waitFor();result.originalReadingResume=true;
   }
  }
  await p.getByRole('button',{name:spec.locale==='zh'?'关闭':'Close',exact:true}).click();await p.getByRole('button',{name:spec.locale==='zh'?'人物':'People',exact:true}).first().click();await p.getByRole('button',{name:spec.locale==='zh'?'回忆':'Memories',exact:true}).click();await snap(p,label+'-memories');
  if(!['expired','old-unpinned'].includes(spec.kind)){const box=p.locator('[data-after-rain="notes"]');await box.waitFor();result.memoriesClueCount=await box.locator('[data-after-rain-clue]').count();}
  report.cases.push(result);writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log('PASS',label);
 }catch(e){await snap(p,label+'-FAIL').catch(()=>{});writeFileSync(out+'/'+label+'-FAIL.json',JSON.stringify({error:String(e),body:(await p.locator('body').innerText()).slice(0,4500)},null,2));throw e}finally{await c.close()}
 }
 // A fresh external guest uses the unchanged original shell and never gets a game account/world.
 const c=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});let nonGets=0;
 await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.js'))return r.fulfill({contentType:'text/javascript',body:loader});if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.impl.js'))return r.fulfill({contentType:'text/javascript',body:impl});if(u.hostname!=='127.0.0.1')return r.abort();if(r.request().method()!=='GET')nonGets++;if(u.pathname.includes('/api/'))return r.continue();const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));return r.fulfill({contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
 const p=await c.newPage();await p.goto(server.url+'/');await p.getByRole('button',{name:'Sign in to start',exact:true}).waitFor();assert.equal(await p.locator('#rpg').count(),0);assert.equal(nonGets,0);await p.screenshot({path:out+'/390-anonymous-external-guest.png'});report.anonymousNoIdentityWorldOrPost=true;await c.close();
 assert.equal(report.pageErrors.length,0);assert.equal(report.missing.length,0);assert.equal(models,0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e);throw e}finally{report.modelCalls=models;writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await server.close();rmSync(dir,{recursive:true,force:true})}
