import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const out='doc/qa/animals-integration-20261006/ui-final-build-v3';await mkdir(out,{recursive:true});
const report={fixedBuild:true,scope:'local actual production Main/View/RPGJS and SQLite synthetic authority; no native platform or real iPhone claim',originalPlayerModified:false,modelCalls:0,mediaPosts:0,pageErrors:[],failedArt:[],cases:[]};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});
const configurations=[...[320,390,1280].flatMap(width=>['cat-walk','gull'].map(name=>({width,name}))),{width:320,name:'cat-rest'},{width:390,name:'cat-rest'},{width:320,name:'cat-sleep'},{width:390,name:'cat-mira'},{width:390,name:'overlap'},{width:390,name:'home-nap'}];
const height=w=>w===320?568:w===390?844:800;
const engineSnapshot=()=>{
 const client=document.querySelector('#rpg')?.__rpgClient;const events=client?.sceneMap?.events?.()??{};
 const actors=Object.entries(events).filter(([id])=>id.startsWith('animal-')||id.startsWith('person-')).map(([id,a])=>({id,x:a.x(),y:a.y(),graphics:a.graphics(),animation:a.animationName()}));
 const textures=[];const visit=node=>{if(node.texture?.source){const source=node.texture.source;if(source.width===800&&source.height===576||source.width===1120&&source.height===640)textures.push({label:source.label,width:source.width,height:source.height,frame:{x:node.texture.frame.x,y:node.texture.frame.y,w:node.texture.frame.width,h:node.texture.frame.height},visible:node.visible,renderable:node.renderable,alpha:node.worldAlpha,bounds:{x:node.getBounds().x,y:node.getBounds().y,w:node.getBounds().width,h:node.getBounds().height}})}for(const child of node.children??[])visit(child)};if(client?.canvasApp?.stage)visit(client.canvasApp.stage);
 return {actors,textures,player:client?.getCurrentPlayer()?{x:client.getCurrentPlayer().x(),y:client.getCurrentPlayer().y()}:null,targets:[...document.querySelectorAll('[data-animal-foot-x]')].map(el=>({id:el.dataset.target,x:Number(el.dataset.animalFootX),y:Number(el.dataset.animalFootY),near:el.dataset.near}))};
};
try{for(const {width,name}of configurations){
 const context=await browser.newContext({viewport:{width,height:height(width)},locale:name==='cat-sleep'?'zh-CN':'en-US',recordVideo:{dir:out,size:{width,height:height(width)}}});
 await context.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)||/^(blob|data):/.test(r.request().url())?r.continue():r.abort());
 const seed=await(await context.request.post('http://127.0.0.1:5425/qa/prepare?case='+name+'&locale='+(name==='cat-sleep'?'zh':'en'))).json();assert.ok(seed.id);
 await context.addInitScript(({id,locale})=>addEventListener('DOMContentLoaded',()=>{window.alteruLocalStorage?.setItem('harbor-opening:'+id,'3');window.alteruLocalStorage?.setItem('harbor-locale',locale);window.alteruLocalStorage?.setItem('harbor-muted','1')}),{id:seed.id,locale:name==='cat-sleep'?'zh':'en'});
 const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(String(e)));page.on('response',r=>{if(/\/(art|animals)\//.test(r.url())&&r.status()>=400)report.failedArt.push(r.url())});
 await page.goto('http://127.0.0.1:5426/?debug=1');await page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await page.waitForTimeout(500);
 const touchTarget=async id=>{const el=page.locator('[data-target="'+id+'"]');const b=await el.boundingBox();assert.ok(b);const point={x:b.x+b.width/2,y:b.y+b.height/2};assert.equal(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-target]')?.getAttribute('data-target'),point),id);await page.mouse.click(point.x,point.y)};
 const snap=async phase=>page.screenshot({path:out+'/'+name+'-'+width+'-'+phase+'-platform-layout.png'});
 const before=await page.evaluate(engineSnapshot);await snap('first');const record={name,width,height:height(width),before};
 if(name==='cat-walk'||name==='gull'){
  await page.evaluate(()=>{const client=document.querySelector('#rpg').__rpgClient;window.__animalMotion=[];const until=performance.now()+25000;const frame=()=>{const actors=Object.entries(client.sceneMap.events()).filter(([id])=>id.startsWith('animal-')).map(([id,a])=>({id,x:a.x(),y:a.y(),animation:a.animationName(),graphic:a.graphics()[0]}));window.__animalMotion.push({t:performance.now(),actors});if(performance.now()<until)requestAnimationFrame(frame)};requestAnimationFrame(frame)});
  if(name==='gull'){await page.keyboard.down('ArrowRight');await page.waitForTimeout(650);await page.keyboard.up('ArrowRight');await page.keyboard.down('ArrowUp');await page.waitForTimeout(650);await page.keyboard.up('ArrowUp');await touchTarget('harbor-gull-3');await page.waitForTimeout(9500)}else await page.waitForTimeout(8500);
  await snap('motion');record.motion=await page.evaluate(()=>window.__animalMotion);record.afterMotion=await page.evaluate(engineSnapshot);
  if(name==='cat-walk'){
   await touchTarget('harbor-cat-1');await page.waitForFunction(()=>document.querySelector('[data-target="harbor-cat-1"]')?.dataset.near==='true',{timeout:15000});assert.equal(await page.locator('.harbor-panel').count(),0);
   await page.locator('.harbor-action.is-ready').click();await page.getByRole('button',{name:'Pet gently',exact:true}).click();await page.waitForTimeout(400);record.petHead=await(await context.request.get('http://127.0.0.1:5425/api/sessions/'+seed.id)).json();assert.equal(record.petHead.animalsV1.individuals['harbor-cat-1'].familiarity,1);assert.equal(record.petHead.townMinutes,seed.townMinutes);assert.equal(record.petHead.cash,seed.cash);assert.equal(record.petHead.energy,seed.energy);assert.deepEqual(record.petHead.items,seed.items);assert.deepEqual(record.petHead.relations,seed.relations);await snap('pet');
   await page.keyboard.press('Escape');await page.reload();await page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await page.waitForTimeout(350);record.restored=await(await context.request.get('http://127.0.0.1:5425/api/sessions/'+seed.id)).json();assert.deepEqual(record.restored.animalsV1,record.petHead.animalsV1);await snap('restored');
  }
 }else if(name==='cat-rest'){
  await touchTarget('harbor-cat-1');await page.waitForFunction(()=>document.querySelector('[data-target="harbor-cat-1"]')?.dataset.near==='true');await page.locator('.harbor-action.is-ready').click();await page.getByRole('button',{name:'Call softly',exact:true}).click();await page.waitForTimeout(350);record.called=await page.evaluate(engineSnapshot);await snap('called');await page.keyboard.press('Escape');await page.waitForTimeout(2600);record.returned=await page.evaluate(engineSnapshot);await snap('returned');
 }else if(name==='cat-sleep'){
  await touchTarget('harbor-cat-1');await page.waitForFunction(()=>document.querySelector('[data-target="harbor-cat-1"]')?.dataset.near==='true');await page.locator('.harbor-action.is-ready').click();assert.equal(await page.getByRole('button',{name:'轻声招呼',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'轻轻抚摸',exact:true}).count(),0);await snap('sleep-panel');
 }else if(name==='home-nap'){
  await page.waitForFunction(()=>document.querySelector('[data-target="bed"]')?.dataset.near==='true');await page.locator('.harbor-action.is-ready').click();await page.getByRole('button',{name:'Nap for three hours',exact:true}).click();await page.waitForTimeout(400);record.napHead=await(await context.request.get('http://127.0.0.1:5425/api/sessions/'+seed.id)).json();assert.equal(record.napHead.townMinutes,1080);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Map',exact:true}).click();await page.locator('.harbor-map-tabs').getByRole('button',{name:'Station Street',exact:true}).click();await page.locator('[data-place="station"]').click();await page.getByRole('button',{name:'Go here',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.harbor-loading')&&document.querySelector('.harbor-location')?.innerText.includes('Station Street'));await page.waitForTimeout(500);record.afterTravel=await page.evaluate(engineSnapshot);assert.ok(record.afterTravel.actors.some(a=>a.id==='animal-harbor-cat-2'&&a.graphics.length));await snap('after-travel');
 }else await page.waitForTimeout(2000);
 record.final=await page.evaluate(engineSnapshot);if(name==='cat-walk'||name==='gull')assert.ok(record.final.textures.length>0,'Actual animal texture must remain after the sequence');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await snap('second');
 const video=page.video();await context.close();record.video=out+'/'+name+'-'+width+'-platform-layout.webm';await video.saveAs(record.video);report.cases.push(record);console.log(JSON.stringify({done:name,width,animalGraphics:record.final.actors.filter(a=>a.id.startsWith('animal-')&&a.graphics.length).length,textures:record.final.textures.length}));await writeFile(out+'/browser-report.json',JSON.stringify(report,null,2));
}
assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.failedArt,[]);
}catch(e){report.failure=String(e);for(const [i,c] of browser.contexts().entries())for(const p of c.pages()){await p.screenshot({path:out+'/failure-'+i+'.png'}).catch(()=>{});console.error((await p.locator('body').innerText()).slice(-1800))}throw e}finally{await writeFile(out+'/browser-report.json',JSON.stringify(report,null,2));await browser.close()}
