import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createAnimalLife,sampleAnimal,assertAnimalNotebook} from '../server/animal-life';import {runtime} from '../server/runtime';import {AnimalContentRegistry,builtInCommissions,contentHash} from '../server/animal-content';import {initial,type Action} from '../src/story/state';import {rooms} from '../src/world/data';import {walkable} from '../src/engine/world';import {dynamicWorld} from '../src/dynamic-assets/layout';import {acceptedAnimals} from '../src/animals/art';import {slotAt} from '../src/animals/behavior';import type {AnimalLifeSave,AnimalCommand} from '../src/animal-life/types';
// @ts-expect-error frozen authority
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const content=new AnimalContentRegistry(),assembled=createAnimalLife(runtime,content);
const placed=(scene='station',minute=540):AnimalLifeSave=>({...initial('en',randomUUID()),scene,townMinutes:minute,position:rooms[scene].spawn,visited:Object.keys(rooms),flags:['key','unpacked','bag-returned','route-open','market-open','alternative-route'],items:{key:1},known:['mara','ruth','dani'],relations:{mara:0,ruth:0}});
export function observationPosition(s:AnimalLifeSave,id:string){const d=acceptedAnimals.find(a=>a.id===id)!,slot=slotAt(d,s.townMinutes??540)!;for(const q of slot.points)for(let y=-112;y<=112;y+=4)for(let x=-112;x<=112;x+=4){const p={x:q.x+x-8,y:q.y+y-6};if(!walkable(dynamicWorld(s.flags,false),s.scene,p))continue;try{sampleAnimal(s,id,p);return p}catch{}}throw Error('NO_QA_OBSERVATION_POSITION')}
const action=(s:AnimalLifeSave,target:string,c:AnimalCommand,p=s.position):Action=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:p,target,action:'animal-life:'+c.verb,payload:{command:c},...(rooms[s.scene].entities.find(e=>e.id===target)?.person?{actorPosition:rooms[s.scene].entities.find(e=>e.id===target)!.at}:{})});
const step=async(s:AnimalLifeSave,target:string,c:AnimalCommand,p=s.position)=>(await assembled.runtime.prepare(s,action(s,target,c,p))).head;
const observe=async(s:AnimalLifeSave,id:string)=>{const p=observationPosition(s,id);return step(await step(s,id,{verb:'sample'},p),id,{verb:'record'},p)};
const residentPos=(s:AnimalLifeSave,id:string)=>{const e=rooms[s.scene].entities.find(e=>e.person===id)!;return {id:e.id,p:e.approach}};

test('old save read/project is pure; all 22 resident/animal memories survive sampling',async()=>{const s=placed(),old=structuredClone(s);assembled.runtime.assertReadable(s);assembled.animalProject(s);assert.deepEqual(s,old);const p=observationPosition(s,'harbor-cat-1'),head=await step(s,'harbor-cat-1',{verb:'sample'},p);assert.deepEqual(head.items,s.items);assert.deepEqual(head.relations,s.relations);assert.equal(head.lifeV1,undefined);assert.equal(head.animalNotebookV1!.sample!.frame.pose,'sun-rest');});
test('cat sunny + sleep records reuse exact B2 discovery IDs; Mara completes once with knowledge only',async()=>{let s=placed();const ref=content.ref('animals:station-cat'),m=residentPos(s,'mara');s=await step(s,m.id,{verb:'brief',ref},m.p);s=await step(s,m.id,{verb:'accept',ref},m.p);s=await observe(s,'harbor-cat-1');assert.ok(s.lifeV1!.collections['observe:harbor-cat-1:sun-rest']);s={...s,scene:'courtyard',position:rooms.courtyard.spawn,townMinutes:1300};s=await observe(s,'harbor-cat-1');s={...s,scene:'station',position:m.p,townMinutes:1980};s=await step(s,m.id,{verb:'share',ref},m.p);assert.equal(s.relations.mara,1);assert.equal(s.animalNotebookV1!.pages.length,1);assert.deepEqual(s.items,{key:1});await assert.rejects(step(s,m.id,{verb:'share',ref},m.p),/COMMISSION_MISMATCH/);});
test('gulls use distinct identity spacing records; no flight/capture/item reward is invented',async()=>{let s=placed('dock',780);const ref=content.ref('animals:shore-space'),r=residentPos(s,'ruth');s=await step(s,r.id,{verb:'brief',ref},r.p);s=await step(s,r.id,{verb:'accept',ref},r.p);s={...s,scene:'coast',position:rooms.coast.spawn,townMinutes:1980};s=await observe(s,'harbor-gull-1');s=await observe(s,'harbor-gull-2');assert.equal(s.lifeV1!.collections['observe:harbor-gull-1:shore-space'].source!.kind,'animal-schedule');s={...s,scene:'dock',position:r.p,townMinutes:2220};s=await step(s,r.id,{verb:'share',ref},r.p);assert.equal(s.relations.ruth,1);assert.deepEqual(s.items,{key:1});});
test('forged proof, pose, target, stale scene/time/version, too close/away and challenge reject without mutation',async()=>{const s=placed(),p=observationPosition(s,'harbor-cat-1'),a=action(s,'harbor-cat-1',{verb:'sample'},p);const before=structuredClone(s);await assert.rejects(assembled.runtime.prepare(s,{...a,payload:{command:{verb:'sample',proof:true,pose:'sleep'}}}),/INVALID_ANIMAL_COMMAND/);assert.deepEqual(s,before);const sampled=await step(s,'harbor-cat-1',{verb:'sample'},p);for(const altered of [{...sampled,townMinutes:541},{...sampled,scene:'courtyard'},{...sampled,version:sampled.version+1}])await assert.rejects(step(altered,'harbor-cat-1',{verb:'record'},p),/STALE|INVALID_POSITION/);await assert.rejects(step(sampled,'harbor-cat-2',{verb:'record'},p),/STALE/);await assert.rejects(step({...s,activeChallenge:{id:'x',kind:'x',scene:s.scene}},'harbor-cat-1',{verb:'sample'},p),/CHALLENGE_ACTIVE/);await assert.rejects(step(s,'harbor-gull-1',{verb:'sample'},p),/ANIMAL_AWAY/);const forged=structuredClone(sampled);forged.animalNotebookV1!.sample!.frame.pose='sleep';assert.throws(()=>assertAnimalNotebook(forged,content),/UNSUPPORTED/);});
test('closed revision retains active settlement and pages; revision content and requirement tamper fail',async()=>{const changed={...builtInCommissions[0],revision:2,title:['新版本','New revision'] as [string,string]};const r=new AnimalContentRegistry([...builtInCommissions,changed],['animals:station-cat@2']);const a=createAnimalLife(runtime,r);let s=placed();const ref=content.ref('animals:station-cat'),m=residentPos(s,'mara');s=await step(s,m.id,{verb:'brief',ref},m.p);s=await step(s,m.id,{verb:'accept',ref},m.p);s=await observe(s,'harbor-cat-1');s={...s,scene:'courtyard',townMinutes:1300,position:rooms.courtyard.spawn};s=await observe(s,'harbor-cat-1');s={...s,scene:'station',townMinutes:1980,position:m.p};const completed=(await a.runtime.prepare(s,action(s,m.id,{verb:'share',ref},m.p))).head;assert.equal(completed.animalNotebookV1!.pages[0].ref.hash,contentHash(builtInCommissions[0]));await assert.rejects(a.runtime.prepare(placed(),action(placed(),m.id,{verb:'brief',ref},m.p)),/CLOSED/);assert.throws(()=>r.get({...ref,hash:'0'.repeat(64)}),/REF_MISMATCH/);});
test('SQLite original authority atomically commits sample+record, replays once, rejects CAS and survives reopen',async()=>{const root=mkdtempSync(join(tmpdir(),'harbor-animal-life-')),path=join(root,'authority.sqlite'),s=placed(),p=observationPosition(s,'harbor-cat-1');const options={path,worldId:'qa-animal-life',gameId:'qa-animal-life',environment:'test'};let store=openAsyncSqliteAuthorityStore(options);const rt={...assembled.runtime,initial:(_locale:any,id:string)=>({...s,id})};let authority=new AsyncSessionAuthority(store,rt);const head=await authority.create('synthetic-owner',randomUUID(),'en');const a=action(head,'harbor-cat-1',{verb:'sample'},p),sample=await authority.action('synthetic-owner',head.id,a);const record=action(sample.head,'harbor-cat-1',{verb:'record'},p);const committed=await authority.action('synthetic-owner',head.id,record);assert.deepEqual((await authority.action('synthetic-owner',head.id,record)).head,committed.head);await store.close();store=openAsyncSqliteAuthorityStore(options);authority=new AsyncSessionAuthority(store,rt);const replay=await authority.action('synthetic-owner',head.id,record);assert.deepEqual(replay.head,committed.head);await assert.rejects(authority.action('synthetic-owner',head.id,{...record,action_id:randomUUID()}),/VERSION_CONFLICT/);await store.close();});
