import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const out=process.env.HARBOR_ANIMAL_EVIDENCE;if(!out)throw Error('EVIDENCE_REQUIRED');await mkdir(out,{recursive:true});
const report={scope:'real Main/View/RPGJS/Pixi with synthetic SQLite authority; loopback only; all external network blocked',comprehension:'unverified',miniapp:'unverified',externalGuest:'unrun; no production shell request',modelCalls:0,mediaCalls:0,cases:[],errors:[]};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});let page;
const snap=()=>{const c=document.querySelector('#rpg').__rpgClient;return {player:{x:c.getCurrentPlayer().x(),y:c.getCurrentPlayer().y()},events:Object.entries(c.sceneMap.events()).map(([id,a])=>({id,x:a.x(),y:a.y(),graphics:a.graphics(),pose:a.animationName()})),canvas:!!c.canvasApp?.stage}};
try{for(const [fixture,animal] of (process.env.ANIMAL_UI_GULL_ONLY?[['animal-gull-space','harbor-gull-1']]:[['animal-cat-sun','harbor-cat-1'],['animal-cat-night','harbor-cat-1'],['animal-gull-space','harbor-gull-1']]))for(const [width,height] of (process.env.ANIMAL_UI_QUICK?[[390,844]]:[[390,844],[320,568]]))for(const locale of (process.env.ANIMAL_UI_QUICK?['en']:['en','zh'])){
 const r={fixture,animal,width,height,locale,steps:[]};report.cases.push(r);const context=await browser.newContext({viewport:{width,height},locale:locale==='zh'?'zh-CN':'en-US'});
 await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)||/^(blob|data):/.test(route.request().url())?route.continue():route.abort());await context.request.post('http://127.0.0.1:5511/qa/prepare?case='+fixture);page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto('http://127.0.0.1:5510/?debug=1');await page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));
 if(await page.locator('.harbor-opening button').count())for(let i=0;i<3;i++)await page.locator('.harbor-opening button').click();await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});
 const text=(zh,en)=>locale==='zh'?zh:en;const shot=async(label)=>{assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`${out}/${fixture}-${width}-${locale}-${label}-platform-layout.png`})};
 await page.waitForTimeout(300);r.before=await page.evaluate(snap);await shot('before');
 await page.locator(`[data-target="${animal}"]`).click();await page.waitForFunction(()=>document.querySelector('.harbor-action.is-ready')?.textContent.match(/Cat|猫|Gull|海鸥/),null,{timeout:12000});await page.keyboard.press('e');await page.getByRole('button',{name:text('静静看一会儿','Watch quietly'),exact:true}).waitFor();await shot('watch');
 await page.getByRole('button',{name:text('静静看一会儿','Watch quietly'),exact:true}).click();await page.getByRole('button',{name:text('记下这次观察','Record this observation'),exact:true}).waitFor();
 const sessions=await(await context.request.get('http://127.0.0.1:5511/api/sessions')).json(),id=sessions[0].id;const read=async()=>{const q=await context.request.get('http://127.0.0.1:5511/api/sessions/'+id);assert.equal(q.status(),200);return q.json()};const sampled=await read();assert.ok(sampled.animalNotebookV1.sample);await page.waitForTimeout(300);r.sample=sampled.animalNotebookV1.sample;r.renderer=await page.evaluate(snap);const ev=r.renderer.events.find(e=>e.id.includes(animal));assert.ok(ev,JSON.stringify(r.renderer));assert.equal(ev.x,r.sample.frame.foot.x);assert.equal(ev.y,r.sample.frame.foot.y);assert.ok(r.renderer.canvas);await shot('sample');
 await page.getByRole('button',{name:text('记下这次观察','Record this observation'),exact:true}).click();await page.getByText(text('观察已登记。它是一个发现，不是行囊里的动物或物品。','Recorded. This is a discovery, not an animal or item in your bag.'),{exact:true}).waitFor();const committed=await read();assert.ok(committed.lifeV1.collections[`observe:${animal}:${r.sample.behavior}`]);assert.equal(committed.animalNotebookV1.sample,undefined);assert.deepEqual(committed.items,sampled.items);r.savedVersion=committed.version;await shot('recorded');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:text('行囊','Bag'),exact:true}).click();await page.getByRole('button',{name:text('收藏','Collections'),exact:true}).click();await page.locator(`[data-life-record="observe:${animal}:${r.sample.behavior}"]`).waitFor();await shot('collection');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));assert.deepEqual((await read()).lifeV1.collections,committed.lifeV1.collections);r.result='pass';await context.close();
}report.result='pass';assert.deepEqual(report.errors,[]);}catch(e){report.result='failed';report.failure=String(e);if(page&&!page.isClosed()){report.text=await page.locator('body').innerText();await page.screenshot({path:out+'/failure-platform-layout.png'})}throw e}finally{await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2));await browser.close()}
console.log(JSON.stringify({result:report.result,cases:report.cases.length,errors:report.errors}));
