import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {compileAnimalStoryChoice,parseAnimalSemanticReview,assertCompiledAnimalChoice,animalGroundingPolicy,type AnimalStoryChoice} from '../server/animal-grounding';import {createAnimalProposalPipeline,createAnimalProposalRuntime} from '../server/animal-proposals';import {canonical,contentHash} from '../server/animal-content';import {runtime} from '../server/runtime';import {initial} from '../src/story/state';import recorded1 from './fixtures/animal-live-20261007.json';import recorded2 from './fixtures/animal-live-m2-20261007.json';
// @ts-expect-error frozen builder/gateway
import {createModelGateway} from '../vendor/dynamic-runtime/packages/dynamic-pipeline/model-gateway.mjs';
// @ts-expect-error frozen original authority
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const choice:AnimalStoryChoice={schema:1,id:'animals:separate-courtyard-routines',revision:1,resident:'dani',theme:'compare-routines',observations:[{animal:'harbor-cat-2',behavior:'sun-rest',period:'morning',scene:'courtyard'},{animal:'harbor-cat-3',behavior:'sun-rest',period:'afternoon',scene:'courtyard'},{animal:'harbor-cat-2',behavior:'sleep',period:'night',scene:'courtyard'},{animal:'harbor-cat-3',behavior:'sleep',period:'night',scene:'courtyard'}]};
test('deterministic cat schedule distinguishes each sun-rest period and permits both actual courtyard night sleeps',()=>{
 const d=compileAnimalStoryChoice(choice,['dani']);assert.match(d.brief[1],/harbor cat 2 sun-resting in Residents’ Courtyard \(morning\)/);assert.match(d.brief[1],/harbor cat 3 sun-resting in Residents’ Courtyard \(afternoon\)/);assert.match(d.brief[1],/harbor cat 2 sleeping in Residents’ Courtyard \(night\)/);assert.match(d.brief[1],/harbor cat 3 sleeping in Residents’ Courtyard \(night\)/);
 for(const [index,period] of [[0,'afternoon'],[1,'morning'],[2,'afternoon']] as const){const c=structuredClone(choice);c.observations[index].period=period;assert.throws(()=>compileAnimalStoryChoice(c,['dani']),/SCHEDULE_MISMATCH/)}
 const wrong=structuredClone(choice);wrong.observations[0].scene='coast';assert.throws(()=>compileAnimalStoryChoice(wrong,['dani']),/SCHEDULE_MISMATCH/);assert.throws(()=>compileAnimalStoryChoice(choice,[]),/GROUNDED_FIELDS/);
});
test('no free factual prose, title, effect/reward, dog/crab ability or client proof fields; compiled facts reject tampering',()=>{
 for(const field of ['brief','title','page','rules','reward','proof','sourceHash'])assert.throws(()=>compileAnimalStoryChoice({...choice,[field]:'any model text'},['dani']),/GROUNDED_FIELDS/);
 assert.throws(()=>compileAnimalStoryChoice({...choice,observations:choice.observations.map((o,i)=>i?o:{...o,animal:'new-crab'})},['dani']),/SCHEDULE_MISMATCH/);const d=compileAnimalStoryChoice(choice,['dani']);assertCompiledAnimalChoice(choice,d);assert.throws(()=>assertCompiledAnimalChoice(choice,{...d,brief:['午后都在庭院','All courtyard cats sunbathe in the afternoon.']}),/GROUNDED_TAMPER/);assert.equal(animalGroundingPolicy.freeNarrative,false);
});
test('sealed M1/M2 responses remain protocol failures; exactly300 is valid,301/9 findings/positive accepted findings reject without truncation',()=>{
 const before=canonical(recorded2);assert.throws(()=>parseAnimalSemanticReview(recorded1.review),/REVIEW_INVALID/);assert.throws(()=>parseAnimalSemanticReview(recorded2.review),/REVIEW_INVALID/);assert.equal(JSON.parse(recorded2.review).findings[0].length,599);assert.throws(()=>compileAnimalStoryChoice(JSON.parse(recorded2.draft),['dani']),/GROUNDED_FIELDS/);
 const v={format:'harbor-animal-review-v1',passed:false,findings:['x'.repeat(300)]};assert.equal(parseAnimalSemanticReview(JSON.stringify(v)).findings[0].length,300);for(const bad of [{...v,findings:['x'.repeat(301)]},{...v,findings:Array(9).fill('short')},{...v,passed:true},{...v,extra:1}])assert.throws(()=>parseAnimalSemanticReview(JSON.stringify(bad)),/REVIEW_INVALID/);assert.equal(canonical(recorded2),before);
});
test('new constrained local fixture stages two cached calls through existing gateway/CAS; adopts optional definition only, readback survives disabled new starts',async()=>{
 const store=openAsyncSqliteAuthorityStore({path:':memory:',worldId:'grounded-free-fixture',gameId:'grounded-free-fixture',environment:'test'});let calls=0;try{
  const gateway=await createModelGateway({store,budgetId:'free-local-fixture',maximum:2,ownerLimits:{'qa-owner':2},transport:async()=>++calls===1?JSON.stringify(choice):JSON.stringify({format:'harbor-animal-review-v2',passed:true,findings:[]})}),pipeline=createAnimalProposalPipeline(store,gateway,'grounded-free-fixture'),base={...runtime,initial:(l:any,id:string)=>({...initial(l,id),known:['dani']})},assembly=createAnimalProposalRuntime(base,pipeline),authority=new AsyncSessionAuthority(store,assembly.runtime),head=await authority.create('qa-owner',randomUUID(),'en'),request=randomUUID(),artifact=await pipeline.propose('qa-owner',head,request);assert.equal(calls,2);assert.deepEqual(await authority.get('qa-owner',head.id),head);assert.deepEqual(await pipeline.propose('qa-owner',head,request),artifact);assert.equal(calls,2);assert.deepEqual(artifact.prepared.grounded,choice);assertCompiledAnimalChoice(choice,artifact.prepared.definition);
  const action={action_id:randomUUID(),expected_version:head.version,scene:head.scene,position:head.position,target:'animal-notebook',action:'animal-life:adopt',payload:{artifactHash:artifact.prepared.artifact_hash}},out=await authority.action('qa-owner',head.id,action);assert.deepEqual(out.head.items,head.items);assert.deepEqual(out.head.relations,head.relations);assert.equal(out.head.cash,head.cash);assert.equal(out.head.animalNotebookV1.adopted[0].ref.hash,contentHash(artifact.prepared.definition));assert.deepEqual((await authority.action('qa-owner',head.id,action)).head,out.head);const disabled=createAnimalProposalRuntime(base,pipeline,false);disabled.runtime.assertReadable(out.head);assert.equal(disabled.animalProject(out.head).commissions.find(c=>c.ref.id===choice.id)!.enabled,false);assert.equal(calls,2);
 }finally{store.close()}
});
test('unsupported plural afternoon facts reject before review or artifact, with original head and empty registry',async()=>{
 const store=openAsyncSqliteAuthorityStore({path:':memory:',worldId:'grounded-free-invalid',gameId:'grounded-free-invalid',environment:'test'});let calls=0;try{
  const wrong=structuredClone(choice);wrong.observations[0].period='afternoon';const gateway=await createModelGateway({store,budgetId:'free-invalid-fixture',maximum:2,ownerLimits:{'qa-owner':2},transport:async()=>{calls++;return JSON.stringify(wrong)}}),pipeline=createAnimalProposalPipeline(store,gateway,'grounded-free-invalid'),base={...runtime,initial:(l:any,id:string)=>({...initial(l,id),known:['dani']})},assembly=createAnimalProposalRuntime(base,pipeline),authority=new AsyncSessionAuthority(store,assembly.runtime),head=await authority.create('qa-owner',randomUUID(),'en'),request=randomUUID();await assert.rejects(pipeline.propose('qa-owner',head,request),/MODEL_DRAFT_INVALID/);assert.equal(calls,1);await assert.rejects(pipeline.propose('qa-owner',head,request),/MODEL_DRAFT_INVALID/);assert.equal(calls,1);assert.deepEqual(await authority.get('qa-owner',head.id),head);await assert.rejects(pipeline.load('qa-owner','0'.repeat(64)),/UNAVAILABLE/);
 }finally{store.close()}
});

test('constrained story completes actual authority observation/share loop, pins knowledge page and grants only original fixed relationship once',async()=>{
 const story:AnimalStoryChoice={...choice,id:'animals:shore-and-courtyard-v4',resident:'owen',theme:'leave-space',observations:[{animal:'harbor-cat-2',behavior:'sun-rest',period:'morning',scene:'courtyard'},{animal:'harbor-gull-3',behavior:'shore-space',period:'afternoon',scene:'dock'}]};const {rooms}=await import('../src/world/data'),{sampleAnimal}=await import('../server/animal-life'),{acceptedAnimals}=await import('../src/animals/art'),{slotAt}=await import('../src/animals/behavior'),{walkable}=await import('../src/engine/world'),{dynamicWorld}=await import('../src/dynamic-assets/layout');
 const store=openAsyncSqliteAuthorityStore({path:':memory:',worldId:'grounded-playable',gameId:'grounded-playable',environment:'test'});let calls=0;try{const gateway=await createModelGateway({store,budgetId:'free-playable',maximum:2,ownerLimits:{'qa-owner':2},transport:async()=>++calls===1?JSON.stringify(story):JSON.stringify({format:'harbor-animal-review-v2',passed:true,findings:[]})}),pipeline=createAnimalProposalPipeline(store,gateway,'grounded-playable'),base={...runtime,initial:(l:any,id:string)=>({...initial(l,id),scene:'coast',position:rooms.coast.spawn,visited:Object.keys(rooms),known:['owen','mara','ruth','dani'],flags:['key','unpacked','route-open','market-open'],items:{key:1}})},assembly=createAnimalProposalRuntime(base,pipeline),authority=new AsyncSessionAuthority(store,assembly.runtime);let s=await authority.create('qa-owner',randomUUID(),'en');const artifact=await pipeline.propose('qa-owner',s,randomUUID());s=(await authority.action('qa-owner',s.id,{action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target:'animal-notebook',action:'animal-life:adopt',payload:{artifactHash:artifact.prepared.artifact_hash}})).head;const ref=s.animalNotebookV1.adopted[0].ref;
 const run=async(action:string,target:string,p=s.position,payload?:any)=>{const e=rooms[s.scene].entities.find(e=>e.id===target);s=(await authority.action('qa-owner',s.id,{action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:p,target,action,payload,...(e?.person?{actorPosition:e.at}:{})})).head};
 await run('travel-map','harbor');let e=rooms.harbor.entities.find(e=>e.person==='owen')!;await run('animal-life:brief',e.id,e.approach,{command:{verb:'brief',ref}});await run('animal-life:accept',e.id,e.approach,{command:{verb:'accept',ref}});
 const observe=async(id:string)=>{const slot=slotAt(acceptedAnimals.find(d=>d.id===id)!,s.townMinutes)!;let point:any;outer:for(const q of slot.points)for(let y=-112;y<=112;y+=4)for(let x=-112;x<=112;x+=4){const p={x:q.x+x-8,y:q.y+y-6};if(!walkable(dynamicWorld(s.flags,false),s.scene,p))continue;try{sampleAnimal(s,id,p);point=p;break outer}catch{}}assert.ok(point);await run('animal-life:sample',id,point,{command:{verb:'sample'}});await run('animal-life:record',id,point,{command:{verb:'record'}})};
 await run('travel-map','courtyard');await observe('harbor-cat-2');await run('travel-map','home');e=rooms.home.entities.find(e=>e.actions?.includes('rest'))!;await run('rest',e.id,e.approach);await run('travel-map','dock');await observe('harbor-gull-3');await run('travel-map','path');e=rooms.path.entities.find(e=>e.person==='owen')!;const share={action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:e.approach,target:e.id,actorPosition:e.at,action:'animal-life:share',payload:{command:{verb:'share',ref}}};s=(await authority.action('qa-owner',s.id,share)).head;assert.equal(s.relations.owen,1);assert.equal(s.animalNotebookV1.pages[0].ref.hash,contentHash(artifact.prepared.definition));assert.deepEqual(s.items,{key:1});assert.deepEqual((await authority.action('qa-owner',s.id,share)).head,s);assert.equal(calls,2);assert.ok(s.lifeV1.collections['observe:harbor-cat-2:sun-rest']);assert.ok(s.lifeV1.collections['observe:harbor-gull-3:shore-space']);
 }finally{store.close()}
});
