import {Readable} from 'node:stream';import {randomUUID} from 'node:crypto';
import {createRuntime} from '../server/runtime';import {createApiHandler} from '../server/http';
// @ts-expect-error frozen local authority fixture
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
import {chromium} from 'playwright';import assert from 'node:assert/strict';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';import {resolve,extname} from 'node:path';
import {initial} from '../src/story/state';import {rooms,people,world} from '../src/world/data';import {walkable} from '../src/engine/world';
const root=resolve('/Users/yin/code/games/harbor-camera-avatar-owner-20261007'),dist=root+'/source/dist',out=root+'/evidence/inputs-combined';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});
const mime:any={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg','.svg':'image/svg+xml','.tmx':'application/xml'};
const report:any={scope:'Actual normal Main/View/RPGJS candidate with read-only synthetic in-memory API; fixtures are not Telegram measurements.',cases:[],errors:[],missing:[],unexpectedActions:[],discardedSyntheticCheckpoints:0,blockedExternal:[],productionSaveWrites:0,models:0,artGeneration:0,hostMeasurement:'UNVERIFIED',physicalPhone:'UNVERIFIED'};
function edge(scene:string,side:string){const r=rooms[scene].interior;let best:any=null,score=Infinity;const north=side.includes('north'),south=side.includes('south'),west=side.includes('west'),east=side.includes('east');const target={x:west?r.x:east?r.x+r.w-16:r.x+r.w/2-8,y:north?r.y:south?r.y+r.h-12:r.y+r.h/2};for(let y=r.y;y<=r.y+r.h-12;y+=2)for(let x=r.x;x<=r.x+r.w-16;x+=2){const d=(west||east?4:1)*Math.abs(x-target.x)+(north||south?4:1)*Math.abs(y-target.y);if(d<score&&walkable(world,scene,{x,y})){best={x,y};score=d}}return best}
async function measure(page:any){return page.evaluate(()=>{const c=(document.querySelector('#rpg') as any).__rpgClient,stage=c.canvasApp.stage;let hero:any,view:any,backdrop:any;const visit=(n:any)=>{if(n.texture?.source?.label?.includes('/hero.png'))hero=n;if('toWorld' in n&&'clamp' in n)view=n;if(n.label==='exploration-overscan')backdrop=n;for(const k of n.children??[])visit(k)};visit(stage);
 const rect=(selector:string)=>{const b=document.querySelector(selector)?.getBoundingClientRect();return b&&{x:b.x,y:b.y,w:b.width,h:b.height,bottom:b.bottom,right:b.right}};const rpg=rect('#rpg')!,w=rect('.harbor-world')!,b=hero.getBounds(),sx=rpg.w/parseFloat(c.width()),sy=rpg.h/parseFloat(c.height()),row=Math.floor(hero.texture.frame.y/128),col=Math.floor(hero.texture.frame.x/128);const alphas=[[[37,14,90,122],[36,14,91,122],[37,14,90,122]],[[39,14,88,122],[40,14,88,122],[38,14,90,122]],[[39,14,88,122],[40,14,88,122],[38,14,90,122]],[[41,14,86,122],[40,14,87,122],[41,14,87,122]]];const a=alphas[row][col];const actor={left:rpg.x+(b.x+b.width*a[0]/128)*sx,top:rpg.y+(b.y+b.height*a[1]/128)*sy,right:rpg.x+(b.x+b.width*a[2]/128)*sx,bottom:rpg.y+(b.y+b.height*a[3]/128)*sy};const objective=rect('.harbor-objective')!,controls=rect('.harbor-controls');const safe={left:w.x+12,top:objective.bottom+12,right:w.right-12,bottom:(controls?.y??w.bottom)-12};const targets=[...document.querySelectorAll<HTMLElement>('.harbor-target--portal[data-readable=true]')].filter(e=>getComputedStyle(e).visibility==='visible'&&getComputedStyle(e).opacity!=='0').map(e=>{const b=e.getBoundingClientRect();return {id:e.dataset.target,left:b.left,top:b.top,right:b.right,bottom:b.bottom}});
 return {player:{x:c.getCurrentPlayer().x(),y:c.getCurrentPlayer().y()},actor,safe,gaps:{top:actor.top-objective.bottom,bottom:(controls?.y??w.bottom)-actor.bottom,left:actor.left-w.x,right:w.right-actor.right},header:rect('.harbor-header'),location:rect('.harbor-location'),objective,controls,world:w,rpg,scale:sx,targets,camera:{center:{x:view.center.x,y:view.center.y},corner:view.toWorld(0,0),opposite:view.toWorld(parseFloat(c.width()),parseFloat(c.height())),clamp:view.plugins.get('clamp')?.options,followPaused:view.plugins.get('follow')?.paused,animatePaused:view.plugins.get('animate')?.paused},backdrop:backdrop&&{texture:backdrop.texture.source.label,world:{x:backdrop.x,y:backdrop.y,w:backdrop.width,h:backdrop.height},tileScale:{x:backdrop.tileScale.x,y:backdrop.tileScale.y}},period:(document.querySelector('.harbor-world') as HTMLElement).dataset.period,overflow:document.documentElement.scrollWidth>innerWidth+1};});}
function verify(m:any,label:string){for(const k of ['top','bottom','left','right'])assert.ok(m.gaps[k]>=11.5,label+' actor '+k+' '+m.gaps[k]);assert.equal(m.overflow,false,label+' overflow');assert.ok(m.backdrop,label+' backdrop');assert.ok(m.camera.followPaused!==false);for(const t of m.targets){assert.ok(t.left>=m.safe.left-1&&t.right<=m.safe.right+1&&t.top>=m.safe.top-1&&t.bottom<=m.safe.bottom+1,label+' caption '+t.id)}}
const actions:any[]=[],runtime=createRuntime(async()=>{throw Error('QA_MODEL_DISABLED')});
try{for(const width of [320,390]){
 const label=width+'-round-trip-platform-layout',locale='en',seed={...initial('en','synthetic-input'),scene:'cafe',position:rooms.cafe.entities.find(e=>e.id==='exit')!.approach,townMinutes:1350,flags:['key','unpacked','bag-returned'],known:Object.keys(people),items:{key:1},visited:Object.keys(rooms)};runtime.assertReadable(seed);
 const store=openAsyncSqliteAuthorityStore({path:':memory:',worldId:'camera-synthetic-qa',gameId:'camera-synthetic-qa'}),authority=new AsyncSessionAuthority(store,{...runtime,initial:(l:any,id:string)=>({...seed,id,locale:l})}),owner='synthetic-'+randomUUID(),api=createApiHandler({authority,usage:{status:async()=>({resetAt:0,dialogue:{remaining:0,maximum:0,retryAt:null,pending:0}})},noteMedia:{}});
 const context=await browser.newContext({viewport:{width,height:width===320?568:844},locale:'en-US',hasTouch:true});await context.addInitScript('window.__name = (fn) => fn');
 await context.route('**/*',async route=>{const req0=route.request(),url=new URL(req0.url());if(url.hostname!=='127.0.0.1'){report.blockedExternal.push(url.origin+url.pathname);return route.abort()}
 if(url.pathname.includes('/api/')){const endpoint=url.pathname.slice(url.pathname.indexOf('/api/'));if(endpoint==='/api/bootstrap')return route.fulfill({contentType:'application/json',body:JSON.stringify({mode:'local-synthetic'})});if(endpoint.endsWith('/action')){const a=req0.postDataJSON();actions.push({width,...a});assert.equal(a.action,'travel')}
 const raw=req0.postData(),req:any=Readable.from(raw?[Buffer.from(raw)]:[]);req.url=endpoint+url.search;req.method=req0.method();req.headers=req0.headers();let status=200,headers:any={},body=Buffer.alloc(0);const res:any={writeHead:(s:number,h:any)=>{status=s;headers=h??{}},end:(b:any)=>{body=Buffer.from(b??'')}};try{await api(req,res,owner)}catch(e:any){status=400;body=Buffer.from(JSON.stringify({error:e.code??e.message,terminal:true}))}return route.fulfill({status,headers,body});}
 const file=resolve(dist,'.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname)));if(!file.startsWith(dist+'/')||!existsSync(file)){report.missing.push(url.pathname);return route.fulfill({status:404,body:'missing'})}return route.fulfill({contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)});
 });const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto('http://127.0.0.1:5498/?debug=1');await page.waitForFunction(()=>!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));for(let i=0;i<3;i++)await page.locator('.harbor-opening button').click();await page.waitForTimeout(300);
 const cafeBefore=await measure(page);verify(cafeBefore,label+' cafe before');await page.locator('.harbor-action').click();await page.locator('.harbor-panel .harbor-primary').click();await page.waitForFunction(()=>(document.querySelector('#rpg') as any).__rpgClient.activeRoom().name.replace(/^map-/,'')==='station'&&!document.querySelector('.harbor-loading'));await page.waitForTimeout(250);const station=await measure(page);verify(station,label+' station');
 // Ground click after camera translation, with the actual inverse transform.
 const target={x:station.player.x,y:station.player.y+36};assert.ok(walkable(world,'station',target));const projected=await page.evaluate(p=>{const c=(document.querySelector('#rpg') as any).__rpgClient;let v:any;const visit=(n:any)=>{if('toWorld' in n&&'clamp' in n)v=n;for(const k of n.children??[])visit(k)};visit(c.canvasApp.stage);const q=v.toScreen(p.x,p.y),b=(document.querySelector('#rpg') as HTMLElement).getBoundingClientRect(),s=b.width/parseFloat(c.width());return {x:b.x+q.x*s,y:b.y+q.y*s}},target);await page.mouse.click(projected.x,projected.y);await page.waitForFunction(p=>{const s=(document.querySelector('#rpg') as any).__rpgClient.getCurrentPlayer();return Math.hypot(s.x()-p.x,s.y()-p.y)<1.5},target);const clicked=await measure(page);verify(clicked,label+' ground click');
 const stick=(await page.locator('.harbor-stick').boundingBox())!;await page.mouse.move(stick.x+stick.width/2,stick.y+stick.height/2);await page.mouse.down();await page.mouse.move(stick.x+stick.width/2+24,stick.y+stick.height/2);const frames=[];for(let i=0;i<5;i++){await page.waitForTimeout(80);const m=await measure(page);verify(m,label+' joystick frame '+i);frames.push(m)}await page.mouse.up();await page.waitForTimeout(150);const stopped=await measure(page);verify(stopped,label+' stop');assert.ok(stopped.player.x>clicked.player.x);await page.waitForTimeout(150);assert.deepEqual((await measure(page)).player,stopped.player);
 // The normal near-target button walks to the entrance, then the ordinary
 // panel submits the original travel command. All authority remains in-memory.
 const entrance=page.locator('[data-target="to-cafe"]');if(await entrance.isVisible())await entrance.click();else {assert.equal(await entrance.getAttribute('data-near'),'true');assert.equal(await page.locator('.harbor-action span').textContent(),'Tide & Table');}await page.waitForFunction(()=>document.querySelector('.harbor-action span')?.textContent==='Tide & Table');await page.waitForTimeout(350);await page.locator('.harbor-action').click();await page.locator('.harbor-panel .harbor-primary').click();await page.waitForFunction(()=>(document.querySelector('#rpg') as any).__rpgClient.activeRoom().name.replace(/^map-/,'')==='cafe'&&!document.querySelector('.harbor-loading'));await page.waitForTimeout(250);const cafeAfter=await measure(page);verify(cafeAfter,label+' returned');await page.screenshot({path:out+'/'+label+'.png'});report.cases.push({width,cafeBefore,station,groundClick:{target,projected,arrived:clicked.player},joystickFrames:frames,stopped,cafeAfter,authority:'original handler + in-memory synthetic SQLite',productionWrites:0});await context.close();await store.close();console.log('PASS',label);
 }assert.equal(actions.length,4);assert.deepEqual(report.errors,[]);assert.deepEqual(report.missing,[]);report.syntheticActions=actions;report.status='PASS';}catch(e:any){report.status='FAIL';report.failure=String(e.stack);throw e}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');await browser.close()}
