import {chromium} from 'playwright';import assert from 'node:assert/strict';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';import {resolve,extname} from 'node:path';
import {initial} from '../src/story/state';import {rooms,people,world} from '../src/world/data';import {walkable} from '../src/engine/world';
const root=resolve('/Users/yin/code/games/harbor-camera-avatar-owner-20261007'),dist=root+'/source/dist',out=root+'/evidence/camera-combined';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});
const mime:any={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg','.svg':'image/svg+xml','.tmx':'application/xml'};
const report:any={scope:'Actual normal Main/View/RPGJS candidate with read-only synthetic in-memory API; fixtures are not Telegram measurements.',cases:[],errors:[],missing:[],unexpectedActions:[],discardedSyntheticCheckpoints:0,blockedExternal:[],productionSaveWrites:0,models:0,artGeneration:0,hostMeasurement:'UNVERIFIED',physicalPhone:'UNVERIFIED'};
function edge(scene:string,side:string){const r=rooms[scene].interior;let best:any=null,score=Infinity;const north=side.includes('north'),south=side.includes('south'),west=side.includes('west'),east=side.includes('east');const target={x:west?r.x:east?r.x+r.w-16:r.x+r.w/2-8,y:north?r.y:south?r.y+r.h-12:r.y+r.h/2};for(let y=r.y;y<=r.y+r.h-12;y+=2)for(let x=r.x;x<=r.x+r.w-16;x+=2){const d=(west||east?4:1)*Math.abs(x-target.x)+(north||south?4:1)*Math.abs(y-target.y);if(d<score&&walkable(world,scene,{x,y})){best={x,y};score=d}}return best}
async function measure(page:any){return page.evaluate(()=>{const c=(document.querySelector('#rpg') as any).__rpgClient,stage=c.canvasApp.stage;let hero:any,view:any,backdrop:any;const visit=(n:any)=>{if(n.texture?.source?.label?.includes('/hero.png'))hero=n;if('toWorld' in n&&'clamp' in n)view=n;if(n.label==='exploration-overscan')backdrop=n;for(const k of n.children??[])visit(k)};visit(stage);
 const rect=(selector:string)=>{const b=document.querySelector(selector)?.getBoundingClientRect();return b&&{x:b.x,y:b.y,w:b.width,h:b.height,bottom:b.bottom,right:b.right}};const rpg=rect('#rpg')!,w=rect('.harbor-world')!,b=hero.getBounds(),sx=rpg.w/parseFloat(c.width()),sy=rpg.h/parseFloat(c.height()),row=Math.floor(hero.texture.frame.y/128),col=Math.floor(hero.texture.frame.x/128);const alphas=[[[37,14,90,122],[36,14,91,122],[37,14,90,122]],[[39,14,88,122],[40,14,88,122],[38,14,90,122]],[[39,14,88,122],[40,14,88,122],[38,14,90,122]],[[41,14,86,122],[40,14,87,122],[41,14,87,122]]];const a=alphas[row][col];const actor={left:rpg.x+(b.x+b.width*a[0]/128)*sx,top:rpg.y+(b.y+b.height*a[1]/128)*sy,right:rpg.x+(b.x+b.width*a[2]/128)*sx,bottom:rpg.y+(b.y+b.height*a[3]/128)*sy};const objective=rect('.harbor-objective')!,controls=rect('.harbor-controls');const safe={left:w.x+12,top:objective.bottom+12,right:w.right-12,bottom:(controls?.y??w.bottom)-12};const targets=[...document.querySelectorAll<HTMLElement>('.harbor-target--portal[data-readable=true]')].filter(e=>getComputedStyle(e).visibility==='visible'&&getComputedStyle(e).opacity!=='0').map(e=>{const b=e.getBoundingClientRect();return {id:e.dataset.target,left:b.left,top:b.top,right:b.right,bottom:b.bottom}});
 return {player:{x:c.getCurrentPlayer().x(),y:c.getCurrentPlayer().y()},actor,safe,gaps:{top:actor.top-objective.bottom,bottom:(controls?.y??w.bottom)-actor.bottom,left:actor.left-w.x,right:w.right-actor.right},header:rect('.harbor-header'),location:rect('.harbor-location'),objective,controls,world:w,rpg,scale:sx,targets,camera:{center:{x:view.center.x,y:view.center.y},corner:view.toWorld(0,0),opposite:view.toWorld(parseFloat(c.width()),parseFloat(c.height())),clamp:view.plugins.get('clamp')?.options,followPaused:view.plugins.get('follow')?.paused,animatePaused:view.plugins.get('animate')?.paused},backdrop:backdrop&&{texture:backdrop.texture.source.label,world:{x:backdrop.x,y:backdrop.y,w:backdrop.width,h:backdrop.height},tileScale:{x:backdrop.tileScale.x,y:backdrop.tileScale.y}},period:(document.querySelector('.harbor-world') as HTMLElement).dataset.period,overflow:document.documentElement.scrollWidth>innerWidth+1};});}
function verify(m:any,label:string){for(const k of ['top','bottom','left','right'])assert.ok(m.gaps[k]>=11.5,label+' actor '+k+' '+m.gaps[k]);assert.equal(m.overflow,false,label+' overflow');assert.ok(m.backdrop,label+' backdrop');assert.ok(m.camera.followPaused!==false);for(const t of m.targets){assert.ok(t.left>=m.safe.left-1&&t.right<=m.safe.right+1&&t.top>=m.safe.top-1&&t.bottom<=m.safe.bottom+1,label+' caption '+t.id)}}
const specs:any[]=[];
for(const [width,height] of [[320,568],[390,844],[1024,768]])for(const locale of ['en','zh'])for(const scene of ['station','cafe','garden','home'])for(const side of ['north','south'])specs.push({width,height,locale,scene,side,minute:780,screenshot:locale==='en'&&width!==1024&&['station','cafe'].includes(scene)});
for(const width of [320,390])for(const scene of ['station','cafe'])for(const side of ['north-west','north-east','south-west','south-east'])specs.push({width,height:width===320?568:844,locale:'en',scene,side,minute:1350,screenshot:width===320});
for(const width of [320,390])for(const scene of ['station','cafe'])specs.push({width,height:width===320?568:844,locale:'en',scene,side:'south',minute:1350,host:true,screenshot:true});
try{for(const spec of specs.filter(s=>!s.host&&[320,390].includes(s.width)&&['station','cafe'].includes(s.scene)&&['north','south'].includes(s.side)&&s.locale==='en')){const {width,height,locale,scene,side,minute,host}=spec,label=`${width}-${scene}-${side}-${locale}-${minute}-${host?'host-fixture':'platform-layout'}`,position=edge(scene,side);let save:any={...initial(locale,'synthetic-camera'),version:5,cursor:5,scene,position,townMinutes:minute,flags:['key','unpacked','bag-returned'],known:Object.keys(people),items:{key:1},history:[],visited:Object.keys(rooms)};const original=JSON.stringify(save);const context=await browser.newContext({viewport:{width,height},locale:locale==='en'?'en-US':'zh-CN',hasTouch:width<800});await context.addInitScript('window.__name = (fn) => fn');
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.hostname!=='127.0.0.1'){report.blockedExternal.push(url.origin+url.pathname);return route.abort()}
 if(url.pathname==='/host-fixture'){return route.fulfill({contentType:'text/html',body:'<!doctype html><style>*{box-sizing:border-box}body{margin:0;height:100dvh;display:grid;grid-template-rows:48px minmax(0,1fr) 64px;font:12px system-ui;background:#1b2637;color:white}header,footer{display:grid;place-items:center}iframe{width:100%;height:100%;border:0;min-height:0}</style><header>HOST FIXTURE · 48px top</header><iframe src="/play/?debug=1"></iframe><footer>HOST FIXTURE · 64px bottom · not Telegram</footer>'})}
 if(url.pathname.includes('/api/')){const endpoint=url.pathname.slice(url.pathname.indexOf('/api/'));let data:any={};if(endpoint==='/api/bootstrap')data={mode:'synthetic-readonly'};else if(endpoint==='/api/sessions')data=[{id:save.id,version:save.version,scene}];else if(endpoint==='/api/sessions/'+save.id)data=save;else if(endpoint.endsWith('/checkpoint')){report.discardedSyntheticCheckpoints++;data={}}else if(endpoint==='/api/usage')data={resetAt:0,dialogue:{remaining:0,maximum:0,retryAt:null,pending:0}};else{report.unexpectedActions.push(endpoint);return route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:'QA_WRITES_BLOCKED',terminal:true})})}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)})}
 const path=url.pathname.startsWith('/play/')?url.pathname.slice(5):url.pathname;const file=resolve(dist,'.'+(path==='/'?'/index.html':decodeURIComponent(path)));if(!file.startsWith(dist+'/')||!existsSync(file)){report.missing.push(path);return route.fulfill({status:404,body:'missing'})}return route.fulfill({status:200,contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)});
 });const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto('http://127.0.0.1:5498/'+(host?'host-fixture':'?debug=1'));const game:any=host?page.frames().find(f=>f.url().includes('/play/'))??await page.waitForEvent('framenavigated',{predicate:f=>f.url().includes('/play/')}):page;await game.waitForFunction(()=>!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));if(host)await game.locator('.harbor-app').evaluate((e:any)=>{e.style.setProperty('--harbor-safe-top','24px');e.style.setProperty('--harbor-safe-bottom','16px')});await page.waitForTimeout(400);const m=await measure(game);try{verify(m,label)}catch(e){writeFileSync(out+'/failed-case.json',JSON.stringify({label,metrics:m},null,2));await page.screenshot({path:out+'/'+label+'-FAIL.png'});throw e}
 const result:any={...spec,label,seedPosition:position,metrics:m,saveFixtureUnchanged:JSON.stringify(save)===original};if(width===320&&scene==='cafe')await page.screenshot({path:out+'/'+label+'.png'});
 if(width===320&&scene==='cafe'&&side==='south'&&locale==='en'){
  const p0=m.player;await game.locator('.harbor-action').click();assert.equal(await game.locator('.harbor-panel').count(),1);await page.keyboard.press('Escape');await page.waitForTimeout(150);const closed=await measure(game);verify(closed,label+' close');assert.deepEqual(closed.player,p0);result.interactionPanelReturnedSamePosition=true;
  await game.getByRole('button',{name:'Map',exact:true}).click();await page.keyboard.press('Escape');await page.waitForTimeout(150);verify(await measure(game),label+' map close');result.mapOpenClose=true;
 }
 if(!host&&width===390&&scene==='station'&&side==='south'&&locale==='en'){
  await page.keyboard.down('ArrowUp');await page.waitForTimeout(350);await page.keyboard.up('ArrowUp');await page.waitForTimeout(150);const stopped=await measure(game);verify(stopped,label+' moved');assert.ok(stopped.player.y<m.player.y);const p1=stopped.player;await page.waitForTimeout(150);assert.deepEqual((await measure(game)).player,p1);result.keyboardMoveStop={before:m.player,after:p1};
  await page.setViewportSize({width:320,height:568});await page.waitForTimeout(250);const resized=await measure(game);verify(resized,label+' resize');assert.deepEqual(resized.player,p1);result.resize={to:{width:320,height:568},metrics:resized};
  await game.getByRole('button',{name:'Menu',exact:true}).click();await game.getByRole('button',{name:'中文'}).click();await game.getByRole('button',{name:'关闭',exact:true}).click();await page.waitForTimeout(250);const localized=await measure(game);verify(localized,label+' language');assert.deepEqual(localized.player,p1);result.languageSwitch={to:'zh',metrics:localized};
 }
 report.cases.push(result);assert.equal(result.saveFixtureUnchanged,true);console.log('PASS',label,m.gaps);await context.close();writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');
 }assert.deepEqual(report.errors,[]);assert.deepEqual(report.missing,[]);assert.deepEqual(report.unexpectedActions,[]);assert.equal(report.cases.length,8);report.status='PASS';}catch(e:any){report.status='FAIL';report.failure=String(e.stack);throw e}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');await browser.close()}
