// @ts-nocheck -- actual compiled Main/View/RPGJS, own normal local browser + isolated SQLite.
import {rooms} from '../src/world/data';
import {initial} from '../src/story/state';import {GAME_UUID} from '../src/game-id';
import {chromium} from '../node_modules/playwright/index.mjs';
import {mkdtempSync,readFileSync,existsSync} from 'node:fs';import {writeFile,mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';
const root=resolve('..'),dist=resolve('dist'),moduleRoot=resolve('.');
const {makeDemoServer}=await import(moduleRoot+'/_qa/temporary-account-server.ts');
const {createExplorationAssembly}=await import(moduleRoot+'/server/exploration-assembly.ts'),{withWildMint}=await import(moduleRoot+'/server/wild-mint.ts'),{withBasilPlantUses}=await import(moduleRoot+'/server/plant-basil.ts');
const assembly=createExplorationAssembly({crabEnabled:true,resolveDialogue:async()=>{throw Error('MODEL_DISABLED')},decorateLife:r=>withWildMint(withBasilPlantUses(r),{enabled:true}),initial:(l,id)=>({...initial(l,id),scene:'cafe',position:rooms.cafe.entities.find(e=>e.id==='exit').approach,known:['mara'],flags:['key','unpacked','bag-returned'],items:{key:1},visited:['station','harbor']})});
const server=await makeDemoServer({directory:mkdtempSync('/tmp/harbor-joystick-'),providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority});

const report={scope:'normal compiled Main/View, own isolated SQLite/capability; cafe/station/cafe real entrance travel, motion receipts, menu, resize; not physical iPhone or Telegram',cases:[],pageErrors:[],paidCalls:0};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
const ready=async(p,scene)=>{await p.waitForFunction(id=>{const c=document.querySelector('#rpg')?.__rpgClient;return c?.getCurrentPlayer()&&c.activeRoom()?.name===id&&!document.querySelector('.harbor-loading')},scene,{timeout:60000});await p.waitForTimeout(200)};
async function snapshot(p,label){const m=await p.evaluate(()=>{const h=document.querySelector('#rpg'),c=h.__rpgClient;let hero,view;const visit=n=>{if(n.texture?.source?.label?.includes('/hero.png'))hero=n;if(n.toWorld&&n.clamp)view=n;for(const k of n.children??[])visit(k)};visit(c.canvasApp.stage);const b=hero.getBounds(),r=h.getBoundingClientRect(),world=document.querySelector('.harbor-world').getBoundingClientRect(),objective=document.querySelector('.harbor-objective').getBoundingClientRect(),controls=document.querySelector('.harbor-controls')?.getBoundingClientRect(),s=r.width/parseFloat(c.width()),q=c.getCurrentPlayer();return {scene:c.activeRoom().name,cameraOwner:c.cameraFollowTargetId(),headGap:r.y+(b.y+b.height*14/128)*s-objective.bottom,footGap:(controls?.y??world.bottom)-(r.y+(b.y+b.height*122/128)*s),position:{x:q.x(),y:q.y()},projected:{x:Number(h.dataset.projectedX),y:Number(h.dataset.projectedY)},pose:q.animationName(),worldPaused:h.dataset.worldPaused,overflow:document.documentElement.scrollWidth>innerWidth+1,camera:{x:view.center.x,y:view.center.y},dpr:devicePixelRatio}});assert.equal(m.cameraOwner,'harbor-safe-area-camera',label);assert.ok(m.headGap>10,label+' head safe '+m.headGap);assert.ok(m.footGap>10,label+' foot safe '+m.footGap);assert.equal(m.overflow,false);await p.screenshot({path:root+'/evidence/camera-'+label+'.png'});return {label,...m}}
try{for(const [width,height] of [[320,568],[390,844],[1280,800]]){
 const rec={width,height,states:[]};report.cases.push(rec);const c=await browser.newContext({viewport:{width,height},hasTouch:true,serviceWorkers:'block'});await c.addInitScript(()=>{window.__name=f=>f});
 await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname.includes('/api/'))return r.fulfill({response:await r.fetch({url:server.url+u.pathname+u.search})});const file=resolve(dist,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(dist+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({contentType:{'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.tmx':'application/xml'}[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
 const p=await c.newPage();p.on('pageerror',e=>report.pageErrors.push(String(e)));try{
 await p.goto(server.url+'/?debug=1');await ready(p,'cafe');for(let i=0;i<3;i++)await p.locator('.harbor-opening button').click();await p.waitForTimeout(1500);rec.states.push(await snapshot(p,width+'-cafe-initial'));
 await p.locator('.harbor-action').click();await p.locator('.harbor-panel .harbor-primary').click();await ready(p,'station');rec.states.push(await snapshot(p,width+'-station-arrival'));
 await p.locator('.harbor-action').click();await p.locator('.harbor-panel .harbor-primary').click();await ready(p,'cafe');rec.states.push(await snapshot(p,width+'-cafe-return'));
 await p.keyboard.down('ArrowUp');await p.waitForTimeout(500);await p.keyboard.up('ArrowUp');await p.waitForTimeout(120);rec.states.push(await snapshot(p,width+'-cafe-moving'));
 await p.locator('.harbor-header nav').getByRole('button',{name:'Map',exact:true}).click();await p.locator('.harbor-map-gesture').waitFor();await p.waitForTimeout(1600);await p.keyboard.press('Escape');await p.waitForSelector('.harbor-controls');await p.waitForTimeout(250);rec.states.push(await snapshot(p,width+'-menu-resume'));
 await p.setViewportSize({width:width===320?390:320,height:width===320?844:568});await p.waitForTimeout(400);rec.states.push(await snapshot(p,width+'-resized'));
 rec.result='PASS';
 }catch(e){rec.result='FAIL';rec.failure=String(e);await p.screenshot({path:root+'/evidence/camera-'+width+'-failure.png'})}finally{await c.unrouteAll({behavior:'ignoreErrors'});await c.close()}
 }assert.equal(report.pageErrors.length,0);assert.ok(report.cases.every(c=>c.result==='PASS'));report.result='PASS';
}catch(e){report.result='FAIL';report.failure=String(e)}finally{await browser.close();await server.close();await writeFile(root+'/evidence/camera-ownership.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report))}
