import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const stage=process.env.CHAPEL_QA_STAGE??'first',out='../evidence/ui-'+stage;await mkdir(out,{recursive:true});
const b=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']}),report=[];let active;
try{for(const f of [{w:320,h:568,locale:'zh',branch:'reading',owner:'990111'},{w:390,h:844,locale:'en',branch:'listening',owner:'990112'},{w:1280,h:800,locale:'en',branch:'reading',owner:'990113'}].filter(f=>!process.env.CHAPEL_QA_WIDTH||f.w===Number(process.env.CHAPEL_QA_WIDTH))){
 const c=await b.newContext({viewport:{width:f.w,height:f.h},hasTouch:f.w<600});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({status:200,body:''}));
 const seed=await(await c.request.get(`http://127.0.0.1:5591/qa/prepare?owner=${f.owner}&scene=hill&x=502&y=397&minute=780`)).json();assert.ok(seed.id,JSON.stringify(seed));
 await c.addInitScript(({id,owner,locale})=>{window.Aigram={isInAigram:true,telegramId:owner,callAigramAPI:async()=>({})};addEventListener('DOMContentLoaded',()=>{window.alteruLocalStorage.setItem('harbor-opening:'+id,'3');window.alteruLocalStorage.setItem('harbor-locale',locale);window.alteruLocalStorage.setItem('harbor-muted','1')})},{id:seed.id,owner:f.owner,locale:f.locale});
 const p=await c.newPage();active=p;const errors=[],failed=[],commands=[];p.on('pageerror',e=>errors.push(String(e)));p.on('response',async r=>{if(r.status()>=400){const body=await r.json().catch(()=>({}));failed.push({path:new URL(r.url()).pathname.split('/').slice(-1)[0],status:r.status(),error:body.error,terminal:body.terminal})}});p.on('request',r=>{if(r.url().endsWith('/action'))commands.push(r.postDataJSON()?.action)});await p.goto('http://127.0.0.1:5590/?debug=1');await p.getByRole('button',{name:f.locale==='zh'?'继续':'Continue',exact:true}).click();
 const ready=()=>p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await ready();await p.waitForTimeout(300);
 const shot=async(name)=>{await p.waitForTimeout(700);await p.screenshot({path:`${out}/${f.w}-${f.locale}-${name}.png`})};
 const head=async()=>(await c.request.get(`http://127.0.0.1:5591/api/sessions/${seed.id}?owner=${f.owner}`)).json();
 const move=async(key,ms)=>{await p.keyboard.down(key);await p.waitForTimeout(ms);await p.keyboard.up(key);await p.waitForTimeout(180)};
 const close=()=>p.getByRole('button',{name:f.locale==='zh'?'关闭':'Close',exact:true}).click();
 const focus=async(id)=>{const target=p.locator(`[data-target="${id}"]`);const label=await target.getAttribute('aria-label');if(!(await p.locator('.harbor-action').innerText()).includes(label))await target.click();await p.waitForFunction(id=>document.querySelector('.harbor-action')?.textContent.includes(document.querySelector(`[data-target="${id}"]`)?.getAttribute('aria-label')??'___'),id);assert.equal(await p.getByRole('dialog').count(),0,'approach does not open content');await shot(id+'-near');await p.locator('.harbor-action').click();await p.getByRole('dialog').waitFor();};
 const enterDoor=async()=>{await p.locator('.harbor-action').click();await p.getByRole('dialog').waitFor();await p.locator('.harbor-choices button').first().click()};
 await shot('outside-entry');await enterDoor();await p.waitForFunction(()=>document.querySelector('.harbor-location')?.textContent.includes('Chapel Hall')||document.querySelector('.harbor-location')?.textContent.includes('教堂大厅'));await ready();await shot('inside-entry');
 assert.equal((await head()).scene,'chapel');
 await move('ArrowRight',1050);await focus('chapel-note');await p.getByRole('button',{name:f.locale==='zh'?'读活动便条':'Read the activity note',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.harbor-dialogue')?.textContent.includes('12:00'));await shot('notice');assert.ok((await head()).flags.includes('chapel:notice-read'));await close();
 if(f.branch==='reading'){
  await move('ArrowLeft',1150);await move('ArrowUp',2050);await move('ArrowLeft',900);await focus('chapel-reading');await p.getByRole('button',{name:f.locale==='zh'?'整理阅读角 · 免费':'Arrange the reading corner · Free',exact:true}).click();
 }else{
  await move('ArrowLeft',400);await move('ArrowUp',400);await focus('chapel-seat');await p.getByRole('button',{name:'Stay and listen · Free',exact:true}).click();
 }
 await p.getByRole('button',{name:f.locale==='zh'?'回看这次相聚':'Remember the visit',exact:true}).waitFor();await shot('participated');const done=await head();assert.ok(done.flags.includes('chapel:completed'));assert.ok(done.flags.includes('chapel:participation:'+f.branch));assert.equal(done.cash,seed.cash);assert.deepEqual(done.items,seed.items);assert.equal(done.energy,seed.energy);await close();
 // A real visit to the main room aisle before returning to the south door.
 if(f.branch==='reading'){await move('ArrowRight',1000);await move('ArrowDown',2100);}else{await move('ArrowLeft',900);await move('ArrowDown',400);}
 if(!(await p.locator('.harbor-action strong').innerText()).match(/Go|前往/))await p.locator('[data-target="exit"]').click();await p.waitForFunction(()=>document.querySelector('.harbor-action strong')?.textContent.match(/Go|前往/));await shot('exit-near');await enterDoor();await p.waitForFunction(()=>!document.querySelector('[data-target="chapel-note"]'));await ready();const back=await head();assert.equal(back.scene,'hill');assert.ok(Math.hypot(back.position.x-502,back.position.y-397)<.01);await shot('outside-return');
 await enterDoor();await p.waitForFunction(()=>!!document.querySelector('[data-target="chapel-note"]'));await ready();await move('ArrowRight',1050);await focus('chapel-note');await p.getByRole('button',{name:f.locale==='zh'?'回看这次相聚':'Remember the visit',exact:true}).click();await shot('remembered');const beforeReload=await head();assert.equal(beforeReload.flags.filter(x=>x==='chapel:meeting-clue').length,1);await close();
 await p.reload();await p.getByRole('button',{name:f.locale==='zh'?'继续':'Continue',exact:true}).click();await ready();const restored=await head();assert.equal(restored.scene,'chapel');assert.equal(restored.id,seed.id);assert.deepEqual(restored.flags,beforeReload.flags);assert.deepEqual(restored.items,seed.items);await shot('restored');await p.waitForTimeout(3500);const beforeMove=await p.evaluate(()=>document.querySelector('#rpg').__rpgClient.getCurrentPlayer().x());await move('ArrowLeft',320);const afterMove=await p.evaluate(()=>document.querySelector('#rpg').__rpgClient.getCurrentPlayer().x());assert.ok(beforeMove-afterMove>12,'ordinary movement resumes after old foreground lease expires');await shot('restored-movement');
 const metrics=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,canvas:document.querySelector('canvas')?.getBoundingClientRect().toJSON(),controls:[...document.querySelectorAll('.harbor-controls button')].map(e=>({text:e.textContent,rect:e.getBoundingClientRect().toJSON()}))}));assert.equal(metrics.overflow,false);assert.deepEqual(errors,[]);assert.equal(failed.every(r=>r.status===409&&['ACTIVE_LEASE_BUSY','ACTIVE_LEASE_EXPIRED','MOTION_EXPIRED','VERSION_CONFLICT','MOTION_SEQUENCE','ACTIVE_SEQUENCE'].includes(r.error)),true,JSON.stringify(failed));assert.equal(commands.some(x=>x==='ask'||x.startsWith('notes-')),false);report.push({...f,passed:true,realDevice:false,seedSynthetic:true,commands,errors,failed,metrics,backPosition:back.position,oneClue:true,restored:true,movementRecoveredAfterReload:true});await c.close();
 }
 await writeFile(out+'/report.json',JSON.stringify({passed:true,stage,normalBuiltMainRpgjs:true,realDevice:false,productionSave:false,modelCalls:0,report},null,2));
}catch(e){if(active&&!active.isClosed()){await active.screenshot({path:out+'/failure.png'});await writeFile(out+'/failure.txt',await active.locator('body').innerText());}throw e;}finally{await b.close()}
