import {motionProjection} from '../src/candidate/render-adapter';
import {nativeCrabBody} from '../src/animals/native-crab';
import {bodyAt} from '../src/animals/spatial';
import {profiles} from '../src/animals/config';
import {findPath} from '../src/engine/world';
import {nativeCrabSheet,nativeCrabAnimation} from '../src/animals/native-crab-art';
import {Assets} from 'pixi.js';import {createRpgSpace,type Space} from '../src/engine/rpg-space';import {rooms,people,tx,type Words} from '../src/world/data';import {heroSheet,sheets,propId,npcSheets} from '../src/world/sheets';import dims from '../src/world/map-dimensions.json';import {initial} from '../src/story/state';import {presentEntity,patrolRadius,residentClearOfPlayer} from '../src/world/residents';import {acceptedAnimals,animalSheets} from '../src/animals/art';import {createAnimalRuntime} from '../src/animals/behavior';import {gameAnimalContext} from '../src/animals/game';import {animalAnimation} from '../src/animals/rpgjs-sheet';import {createNativeCrab,nativeCrabProfile} from '../src/animals/native-crab';import type {Facing} from '../src/animals/types';import {landWorld} from '../src/life/land';import {dynamicWorld} from '../src/dynamic-assets/layout';import {walkable,type Point} from '../src/engine/world';import {previewClear,type Geometry} from './animal-stand-space';import {chooseNativeCrabLane,chooseNativePlayerStart,nativeCrabPreviewPolicy} from './crab-c1-space';import geometryFile from './animal-stand-space-geometry.json';import manifest from '../src/animals/native-crab-manifest.json';import '../src/style.css';
if(import.meta.env.PROD)throw Error('NATIVE_CRAB_C1_DEV_ONLY');
const q=new URLSearchParams(location.search),direction=(q.get('direction')??'down') as Facing,scene=q.get('scene')??'coast',locale=q.get('lang')==='zh'?'zh':'en',text=(v:Words)=>tx(v,locale);
if(!['down','left','right','up'].includes(direction)||!['coast','beach','dock'].includes(scene))throw Error('CRAB_QA_SCOPE');document.documentElement.lang=locale;
const root=document.querySelector('#root')!;root.innerHTML=`<header class="c1-head"><b>${text(['蟹的原生横移','Native crab sidestep'])} · ${direction}</b><p>${text(['本地候选：完整步态验证；未开放生产动物或存档。','Local candidate: native gait review; production animals and saves remain closed.'])}</p><output id="qa-ready" aria-live="polite">${text(['载入中','Loading'])}</output></header><div class="c1-world"><div id="rpg"></div></div><footer class="c1-controls"></footer>`;
const preferred:Point={...({coast:{x:1040,y:550},beach:{x:540,y:530},dock:{x:700,y:650}}[scene]!)},save={...initial('en','crab-c1-native-qa-only'),scene,townMinutes:Number(q.get('minute')??540),position:direction==='down'||direction==='up'?{x:preferred.x-8,y:preferred.y-116}:{x:preferred.x-100,y:preferred.y-12},flags:['key','unpacked','route-open','market-open']},playerStart={...save.position},spatialWorld=landWorld(dynamicWorld(save.flags,false),save.landV1),geometry=geometryFile as unknown as Geometry,relative={...manifest.displayEnvelope},region=spatialWorld.scenes[scene].interior;
if(!walkable(spatialWorld,scene,save.position)){save.position={...spatialWorld.scenes[scene].spawn};Object.assign(playerStart,save.position)}
const originalAnimals=createAnimalRuntime(acceptedAnimals),positions=new Map<string,Point>(),patrols=new Map<string,{side:number;pause:number;distance:number}>();let states=originalAnimals.tick(0,gameAnimalContext(save,save.position,{world:spatialWorld}));
let batch=false;let blocker=false,paused=false,running=false,space:Space|null=null,frames=0,seconds=0,lastAction='initial',approachComplete=false,lastApproachAccepted=false;const retreatTrace:any[]=[];
const context=()=>{const c=gameAnimalContext(save,save.position,{world:spatialWorld,positions,paused});if(blocker)c.forbidden[scene]=[...(c.forbidden[scene]??[]),region];return c;};
const lane=chooseNativeCrabLane(preferred,scene,region,relative,{context:context(),states,geometry},direction);
if(lane){const start=chooseNativePlayerStart(lane.ends[0],direction,spatialWorld,scene);if(start){Object.assign(playerStart,start);save.position={...start}}}
originalAnimals.reset();states=originalAnimals.tick(0,context());
const pixelFoot=(p:Point)=>({x:Math.round(p.x),y:Math.round(p.y)});
const make=()=>lane?createNativeCrab([{id:'qa-native-crab',visualVersion:'shore-crab-native-c1-v2',schedule:{morning:lane,afternoon:lane,evening:lane,night:lane}}],{displayClear:(foot,id,r,c)=>previewClear(pixelFoot(foot),id,r,relative,{context:c,states,geometry})}):null;
let runtime=make(),frame=runtime?.tick(0,context())[0]??null;
const native={...nativeCrabSheet(),id:'qa-native-crab'};
const actors=new Map<string,any>();const event=(id:string,x:number,y:number,graphic:string,animation='stand')=>({id,x,y,event:{onInit(this:any){this.setHitbox(1,1);this.through=true;this.animationFixed=true;this.setGraphic(graphic);this.animationName.set(animation);this.syncChanges();actors.set(id,this)}}});
const layer=(id:string,name:string)=>{const d=dims[(id+'-'+name) as keyof typeof dims];return d.empty?[]:[event(name+'-'+id,d.x,d.y+(name==='front'?d.height:0),name+'-'+id)]};
await Promise.all([native.image,heroSheet.image,...sheets.filter(s=>s.id.endsWith('-'+scene)||s.id.startsWith('prop-'+scene+'-')||s.id.startsWith('npc-')).map(s=>s.image),...animalSheets.map(s=>s.image)].map(async url=>{const texture=await Assets.load(url);if(url===native.image)texture.source.scaleMode='nearest'}));
const render=()=>{const actor=actors.get('qa-native-crab'),animation=frame?nativeCrabAnimation(frame):'hidden-'+direction;if(actor){if(frame&&(actor.x()!==pixelFoot(frame.foot).x||actor.y()!==pixelFoot(frame.foot).y))void actor.teleport(pixelFoot(frame.foot));if(actor.graphics()[0]!=='qa-native-crab')actor.setGraphic('qa-native-crab');if(actor.animationName()!==animation)actor.animationName.set(animation);actor.syncChanges();}
 document.querySelector('#qa-ready')!.textContent=frame?.visible?text(['当前动作：','Pose: '])+frame.pose+' · '+frame.phase:text(['暂不展示：没有安全空间','Hidden: no safe display space']);};
const advance=(dt:number)=>{if(!runtime)return;const used=paused?0:Math.min(dt,.04);states=originalAnimals.tick(used,context());
 for(const e of rooms[scene].entities.filter(e=>e.person&&presentEntity(save,e))){const actor=actors.get('person-'+e.id);if(!actor)continue;const current=positions.get(scene+'/'+e.id)??e.at,radius=patrolRadius(e.person),patrol=patrols.get(e.id)??{side:1,pause:0,distance:0};patrols.set(e.id,patrol);
  const near=Math.hypot(save.position.x+8-current.x,save.position.y+6-current.y)<110;let next={...current};
  if(used&&!near&&radius){if(patrol.pause>0)patrol.pause=Math.max(0,patrol.pause-used);else{const goal=e.at.x+patrol.side*radius,dx=Math.sign(goal-current.x)*Math.min(Math.abs(goal-current.x),30*used);next.x+=dx;
   if(!walkable(spatialWorld,scene,{x:next.x-8,y:next.y-6})||rooms[scene].entities.some(o=>o.person&&o.id!==e.id&&presentEntity(save,o)&&Math.hypot(next.x-(positions.get(scene+'/'+o.id)??o.at).x,next.y-o.at.y)<28)){next={...current};patrol.side*=-1;patrol.pause=.8}
   patrol.distance+=Math.abs(next.x-current.x);if(Math.abs(goal-next.x)<.1){patrol.side*=-1;patrol.pause=1.5}
  }}positions.set(scene+'/'+e.id,next);if(!batch){if(next.x!==actor.x()||next.y!==actor.y())void actor.teleport(next);actor.syncChanges()};
 }
 for(const state of states.filter(a=>a.scene===scene)){if(batch)continue;const actor=actors.get(state.id);if(!actor)continue;if(state.visible){if(actor.graphics()[0]!=='animal-'+state.visualVersion)actor.setGraphic('animal-'+state.visualVersion);void actor.teleport({x:Math.round(state.foot.x),y:Math.round(state.foot.y-state.elevation)});const anim=animalAnimation(state);if(actor.animationName()!==anim)actor.animationName.set(anim)}else if(actor.graphics().length)actor.setGraphic([]);actor.syncChanges()}
 frame=runtime.tick(dt,context())[0];if(frame&&['retreat','alert'].includes(frame.phase)&&retreatTrace.length<32)retreatTrace.push({phase:frame.phase,foot:{...frame.foot},player:{...save.position},groundProfile:frame.profileRevision});frames++;seconds+=used;if(!batch)render();};
const atNear=()=>{if(!frame?.visible||!lane)return null;const a=direction==='down'||direction==='up'?'x':'y',perp=a==='x'?'y':'x';const candidates=[-1,1].flatMap(sign=>[48,56,60].map(distance=>({x:frame!.foot.x-8,y:frame!.foot.y-6,[perp]:frame!.foot[perp]+sign*distance-(perp==='x'?8:6)})));
 return candidates.find(p=>walkable(spatialWorld,scene,p)&&previewClear(frame!.foot,scene,region,relative,{context:gameAnimalContext(save,p,{world:spatialWorld}),states,geometry}))??null;};
const buttons:[string,Words,()=>void|Promise<void>][]=[['run',['运行 / 停止','Run / stop'],()=>{running=!running;advance(0)}],['pause',['暂停 / 恢复','Pause / resume'],()=>{paused=!paused;advance(0)}],['near',['靠近','Approach'],()=>{const p=atNear();if(p&&space){running=true;approachComplete=false;lastApproachAccepted=space.walkTo(p,()=>{approachComplete=true;running=false;advance(0)});advance(0)}}],['away',['离开','Step away'],()=>{running=true;space?.walkTo(playerStart,()=>{running=false;advance(0)});advance(0)}],['block',['阻挡 / 恢复','Block / restore'],()=>{blocker=!blocker;advance(0)}],['reset',['重置候选','Reset candidate'],async()=>{running=false;paused=false;blocker=false;await space?.restore(scene,playerStart);runtime=make();frames=0;seconds=0;advance(0)}]];
for(const[id,label,action]of buttons){const button=document.createElement('button');button.id=id;button.textContent=text(label);button.onpointerdown=()=>{lastAction=id;void action()};document.querySelector('.c1-controls')!.append(button)}
const playerCollisionWorld=()=>{const obstacles=[...spatialWorld.scenes[scene].obstacles,...Object.values(context().people).filter(p=>p.scene===scene).map(p=>p.body),...states.filter(a=>a.visible&&a.scene===scene).map(a=>bodyAt(a.foot,profiles[a.species])),...(frame?.visible?[nativeCrabBody(frame.foot,frame.direction)]:[])];return {...spatialWorld,scenes:{...spatialWorld.scenes,[scene]:{...spatialWorld.scenes[scene],obstacles}}}};
createRpgSpace({walkable:(p,id)=>walkable(playerCollisionWorld(),id,p),findPath:(a,b,id)=>findPath(playerCollisionWorld(),id,a,b),world:spatialWorld,host:document.querySelector('#rpg')!,scene,position:save.position,speed:112,stride:48,sheet:heroSheet,spritesheets:[native,...sheets,...animalSheets],controlsBlocked:()=>false,onPosition:p=>{save.position={...p};motionProjection.points=[];motionProjection.traceStart={...p};advance(0)},onDestination:()=>{},onFrame:dt=>{advance(running?dt:0)},onError:e=>{document.querySelector('#qa-ready')!.textContent=String(e)},cameraBounds:id=>rooms[id].outdoor?{x:0,y:0,w:1440,h:1088}:{x:rooms[id].interior.x-8,y:rooms[id].interior.y-64,w:rooms[id].interior.w+16,h:rooms[id].interior.h+72},mapEvents:id=>[...layer(id,'base'),...layer(id,'north'),...layer(id,'side'),...rooms[id].props.filter(p=>!p.floorDecoration).map(p=>event(propId(id,p),p.at.x,p.at.y,propId(id,p))),...rooms[id].entities.filter(e=>e.person&&presentEntity({...save,scene:id},e)).map(e=>event('person-'+e.id,e.at.x,e.at.y,'npc-'+e.person)),...states.filter(s=>s.visible&&s.scene===id).map(s=>event(s.id,s.foot.x,s.foot.y,'animal-'+s.visualVersion,animalAnimation(s))),...(id===scene&&lane?[event('qa-native-crab',frame?.foot.x??lane.ends[0].x,frame?.foot.y??lane.ends[0].y,'qa-native-crab',frame?.visible?'stand':'hidden')]:[]),...layer(id,'front')],onReady:s=>{space=s;s.pause(false);motionProjection.block?.(false);render();
 (window as any).__crabC1Qa={ready:true,space:s,actors,step:(dt:number,count:number)=>{if(count<0||count>3600)throw Error('STEP_CAP');batch=true;try{for(let n=0;n<count;n++)advance(dt)}finally{batch=false}advance(0);return frame;},snapshot:()=>JSON.parse(JSON.stringify({scene,renderedScene:s.renderedScene(),direction,preferred,lane,frame,paused,running,blocker,frames,seconds,lastAction,approachComplete,lastApproachAccepted,retreatTrace,playerStart,playerPosition:save.position,nearPosition:atNear(),renderedFoot:frame?pixelFoot(frame.foot):null,actorFoot:frame?{x:actors.get('qa-native-crab')?.x(),y:actors.get('qa-native-crab')?.y()}:null,nativeGraphic:actors.get('qa-native-crab')?.graphics?.()??[],nativeAnimation:actors.get('qa-native-crab')?.animationName?.(),safe:frame?.visible?previewClear(pixelFoot(frame.foot),scene,region,relative,{context:context(),states,geometry}):null,displayEnvelope:relative,source:frame?manifest.frames[(direction+'-'+frame.pose) as keyof typeof manifest.frames]:null,projectedFoot:frame?s.project(pixelFoot(frame.foot)):null,projectedNativeBounds:frame?[s.project({x:pixelFoot(frame.foot).x+relative.x,y:pixelFoot(frame.foot).y+relative.y}),s.project({x:pixelFoot(frame.foot).x+relative.x+relative.w,y:pixelFoot(frame.foot).y+relative.y+relative.h})]:null,originalAnimalFeet:states.filter(t=>t.visible&&t.scene===scene).map(t=>({id:t.id,authoredFoot:{...t.foot},foot:{x:actors.get(t.id)?.x(),y:actors.get(t.id)?.y()},})),townMinutes:save.townMinutes,originalPeopleFeet:rooms[scene].entities.filter(e=>e.person&&presentEntity(save,e)).map(e=>({id:e.id,authoredFoot:{...e.at},foot:{x:actors.get('person-'+e.id)?.x(),y:actors.get('person-'+e.id)?.y()}})),registeredResidents:Object.keys(people).length,npcSheets:npcSheets.length,acceptedAnimals:acceptedAnimals.length,policy:nativeCrabPreviewPolicy,profile:nativeCrabProfile,originalRenderer:true,nativeSources:9,directionFrames:12,activationAllowed:false,localMovementFixtureAcknowledgements:true,productionWrites:0,realPhone:false,miniApp:false}))};
}});
addEventListener('visibilitychange',()=>{if(document.hidden){paused=true;running=false;advance(0)}});
