import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out='doc/qa/crops-integrated-20261005';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});
const report={cases:[],errors:[],failedArt:[]};
try{for(const [width,height] of (process.env.CROP_QUICK?[[390,844]]:[[390,844],[320,568],[1280,800]])){const c=await browser.newContext({viewport:{width,height},locale:'en-US'});await c.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)||/^(blob|data):/.test(r.request().url())?r.continue():r.abort());
const p=await c.newPage();p.on('pageerror',e=>report.errors.push(String(e)));p.on('response',r=>{if(r.url().includes('/art/')&&r.status()>=400)report.failedArt.push(r.url())});
for(const stage of (process.env.CROP_QUICK?['ready']:['young','growing','ready','dry','bag'])){const r=await c.request.post('http://127.0.0.1:5321/qa/prepare?case=art-'+stage);assert.equal(r.status(),200);const s=await r.json();await p.addInitScript(id=>addEventListener('DOMContentLoaded',()=>{window.alteruLocalStorage?.setItem('harbor-opening:'+id,'3');window.alteruLocalStorage?.setItem('harbor-locale','en');window.alteruLocalStorage?.setItem('harbor-muted','1')}),s.id);
await p.goto('http://127.0.0.1:5320/?debug=1');await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await p.waitForTimeout(1200);await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});
const rendered=await p.evaluate(()=>{const out=[];const walk=n=>{if(!n)return;const label=n.texture?.source?.label;if(label?.startsWith('prop-garden-crop-'))out.push({label,x:n.x,y:n.y,scale:n.scale?.x,alpha:n.worldAlpha});for(const ch of n.children??[])walk(ch)};walk(document.querySelector('#rpg').__rpgClient.canvasApp.stage);return out});
if(stage==='bag'){await p.getByRole('button',{name:'Bag',exact:true}).click();await p.locator('.harbor-crop-icon').last().waitFor();assert.equal(await p.locator('.harbor-crop-icon').count(),3)}else {assert.equal(rendered.length,3);assert.ok(rendered.every(v=>v.label.includes(stage==='dry'?'growing':stage)))}
assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:`${out}/${stage}-${width}-platform-layout.png`});report.cases.push({width,height,stage,rendered,icons:await p.locator('.harbor-crop-icon').count()});}
await c.close();}assert.deepEqual(report.errors,[]);assert.deepEqual(report.failedArt,[])}finally{await browser.close();await writeFile(out+'/capture-report.json',JSON.stringify(report,null,2))}
console.log(JSON.stringify({states:report.cases.length,errors:report.errors,failedArt:report.failedArt}));
