import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {DatabaseSync} from 'node:sqlite';import {serialize,deserialize} from 'node:v8';
import {encodePackage,decodePackage} from '../src/dynamic-assets/wire.mjs';
import {createHarborLibraryBridge} from '../server/dynamic-assets/bridge.mjs';import {createHarborDynamicReader} from '../src/dynamic-assets/browser-reader.mjs';
import {createMemoryByteCache} from '../vendor/dynamic-assets/runtime/service-consumer.mjs';import {digest,styleProfile} from '../vendor/dynamic-assets/runtime/core.mjs';
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';import {createRuntime} from '../server/runtime.ts';import {GAME_UUID} from '../src/game-id.ts';
const image=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'));
async function fixture(t){
 const root=await mkdtemp(join(tmpdir(),'harbor-dynamic-bridge-'));const state=openAsyncSqliteAuthorityStore({path:join(root,'story.sqlite'),worldId:'local-bridge-test',gameId:GAME_UUID,environment:'test'});
 const authority=new AsyncSessionAuthority(state,createRuntime()),owner='a'.repeat(64),token='b'.repeat(64);const head=await authority.create(owner,crypto.randomUUID(),'en');
 let database;function open(){database=new DatabaseSync(join(root,'grants.sqlite'));database.exec('CREATE TABLE IF NOT EXISTS grants (owner TEXT, session TEXT, room TEXT, record BLOB, PRIMARY KEY(owner,session,room))')};open();
 const key=k=>[k.owner,k.sessionId,k.roomId];const store={get:async k=>{const r=database.prepare('SELECT record FROM grants WHERE owner=? AND session=? AND room=?').get(...key(k));return r?deserialize(Buffer.from(r.record)):null},renew:async(k,previous,v)=>{database.prepare('UPDATE grants SET record=? WHERE owner=? AND session=? AND room=?').run(serialize(v),...key(k));return v},putIfAbsent:async(k,v)=>{database.prepare('INSERT OR IGNORE INTO grants VALUES (?,?,?,?)').run(...key(k),serialize(v));return store.get(k)}};
 const config={timePolicy:'user-approved-budget-only-20261001',expiresAt:null,publicOrigin:'https://game.aiwaves.tech'};const request={headers:{'x-harbor-edge':token,'x-harbor-owner':owner,'x-harbor-game':GAME_UUID,origin:config.publicOrigin}};
 const geometry={seat:{anchor:[.5,1],scale:1,eventAt:{x:1,y:1},imageOffset:{x:0,y:0},supportPropId:null,footprints:[]}},geometryHash=await digest(geometry.seat);
 const compatProfile={pixelScale:{value:1,unit:'source-px/game-px'},density:{value:1,unit:'source-px/world-unit'},paletteId:'synthetic-palette',projection:'synthetic-approved-exemplar',lighting:'synthetic-light'};
 const profile=await styleProfile({styleFamilyId:'synthetic-style',profileId:'synthetic-slot',version:1,compatProfile}),hash=await digest(image);
 let manifest={format:'rpg-asset-published-manifest-v2',metadataSchemaVersion:2,assetId:'synthetic-chair',renditionId:'synthetic-chair',revision:'2',status:'published',width:1,height:1,semanticItemId:'chair',category:'prop',orientation:'front',view:'elevated-2d',usageClass:'prop',uses:['room-prop'],preferredUses:['room-prop'],styleFamilyId:profile.styleFamilyId,profileId:profile.profileId,profileVersion:1,profileHash:profile.hash,compatProfile,source:{url:'local:synthetic-only'},license:{id:'synthetic-test',name:'Synthetic QA',allowed:true,notice:'Synthetic automated-test fixture, not human art approval.'},rights:{status:'documented'},approval:{hash,manifestHash:'c'.repeat(64),actor:'synthetic-fixture',at:'2026-10-03T00:00:00Z'},files:[{path:'original.png',mime:'image/png',bytes:image.length,sha256:hash}],viewContract:{schemaVersion:1,view:'elevated-2d',orientationModel:'object-front-screen-axis-v1',screenFront:'down',projectionId:compatProfile.projection,calibration:{status:'unmeasured'},applicability:{kind:'exact-slot',roomId:'station',slotId:'seat',geometryHash},evidenceRef:'synthetic-geometry'}};
 const need={needId:'seat',itemId:'chair',category:'prop',orientation:'front',view:'elevated-2d',purpose:'room-prop',minWidth:1,maxWidth:1,minHeight:1,maxHeight:1,quantity:1,minDistinct:1,placementScope:{roomId:'station',slotId:'seat',geometryHash}};
 const templates=[{allowedAssetId:'synthetic-chair',allowedRevision:2,id:'synthetic-harbor-template',version:1,roomId:'station',profile,geometry,layout:{width:2,height:2,placements:[{slotId:'seat',itemId:'chair',orientation:'front',x:1,y:1}]},slots:[{slotId:'seat',need,request:{itemId:'chair',category:'prop',orientation:'front',usage:'prop',dimensions:{minWidth:1,maxWidth:1,minHeight:1,maxHeight:1},requiredTags:['room-prop'],purposeTags:['room-prop']}}]}];
 let searches=0;const catalog={searchPublished:async()=>{searches++;return [JSON.stringify(manifest)]},getManifest:async()=>JSON.stringify(manifest),getFile:async()=>image.slice()};
 let clock=Date.now();const make=()=>createHarborLibraryBridge({authority,store,catalog,templates,config,edgeToken:token,policy:{assert:()=>true,expires:()=>clock+86400000},now:()=>clock,ttlMs:1000});let bridge=make();
 t.after(async()=>{database.close();await state.close();await rm(root,{recursive:true,force:true})});
 return {head,request,catalog,templates,store,make,expire:()=>{clock+=2000},get bridge(){return bridge},get searches(){return searches},mutate:f=>f(manifest),reopen:()=>{database.close();open();bridge=make()},revoke:()=>database.exec('DELETE FROM grants')};
}
test('Harbor candidate: verified edge owner -> exact selection -> persisted grant; reopen restores without search and wrong owners/rooms fail',async t=>{
 const f=await fixture(t);const a=await f.bridge.prepare(f.request,f.head.id,'station');assert.equal(a.kind,'locked');assert.equal(f.searches,1);
 const original=a.record;f.reopen();f.catalog.searchPublished=async()=>{throw Error('Must not reselect on restore')};assert.deepEqual((await f.bridge.prepare(f.request,f.head.id,'station')).record,original);
 await assert.rejects(f.bridge.package({headers:{...f.request.headers,'x-harbor-owner':'forged'}},f.head.id,'station'),/EDGE_IDENTITY_REQUIRED/);
 await assert.rejects(f.bridge.package({headers:{...f.request.headers,'x-harbor-owner':'d'.repeat(64)}},f.head.id,'station'),/SESSION_NOT_FOUND/);
 await assert.rejects(f.bridge.prepare(f.request,f.head.id,'home'),/ROOM_ASSET_SCOPE_DENIED/);
 const g=original.grant;await assert.rejects(f.bridge.deliver(f.request,f.head.id,'station','blob',{consumerId:g.scope.consumerId,grantHash:original.grantHash,pin:{...g.pins[0],revision:3}}),/ASSET_PIN_DENIED/);
});
test('Harbor candidate: actual service consumer verifies byte chain, same pair on outage, denial/revocation clears cache and never falls back',async t=>{
 const f=await fixture(t),prepared=await f.bridge.prepare(f.request,f.head.id,'station'),record=prepared.record,g=record.grant;
 assert.deepEqual(decodePackage(JSON.parse(JSON.stringify(encodePackage(record)))),record);
 const attachment={grantHash:record.grantHash,roomHash:g.room.hash,templateHash:g.template.hash,scope:g.scope};const base='http://127.0.0.1/'+GAME_UUID+'/api/sessions/'+f.head.id+'/assets/station/';let offline=false,denied=false;const calls=[];
 const fetchImpl=async(url,options)=>{const action=new URL(url).pathname.split('/').at(-1);calls.push(action);if(denied)return new Response('{}',{status:403});if(offline)throw Error('synthetic-network-outage');const out=await f.bridge.deliver(f.request,f.head.id,'station',action,JSON.parse(options.body));return new Response(out.bytes,{headers:{'Content-Type':out.mime,'X-Consumer-Grant':out.grantHash}})};
 const cache=createMemoryByteCache(),reader=await createHarborDynamicReader({attachment,wire:encodePackage(record),baseUrl:()=>base,baseURI:'http://127.0.0.1/',fetchImpl,cacheStore:cache});
 const result=await reader.resolve();assert.deepEqual(calls,['check','manifest','blob','check']);assert.equal(result.remoteAuthorizationConfirmed,true);assert.deepEqual(result.files[0].bytes,image);assert.equal(result.assets[0].propId,'seat');assert.equal(result.assets[0].sourceWidth,1);assert.deepEqual(result.assets[0].geometry,{anchor:[.5,1],scale:1,offset:{x:0,y:0}});
 offline=true;assert.equal((await reader.resolve()).mode,'offline-template');offline=false;denied=true;await assert.rejects(reader.resolve(),/AUTH_DENIED/);assert.equal((await cache.keys()).length,0);
 await assert.rejects(createHarborDynamicReader({attachment:{...attachment,roomHash:'f'.repeat(64)},wire:encodePackage(record),baseUrl:()=>base,baseURI:'http://127.0.0.1/',fetchImpl}),/JOURNEY_ASSET_BINDING_MISMATCH/);
 await assert.rejects(createHarborDynamicReader({attachment,wire:encodePackage(record),baseUrl:()=>base.replace('/assets/station/','/assets/home/'),baseURI:'http://127.0.0.1/',fetchImpl}),/SAME_GAME_ASSET_ENDPOINT_REQUIRED/);
 f.revoke();await assert.rejects(f.bridge.package(f.request,f.head.id,'station'),/ROOM_ASSETS_NOT_PREPARED/);
});
test('Harbor candidate: missing view/geometry mismatch is a gap, no grants or generation; concurrent prepare persists one whole version',async t=>{
 const f=await fixture(t);f.mutate(m=>m.view='unknown');const missing=await f.bridge.prepare(f.request,f.head.id,'station');assert.equal(missing.kind,'unavailable');assert.equal(missing.generationAuthorized,false);assert.equal(await f.store.get({owner:f.request.headers['x-harbor-owner'],sessionId:f.head.id,roomId:'station'}),null);
 f.mutate(m=>{m.view='elevated-2d';m.viewContract.applicability.geometryHash='0'.repeat(64)});assert.equal((await f.bridge.prepare(f.request,f.head.id,'station')).kind,'unavailable');
 f.mutate(m=>m.viewContract.applicability.geometryHash=f.templates[0].slots[0].need.placementScope.geometryHash);
 const [a,b]=await Promise.all([f.bridge.prepare(f.request,f.head.id,'station'),f.bridge.prepare(f.request,f.head.id,'station')]);assert.equal(a.record.grantHash,b.record.grantHash);const searches=f.searches;f.expire();await assert.rejects(f.bridge.package(f.request,f.head.id,'station'),/GRANT_EXPIRED/);const renewed=await f.bridge.prepare(f.request,f.head.id,'station');assert.equal(renewed.record.grant.room.hash,a.record.grant.room.hash);assert.notEqual(renewed.record.grantHash,a.record.grantHash);assert.equal(f.searches,searches);
});
