// @ts-nocheck -- actual compiled Main/View/RPGJS, own normal local browser + isolated SQLite.
import {initial} from '../src/story/state';import {GAME_UUID} from '../src/game-id';
import {chromium} from '../node_modules/playwright/index.mjs';
import {mkdtempSync,readFileSync,existsSync} from 'node:fs';import {writeFile,mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';
const root=resolve('..'),label=process.env.JOY_LABEL??'demand',dist=resolve(process.env.JOY_DIST??root+'/source/dist'),width=Number(process.env.JOY_WIDTH??390),height=width===320?568:844;
const delays=process.env.JOY_DELAYS?.split(',').map(Number)??[180,220,170,240,190,200,850,180,210,170,620,240];
const moduleRoot=resolve(process.env.JOY_SOURCE??'.');
const {makeDemoServer}=await import(moduleRoot+'/_qa/temporary-account-server.ts');
const {createExplorationAssembly}=await import(moduleRoot+'/server/exploration-assembly.ts'),{withWildMint}=await import(moduleRoot+'/server/wild-mint.ts'),{withBasilPlantUses}=await import(moduleRoot+'/server/plant-basil.ts');
const assembly=createExplorationAssembly({crabEnabled:true,resolveDialogue:async()=>{throw Error('MODEL_DISABLED')},decorateLife:r=>withWildMint(withBasilPlantUses(r),{enabled:true}),initial:(l,id)=>({...initial(l,id),scene:'station',position:{x:480,y:557},known:['mara'],flags:['key','unpacked','bag-returned'],items:{key:1},visited:['station','harbor']})});
const server=await makeDemoServer({directory:mkdtempSync('/tmp/harbor-joystick-'),providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority});
const rec={label,width,height,delays,scope:'compiled Main/View/RPGJS with original authority in isolated own SQLite. Continuous CDP touchMove fine-angle jitter. Delays replay observed ordinary production response/request variation. Synthetic initial save; not physical phone',events:[],inputs:[],pageErrors:[],paidCalls:0};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
const c=await browser.newContext({viewport:{width,height},hasTouch:true,serviceWorkers:'block'});let seq=0,p;
try{
 await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());try{if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname.includes('/api/')){const op=u.pathname.split('/').at(-1);let b;try{b=q.postDataJSON()}catch{};const trace=['motion','active-play'].includes(op);let delay=trace?delays[seq++%delays.length]:0;if(trace)rec.events.push({at:Date.now(),phase:'send',action:b?.action,points:b?.payload?.points,delay});
 // Vary inbound and outbound independently to reproduce receipt-time compression.
 if(delay)await new Promise(z=>setTimeout(z,Math.floor(delay*.55)));const response=await r.fetch({url:server.url+u.pathname+u.search});if(delay)await new Promise(z=>setTimeout(z,Math.ceil(delay*.45)));if(trace){const v=await response.json();rec.events.push({at:Date.now(),phase:'ack',action:b?.action,status:response.status(),error:v.error,retryAfterMs:v.retryAfterMs,position:v.fields?.position,townMinutes:v.fields?.townMinutes})}return r.fulfill({response})}
 const file=resolve(dist,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(dist+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({contentType:{'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.tmx':'application/xml'}[extname(file)]??'application/octet-stream',body:readFileSync(file)});
 }catch(e){rec.routeError=String(e);if(!p?.isClosed())await r.abort().catch(()=>{})}});
 await c.addInitScript(()=>{window.__name=f=>f;window.__longTasks=[];new PerformanceObserver(l=>window.__longTasks.push(...l.getEntries().map(e=>({start:performance.timeOrigin+e.startTime,ms:e.duration})))).observe({type:'longtask',buffered:true})});
 p=await c.newPage();p.on('pageerror',e=>rec.pageErrors.push(String(e)));await p.goto(server.url+'/?debug=1');await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'),null,{timeout:60000});for(let i=0;i<3;i++)await p.locator('.harbor-opening button').click();await p.waitForTimeout(3500);
 await p.evaluate(()=>{window.__samples=[];window.__sampling=true;const sample=()=>{if(!window.__sampling)return;const host=document.querySelector('#rpg'),c=host.__rpgClient,q=c.getCurrentPlayer();window.__samples.push({at:Date.now(),x:q.x(),y:q.y(),worldPaused:host.dataset.worldPaused,predictionBlocked:host.dataset.predictionBlocked,points:host.dataset.motionPoints,distance:host.dataset.motionDistance,block:host.dataset.motionBlock,projectedX:host.dataset.projectedX,projectedY:host.dataset.projectedY,rendererQueue:q.frames?.length});requestAnimationFrame(sample)};requestAnimationFrame(sample)});
 const box=await p.locator('.harbor-stick').boundingBox(),cdp=await c.newCDPSession(p);let first=true;rec.inputStart=Date.now();
 while(Date.now()-rec.inputStart<25000){const t=Date.now()-rec.inputStart,sign=Math.floor(t/5000)%2===0?1:-1,angle=.07*Math.sin(t/43)+.013*Math.sin(t/13),x=box.x+box.width/2+sign*35*Math.cos(angle),y=box.y+box.height/2+35*Math.sin(angle);await cdp.send('Input.dispatchTouchEvent',{type:first?'touchStart':'touchMove',touchPoints:[{id:1,x,y}]});first=false;rec.inputs.push({at:Date.now(),x,y});await p.waitForTimeout(24)}
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();rec.inputEnd=Date.now();rec.samples=await p.evaluate(()=>window.__samples);rec.longTasks=await p.evaluate(()=>window.__longTasks);const frames=rec.samples.filter(s=>s.at>=rec.inputStart+100&&s.at<=rec.inputEnd-100);let start;rec.zeroRuns=[];rec.gaps=[];let distance=0;
 for(let i=1;i<frames.length;i++){const a=frames[i-1],b=frames[i],dt=b.at-a.at,d=Math.hypot(b.x-a.x,b.y-a.y);distance+=d;if(dt>100)rec.gaps.push({at:a.at,ms:dt});if(d<.1){start??=a}else if(start){if(b.at-start.at>=100)rec.zeroRuns.push({...start,to:b.at,ms:b.at-start.at});start=undefined}}
 if(start)rec.zeroRuns.push({...start,to:rec.inputEnd,ms:rec.inputEnd-start.at});const gaps=frames.slice(1).map((s,i)=>s.at-frames[i].at).sort((a,b)=>a-b);rec.raf={maximum:Math.max(...gaps),p99:gaps[Math.floor(gaps.length*.99)],p95:gaps[Math.floor(gaps.length*.95)]};rec.meanSpeed=distance/((frames.at(-1).at-frames[0].at)/1000);rec.maxQueuePoints=Math.max(...frames.map(s=>Number(s.points)||0));rec.maxQueueDistance=Math.max(...frames.map(s=>Number(s.distance)||0));const renderErrors=frames.map(s=>s.projectedX===undefined?0:Math.hypot(s.x-Number(s.projectedX),s.y-Number(s.projectedY))).sort((a,b)=>a-b);rec.maximumRenderLag=renderErrors.at(-1);rec.renderLagP95=renderErrors[Math.floor(renderErrors.length*.95)];rec.maximumRendererQueue=Math.max(...frames.map(s=>s.rendererQueue??0));rec.worldPauseFrames=frames.filter(s=>s.worldPaused==='true').length;rec.inputFirstMoveMs=rec.samples.find(s=>s.at>rec.inputStart&&Math.hypot(s.x-480,s.y-557)>.5)?.at-rec.inputStart;rec.sustainedLongTasks=rec.longTasks.filter(l=>l.start>=rec.inputStart&&l.start<=rec.inputEnd);
 await p.screenshot({path:root+'/evidence/joystick-'+label+'-'+width+'.png'});await p.evaluate(()=>window.__sampling=false);
 // Real menu pause, close/resume, and confirmed position across reload.
 await p.locator('.harbor-header nav').getByRole('button',{name:'Map',exact:true}).click();await p.locator('.harbor-map-gesture').waitFor();await p.waitForTimeout(4000);const point=()=>p.evaluate(()=>{const q=document.querySelector('#rpg').__rpgClient.getCurrentPlayer();return{x:q.x(),y:q.y()}});const a=await point();await p.waitForTimeout(600);assert.deepEqual(await point(),a,'menu really pauses');await p.keyboard.press('Escape');await p.waitForSelector('.harbor-controls');const before=await point(),t=Date.now();await p.keyboard.down('ArrowLeft');await p.waitForFunction(v=>{const q=document.querySelector('#rpg').__rpgClient.getCurrentPlayer();return Math.abs(q.x()-v)>1},before.x,{timeout:2000});rec.menuResumeFirstMoveMs=Date.now()-t;await p.keyboard.up('ArrowLeft');await p.waitForTimeout(2500);
 await p.locator('.harbor-header nav').getByRole('button',{name:'Map',exact:true}).click();await p.locator('.harbor-map-gesture').waitFor();await p.waitForTimeout(4000);const [j]=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions')).json();const saved=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions/'+j.id)).json();rec.saved={position:saved.position,scene:saved.scene,version:saved.version,townMinutes:saved.townMinutes};assert.equal(saved.cash,25);assert.equal(saved.items.key,1);await p.reload();await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));assert.ok(Math.hypot((await point()).x-saved.position.x,(await point()).y-saved.position.y)<2,'reload exact confirmed head');
 rec.result=rec.zeroRuns.some(r=>r.ms>=150)?'STUTTER_REPRODUCED':'PASS';if(label==='sealed'){assert.ok(rec.maximumRenderLag<112*rec.raf.maximum/1000+2,'local sprite error stays within one measured frame and integer pixel rounding');assert.ok(rec.renderLagP95<112*rec.raf.p95/1000+2,'typical local sprite error stays within one measured frame');assert.ok(rec.maximumRendererQueue<=2,'no redundant local renderer queue backlog')}if(['final','sealed'].includes(label))assert.ok(rec.menuResumeFirstMoveMs<150,'same-owner menu resume does not wait for a network round trip');assert.equal(rec.pageErrors.length,0);assert.equal(rec.worldPauseFrames,0);
}catch(e){rec.failure=String(e);rec.result='HARNESS_OR_ASSERTION_FAILED';if(p)await p.screenshot({path:root+'/evidence/joystick-'+label+'-'+width+'-failure.png'}).catch(()=>{})}
finally{await c.unrouteAll({behavior:'ignoreErrors'});await browser.close();await server.close();await writeFile(root+'/evidence/joystick-'+label+'-'+width+'.json',JSON.stringify(rec,null,2)+'\n');console.log(JSON.stringify({label,width,result:rec.result,zeroRuns:rec.zeroRuns,raf:rec.raf,meanSpeed:rec.meanSpeed,maxQueuePoints:rec.maxQueuePoints,maxQueueDistance:rec.maxQueueDistance,inputFirstMoveMs:rec.inputFirstMoveMs,menuResumeFirstMoveMs:rec.menuResumeFirstMoveMs,maximumRenderLag:rec.maximumRenderLag,renderLagP95:rec.renderLagP95,maximumRendererQueue:rec.maximumRendererQueue,sustainedLongTasks:rec.sustainedLongTasks,errors:rec.events.filter(e=>e.error),failure:rec.failure}))}
