import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {initial,applyAction,availableTopics,type Save,type Action} from '../src/story/state';
import {advanceAwake} from '../src/story/fatigue';import {rooms,entityAt} from '../src/world/data';import {residentHere,residentRoutes} from '../src/world/residents';import {runtime} from '../server/runtime';
// @ts-expect-error frozen runtime
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const action=(s:Save,target:string,verb:string):Action=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:entityAt(s.scene,target)?.approach??s.position,target,action:verb});
const act=(s:Save,target:string,verb:string)=>applyAction(s,action(s,target,verb)).head;
const placed=(scene='home'):Save=>({...initial('en',randomUUID()),scene,position:rooms[scene].spawn,flags:['key','unpacked'],items:{key:1},visited:Object.keys(rooms)});
test('13 schedules: exactly one active authored location per daytime period, none overnight; Mara prologue remains available',()=>{assert.equal(Object.keys(residentRoutes).length,13);for(const [person,routes] of Object.entries(residentRoutes))for(const [i,m] of [540,780,1080,1300].entries()){const s={townMinutes:m,flags:['bag-returned']};const locations=Object.values(rooms).filter(r=>r.entities.some(e=>e.person===person)&&residentHere(s,person,r.id));assert.equal(locations.length,i===3?0:1,person+' '+m);if(i<3)assert.equal(locations[0].id,routes[i].scene)}for(const m of [540,800,1100,1400])assert.equal(residentHere({townMinutes:m,flags:['key','unpacked']},'mara','station'),true)});
test('legacy save needs no migration and reading/reload does not age the player; malformed awake time rejected',()=>{const s=placed();delete s.townMinutes;assert.equal(s.awakeMinutes,undefined);const before=structuredClone(s);runtime.assertReadable(s);assert.deepEqual(runtime.upgrade(s),before);assert.deepEqual(s,before);assert.throws(()=>runtime.assertReadable({...s,awakeMinutes:-1}));assert.throws(()=>runtime.assertReadable({...s,awakeMinutes:Infinity}))});
test('fatigue is partition-independent; zero energy can reach home and sleep, nap is free',()=>{let s=placed('garden');advanceAwake(s,600);assert.equal(s.energy,100);advanceAwake(s,60);assert.equal(s.energy,95);const other={energy:100,awakeMinutes:0};for(let i=0;i<66;i++)advanceAwake(other,10);assert.equal(other.energy,s.energy);s.energy=0;s.awakeMinutes=1200;const held=structuredClone(s.items),cash=s.cash;s=act(s,'home','travel-map');s=act(s,'bed','sleep');assert.equal(s.energy,100);assert.equal(s.awakeMinutes,0);s.awakeMinutes=660;s=act(s,'bed','rest');assert.equal(s.awakeMinutes,300);assert.equal(s.cash,cash);assert.deepEqual(s.items,held)});
test('residents away from workplaces do not carry their counters and sports with them',()=>{let s=placed('coast');s.known=['ruth','idris'];s.townMinutes=1080;assert.throws(()=>act(s,'ruth','challenge-start:fishing'),/CHALLENGE_UNAVAILABLE/);assert.throws(()=>act(s,'idris','challenge-start:sparring'),/CHALLENGE_UNAVAILABLE/);s.scene='market';assert.ok(!availableTopics(s,'luis').some(t=>['snack','water'].includes(t.id)));s.scene='harbor';assert.ok(!availableTopics(s,'theo').some(t=>['bag','fish'].includes(t.id)))});
test('rest CAS, duplicate/lost response, restart and owner isolation preserve a legacy save and one time advance',async()=>{const dir=mkdtempSync(join(tmpdir(),'life-only-')),cfg={path:join(dir,'qa.sqlite'),worldId:'life-only',gameId:'life-only'};let store=openAsyncSqliteAuthorityStore(cfg);const rt={...runtime,initial:(locale:any,id:string)=>({...placed(),id,locale,awakeMinutes:undefined,energy:0,cash:31,flags:['key','unpacked','talk:mara:key'],history:[{id:'old-talk',kind:'talk',person:'mara',text:['旧记录','Old record']}]})};try{let auth=new AsyncSessionAuthority(store,rt),s=await auth.create('A',randomUUID(),'en');const a=action(s,'bed','rest');const results=await Promise.allSettled([auth.action('A',s.id,a),auth.action('A',s.id,{...a,action_id:randomUUID()})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const current=await auth.get('A',s.id);assert.equal(current.townMinutes,720);assert.equal(current.awakeMinutes,0);assert.equal(current.energy,100);assert.equal(current.cash,31);await auth.action('A',s.id,a);assert.deepEqual(await auth.get('A',s.id),current);await store.close();store=openAsyncSqliteAuthorityStore(cfg);auth=new AsyncSessionAuthority(store,rt);assert.deepEqual(await auth.get('A',s.id),current);await assert.rejects(auth.get('B',s.id),/SESSION_NOT_FOUND/)}finally{await store.close();rmSync(dir,{recursive:true,force:true})}});
