import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initial,applyAction,type Action} from '../src/story/state';
import {crops,plotStatus} from '../src/story/crops';
import {rooms,entityAt} from '../src/world/data';
import {runtime} from '../server/runtime';
import {createLifeRuntime,parseLifeCommand,type LifeHost} from '../server/life-runtime';
import {ContentRegistry,definitionHash,legacyDefinitions,snapPeaDefinition,validateCropDefinition} from '../src/life/registry';
import {addLot,assertLifeReadable,consumeLot,pinLegacy,reconcileAuthored,giftItems} from '../src/life/save';
import {applyLife,lifePlotStatus} from '../src/life/rules';
import type {Admission,Command,ContentRef,LifeSave} from '../src/life/types';
import {acceptedAnimals} from '../src/animals/art';
import {createAnimalRuntime} from '../src/animals/behavior';
import {gameAnimalContext} from '../src/animals/game';
// @ts-expect-error pinned runtime has no declaration
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';

const registry=(enabled=true,defs=[snapPeaDefinition])=>new ContentRegistry(defs,enabled?new Set(defs.map(d=>d.id+'@'+d.revision)):new Set());
const placed=(scene='grocery'):LifeSave=>({...initial('en',randomUUID()),scene,position:{...rooms[scene].spawn},flags:['key','unpacked'],items:{key:1},known:['theo','dani'],visited:Object.keys(rooms)});
const admit=(s:LifeSave,c:Command):Admission=>({scene:s.scene,target:c.verb==='buy-seed'||c.verb==='sell'?'crop-counter':'qa-life-target',...('plot' in c?{plot:c.plot,cultivated:true}:{}),...(['accept-order','deliver-order'].includes(c.verb)?{resident:'theo' as const,premiseRead:true}:{}),...(c.verb==='share-dani'?{resident:'dani' as const,premiseRead:true}:{}),...(c.verb==='display-gift'?{displaySlot:c.slot}:{}),...(c.verb==='observe-animal'?{animal:{id:c.animal,behavior:c.behavior,visualVersion:'domestic-cat-v1'}}:{})});
const step=(s:LifeSave,c:Command,r=registry(),a=admit(s,c))=>{const result=applyLife(s,{actionId:randomUUID(),expectedVersion:s.version,command:c},r,a);result.head.version++;result.head.cursor++;return result.head};
const withProduce=(quantity=3,r=registry(),ref=r.ref('crop:snap-pea'),scene='grocery')=>{const s=pinLegacy(placed(scene),r);addLot(s,r,ref,'produce',quantity,'qa-authored-harvest');return s};
const rejectsPure=(s:LifeSave,c:Command,message:RegExp,r=registry(),a=admit(s,c))=>{const old=structuredClone(s);assert.throws(()=>step(s,c,r,a),message);assert.deepEqual(s,old)};

test('registry locks all legacy economics; immutable revision hashes and strict five-part species contract',()=>{
 const r=registry();for(const [id,c] of Object.entries(crops)){const d=r.get(r.ref('crop:'+id));assert.deepEqual([d.seedCost,d.growMinutes,d.yield,d.salePrice],[c.cost,c.minutes,c.yield,c.price]);assert.ok(Object.isFrozen(d));assert.ok(Object.isFrozen(d.name))}
 assert.equal(definitionHash({...snapPeaDefinition}),r.ref('crop:snap-pea').hash);
 assert.throws(()=>new ContentRegistry([{...snapPeaDefinition,yield:4},{...snapPeaDefinition,yield:3}]),/REVISION_CONFLICT/);
 assert.throws(()=>new ContentRegistry([{...legacyDefinitions[0],revision:2}]),/LEGACY_ID_LOCKED/);
 assert.throws(()=>new ContentRegistry([snapPeaDefinition,{...snapPeaDefinition,id:'crop:renamed-pea',name:['改名豆','Renamed pea']}]),/COSMETIC_SPECIES_DUPLICATE/);
 for(const candidate of [{id:'crop:snap-pea',name:['新豆','New pea']},{...snapPeaDefinition,condition:'anywhere'},{...snapPeaDefinition,actions:['breed']},{...snapPeaDefinition,output:'money'},{...snapPeaDefinition,uses:['decorative']},{...snapPeaDefinition,saleSink:'any-npc'},{...snapPeaDefinition,code:'return cash+100'},{...snapPeaDefinition,yield:6,salePrice:10},{...snapPeaDefinition,assets:['https://example.com/unapproved.png']}])assert.throws(()=>validateCropDefinition(candidate));
 const altered={...r.ref('crop:snap-pea'),hash:'0'.repeat(64)};assert.throws(()=>r.get(altered),/REF_MISMATCH/);
 const original=structuredClone(snapPeaDefinition),rr=new ContentRegistry([original]);original.yield=6;assert.equal(rr.get(rr.ref(original.id)).yield,3);
 const cost=crops.radish.cost;try{crops.radish.cost=cost+1;assert.throws(()=>registry(),/LEGACY_ENGINE_DRIFT/);assert.equal(legacyDefinitions[0].seedCost,cost)}finally{crops.radish.cost=cost}
});
test('read-old no-write, lazy pinning idempotent, starter/flags/history/old crops unchanged and no discovery rewards',()=>{
 const s=placed();s.items={'seed-basil':2,'crop-basil':3};s.plots={'crop-bed-2':{crop:'basil',grown:200,updatedAt:500,wetUntil:1220}};s.flags.push('crop-starter','market-open');s.history=[{id:'old-note',kind:'action',text:['原文','Original']}];s.animalsV1={schema:1,individuals:{'harbor-cat-1':{familiarity:2,lastPetMinute:540}}};const r=registry(),old=structuredClone(s);
 runtime.assertReadable(s);assertLifeReadable(s,r);assert.deepEqual(s,old);const pinned=pinLegacy(s,r);assert.deepEqual(pinLegacy(pinned,r),pinned);assert.deepEqual({...pinned,lifeV1:undefined},{...old,lifeV1:undefined});assert.equal(pinned.lifeV1!.lots.length,2);assert.equal(pinned.lifeV1!.legacyPlotRefs['crop-bed-2'].id,'crop:basil');assert.deepEqual(pinned.lifeV1!.collections,{});assert.deepEqual(pinned.lifeV1!.firstRewards,[]);assert.deepEqual(pinned.lifeV1!.events,[]);
});
test('large legitimate legacy stock is grandfathered; B1 capacity does not strand original harvests',()=>{
 const r=registry();let s=placed('garden');s.items['crop-basil']=12000;s.plots={'crop-bed-2':{crop:'basil',grown:720,updatedAt:540,wetUntil:540}};s=pinLegacy(s,r);const a:Action={action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:entityAt(s.scene,'crop-bed-2')!.approach,target:'crop-bed-2',action:'harvest-crop'};s=reconcileAuthored(s,applyAction(s,a).head,r,a.action_id);assert.equal(s.items['crop-basil'],12003);assert.equal(s.lifeV1!.lots[0].quantity,12003);assertLifeReadable(s,r);s.scene='grocery';s=step(s,{verb:'sell',ref:r.ref('crop:basil')},r);assert.equal(s.items['crop-basil'],12002);
});
test('legacy authored sale, plant, water and harvest mirror only actual inventory delta once',()=>{
 const r=registry();let s=pinLegacy(placed('garden'),r);addLot(s,r,r.ref('crop:basil'),'seed',1,'fixture');
 const act=(target:string,verb:string)=>{const a:Action={action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:entityAt(s.scene,target)!.approach,target,action:verb};const before=s;s=reconcileAuthored(before,applyAction(before,a).head,r,a.action_id);assertLifeReadable(s,r)};
 act('crop-bed-2','plant:basil');act('crop-bed-2','water-crop');s.townMinutes!+=720;assert.ok(plotStatus(s,'crop-bed-2')!.ready);act('crop-bed-2','harvest-crop');assert.equal(s.items['crop-basil'],3);assert.deepEqual(s.lifeV1!.legacyPlotRefs,{});s.scene='grocery';s.position=rooms.grocery.spawn;s.townMinutes=1980;act('crop-counter','sell-crop:basil');assert.equal(s.items['crop-basil'],2);assert.equal(s.lifeV1!.lots.find(l=>l.ref.id==='crop:basil'&&l.kind==='produce')!.quantity,2);assert.equal(s.cash,28);
});
test('watered growth dry-pauses, boundaries and repeated watering, across midnight and labor fatigue',()=>{
 const r=registry(),ref=r.ref('crop:snap-pea');let s=step(placed(),{verb:'buy-seed',ref},r);s.scene='garden';s.position=rooms.garden.spawn;s.townMinutes=1430;s=step(s,{verb:'plant',ref,plot:'life-bed-1'},r);assert.equal(s.energy,98);assert.equal(lifePlotStatus(s,'life-bed-1',r)!.grown,0);s.townMinutes!+=1000;assert.equal(lifePlotStatus(s,'life-bed-1',r)!.grown,0);s=step(s,{verb:'water',plot:'life-bed-1'},r);const wetStart=s.lifeV1!.plots['life-bed-1'].updatedAt;rejectsPure(s,{verb:'water',plot:'life-bed-1'},/WATER_UNAVAILABLE/,r);s.townMinutes=wetStart+719;rejectsPure(s,{verb:'harvest',plot:'life-bed-1'},/CROP_NOT_READY/,r);s.townMinutes=wetStart+720;assert.ok(lifePlotStatus(s,'life-bed-1',r)!.ready);s=step(s,{verb:'harvest',plot:'life-bed-1'},r);assert.equal(s.items['life-produce:snap-pea'],3);assert.equal(s.energy,94);assert.equal(s.awakeMinutes,30);rejectsPure(s,{verb:'harvest',plot:'life-bed-1'},/PLOT_EMPTY/,r);
 const slow={...snapPeaDefinition,revision:2,growMinutes:1440};const rr=registry(true,[snapPeaDefinition,slow]);let q=pinLegacy(placed('garden'),rr);q.lifeV1!.plots['life-bed-1']={ref:rr.ref('crop:snap-pea',2),grown:0,updatedAt:540,wetUntil:1260};q.townMinutes=5000;assert.equal(lifePlotStatus(q,'life-bed-1',rr)!.grown,720);q.awakeMinutes=650;q=step(q,{verb:'water',plot:'life-bed-1'},rr);assert.equal(q.energy,93);q.townMinutes!+=720;q=step(q,{verb:'harvest',plot:'life-bed-1'},rr);assert.equal(q.energy,91);
});
test('three actual rule routes: $29 + seed/Theo gift, $27 + seed, $31/no seed; next planting consumes seed but keeps discovery',()=>{
 const r=registry(),ref=r.ref('crop:snap-pea');const crop=()=>{let s=step(placed(),{verb:'buy-seed',ref},r);s.scene='garden';s.position=rooms.garden.spawn;s=step(s,{verb:'plant',ref,plot:'life-bed-1'},r);s=step(s,{verb:'water',plot:'life-bed-1'},r);s.townMinutes!+=720;s=step(s,{verb:'harvest',plot:'life-bed-1'},r);s.townMinutes=1980;return s};
 let a=crop();a.scene='cafe';a=step(a,{verb:'accept-order',ref},r);a=step(a,{verb:'deliver-order'},r);a=step(a,{verb:'save-seed',ref},r);assert.deepEqual([a.cash,a.items['life-seed:snap-pea'],a.items['life-produce:snap-pea'],a.relations.theo,a.items[giftItems[0]]],[29,1,0,2,1]);
 let b=crop();b=step(b,{verb:'save-seed',ref},r);b.scene='grocery';b=step(step(b,{verb:'sell',ref},r),{verb:'sell',ref},r);assert.deepEqual([b.cash,b.items['life-seed:snap-pea'],b.relations.theo??0],[27,1,0]);b.scene='garden';b=step(b,{verb:'plant',ref,plot:'life-bed-1'},r);assert.equal(b.items['life-seed:snap-pea'],0);assert.ok(b.lifeV1!.collections['seed:crop:snap-pea']);
 let c=crop();c.scene='grocery';for(let n=0;n<3;n++)c=step(c,{verb:'sell',ref},r);assert.equal(c.cash,31);assert.equal(c.items['life-seed:snap-pea']??0,0);assert.equal(c.lifeV1!.collections['seed:crop:snap-pea'],undefined);rejectsPure(c,{verb:'plant',ref,plot:'life-bed-1'},/ITEMS_MISSING/,r);
});
test('ref-pinned v1 inventory/order survive changed v2 economics; wrong batch cannot satisfy accepted order',()=>{
 const d2={...snapPeaDefinition,revision:2,seedCost:7,yield:2,salePrice:5};const r=registry(true,[snapPeaDefinition,d2]),v1=r.ref('crop:snap-pea'),v2=r.ref('crop:snap-pea',2);let s=withProduce(3,r,v1,'cafe');s=step(s,{verb:'accept-order',ref:v1},r);addLot(s,r,v2,'produce',4,'qa-v2-harvest');s=step(s,{verb:'deliver-order'},r);assert.equal(s.cash,35);assert.equal(s.lifeV1!.lots.find(l=>l.kind==='produce'&&l.ref.revision===2)!.quantity,4);s=step(s,{verb:'save-seed',ref:v1},r);assert.equal(s.lifeV1!.lots.find(l=>l.kind==='seed')!.ref.revision,1);s.scene='grocery';s=step(s,{verb:'sell',ref:v2},r);assert.equal(s.cash,40);
 let q=withProduce(2,r,v2,'cafe');q=step(q,{verb:'accept-order',ref:v1},r);rejectsPure(q,{verb:'deliver-order'},/ITEMS_MISSING/,r);
});
test('stop-new blocks purchase/plant/new order but preserves old harvest/sale/conversion/order settlement',()=>{
 const on=registry(),off=registry(false),ref=on.ref('crop:snap-pea');let s=withProduce(2,on,ref,'cafe');s=step(s,{verb:'accept-order',ref},on);s=step(s,{verb:'deliver-order'},off);assert.equal(s.cash,35);s.scene='grocery';rejectsPure(s,{verb:'buy-seed',ref},/CONTENT_NOT_ENABLED/,off);
 let q=withProduce(3,on);q=step(q,{verb:'save-seed',ref},off);rejectsPure(q,{verb:'plant',ref,plot:'life-bed-1'},/CONTENT_NOT_ENABLED/,off);q=step(q,{verb:'sell',ref},off);q.scene='cafe';rejectsPure(q,{verb:'accept-order',ref},/CONTENT_NOT_ENABLED/,off);q.scene='garden';q.lifeV1!.plots['life-bed-1']={ref,grown:720,updatedAt:540,wetUntil:540};q=step(q,{verb:'harvest',plot:'life-bed-1'},off);assert.equal(q.items['life-produce:snap-pea'],4);
});
test('cash/inventory/energy overflow and insufficient item rejection have zero side effects',()=>{
 const r=registry(),ref=r.ref('crop:snap-pea');let s=withProduce();s.cash=998;rejectsPure(s,{verb:'sell',ref},/PURSE_FULL/,r);s.scene='cafe';s=step(s,{verb:'accept-order',ref},r);s.cash=995;rejectsPure(s,{verb:'deliver-order'},/PURSE_FULL/,r);assert.equal(s.items[giftItems[0]],undefined);
 s=withProduce();s.energy=1;s.lifeV1!.plots['life-bed-1']={ref,grown:720,updatedAt:540,wetUntil:540};rejectsPure(s,{verb:'harvest',plot:'life-bed-1'},/ENERGY_LOW/,r);s.cash=5;rejectsPure(s,{verb:'buy-seed',ref},/CASH_LOW/,r);
 s=withProduce(9999);rejectsPure(s,{verb:'harvest',plot:'life-bed-1'},/PLOT_EMPTY/,r);s.lifeV1!.plots['life-bed-1']={ref,grown:720,updatedAt:540,wetUntil:540};rejectsPure(s,{verb:'harvest',plot:'life-bed-1'},/INVENTORY_FULL/,r);s=withProduce(1);s=step(s,{verb:'save-seed',ref},r);rejectsPure(s,{verb:'save-seed',ref},/ITEMS_MISSING/,r);
});
test('orders require introduction/premise/presence; deadline exclusive, no item loss; one active/cooldown/one first gift',()=>{
 const r=registry(),ref=r.ref('crop:snap-pea');let s=withProduce(4,r,ref,'cafe');s.known=[];rejectsPure(s,{verb:'accept-order',ref},/INTRODUCE_FIRST/,r);s.known=['theo'];rejectsPure(s,{verb:'accept-order',ref},/ORDER_PREMISE_UNREAD/,r,{...admit(s,{verb:'accept-order',ref}),premiseRead:false});s=step(s,{verb:'accept-order',ref},r);assert.equal(s.lifeV1!.order!.dueMinute,3900);rejectsPure(s,{verb:'accept-order',ref},/ORDER_ACTIVE/,r);s.townMinutes=3899;s=step(s,{verb:'deliver-order'},r);const end=s.lifeV1!.cooldownUntil;rejectsPure(s,{verb:'accept-order',ref},/ORDER_COOLDOWN/,r);s.townMinutes=Math.ceil(end/1440)*1440+540;s=step(s,{verb:'accept-order',ref},r);s=step(s,{verb:'deliver-order'},r);assert.equal(s.relations.theo,2);assert.equal(s.items[giftItems[0]],1);
 let q=withProduce(2,r,ref,'cafe');q=step(q,{verb:'accept-order',ref},r);q.townMinutes=3900;rejectsPure(q,{verb:'deliver-order'},/ORDER_EXPIRED/,r);q=step(q,{verb:'close-order'},r);assert.equal(q.items['life-produce:snap-pea'],2);assert.equal(q.cash,25);assert.equal(q.items[giftItems[0]],undefined);
});
test('observation collections/Dani gift are distinct from physical inventory and cat memory; stable behavior proof required',()=>{
 const r=registry(),ref=r.ref('crop:snap-pea');let s=withProduce(1,r,ref,'garden');s.animalsV1={schema:1,individuals:{'harbor-cat-1':{familiarity:2,lastPetMinute:540}}};s=step(s,{verb:'save-seed',ref},r);rejectsPure(s,{verb:'share-dani'},/DISCOVERIES_MISSING/,r);
 for(const [behavior,town,scene] of [['sun-rest',540,'station'],['sleep',1300,'courtyard']] as const){s.townMinutes=town;s.scene=scene;s.position=rooms[scene].spawn;const cmd={verb:'observe-animal' as const,animal:'harbor-cat-1',behavior};rejectsPure(s,cmd,/ANIMAL_PROOF_REQUIRED/,r,{scene,target:'qa-life-target'});const snapshot=createAnimalRuntime(acceptedAnimals).tick(0,gameAnimalContext(s,s.position)).find(x=>x.id===cmd.animal)!;assert.equal(snapshot.visible,true);assert.equal(snapshot.phase,behavior);s=step(s,cmd,r,{...admit(s,cmd),animal:{id:snapshot.id,behavior:snapshot.phase as typeof behavior,visualVersion:snapshot.visualVersion}});const count=Object.keys(s.lifeV1!.collections).length;s=step(s,cmd,r);assert.equal(Object.keys(s.lifeV1!.collections).length,count)}
 s.townMinutes=1980;s.scene='garden';s.position=rooms.garden.spawn;const beforeItems=structuredClone(s.items),memory=structuredClone(s.animalsV1);s=step(s,{verb:'share-dani'},r);assert.equal(s.relations.dani,1);assert.equal(s.items[giftItems[1]],1);assert.equal(s.items['life-seed:snap-pea'],beforeItems['life-seed:snap-pea']);assert.deepEqual(s.animalsV1,memory);rejectsPure(s,{verb:'share-dani'},/SHARE_ALREADY_DONE/,r);
 const oldCount=Object.keys(s.lifeV1!.collections).length;rejectsPure(s,{verb:'observe-animal',animal:'harbor-cat-2',behavior:'sleep'},/ANIMAL_PROOF_REQUIRED/,r,{scene:'garden',target:'qa-life-target',animal:{id:'harbor-cat-1',behavior:'sleep',visualVersion:'domestic-cat-v1'}});assert.equal(Object.keys(s.lifeV1!.collections).length,oldCount);
});
test('gift display never duplicates physical keepsake; removal keeps discovery; unknown slots and unowned gifts rejected',()=>{
 const r=registry(),ref=r.ref('crop:snap-pea');let s=step(step(withProduce(2,r,ref,'cafe'),{verb:'accept-order',ref},r),{verb:'deliver-order'},r);s=step(s,{verb:'display-gift',slot:'home-shelf-1',gift:giftItems[0]},r);assert.equal(s.items[giftItems[0]],1);rejectsPure(s,{verb:'display-gift',slot:'home-shelf-2',gift:giftItems[0]},/GIFT_ALREADY_DISPLAYED/,r);rejectsPure(s,{verb:'display-gift',slot:'home-shelf-2',gift:giftItems[1]},/GIFT_MISSING/,r);rejectsPure(s,{verb:'display-gift',slot:'unregistered',gift:giftItems[0]},/DISPLAY_ADMISSION_REQUIRED/,r);s=step(s,{verb:'display-gift',slot:'home-shelf-1'},r);assert.deepEqual(s.lifeV1!.display,{});assert.ok(s.lifeV1!.collections['gift:'+giftItems[0]]);assert.equal(s.items[giftItems[0]],1);
});
test('news retains frozen source hash separate from fictional completion; unread/uncommitted/client assertion rejected',()=>{
 const r=registry(),s=placed(),cmd={verb:'news-memento' as const,edition:'qa-frozen-edition'},proof={id:cmd.edition,hash:'1'.repeat(64),read:true,fictionComplete:true};rejectsPure(s,cmd,/NEWS_PROOF_REQUIRED/,r,{...admit(s,cmd),news:{...proof,read:false}});rejectsPure(s,cmd,/NEWS_PROOF_REQUIRED/,r,{...admit(s,cmd),news:{...proof,fictionComplete:false}});const q=step(s,cmd,r,{...admit(s,cmd),news:proof});const recorded=q.lifeV1!.collections['news:first-experience'].source!;assert.equal(recorded.kind,'frozen-news');assert.ok(recorded.kind==='frozen-news');assert.equal(recorded.hash,proof.hash);assert.equal(q.cash,s.cash);assert.deepEqual(q.items,s.items);const again=step(q,{verb:'news-memento',edition:'qa-next-edition'},r,{...admit(q,cmd),news:{...proof,id:'qa-next-edition'}});assert.equal(Object.keys(again.lifeV1!.collections).length,1);assert.equal(again.lifeV1!.collections['news:first-experience'].source!.id,cmd.edition);
 const action:Action={action_id:randomUUID(),expected_version:0,scene:s.scene,position:s.position,target:'news',action:'life:news-memento',payload:{command:cmd,proof}};assert.throws(()=>parseLifeCommand(action),/INVALID_LIFE_COMMAND/);
});
test('bounded aggregates/events avoid unbounded lots/stories; corrupted ledger/plot/ref/future provenance rejected',()=>{
 const r=registry(),ref=r.ref('crop:snap-pea');let s=withProduce(150);for(let n=0;n<140;n++)s=step(s,{verb:'save-seed',ref},r);assert.equal(s.lifeV1!.lots.length,2);assert.equal(s.lifeV1!.events.length,128);assert.equal(Object.keys(s.lifeV1!.collections).length,1);
 for(const mutate of [(q:LifeSave)=>q.items['life-seed:snap-pea']++,(q:LifeSave)=>q.lifeV1!.lots[0].ref.hash='0'.repeat(64),(q:LifeSave)=>q.lifeV1!.collections['seed:crop:snap-pea'].minute=100000,(q:LifeSave)=>q.lifeV1!.plots.bad={ref,grown:0,updatedAt:540,wetUntil:540},(q:LifeSave)=>(q.lifeV1 as any).arbitrary=true,(q:LifeSave)=>q.lifeV1!.events.push(q.lifeV1!.events[0])]){const q=structuredClone(s);mutate(q);assert.throws(()=>assertLifeReadable(q,r),/UNSUPPORTED_LIFE_SAVE/)}
});

// Fixture host is explicit and not exported to public routes. New plot geometry,
// viewed-premise and live observed pose admission remain B2 integration gates.
const qaHost:LifeHost={admit:(s,a,c)=>({...admit(s,c),target:a.target})};
const action=(s:LifeSave,c:Command,id=randomUUID()):Action=>({action_id:id,expected_version:s.version,scene:s.scene,position:s.position,target:admit(s,c).target,action:'life:'+c.verb,payload:{command:c}});
const stores=()=>{const dir=mkdtempSync(join(tmpdir(),'harbor-life-b1-'));return {dir,config:{path:join(dir,'qa.sqlite'),worldId:'life-b1-qa',gameId:'life-b1-qa'}}};
test('actual SQLite: duplicate/replay, two-handle CAS, restart, stale version/payload mismatch/owner isolation and zero writes on reject',async()=>{
 const {dir,config}=stores(),r=registry(),ref=r.ref('crop:snap-pea');let store=openAsyncSqliteAuthorityStore(config),second=openAsyncSqliteAuthorityStore(config);const rt=createLifeRuntime({...runtime,initial:(locale:any,id:string)=>({...withProduce(3,r,ref,'cafe'),id,locale})},r,qaHost);
 try{let aa=new AsyncSessionAuthority(store,rt),bb=new AsyncSessionAuthority(second,rt);let s:LifeSave=await aa.create('synthetic-life-A',randomUUID(),'en');const accept=action(s,{verb:'accept-order',ref});await aa.action('synthetic-life-A',s.id,accept);s=await aa.get('synthetic-life-A',s.id);const deliver=action(s,{verb:'deliver-order'}),other={...deliver,action_id:randomUUID()};const results=await Promise.allSettled([aa.action('synthetic-life-A',s.id,deliver),bb.action('synthetic-life-A',s.id,other)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const winner=results[0].status==='fulfilled'?deliver:other;const committed:LifeSave=await aa.get('synthetic-life-A',s.id);assert.deepEqual([committed.version,committed.cursor,committed.cash,committed.items['life-produce:snap-pea'],committed.relations.theo,committed.items[giftItems[0]],committed.lifeV1!.events.length],[2,2,35,1,2,1,2]);
 await bb.action('synthetic-life-A',s.id,winner);assert.deepEqual(await aa.get('synthetic-life-A',s.id),committed);
 await assert.rejects(aa.action('synthetic-life-A',s.id,{...winner,action:'life:close-order',payload:{command:{verb:'close-order'}}}),/ACTION_ID_CONFLICT/);
 await assert.rejects(bb.action('synthetic-life-A',s.id,action({...committed,version:0},{verb:'save-seed',ref})),/VERSION_CONFLICT/);
 const rejected=action(committed,{verb:'deliver-order'});await assert.rejects(aa.action('synthetic-life-A',s.id,rejected),/ORDER_MISSING/);assert.deepEqual(await aa.get('synthetic-life-A',s.id),committed);await assert.rejects(bb.get('synthetic-life-B',s.id),/SESSION_NOT_FOUND/);
 await store.close();store=openAsyncSqliteAuthorityStore(config);aa=new AsyncSessionAuthority(store,rt);assert.deepEqual(await aa.get('synthetic-life-A',s.id),committed);await aa.action('synthetic-life-A',s.id,winner);assert.deepEqual(await aa.get('synthetic-life-A',s.id),committed);
 await store.transaction(async(repo:any)=>{assert.equal((await repo.events(s.id,-1)).length,2);assert.ok(!(await repo.receipt('synthetic-life-A',rejected.action_id)))});
 }finally{await store.close();await second.close();rmSync(dir,{recursive:true,force:true})}
});
test('actual SQLite old raw save remains byte-equivalent on open/reopen; first successful life action atomically pins without rewriting history',async()=>{
 const {dir,config}=stores(),r=registry(),ref=r.ref('crop:basil');let store=openAsyncSqliteAuthorityStore(config);const rt=createLifeRuntime(runtime,r,qaHost);const old=placed();old.items={'crop-basil':3,'seed-tomato':2};old.plots={'crop-bed-3':{crop:'tomato',grown:720,updatedAt:540,wetUntil:1260}};old.animalsV1={schema:1,individuals:{'harbor-cat-1':{familiarity:1,lastPetMinute:540}}};old.flags.push('crop-starter','news:checked');old.history=[{id:'old-completion',kind:'action',text:['先前奖励','Prior reward']}];
 try{await store.transaction(async(repo:any)=>{await repo.insert('synthetic-old',randomUUID(),'qa-old-fixture',old,Date.now());await repo.write('synthetic-old',old,old.cursor,Date.now())});let auth=new AsyncSessionAuthority(store,rt);assert.deepEqual(await auth.get('synthetic-old',old.id),old);await store.close();store=openAsyncSqliteAuthorityStore(config);auth=new AsyncSessionAuthority(store,rt);assert.deepEqual(await auth.get('synthetic-old',old.id),old);const result=await auth.action('synthetic-old',old.id,action(old,{verb:'save-seed',ref}));const s:LifeSave=result.head;assert.equal(s.items['crop-basil'],2);assert.equal(s.items['seed-basil'],1);assert.equal(s.cash,old.cash);assert.deepEqual(s.plots,old.plots);assert.deepEqual(s.animalsV1,old.animalsV1);assert.deepEqual(s.flags,old.flags);assert.deepEqual(s.history[0],old.history[0]);assert.equal(s.history.length,2);assert.equal(s.lifeV1!.events.length,1);assert.deepEqual(s.lifeV1!.firstRewards,[]);await store.transaction(async(repo:any)=>{assert.equal((await repo.events(old.id,-1)).length,1)});
 }finally{await store.close();rmSync(dir,{recursive:true,force:true})}
});
test('unmounted runtime rejects client proofs, invalid command fields and missing host; normal animal/story actions preserve life ledger',async()=>{
 const r=registry();assert.throws(()=>createLifeRuntime(runtime,r,undefined as any),/HOST_REQUIRED/);const s=pinLegacy(placed('station'),r),original=structuredClone(s);s.position={x:748,y:670};s.townMinutes=780;const rt=createLifeRuntime(runtime,r,qaHost);const foot=createAnimalRuntime(acceptedAnimals).tick(0,gameAnimalContext(s,s.position)).find(a=>a.id==='harbor-cat-1')!.foot;const cmd:Action={action_id:randomUUID(),expected_version:0,scene:s.scene,position:{x:foot.x-8,y:foot.y+34},target:'harbor-cat-1',action:'animal-pet',actorPosition:foot};const result=await rt.prepare(s,cmd);assert.equal(result.head.animalsV1!.individuals['harbor-cat-1'].familiarity,1);assert.deepEqual(result.head.lifeV1,s.lifeV1);assert.deepEqual(s.lifeV1,original.lifeV1);
 const malformed=action(s,{verb:'observe-animal',animal:'harbor-cat-1',behavior:'sun-rest'});(malformed.payload as any).command.proof={pose:'sun-rest'};assert.throws(()=>rt.validateAction(malformed),/INVALID_LIFE_COMMAND/);const denying=createLifeRuntime(runtime,r,{admit:(head,a)=>({scene:head.scene,target:a.target})});await assert.rejects(denying.prepare(s,action(s,{verb:'observe-animal',animal:'harbor-cat-1',behavior:'sun-rest'})),/ANIMAL_PROOF_REQUIRED/);
});
