// @ts-nocheck -- real compiled Main/View, ordinary input, explicitly synthetic local accounts only.
import {createExplorationAssembly} from '../server/exploration-assembly';
import {withBasilPlantUses} from '../server/plant-basil';
import {createPlantsRegistry,snapPeaV2Ref} from '../server/life-plants-b2';
import {pinLegacy,addLot} from '../src/life/save';
import {makeDemoServer} from './temporary-account-server';
import {initial} from '../src/story/state';
import {rooms} from '../src/world/data';
import {GAME_UUID} from '../src/game-id';
import {mkdtempSync,readFileSync,existsSync} from 'node:fs';
import {join,resolve,extname} from 'node:path';
import {writeFile,mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const directory=mkdtempSync('/tmp/harbor-menu-b24-final-'),out='../evidence/platform-layout';await mkdir(out,{recursive:true});
let models=0;const registry=createPlantsRegistry();
const assembly=createExplorationAssembly({crabEnabled:true,resolveDialogue:async()=>{models++;throw Error('QA_MODEL_DISABLED')},
 decorateLife:r=>withBasilPlantUses(r),
 initial:(l,id)=>{let s=pinLegacy({...initial(l,id),scene:'station',position:{...rooms.station.spawn},
  flags:['key','unpacked','bag-returned','alternative-route','route-open','market-open'],visited:Object.keys(rooms),known:['mara','theo','dani','june'],energy:55,
  items:{key:1,toolbag:1,toolkit:1,wood:2,fish:1,photo:1,route:1,'packed-snack':2,'seed-radish':3,'seed-basil':2,'seed-tomato':2,'crop-radish':2,'crop-basil':3,'crop-tomato':2}},registry);
  addLot(s,registry,snapPeaV2Ref,'seed',2,'synthetic-ui-pea-seed');addLot(s,registry,snapPeaV2Ref,'produce',2,'synthetic-ui-pea-produce');
  return s}
});
const server=await makeDemoServer({directory,port:0,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const report={scope:'compiled actual Main/View/RPGJS; synthetic settled normal browser-cookie account/SQLite; external traffic blocked. Touch is CDP input, not physical device/Telegram.',cases:[],errors:[],models:0,externalBlocked:0};
let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1','--disable-gpu-shader-disk-cache']});
 for(const [width,height,locale] of [[320,568,'zh'],[390,844,'en'],[1280,800,'en']]){
  const label=`${width}-${locale}`,c=await browser.newContext({viewport:{width,height},locale:locale==='zh'?'zh-CN':'en-US',hasTouch:true,serviceWorkers:'block'});
  let failLife=false;const actions=[];
  await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1'){report.externalBlocked++;return r.abort()}
   if(u.pathname.includes('/api/')){if(failLife&&u.pathname.endsWith('/life'))return r.fulfill({status:503,contentType:'application/json',body:'{"error":"LOCAL_READ_TEST"}'});if(u.pathname.endsWith('/action')){actions.push(JSON.parse(r.request().postData()!));await new Promise(r=>setTimeout(r,120))}return r.fulfill({response:await r.fetch()})}
   const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
  await c.addInitScript(()=>{window.__name=f=>f});const p=await c.newPage();p.setDefaultTimeout(20000);p.on('pageerror',e=>report.errors.push({label,error:String(e)}));
  const tx=(zh,en)=>locale==='zh'?zh:en,record={width,height,locale,checks:[]};report.cases.push(record);
  const check=(name,truth)=>{assert.ok(truth,name);record.checks.push(name)};
  const ready=()=>p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));
  const head=async()=>{const id=await p.evaluate(()=>window.alteruLocalStorage.getItem('harbor-journey'));return (await c.request.get(`${server.url}/${GAME_UUID}/api/sessions/${id}`)).json()};
  const snap=async name=>p.screenshot({path:`${out}/${label}-${name}.png`});
  const settle=()=>p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(null)))));
  const root=async name=>{await p.locator('.harbor-mainnav').getByRole('button',{name,exact:true}).click();await settle()};
  const mapMeasure=()=>p.evaluate(()=>{const b=document.querySelector('.harbor-panel__body'),m=document.querySelector('.harbor-map-gesture'),s=document.querySelector('.harbor-panel > .harbor-subnav');return {scrollTop:b.scrollTop,scrollHeight:b.scrollHeight,clientHeight:b.clientHeight,zoom:document.querySelector('.harbor-map-tools span').textContent,transform:document.querySelector('.harbor-map-paper').style.transform,bodyBox:b.getBoundingClientRect().toJSON(),mapBox:m.getBoundingClientRect().toJSON(),subnavBox:s.getBoundingClientRect().toJSON(),parent:s.parentElement.className,overflow:document.documentElement.scrollWidth>innerWidth+1}});
  await p.goto(server.url+'/?debug=1');await ready();for(let i=0;i<3;i++)await p.locator('.harbor-opening button').click();await settle();
  await p.locator('.harbor-header nav').getByRole('button',{name:tx('地图','Map'),exact:true}).click();await settle();await p.locator('.harbor-map-gesture').waitFor();await p.waitForTimeout(200);
  check('opening transfers focus into modal',await p.evaluate(()=>!!document.activeElement.closest('[role="dialog"]')));
  record.top=await mapMeasure();check('classification outside clipped scroll body',record.top.subnavBox.y+record.top.subnavBox.height<=record.top.bodyBox.y+1);await snap('map-top');
  await p.getByRole('button',{name:tx('放大','Zoom in'),exact:true}).click();await settle();await p.locator('.harbor-panel__body').evaluate(e=>e.scrollTo(0,0));record.zoomed=await mapMeasure();const box=await p.locator('.harbor-map-gesture').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+Math.min(box.height/2,70));await p.mouse.wheel(0,180);await p.waitForTimeout(300);record.wheel=await mapMeasure();check('wheel scrolls without zoom',record.wheel.zoom===record.zoomed.zoom&&record.wheel.scrollTop>record.zoomed.scrollTop);await snap('map-wheel');
  const saved=await mapMeasure();await root(tx('地图','Map'));await p.waitForTimeout(100);check('repeated root retains zoom and reading position',(await mapMeasure()).transform===saved.transform&&(await mapMeasure()).scrollTop===saved.scrollTop);
  await root(tx('行囊','Bag'));await root(tx('地图','Map'));await p.waitForTimeout(200);record.restored=await mapMeasure();check('cross-menu map view and scroll restored',record.restored.transform===saved.transform&&Math.abs(record.restored.scrollTop-saved.scrollTop)<2);
  await p.locator('.harbor-panel__body').evaluate(e=>e.scrollTo(0,0));await p.waitForTimeout(100);
  // Native page-scroll gesture over the map; no map zoom/pan mode enabled.
  const touch=await c.newCDPSession(p),tb=await p.locator('.harbor-map-gesture').boundingBox(),sy=tb.y+Math.min(tb.height-15,100),sx=tb.x+tb.width/2;
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:sx,y:sy}]});for(let n=1;n<=5;n++){await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:sx,y:sy-n*12}]});await p.waitForTimeout(20)}await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(250);record.touch=await mapMeasure();check('normal touch scroll keeps zoom',record.touch.zoom===saved.zoom&&record.touch.scrollTop>0);
  await p.getByRole('button',{name:tx('拖动地图','Pan map'),exact:true}).click();await settle();check('pan mode explicit and reversible',await p.locator('.harbor-map-gesture').getAttribute('data-pan')==='true');await p.getByRole('button',{name:tx('放大','Zoom in'),exact:true}).click();await p.locator('.harbor-panel__body').evaluate(e=>e.scrollTo(0,0));const panBefore=await mapMeasure(),pb=await p.locator('.harbor-map-gesture').boundingBox(),py=pb.y+pb.height/2,px=pb.x+pb.width/2;await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:px,y:py}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:px+40,y:py}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();check('explicit touch pan moves only map', (await mapMeasure()).transform!==panBefore.transform&&(await mapMeasure()).scrollTop===panBefore.scrollTop);await p.getByRole('button',{name:tx('结束拖动','Done panning'),exact:true}).click();await settle();check('normal touch scrolling restored',await p.locator('.harbor-map-gesture').getAttribute('data-pan')==='false');
  await p.getByRole('button',{name:tx('全图','Fit'),exact:true}).click();await settle();await p.locator('.harbor-panel__body').evaluate(e=>e.scrollTo(0,e.scrollHeight));await snap('map-bottom');
  await p.locator('.harbor-panel > .harbor-subnav').getByRole('button',{name:tx('探索事项','Exploration'),exact:true}).click();await settle();check('map exploration switch',await p.locator('.harbor-map-gesture').count()===0);await p.locator('.harbor-panel > .harbor-subnav').getByRole('button',{name:tx('地点','Places'),exact:true}).click();await settle();check('places switch restores map',await p.locator('.harbor-map-gesture').count()===1);
  await root(tx('人物','People'));await p.locator('.harbor-rel__person').first().click();await settle();await p.locator('.harbor-rel__identity').waitFor();check('person details open',await p.locator('.harbor-rel__identity').count()===1);await p.getByRole('button',{name:tx('返回列表','Back to list'),exact:true}).click();await settle();await p.locator('.harbor-rel__list').waitFor();check('person back restores list',await p.locator('.harbor-rel__list').count()===1);
  await root(tx('系统','System'));for(const [zh,en] of [['设置','Settings'],['操作与帮助','Controls & help'],['我的旅程','My journeys']]){await p.getByRole('button',{name:tx(zh,en),exact:true}).click();await settle();await p.getByRole('button',{name:tx('返回上一处','Back'),exact:true}).click();await settle();check(en+' back returns to system root',await p.locator('.harbor-system__options').count()===1)}
  await root(tx('行囊','Bag'));await p.waitForTimeout(200);await snap('bag-list');check('unpublished mint and AI actions absent',await p.locator('[data-bag-item*="harbor-mint"]').count()===0&&await p.getByRole('button',{name:tx('收入记录 · 消耗一份叶','Add to my notebook · use one portion'),exact:true}).count()===0);record.art=await p.locator('[data-bag-item]').evaluateAll(es=>es.map(e=>({id:e.getAttribute('data-bag-item'),quantity:e.querySelector('.harbor-bag__quantity').textContent,art:e.querySelector('[data-item-art]').getAttribute('data-item-art'),source:e.querySelector('img')?.getAttribute('data-crop-source'),loaded:!e.querySelector('img')||e.querySelector('img').naturalWidth>0,svg:e.querySelectorAll('svg').length})));
  check('all eight formal corresponding art assets loaded',record.art.filter(a=>a.art==='available').length===8&&record.art.every(a=>a.loaded));check('no generic SVG represents goods',record.art.every(a=>a.svg===0));check('bag sections flow with body without overlay',await p.locator('.harbor-bag > .harbor-subnav').evaluate(e=>getComputedStyle(e).position==='relative'));await p.locator('.harbor-bag__list').getByRole('button').filter({has:p.locator('[data-item-art="available"]')}).first().click();await settle();await snap('bag-existing-art');await p.getByRole('button',{name:tx('返回物品列表','Back to items'),exact:true}).click();await settle();
  await p.locator('[data-bag-item="item:wood"]').tap();await settle();check('detail heading receives focus',await p.evaluate(()=>document.activeElement.matches('[data-bag-detail] h3')));check('detail uses same wood art',await p.locator('[data-bag-detail] img').getAttribute('data-crop-source')==='./art/bag/wood.png');await snap('bag-detail');
  await p.getByRole('button',{name:tx('返回物品列表','Back to items'),exact:true}).click();await settle();check('back focus returns to selected row',await p.evaluate(()=>document.activeElement.getAttribute('data-bag-item')==='item:wood'));
  await p.locator('[data-bag-item="item:photo"]').click();await settle();await p.getByRole('button',{name:tx('放大查看','View closely'),exact:true}).click();await settle();await p.keyboard.press('Escape');await settle();check('Escape closes only top portrait',await p.locator('.harbor-portrait-full').count()===0&&await p.locator('.harbor-panel--bag').count()===1);check('portrait returns focus to its opener',await p.getByRole('button',{name:tx('放大查看','View closely'),exact:true}).evaluate(e=>e===document.activeElement));
  await p.getByRole('button',{name:tx('返回物品列表','Back to items'),exact:true}).click();await settle();
  const before=await head();await p.locator('[data-bag-item="crop:radish@1:produce"]').click();await settle();const saveSeed=p.getByRole('button',{name:tx('留种 · 消耗1份收成','Save seed · use 1 harvest unit'),exact:true});await saveSeed.evaluate(e=>{e.click();e.click();e.click()});await p.waitForFunction(()=>document.querySelector('[data-bag-item="crop:radish@1:produce"] .harbor-bag__quantity')?.textContent==='×1');const after=await head();check('rapid leave-seed clicks settle once',after.items['crop-radish']===before.items['crop-radish']-1&&after.items['seed-radish']===before.items['seed-radish']+1&&actions.filter(a=>a.action==='life:save-seed').length===1);record.saveSeedDelta={produce:-1,seed:1,version:after.version-before.version};
  await p.getByRole('button',{name:tx('返回物品列表','Back to items'),exact:true}).click();await settle();await p.locator('[data-bag-item="item:packed-snack"]').click();await settle();const beforeSnack=await head();await p.getByRole('button',{name:tx('吃1份 · 精力+30','Eat 1 · +30 energy'),exact:true}).evaluate(e=>{e.click();e.click()});await p.waitForFunction(()=>document.querySelector('[data-bag-item="item:packed-snack"] .harbor-bag__quantity')?.textContent==='×1');const afterSnack=await head();check('snack settles once and refreshes energy',afterSnack.items['packed-snack']===beforeSnack.items['packed-snack']-1&&afterSnack.energy===beforeSnack.energy+30&&actions.filter(a=>a.action==='snack-eat').length===1);
  await p.getByRole('button',{name:tx('返回物品列表','Back to items'),exact:true}).click();await settle();await p.locator('[data-bag-item="item:packed-snack"]').click();await settle();await p.getByRole('button',{name:tx('吃1份 · 精力+30','Eat 1 · +30 energy'),exact:true}).evaluate(e=>{e.click();e.click()});await p.waitForFunction(()=>document.querySelector('[data-bag-detail] h3')?.textContent?.includes('×0'));check('depleted selected snack remains at zero without duplicate consumption',await p.getByRole('button',{name:tx('吃1份 · 精力+30','Eat 1 · +30 energy'),exact:true}).count()===0&&actions.filter(a=>a.action==='snack-eat').length===2);await snap('bag-depleted');
  await p.getByRole('button',{name:tx('返回物品列表','Back to items'),exact:true}).click();await settle();await p.locator('.harbor-bag__search input').fill('zzzz');check('search empty state and clear work',await p.locator('[data-bag-item]').count()===0);await p.locator('.harbor-bag__search input').fill('');if(width<700)await p.locator('.harbor-bag__category select').selectOption('produce');else await p.locator('.harbor-bag__filters').getByRole('button',{name:tx('收成','Harvest'),exact:true}).click();await settle();check('category filter contains harvest only',await p.locator('[data-bag-item]').count()===4);if(width<700)await p.locator('.harbor-bag__category select').selectOption('all');else await p.locator('.harbor-bag__filters').getByRole('button',{name:tx('全部','All'),exact:true}).click();await settle();
  // Focus wrap remains in the active modal; page movement and time stay paused.
  await p.locator('[data-menu-close]').focus();await p.keyboard.press('Shift+Tab');check('backward Tab wraps inside modal',await p.evaluate(()=>!!document.activeElement.closest('.harbor-panel')));await p.keyboard.press('Tab');check('forward Tab wraps to close',await p.evaluate(()=>document.activeElement.hasAttribute('data-menu-close')));
  const paused=await head(),playerBefore=await p.evaluate(()=>{const p=document.querySelector('#rpg').__rpgClient.getCurrentPlayer();return [p.x(),p.y()]});await p.keyboard.press('ArrowRight');await p.waitForTimeout(1200);const still=await head(),playerAfter=await p.evaluate(()=>{const p=document.querySelector('#rpg').__rpgClient.getCurrentPlayer();return [p.x(),p.y()]});check('menu reading pauses authoritative time and world movement',still.townMinutes===paused.townMinutes&&JSON.stringify(playerBefore)===JSON.stringify(playerAfter));
  check('no horizontal page overflow',!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1));
  await p.locator('.harbor-bag__search input').focus();await p.keyboard.press('Escape');await settle();check('Escape works from search and restores header opener',await p.locator('.harbor-panel').count()===0&&await p.evaluate(()=>!!document.activeElement.closest('.harbor-header')));
  await p.locator('.harbor-header nav').getByRole('button',{name:tx('行囊','Bag'),exact:true}).click();await settle();await p.locator('[data-menu-close]').click();await settle();check('close can reopen and restores opener',await p.locator('.harbor-panel').count()===0);await p.locator('.harbor-header nav').getByRole('button',{name:tx('行囊','Bag'),exact:true}).click();await settle();await snap('bag-final');
  // Intentional unavailable projection read; saved quantities and exact artwork stay visible, uses disabled.
  failLife=true;await p.reload();await ready();await p.locator('.harbor-header nav').getByRole('button',{name:tx('行囊','Bag'),exact:true}).click();await settle();await p.getByRole('button',{name:tx('重试读取','Try again'),exact:true}).waitFor();await p.locator('[data-bag-item="crop:radish@1:produce"]').click();await settle();check('read failure keeps saved quantity and art',await p.locator('[data-bag-item="crop:radish@1:produce"] .harbor-bag__quantity').innerText()==='×1'&&await p.locator('[data-bag-detail] img').count()===1);check('read failure cannot invent a use action',await p.getByRole('button',{name:tx('留种 · 消耗1份收成','Save seed · use 1 harvest unit'),exact:true}).count()===0);await snap('bag-read-failure');
  failLife=false;await p.getByRole('button',{name:tx('重试读取','Try again'),exact:true}).click();await settle();await p.getByRole('button',{name:tx('留种 · 消耗1份收成','Save seed · use 1 harvest unit'),exact:true}).waitFor();check('retry restores original authoritative quantity',await p.locator('[data-bag-item="crop:radish@1:produce"] .harbor-bag__quantity').innerText()==='×1');await snap('bag-read-recovered');
  record.finalHead={id:(await head()).id,version:(await head()).version,items:(await head()).items};record.actions=actions.map(a=>({action:a.action,id:a.action_id}));await c.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2));
 }
 checkDistinct();function checkDistinct(){assert.equal(new Set(report.cases.map(c=>c.finalHead.id)).size,3);assert.ok(report.cases.every(c=>c.finalHead.items.wood===2))}
 assert.equal(report.errors.length,0);assert.equal(models,0);report.models=models;report.result='PASS';
}catch(e){report.failure=String(e);for(const context of browser?.contexts()??[])for(const p of context.pages())await p.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1}finally{report.models=models;await writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser?.close();await server.close()}
console.log(JSON.stringify({result:report.result,cases:report.cases.map(c=>({width:c.width,checks:c.checks.length})),errors:report.errors,failure:report.failure,models}));
