// @ts-nocheck -- isolated normal browser capability, unchanged actual authority, synthetic own initial state.
import {createExplorationAssembly} from '../server/exploration-assembly';
import {withBasilPlantUses} from '../server/plant-basil';import {withWildMint} from '../server/wild-mint';
import {makeDemoServer} from './temporary-account-server';import {initial} from '../src/story/state';
import assert from 'node:assert/strict';import {GAME_UUID} from '../src/game-id';import {chromium} from 'playwright';import {mkdtempSync,existsSync,readFileSync} from 'node:fs';import {mkdir,writeFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';
const out=resolve('../evidence/smoothness');await mkdir(out,{recursive:true});
const builds=process.env.SMOOTH_DIST?[[process.env.SMOOTH_LABEL??'candidate',resolve(process.env.SMOOTH_DIST)]]:[['6a25ce8','/Users/yin/code/games/harbor-native-release-6a25ce8-20261008/source/dist'],['a08f9b5','/Users/yin/code/games/harbor-motion-p0-6a25-20261008/source/dist']];
const delays=process.env.SMOOTH_DELAYS?.split(',').map(Number)??[0,600,1500];
const assembly=createExplorationAssembly({crabEnabled:true,resolveDialogue:async()=>{throw Error('MODEL_DISABLED')},decorateLife:r=>withWildMint(withBasilPlantUses(r),{enabled:true}),initial:(l,id)=>({...initial(l,id),scene:'station',position:{x:480,y:557},known:['mara'],flags:['key','unpacked','bag-returned'],items:{key:1},visited:['station','harbor']})});
const server=await makeDemoServer({directory:mkdtempSync('/tmp/harbor-smooth-'),port:5595,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority});
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
const report={scope:'actual compiled Main/View/RPGJS and normal own isolated SQLite/browser capability; rAF player+NPC coordinates, real input and public protocol; synthetic initial state; no physical phone/Telegram/model',cases:[],paidCalls:0};
function summarize(samples,events,from,to){
 const frames=samples.filter(s=>s.at>=from&&s.at<=to),runs=[];let start;const travel=frames.reduce((n,s,i)=>i?n+Math.abs(s.x-frames[i-1].x):n,0);let zero=0;
 for(let i=1;i<frames.length;i++){const a=frames[i-1],b=frames[i],still=Math.abs(b.x-a.x)<.1,dt=b.at-a.at;if(still){zero+=dt;start??=a.at}else if(start!==undefined){if(b.at-start>=120)runs.push({start,end:b.at,ms:b.at-start,requests:events.filter(e=>e.at>=start&&e.at<=b.at).map(e=>({phase:e.phase,action:e.action,status:e.status,error:e.error}))});start=undefined}}
 if(start!==undefined&&to-start>=120)runs.push({start,end:to,ms:to-start});
 const npcTravel=frames.reduce((n,s,i)=>{if(!i)return n;const previous=frames[i-1].actors;return n+s.actors.reduce((d,a)=>{const p=previous.find(x=>x.id===a.id);return d+(p?Math.hypot(a.x-p.x,a.y-p.y):0)},0)},0);
 const gaps=frames.slice(1).map((s,i)=>s.at-frames[i].at).sort((a,b)=>a-b);
 return{worldPausedMs:frames.slice(1).reduce((n,s,i)=>n+(s.worldPaused==='true'?s.at-frames[i].at:0),0),travel,meanSpeed:travel/((to-from)/1000),zeroDisplacementMs:zero,longestZeroRunMs:Math.max(0,...runs.map(r=>r.ms)),runs,npcTravel,rafP95Ms:gaps[Math.floor(gaps.length*.95)]??0,frameCount:frames.length};
}
try{for(const[build,dist]of builds)for(const delay of delays)for(const[width,height]of(process.env.SMOOTH_VERIFY?[[320,568],[390,844],[1280,800]]:[[390,844]])){if(width===1280&&delay!==0)continue;
 const label=build+'-'+delay+(process.env.SMOOTH_VERIFY?'-'+width:''),rec={label,build,delay,width,height,events:[],pageErrors:[]};report.cases.push(rec);const c=await browser.newContext({viewport:{width,height},hasTouch:true,serviceWorkers:'block'});
 await c.route('**/*',async r=>{try{const q=r.request(),u=new URL(q.url());if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname.includes('/api/')){const operation=u.pathname.split('/').at(-1);let b;try{b=q.postDataJSON()}catch{};if(['motion','active-play'].includes(operation)&&q.method()==='POST'){rec.events.push({at:Date.now(),phase:'send',action:b.action});if(delay)await new Promise(z=>setTimeout(z,delay))}const response=await r.fetch({url:server.url+u.pathname+u.search});if(['motion','active-play'].includes(operation)){const v=await response.json();rec.events.push({at:Date.now(),phase:'ack',action:b?.action,status:response.status(),error:v.error,townMinutes:v.fields?.townMinutes,position:v.fields?.position})}return r.fulfill({response})}const file=resolve(dist,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(dist+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({contentType:{'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.tmx':'application/xml'}[extname(file)]??'application/octet-stream',body:readFileSync(file)})}catch{}});
 await c.addInitScript(()=>{window.__name=f=>f});const p=await c.newPage();p.on('pageerror',e=>rec.pageErrors.push(String(e)));try{
 await p.goto(server.url+'/?debug=1');await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'),null,{timeout:60000});for(let i=0;i<3;i++)await p.locator('.harbor-opening button').click();
 for(let i=0;i<200;i++){const m=rec.events.filter(v=>v.phase==='ack'&&v.action==='candidate-motion-open'&&v.status===200).at(-1),a=rec.events.filter(v=>v.phase==='ack'&&v.action==='candidate-active-open'&&v.status===200).at(-1);if(m&&a)break;await p.waitForTimeout(100)}await p.waitForTimeout(200);
 await p.evaluate(()=>{window.__samples=[];window.__sampling=true;const sample=()=>{if(!window.__sampling)return;const c=document.querySelector('#rpg').__rpgClient,p=c.getCurrentPlayer();window.__samples.push({at:Date.now(),x:p.x(),y:p.y(),worldPaused:document.querySelector('#rpg').dataset.worldPaused,predictionBlocked:document.querySelector('#rpg').dataset.predictionBlocked,actors:Object.values(c.sceneMap.events()).filter(e=>(e.id.startsWith('person-')||e.id.includes('animal')||e.id.includes('dog')||e.id.includes('crab'))&&e.graphics().length).map(e=>({id:e.id,x:e.x(),y:e.y(),pose:e.animationName()}))});requestAnimationFrame(sample)};requestAnimationFrame(sample)});
 rec.inputStart=Date.now();await p.keyboard.down('ArrowRight');await p.waitForTimeout(6000);await p.keyboard.up('ArrowRight');rec.inputEnd=Date.now();await p.waitForTimeout(1500);rec.samples=await p.evaluate(()=>{return window.__samples});rec.moving=summarize(rec.samples,rec.events,rec.inputStart+150,rec.inputEnd-150);await p.screenshot({path:out+'/'+label+'.png'});rec.result='MEASURED';
 if(process.env.SMOOTH_VERIFY){
  assert.ok(rec.moving.meanSpeed>100,label+' initial continuous speed');assert.equal(rec.moving.worldPausedMs,0,label+' network does not pause world');assert.ok(rec.moving.longestZeroRunMs<(delay===1500?600:150),label+' no periodic whole-request movement freeze');
  const measure=()=>p.evaluate(()=>{const c=document.querySelector('#rpg').__rpgClient,p=c.getCurrentPlayer();return{x:p.x(),y:p.y(),actors:Object.values(c.sceneMap.events()).filter(e=>(e.id.startsWith('person-')||e.id.includes('animal')||e.id.includes('dog'))&&e.graphics().length).map(e=>({id:e.id,x:e.x(),y:e.y()}))}});
  const a=await measure();await p.waitForTimeout(1000);const b=await measure();assert.ok(Math.hypot(a.x-b.x,a.y-b.y)<2,'key release stops without teleport');
  if(width<1280){const box=await p.locator('.harbor-stick').boundingBox(),cdp=await c.newCDPSession(p);rec.touchStart=Date.now();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:box.x+box.width/2-35,y:box.y+box.height/2}]});await p.waitForTimeout(6000);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});rec.touchEnd=Date.now();await cdp.detach();await p.waitForTimeout(500);rec.touch=summarize(await p.evaluate(()=>window.__samples),rec.events,rec.touchStart+150,rec.touchEnd-150);assert.ok(rec.touch.meanSpeed>80,'continuous actual touch motion');assert.equal(rec.touch.worldPausedMs,0);assert.ok(rec.touch.longestZeroRunMs<(delay===1500?1600:200));}
  await p.locator('.harbor-header nav').getByRole('button',{name:'Map',exact:true}).click();await p.locator('.harbor-map-gesture').waitFor();await p.waitForTimeout(delay===1500?11000:2500);const paused=await measure();await p.waitForTimeout(1000);const still=await measure();assert.deepEqual(still,paused,'real menu pauses player and NPC');
  const [j]=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions')).json(),saved=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions/'+j.id)).json();rec.saved={position:saved.position,scene:saved.scene,version:saved.version,townMinutes:saved.townMinutes,clockRemainder:saved.activePlayClock.remainderMs};assert.equal(saved.cash,25);assert.equal(saved.items.key,1);await p.reload();await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));const reopened=await measure();assert.ok(Math.hypot(reopened.x-saved.position.x,reopened.y-saved.position.y)<2,'reload preserves confirmed head');
  await p.evaluate(()=>{window.__samples=[];window.__sampling=true;const sample=()=>{if(!window.__sampling)return;const c=document.querySelector('#rpg').__rpgClient,p=c.getCurrentPlayer();window.__samples.push({at:Date.now(),x:p.x(),y:p.y(),worldPaused:document.querySelector('#rpg').dataset.worldPaused,predictionBlocked:document.querySelector('#rpg').dataset.predictionBlocked,actors:Object.values(c.sceneMap.events()).filter(e=>(e.id.startsWith('person-')||e.id.includes('animal')||e.id.includes('dog')||e.id.includes('crab'))&&e.graphics().length).map(e=>({id:e.id,x:e.x(),y:e.y(),pose:e.animationName()}))});requestAnimationFrame(sample)};requestAnimationFrame(sample)});
  const cdp=await c.newCDPSession(p);rec.backgroundStart=Date.now();await cdp.send('Page.setWebLifecycleState',{state:'frozen'});await new Promise(r=>setTimeout(r,3500));await cdp.send('Page.setWebLifecycleState',{state:'active'});await cdp.detach();await p.waitForTimeout(delay===1500?7000:3000);rec.resumeStart=Date.now();await p.keyboard.down('ArrowRight');await p.waitForTimeout(2500);await p.keyboard.up('ArrowRight');rec.resumeEnd=Date.now();rec.resume=summarize(await p.evaluate(()=>window.__samples),rec.events,rec.resumeStart+150,rec.resumeEnd-150);assert.ok(rec.resume.travel>100,'browser lifecycle resume input works');assert.ok(!rec.events.some(e=>e.error&&!['MOTION_EXPIRED','ACTIVE_LEASE_EXPIRED','MOTION_TOO_FAST'].includes(e.error)),'no unexpected protocol error');assert.equal(rec.pageErrors.length,0);rec.result='PASS';
 }
 await p.evaluate(()=>{window.__sampling=false});
 }catch(e){rec.result='FAIL';rec.failure=String(e)}finally{await c.unrouteAll({behavior:'ignoreErrors'});await c.close();await writeFile(out+'/report-'+(process.env.SMOOTH_LABEL??'comparison')+'.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({label,result:rec.result,moving:rec.moving&&{meanSpeed:rec.moving.meanSpeed,longestZeroRunMs:rec.moving.longestZeroRunMs,zeroDisplacementMs:rec.moving.zeroDisplacementMs,npcTravel:rec.moving.npcTravel,rafP95Ms:rec.moving.rafP95Ms},failure:rec.failure}))}
}}finally{await browser.close();await server.close()}
