// @ts-nocheck -- compiled Main/RPGJS with explicit local-only synthetic fixture.
import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';import {withWildMint} from '../server/wild-mint';import {makeDemoServer} from './temporary-account-server';import {initial} from '../src/story/state';import {GAME_UUID} from '../src/game-id';
import {mkdtempSync,readFileSync,existsSync} from 'node:fs';import {join,resolve,extname} from 'node:path';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {chromium} from 'playwright';import assert from 'node:assert/strict';
const out=resolve('../evidence/browser'),directory=mkdtempSync('/tmp/harbor-p0-'),dist=resolve(process.env.P0_DIST??'dist'),onlyDelay=process.env.P0_ONLY_DELAY===undefined?null:Number(process.env.P0_ONLY_DELAY);await mkdir(out,{recursive:true});let models=0;
const assembly=createExplorationAssembly({crabEnabled:true,resolveDialogue:async()=>{models++;throw Error('QA_MODEL_BLOCKED')},decorateLife:r=>withWildMint(withBasilPlantUses(r,{enabled:true}),{enabled:true}),initial:(l,id)=>({...initial(l,id),scene:'station',position:{x:733,y:557},known:['mara'],flags:['key','unpacked','bag-returned'],items:{key:1},visited:['station','harbor']})});
const server=await makeDemoServer({directory,port:5594,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority});const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const prior=process.env.P0_RESUME?JSON.parse(await readFile(out+'/report.json','utf8')):null;
const report={scope:'compiled actual Main/View/RPGJS, isolated normal local browser capability and explicitly synthetic settled fixture; real keyboard/joystick/target input; local SQLite actual unchanged server rules; no original saves/model; not physical/Telegram',dist,cases:prior?.cases.filter(c=>c.result==='PASS')??[],errors:[],models:0};const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
try{
 for(const [width,height] of [[320,568],[390,844],[1280,800]])for(const delay of (onlyDelay===null?(width===1280?[0]:[0,600,1500]):[onlyDelay])){
  const label=`${width}-${delay}`;if(report.cases.some(c=>c.label===label&&c.result==='PASS'))continue;const rec={label,width,height,delay,checks:[],requests:[],samples:[],pageErrors:[]};report.cases.push(rec);const c=await browser.newContext({viewport:{width,height},locale:'en-US',hasTouch:width<1280,serviceWorkers:'block'});
  await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname.includes('/api/')){const operation=u.pathname.split('/').at(-1);let b;try{b=q.postDataJSON()}catch{};if(['ask','notes-generate'].includes(b?.action)||u.pathname.includes('/media/')||u.pathname.includes('/assets/'))return r.abort();if(q.method()==='POST'&&['motion','active-play'].includes(operation)){rec.requests.push({at:Date.now(),phase:'send',action:b.action,position:b.position});if(delay)await new Promise(z=>setTimeout(z,delay));}const res=await r.fetch({url:server.url+u.pathname+u.search});if(['motion','active-play'].includes(operation)){const body=await res.json();rec.requests.push({at:Date.now(),phase:'ack',operation,status:res.status(),error:body.error,position:body.fields?.position});}return r.fulfill({response:res});}const file=resolve(dist,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(dist+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({status:200,contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)});});
  const p=await c.newPage();p.setDefaultTimeout(30000);p.on('pageerror',e=>rec.pageErrors.push(String(e)));const point=()=>p.evaluate(()=>{const p=document.querySelector('#rpg').__rpgClient.getCurrentPlayer();return {x:p.x(),y:p.y()}});const ready=()=>p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'),null,{timeout:60000});const check=(name,value)=>{assert.ok(value,label+': '+name);rec.checks.push(name)};
  try{
   await p.goto(server.url+'/?debug=1');await ready();for(let i=0;i<3;i++)await p.locator('.harbor-opening button').click();for(let i=0;i<180;i++){const ack=rec.requests.filter(v=>v.phase==='ack'),m=ack.filter(v=>v.operation==='motion'&&v.status===200).at(-1),a=ack.filter(v=>v.operation==='active-play').at(-1);if(m&&a?.status===200&&a.at>m.at)break;await p.waitForTimeout(100)}await p.waitForTimeout(200);
   await p.evaluate(()=>{window.__p0=[];window.__p0timer=setInterval(()=>{const p=document.querySelector('#rpg').__rpgClient.getCurrentPlayer();window.__p0.push({at:Date.now(),x:p.x(),y:p.y()})},60)});await p.keyboard.down('ArrowRight');await p.waitForTimeout(12000);await p.keyboard.up('ArrowRight');await p.waitForTimeout(3500);rec.samples=await p.evaluate(()=>{clearInterval(window.__p0timer);return window.__p0});rec.rebounds=rec.samples.flatMap((s,i)=>i&&s.x<rec.samples[i-1].x-15?[{before:rec.samples[i-1],after:s}]:[]);rec.range={min:Math.min(...rec.samples.map(s=>s.x)),max:Math.max(...rec.samples.map(s=>s.x))};check('12-second held input has no backward restore',rec.rebounds.length===0);check('held input makes confirmed progress',rec.range.max-rec.range.min>5);await p.screenshot({path:out+'/'+label+'-continuous.png'});
   const map=p.locator('.harbor-header nav').getByRole('button',{name:'Map',exact:true});await map.focus();await p.keyboard.press('Enter');await p.locator('.harbor-map-gesture').waitFor();await p.waitForTimeout(2500);const paused=await point();await p.waitForTimeout(1600);check('menu pauses without coordinate reset',Math.hypot((await point()).x-paused.x,(await point()).y-paused.y)<1);for(let i=0;i<12&&await p.locator('.harbor-panel').count();i++){await p.keyboard.press('Escape');await p.waitForTimeout(300)}check('menu actually closes after its confirmation',await p.locator('.harbor-panel').count()===0);await p.waitForTimeout(2000);await p.keyboard.down('ArrowLeft');await p.waitForTimeout(delay===1500?10000:2200);await p.keyboard.up('ArrowLeft');await p.waitForTimeout(delay===1500?6500:3500);check('stop and resume after menu keep input usable',(await point()).x<paused.x-3);
   if(delay===0&&width===390){const begin=await point(),box=await p.locator('.harbor-stick').boundingBox(),cdp=await c.newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2-25,y:box.y+box.height/2,id:1}]});await p.waitForTimeout(800);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(1300);check('real mobile viewport joystick touch moves and releases',(await point()).x<begin.x-5);await cdp.detach();await p.keyboard.down('ArrowRight');await p.waitForTimeout(3500);await p.keyboard.up('ArrowRight');await p.waitForFunction(()=>document.querySelector('.harbor-action.is-ready')?.textContent.includes('The Harbor'),null,{timeout:45000});await p.locator('.harbor-action.is-ready').click();await p.getByRole('button',{name:'Go to The Harbor',exact:true}).click();await ready();await p.waitForTimeout(800);check('legitimate scene arrival is restored',await p.locator('.harbor-location').innerText().then(v=>v.includes('The Harbor')));}
   const closeMap=p.locator('.harbor-header nav').getByRole('button',{name:'Map',exact:true});await closeMap.focus();await p.keyboard.press('Enter');await p.locator('.harbor-map-gesture').waitFor();await p.waitForTimeout(delay?4500:1200);const [j]=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions')).json(),saved=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions/'+j.id)).json();rec.saved={position:saved.position,scene:saved.scene,version:saved.version,cash:saved.cash};await p.reload();await ready();await p.waitForTimeout(200);const reopened=await point();check('reopen restores actual committed position',Math.hypot(reopened.x-saved.position.x,reopened.y-saved.position.y)<4);check('original inventory and cash unchanged',saved.cash===25&&saved.items.key===1);check('no page errors',rec.pageErrors.length===0);check('strict transport checks report no unexpected failure',!rec.requests.some(v=>v.error&&!['ACTIVE_LEASE_BUSY','MOTION_EXPIRED','ACTIVE_LEASE_EXPIRED'].includes(v.error)));const expired=rec.requests.filter(v=>v.error==='MOTION_EXPIRED');check('every expired motion has a later server-confirmed step',expired.every(e=>rec.requests.some(v=>v.at>e.at&&v.phase==='ack'&&v.operation==='motion'&&v.status===200&&v.position)));rec.result='PASS';
  }catch(e){rec.result='FAIL';rec.failure=String(e);await p.screenshot({path:out+'/'+label+'-failure.png'}).catch(()=>{});rec.buttons=await p.getByRole('button').allTextContents().catch(()=>[]);report.errors.push({label,error:rec.failure});}finally{await c.unrouteAll({behavior:'ignoreErrors'});await c.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({label,result:rec.result,checks:rec.checks,failure:rec.failure,range:rec.range,rebounds:rec.rebounds?.length}));}
 }
 report.models=models;report.result=report.errors.length?'FAIL':'PASS';assert.equal(models,0);
}finally{await browser.close();await server.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2)+'\n');}if(report.result==='FAIL')process.exitCode=1;
