// @ts-nocheck -- compiled real Main/View, local synthetic account and ordinary input.
import {mintNode} from '../src/life/plant-uses';
import {mintEntities} from '../src/world/wild-mint-art';
import {localPoint,isCluster} from '../src/candidate/continuity';
import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';import {withWildMint} from '../server/wild-mint';import {makeDemoServer} from './temporary-account-server';import {initial} from '../src/story/state';import {rooms} from '../src/world/data';import {GAME_UUID} from '../src/game-id';
import {mkdtempSync,rmSync,readFileSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve,extname} from 'node:path';import {writeFile,mkdir} from 'node:fs/promises';import {chromium} from 'playwright';import assert from 'node:assert/strict';
const directory=mkdtempSync(join(tmpdir(),'dog-mint-road-ui-')),out=process.env.HARBOR_PREP_UI_OUT??'../live-20261007/evidence/native-main-ui-final';await mkdir(out,{recursive:true});let spec,models=0;
const assembly=createExplorationAssembly({crabEnabled:true,resolveDialogue:async()=>{models++;throw Error('QA_MODEL_DISABLED')},decorateLife:r=>withWildMint(withBasilPlantUses(r,{enabled:true}),{enabled:true}),initial:(l,id)=>({...initial(l,id),...structuredClone(spec),id,version:0,cursor:0,history:[]})});
const server=await makeDemoServer({directory,port:5579,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const report={scope:'local compiled actual Main/View/RPGJS + temporary account/SQLite; explicitly synthetic settled initial scene; subsequent normal keyboard/menu input. Native dog/mint admitted candidate. Not physical/Telegram.',cases:[],errors:[],models:0,externalBlocked:0};
let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1','--disable-gpu-shader-disk-cache']});
 for(const [width,height,locale] of [[320,568,'zh'],[390,844,'en'],[1280,800,'en']])for(const scene of (process.env.HARBOR_PREP_UI_HILL?['hill']:['hill','station'])){
  spec={scene,townMinutes:540,flags:['key','unpacked','bag-returned','alternative-route','route-open','market-open'],visited:Object.keys(rooms),known:['dani','theo','mara'],items:{key:1},position:scene==='hill'?{...mintEntities('hill')[0].approach}:{x:600,y:760}};
  const label=`${width}-${locale}-${scene}`,c=await browser.newContext({viewport:{width,height},locale:locale==='zh'?'zh-CN':'en-US',serviceWorkers:'block'});
  await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1'){report.externalBlocked++;return r.abort()}if(u.pathname.includes('/api/'))return r.fulfill({response:await r.fetch({url:server.url+u.pathname+u.search})});const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({status:200,contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
  await c.addInitScript(()=>{window.__name=f=>f});const page=await c.newPage();page.on('pageerror',e=>report.errors.push({label,error:String(e)}));page.setDefaultTimeout(20000);await page.goto(server.url+'/?debug=1');
  const ready=()=>page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await ready();for(let i=0;i<3;i++)await page.locator('.harbor-opening button').click();
  const measure=()=>page.evaluate(()=>{const c=document.querySelector('#rpg').__rpgClient,p=c.getCurrentPlayer(),ev=Object.values(c.sceneMap.events());return {room:c.activeRoom()?.name,position:{x:p.x(),y:p.y()},events:ev.length,newDogs:ev.filter(e=>e.id.includes('dog')).length,newMint:ev.filter(e=>e.id.includes('mint')).length,overflow:document.documentElement.scrollWidth>innerWidth+1,loading:!!document.querySelector('.harbor-loading'),error:document.querySelector('.harbor-error')?.textContent}});
  const before=await measure();assert.equal(before.newDogs,scene==='station'?1:0);assert.equal(before.newMint,scene==='hill'?1:0);assert.ok(before.events>10);assert.equal(before.overflow,false);
  await page.screenshot({path:`${out}/${label}-baseline-platform-layout.png`});
  let after=before;
  if(scene==='hill'){
   await page.locator('.harbor-action.is-ready').click();await page.locator('[data-wild-mint]').waitFor();await page.getByRole('button',{name:locale==='zh'?'采一份叶':'Collect one portion of leaves',exact:true}).click();await page.waitForTimeout(800);await page.screenshot({path:`${out}/${label}-collected-platform-layout.png`});await page.getByRole('button',{name:locale==='zh'?'关闭':'Close',exact:true}).click();
   await page.getByRole('button',{name:locale==='zh'?'行囊':'Bag',exact:true}).click();const leaf=page.locator('[data-bag-item="item:wild:harbor-mint-leaf"]');await leaf.waitFor();await leaf.click();await page.waitForTimeout(400);await page.screenshot({path:`${out}/${label}-bag-platform-layout.png`});
  }else{await page.keyboard.down('ArrowUp');await page.waitForTimeout(600);await page.keyboard.up('ArrowUp');await page.waitForTimeout(700);after=await measure();assert.ok(after.position.y<before.position.y-8);await page.screenshot({path:`${out}/${label}-moved-platform-layout.png`});}
  const [journey]=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions')).json();const head=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions/'+journey.id)).json();if(scene==='hill'){assert.equal(head.items['wild:harbor-mint-leaf'],1);assert.equal(head.plantUsesV1.mint.stock,1);}assert.equal(head.items.key,1);
  await page.reload();await ready();const restored=await measure(),savedDisplay=isCluster(head.scene)?localPoint(head.scene,restored.position):restored.position;assert.ok(Math.hypot(savedDisplay.x-head.position.x,savedDisplay.y-head.position.y)<4);report.cases.push({label,before,after,restored,version:head.version,result:'PASS'});await c.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2));
 }
 assert.deepEqual(report.errors,[]);assert.equal(models,0);report.models=models;report.result='PASS';
}catch(e){report.result='FAIL';report.failure=String(e);report.stack=e.stack;process.exitCode=1}
finally{await writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser?.close();await server.close();rmSync(directory,{recursive:true,force:true})}console.log(JSON.stringify({result:report.result,cases:report.cases.length,failure:report.failure,errors:report.errors}));
