import {walkable} from '../src/engine/world';
import {test,after} from 'node:test';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
import {createNativeCrab,nativeCrabBody,nativeCrabClear,nativeCrabProfile} from '../src/animals/native-crab';
import {nativeCrabSheet,nativeCrabManifest} from '../src/animals/native-crab-art';
import type {Facing,Context} from '../src/animals/types';import {createAnimalRuntime} from '../src/animals/behavior';import {acceptedAnimals} from '../src/animals/art';import {gameAnimalContext,animalPeople} from '../src/animals/game';import {bodyAt,overlaps} from '../src/animals/spatial';import {profiles} from '../src/animals/config';import {initial} from '../src/story/state';import {people,rooms} from '../src/world/data';import {dynamicWorld} from '../src/dynamic-assets/layout';import {landWorld} from '../src/life/land';import {runtime} from '../server/runtime';import {sampleAnimal,createAnimalLife} from '../server/animal-life';import {validAnimalSave} from '../src/animals/memory';import {contentHash} from '../server/animal-content';import {chooseNativeCrabLane,chooseNativePlayerStart} from './crab-c1-space';import {previewClear,type Geometry} from './animal-stand-space';import geometryFile from './animal-stand-space-geometry.json';
const metrics={sourceCommit:'ce6944b756efe8ed0ff0f7453673d5c82141cbbd',scenarios:0,groundAndVisualFrames:0,overlapCases:0,actorIDs:new Set<string>(),modelCalls:0};after(()=>writeFileSync('../evidence/native-ground-matrix.json',JSON.stringify({...metrics,actorIDs:[...metrics.actorIDs].sort()},null,2)+'\n'));
const directions:Facing[]=['down','left','right','up'],geometry=geometryFile as unknown as Geometry,relative=nativeCrabManifest.displayEnvelope,preferred={coast:{x:1040,y:550},beach:{x:540,y:530},dock:{x:700,y:650}};
const defs=(scene:string,direction:Facing,lane:any)=>[{id:'qa-native-crab',visualVersion:'shore-crab-native-c1-v2' as const,schedule:{morning:lane,afternoon:lane,evening:lane,night:lane}}];
test('native geometry pin, four-direction ground reflection, complete consumer sheets and disabled production',()=>{
 assert.equal(nativeCrabManifest.nativeSources,9);assert.equal(Object.keys(nativeCrabManifest.frames).length,12);assert.equal(nativeCrabProfile.productionEnabled,false);assert.equal(nativeCrabProfile.saveRegistration,false);assert.notDeepEqual(nativeCrabProfile.ground.down,{w:14,h:8});
 assert.equal(nativeCrabProfile.ground.right.x,-nativeCrabProfile.ground.left.x-nativeCrabProfile.ground.left.w);for(const d of directions)for(const p of ['stand','walkA','walkB'])assert.ok(nativeCrabSheet().textures[p+'-'+d]);
});
test('latest formal world all shore maps/4 directions/4 periods with dynamic original animals and all 22 configured residents',()=>{
 assert.equal(Object.keys(people).length,22);for(const minute of [540,780,1080,1300]){
  Object.keys(animalPeople({townMinutes:minute,flags:['key','unpacked','route-open','market-open']})).forEach(id=>metrics.actorIDs.add(id));
  for(const scene of ['coast','beach','dock'] as const)for(const direction of directions){
   const at=preferred[scene],save={...initial('en','qa-old-native'),scene,townMinutes:minute,position:{x:at.x-8,y:at.y-116},flags:['key','unpacked','route-open','market-open']},world=landWorld(dynamicWorld(save.flags,false),save.landV1),ctx=gameAnimalContext(save,save.position,{world}),animals=createAnimalRuntime(acceptedAnimals);let states=animals.tick(0,ctx);
   const lane=chooseNativeCrabLane(at,scene,world.scenes[scene].interior,relative,{context:ctx,states,geometry},direction);assert.ok(lane,`${scene}/${direction}/${minute}`);
   const start=chooseNativePlayerStart(lane.ends[0],direction,world,scene);assert.ok(start,`${scene}/${direction}: player start`);save.position=start;ctx.player={...start,...world.actor};animals.reset();states=animals.tick(0,ctx);const original=contentHash(save),engine=createNativeCrab(defs(scene,direction,lane),{displayClear:(p,id,r,c)=>previewClear({x:Math.round(p.x),y:Math.round(p.y)},id,r,relative,{context:c,states,geometry})});
   let maximumDistance=0;for(let i=0;i<360;i++){states=animals.tick(1/60,ctx);const reserved=states.filter(a=>a.visible&&a.scene===scene).map(a=>bodyAt(a.foot,profiles[a.species])),f=engine.tick(1/60,ctx,reserved)[0];maximumDistance=Math.max(maximumDistance,f.distance);if(f.visible){assert.ok(nativeCrabClear(f.foot,direction,scene,lane.region,ctx,reserved));assert.ok(previewClear({x:Math.round(f.foot.x),y:Math.round(f.foot.y)},scene,lane.region,relative,{context:ctx,states,geometry}));assert.equal(f.foot[direction==='down'||direction==='up'?'y':'x'],lane.ends[0][direction==='down'||direction==='up'?'y':'x']);metrics.groundAndVisualFrames++}}
   assert.ok(maximumDistance>8,`${scene}/${direction}/${minute}: real stride progress ${JSON.stringify({maximumDistance,lane,frame:engine.snapshot()[0]})}`);assert.equal(contentHash(save),original);metrics.scenarios++;
  }
 }assert.equal(metrics.scenarios,48);assert.ok(metrics.groundAndVisualFrames>12000);assert.equal(metrics.actorIDs.size,22);
});
test('native body prevents planted/swing footprint crossing for water, props, player, people and existing animals; old overlap hides only crab',()=>{
 for(const direction of directions){const scene='coast',region={x:0,y:0,w:500,h:500},lane={scene,region,facing:direction,ends:[{x:200,y:240},{x:direction==='down'||direction==='up'?264:200,y:direction==='down'||direction==='up'?240:304}]} as const,ctx:Context={world:{width:500,height:500,step:4,actor:{w:16,h:12},scenes:{coast:{interior:region,spawn:{x:10,y:10},obstacles:[]}}},scene,townMinutes:540,player:{x:10,y:10,w:16,h:12},people:{},forbidden:{coast:[]},paused:false},body=nativeCrabBody(lane.ends[0],direction);
  for(const blocker of ['obstacle','player','people','old-animal']){const c=structuredClone(ctx),reserved:any[]=[];if(blocker==='obstacle')c.world.scenes.coast.obstacles=[body];if(blocker==='player')c.player={...body};if(blocker==='people')c.people.owen={scene,foot:lane.ends[0],body};if(blocker==='old-animal')reserved.push(body);assert.equal(nativeCrabClear(lane.ends[0],direction,scene,region,c,reserved),false);const frozen=contentHash(c),e=createNativeCrab(defs(scene,direction,lane));for(let i=0;i<120;i++){const f=e.tick(1/60,c,reserved)[0];if(f.visible)assert.equal(overlaps(nativeCrabBody(f.foot,direction),body),false)}assert.equal(contentHash(c),frozen);metrics.overlapCases++}
  const engine=createNativeCrab(defs(scene,direction,lane));let f=engine.tick(0,ctx)[0];assert.ok(f.visible);const full=structuredClone(ctx);full.forbidden.coast=[region];assert.equal(engine.tick(1/60,full)[0].visible,false);assert.ok(engine.tick(0,ctx)[0].visible);const paused={...ctx,paused:true},before=engine.tick(0,paused)[0];assert.deepEqual(engine.tick(5,paused)[0],before);
 }
});
test('latest formal old-save readers stay 3 cats/4 gulls, reject crab memory and crab proof; native import never writes player state',()=>{
 const s=initial('en','native-old-reader'),before=contentHash(s);runtime.assertReadable(s);createAnimalLife(runtime).runtime.assertReadable(s);assert.equal(acceptedAnimals.length,7);assert.ok(!acceptedAnimals.some(a=>String(a.species)==='crab'));assert.equal(validAnimalSave({schema:1,individuals:{'qa-native-crab':{familiarity:1}}},acceptedAnimals,540),false);assert.throws(()=>sampleAnimal({...s,scene:'coast'},'qa-native-crab',{x:700,y:700}),/ANIMAL_AWAY/);nativeCrabSheet();assert.equal(contentHash(s),before);
});

test('retreat is lateral and bounded; blocked side holds stand, finished retreat never walks back toward player until resume distance',()=>{
 const region={x:0,y:0,w:500,h:500},ctx:Context={world:{width:500,height:500,step:4,actor:{w:16,h:12},scenes:{coast:{interior:region,spawn:{x:10,y:10},obstacles:[]}}},scene:'coast',townMinutes:540,player:{x:192,y:184,w:16,h:12},people:{},forbidden:{coast:[]},paused:false};
 for(const direction of directions){const axis=direction==='down'||direction==='up'?'x':'y',lane={scene:'coast',region,facing:direction,ends:[{x:200,y:240},{x:axis==='x'?264:200,y:axis==='x'?240:304}]} as const,c=structuredClone(ctx);if(axis==='y')c.player={x:142,y:234,w:16,h:12};const e=createNativeCrab(defs('coast',direction,lane));e.tick(0,c);let f=e.tick(1/60,c)[0];assert.equal(f.phase,'retreat');for(let i=0;i<240;i++)f=e.tick(1/60,c)[0];assert.equal(f.foot[axis],lane.ends[1][axis]);assert.equal(f.phase,'alert');assert.equal(f.pose,'stand');const stop=structuredClone(f.foot);for(let i=0;i<240;i++)f=e.tick(1/60,c)[0];assert.deepEqual(f.foot,stop);assert.ok(f.distance<=64+1e-7);const blocker=axis==='x'?{x:230,y:205,w:2,h:35}:{x:180,y:270,w:35,h:2};c.world.scenes.coast.obstacles=[blocker];const blocked=createNativeCrab(defs('coast',direction,lane));blocked.tick(0,c);f=blocked.tick(1/60,c)[0];assert.equal(f.phase,'alert');assert.equal(f.pose,'stand');assert.deepEqual(f.foot,lane.ends[0]);
 }
});

test('all 22 actual resident art/ground profiles across four crab facings resolve synthetic overlap without moving the resident or player',()=>{
 const region={x:0,y:0,w:500,h:500},scene='coast';for(const direction of directions)for(const id of Object.keys(people)){
  const origin={x:200,y:240},axis=direction==='down'||direction==='up'?'x':'y',lane={scene,region,facing:direction,ends:[origin,{x:axis==='x'?264:200,y:axis==='x'?240:304}]} as const,ctx:Context={world:{width:500,height:500,step:4,actor:{w:16,h:12},scenes:{coast:{interior:region,spawn:{x:10,y:10},obstacles:[]}}},scene,townMinutes:540,player:{x:400,y:400,w:16,h:12},people:{[id]:{scene,foot:origin,body:{x:origin.x-9,y:origin.y-8,w:18,h:8}}},forbidden:{coast:[]},paused:false},pin=contentHash(ctx);
  assert.equal(nativeCrabClear(origin,direction,scene,region,ctx),false);const engine=createNativeCrab(defs(scene,direction,lane),{displayClear:(p,s,r,c)=>previewClear(p,s,r,relative,{context:c,states:[],geometry})});for(let i=0;i<30;i++){const f=engine.tick(1/60,ctx)[0];if(f.visible){assert.ok(nativeCrabClear(f.foot,direction,scene,region,ctx));assert.ok(previewClear(f.foot,scene,region,relative,{context:ctx,states:[],geometry}))}}assert.equal(contentHash(ctx),pin);metrics.overlapCases++;
 }
});
