import {test} from 'node:test';import assert from 'node:assert/strict';import {configuredNews} from '../server/news/configured';import {createRuntime} from '../server/runtime';import {entityAt} from '../src/world/data';import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
test('exact expiry boundary stops an unread edition but preserves an already-started story',async()=>{
 const path='doc/qa/real-news-20261005/catalog.json';
 const frozenBytes=readFileSync(path,'utf8');const edition=JSON.parse(frozenBytes).records[0];
 const expiry=Date.parse(edition.expiresAt);let now=expiry-1;
 const b=configuredNews(createRuntime(),path,()=>now);
 const unread={...b.runtime.initial('en',randomUUID()),scene:'garden',known:['dani'],position:entityAt('garden','dani')!.approach};
 const action={action_id:randomUUID(),expected_version:0,scene:'garden',position:unread.position,target:'dani',action:'talk:visitor-news'};
 assert.equal(b.newsProject!(unread).newsAvailability,'current');
 const started=(await b.runtime.prepare(unread,action)).head;
 assert.ok(started.flags.includes('news:heard'));
 now=expiry;
 assert.equal(b.runtime.initial('en',randomUUID()).newsEdition,undefined);
 assert.equal(b.newsProject!(unread).newsAvailability,'expired');
 assert.equal(b.newsProject!(unread).version,unread.version);
 await assert.rejects(b.runtime.prepare(unread,{...action,action_id:randomUUID()}),/NEWS_SOURCE_UNAVAILABLE/);
 const continued=(await b.runtime.prepare(started,{...action,action_id:randomUUID(),expected_version:started.version,action:'talk:visitor-test'})).head;
 assert.equal(continued.newsEdition.id,edition.id);
 assert.equal(continued.newsEdition.fetchedAt,edition.fetchedAt);
 assert.equal(continued.newsEdition.expiresAt,edition.expiresAt);
 assert.ok(continued.flags.includes('news:test'));
 const finished=(await b.runtime.prepare(continued,{...action,action_id:randomUUID(),expected_version:continued.version,action:'talk:visitor-budget'})).head;
 assert.ok(finished.flags.includes('news:checked'));
 assert.equal(finished.cash,unread.cash);
 assert.equal(finished.newsEdition.expiresAt,edition.expiresAt);
 assert.equal(readFileSync(path,'utf8'),frozenBytes);
});
test('frozen news config opt-in retains source dates; expiry is not silently refreshed',()=>{const now=Date.parse('2026-10-05T10:00:00Z'),base=createRuntime();assert.equal(configuredNews(base).runtime,base);const bundle=configuredNews(base,'doc/qa/real-news-20261005/catalog.json',()=>now);const s=bundle.runtime.initial('en',randomUUID());assert.equal(s.newsEdition.publishedAt,'2026-09-16T18:00:00.000Z');assert.equal(bundle.newsProject!(s).newsAvailability,'current');const later=configuredNews(base,'doc/qa/real-news-20261005/catalog.json',()=>Date.parse('2026-10-10T00:00Z'));assert.equal(later.runtime.initial('en',randomUUID()).newsEdition,undefined);assert.equal(later.newsProject!(s).newsAvailability,'expired')});
test('expired/unavailable stories reject free-dialogue topic resolution too',async()=>{const now=Date.parse('2026-10-05T10:00Z');const base=createRuntime(async()=>({topic:'visitor-news',reply:['测试','Test']}));const b=configuredNews(base,'doc/qa/real-news-20261005/catalog.json',()=>now);const s={...b.runtime.initial('en',randomUUID()),scene:'garden',known:['dani'],position:entityAt('garden','dani')!.approach};const expired=configuredNews(base,'doc/qa/real-news-20261005/catalog.json',()=>Date.parse('2026-10-10T00:00Z'));await assert.rejects(expired.runtime.prepare(s,{action_id:randomUUID(),expected_version:0,scene:'garden',position:s.position,target:'dani',action:'ask',payload:{text:'What is new?'}},undefined,{owner:'QA'}),/NEWS_SOURCE_UNAVAILABLE/)});
test('an existing unread journey pins real news at its next notebook action; read legacy story stays intact',async()=>{const b=configuredNews(createRuntime(),'doc/qa/real-news-20261005/catalog.json',()=>Date.parse('2026-10-05T10:00Z'));const old={...createRuntime().initial('en',randomUUID()),scene:'garden',known:['dani'],position:entityAt('garden','dani')!.approach};const a={action_id:randomUUID(),expected_version:0,scene:'garden',position:old.position,target:'dani',action:'talk:visitor-news'};const result=await b.runtime.prepare(old,a);assert.equal(old.newsMode,undefined);assert.equal(result.head.newsMode,'live');assert.equal(result.head.newsEdition.source,'Federal Reserve Board');const read={...old,flags:['news:heard']};const continued=await b.runtime.prepare(read,{...a,action:'talk:visitor-test'});assert.equal(continued.head.newsMode,undefined);assert.match(continued.text[1],/06:00/)});
