import{test}from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{initial,applyAction,availableTopics,type Save}from'../src/story/state';import{nextResidents}from'../src/world/next-residents';import{nextStoryLeads}from'../src/story/next-neighbors';import{relationshipStory}from'../src/story/relationships';import{dialogueContext}from'../server/dialogue-context';import{runtime}from'../server/runtime';import{rooms,entityAt,people}from'../src/world/data';import{residentRoutes,residentHere}from'../src/world/residents';
// @ts-expect-error frozen runtime
import{AsyncSessionAuthority,openAsyncSqliteAuthorityStore}from'../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const command=(s:Save,p:string,action:string)=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:entityAt(s.scene,p)!.approach,target:p,action});
const visit=(s:Save,p:string):Save=>({...s,scene:residentRoutes[p][0].scene,townMinutes:540,position:entityAt(residentRoutes[p][0].scene,p)!.approach});
test('six prior occupations, 22 configured identities, no unseen spoilers; all offline outcomes preserve mainline and wallet',()=>{
 assert.equal(Object.keys(people).length,22);assert.equal(new Set(nextResidents.map(p=>p.role[1])).size,6);
 for(const p of nextResidents)for(const choice of ['n2-choice-a','n2-choice-b']){
 let s=visit(initial('en','next-six'),p.id);const run=(person:string,act:string)=>s=applyAction(s,command(s,person,act)).head;
 assert.equal(nextStoryLeads(s).length,0);assert.equal(availableTopics(s,p.id).length,0);run(p.id,'introduce');assert.ok(availableTopics(s,p.id).some(t=>t.id==='n2-start'));assert.ok(!availableTopics(s,p.id).some(t=>t.id===choice));run(p.id,'talk:n2-start');
 const one=relationshipStory(s).leads.find(l=>l.id==='neighbors2-'+p.id)!;assert.deepEqual(one.people,[p.id]);assert.ok(one.next&&one.place);assert.throws(()=>run(p.id,'talk:'+choice),/TOPIC_UNAVAILABLE/);
 s=visit(s,p.partner);run(p.partner,'introduce');run(p.partner,'talk:n2-'+p.id+'-consult');s=visit(s,p.id);const before=structuredClone(s);run(p.id,'talk:'+choice);
 assert.ok(s.flags.includes('neighbors2:'+p.id+':done'));assert.equal(s.relations[p.id],1);assert.equal(s.relations[p.partner],1);assert.equal(s.cash,before.cash);assert.deepEqual(s.items,before.items);assert.equal(s.standing,before.standing);assert.ok(!s.flags.includes('market-open'));
 assert.throws(()=>run(p.id,'talk:'+choice),/TOPIC_UNAVAILABLE/);assert.ok(!availableTopics(s,p.id).some(t=>t.id==='n2-start'||t.id==='n2-choice-a'||t.id==='n2-choice-b'));
 const ctx=dialogueContext(s,p.id);assert.equal(ctx.residentLife.neighborStory?.completed,true);assert.equal(nextStoryLeads(s)[0].state,'done');assert.ok(s.history.some(h=>h.person===p.partner));run(p.id,'talk:n2-recall');assert.ok(!availableTopics(s,p.id).some(t=>t.id==='n2-recall'));runtime.assertReadable(s);
 }
});
test('waiting stories persist through missed schedules and night; delayed consultation cannot be skipped',()=>{for(const p of nextResidents){let s=visit(initial('en','wait'),p.id);s.known=[p.id];s=applyAction(s,command(s,p.id,'talk:n2-start')).head;const night={...s,townMinutes:1300};assert.equal(nextStoryLeads(night)[0].place,undefined);assert.match(nextStoryLeads(night)[0].next![1],/06:00/);assert.equal(residentHere(night,p.id,s.scene),false);assert.ok(!availableTopics(night,p.id).length);const tomorrow={...s,townMinutes:1980};assert.equal(nextStoryLeads(tomorrow)[0].state,'active');}});
test('actual local authority: completion response replay, restart and owner isolation',async()=>{const dir=mkdtempSync(join(tmpdir(),'six-neighbor-'));const cfg={path:join(dir,'qa.sqlite'),worldId:'six-neighbors',gameId:'six-neighbors'};let store=openAsyncSqliteAuthorityStore(cfg);const p=nextResidents[0];const seed={...runtime,initial:(l:any,id:string)=>({...visit(initial(l,id),p.id),known:[p.id,p.partner],flags:['talk:'+p.id+':n2-start','talk:'+p.partner+':n2-'+p.id+'-consult']})};try{let auth=new AsyncSessionAuthority(store,seed),s=await auth.create('A',randomUUID(),'en');const a=command(s,p.id,'talk:n2-choice-a');await auth.action('A',s.id,a);await auth.action('A',s.id,a);const head=await auth.get('A',s.id);assert.equal(head.version,1);assert.equal(head.relations[p.id],1);await store.close();store=openAsyncSqliteAuthorityStore(cfg);auth=new AsyncSessionAuthority(store,seed);assert.deepEqual(await auth.get('A',s.id),head);await assert.rejects(auth.get('B',s.id),/SESSION_NOT_FOUND/)}finally{await store.close();rmSync(dir,{recursive:true,force:true})}});
