import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {Pool} from 'pg';
import {makeDemoServer} from './temporary-account-server';import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';import {initial,type Save} from '../src/story/state';import {entityAt,rooms} from '../src/world/data';import {GAME_UUID} from '../src/game-id';import {motionActionId,applyMotionAck} from '../src/candidate/clock-types';import {activePlayActionId} from '../src/candidate/active-play-types';import {nativeCrabId,nativeCrabPin} from '../src/animals/native-crab-config';import {nativeCrabFrame,advanceNativeCrab,currentNativeSample,validNativeCrabField} from '../src/animals/native-crab-game';import {crabCommissionRef} from '../server/native-crab-life';import {landWorld} from '../src/life/land';import {dynamicWorld} from '../src/dynamic-assets/layout';import {findPath} from '../src/engine/world';import {lifeProjectionKey} from '../src/candidate/life-projection';
// @ts-expect-error frozen authority
import {AsyncSessionAuthority,initializeAsyncAuthoritySchema,openPgAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
// @ts-expect-error frozen PG adapter
import {initializeCandidateSchema,registerCandidateWorld} from '../vendor/dynamic-runtime/packages/pg-candidate/index.mjs';
for(const backend of process.env.HARBOR_ACCOUNT_QA_PG_URL?['pg']:['sqlite'])test(`native crab ${backend}/normal account HTTP: real authority checkpoint/proof, bounded head, atomic observation/share, rollback and restart`,async()=>{
 const directory=mkdtempSync(join(tmpdir(),'harbor-crab-owner-'));let now=100000,enabled=true,models=0,waits=0;const client=randomUUID(),cases:string[]=[];
 const factory=()=>createExplorationAssembly({now:()=>now,boot:'native-crab-owner-only',crabEnabled:enabled,observeWait:async(ms:number)=>{assert.equal(ms,400);waits++;now+=ms},decorateLife:(r:any)=>withBasilPlantUses(r),resolveDialogue:async()=>{models++;throw Error('MODEL_FORBIDDEN')},initial:(l:any,id:string)=>({...initial(l,id),scene:'coast',position:{x:1032,y:462},known:['ruth'],flags:['key','unpacked'],visited:Object.keys(rooms)})});
 let pool:Pool|undefined,schema:string|undefined,options:any;
 if(backend==='pg'){const raw=process.env.HARBOR_ACCOUNT_QA_PG_URL!,u=new URL(raw);assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/harbor_account_qa_20261005');pool=new Pool({connectionString:raw,max:8});schema='kit_crab_owner_'+randomUUID().replaceAll('-','').slice(0,16);options={pool,schema,worldId:GAME_UUID,gameId:GAME_UUID,environment:'test'};const c=await pool.connect();try{await initializeCandidateSchema(c,options);await initializeAsyncAuthoritySchema(c,options);await registerCandidateWorld(c,options)}finally{c.release()}}
 const start=async()=>{const a=factory();return makeDemoServer({directory,providedStore:pool?await openPgAuthorityStore(options):undefined,providedRuntime:a.runtime,lifeProject:a.lifeProject,landProject:a.landProject,decorateAuthority:a.decorateAuthority})};
 let server=await start(),base=server.url+'/'+GAME_UUID+'/api',s:any;let cookie='',owner='';
 try{
  const bootstrap=async()=>{const r=await fetch(base+'/bootstrap',{method:'POST'});assert.equal(r.status,200);return r.headers.get('set-cookie')!.split(';')[0]};cookie=await bootstrap();owner=createHash('sha256').update(cookie.split('=')[1]).digest('hex');
  const req=async(path:string,body?:any,cap=cookie)=>{const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cap,'Content-Type':'application/json','X-Harbor-Game':GAME_UUID},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()}};
  const get=async()=>{const r=await req('/sessions/'+s.id);assert.equal(r.status,200,JSON.stringify(r));s=r.body;return s};const create=async()=>{const r=await req('/sessions',{enrollment_id:randomUUID(),locale:'en'});assert.equal(r.status,200,JSON.stringify(r));s=r.body};
  const action=(verb:string,target=nativeCrabId,payload:any={command:{verb}},patch:any={})=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target,action:'animal-life:'+verb,payload,activePlay:s.activePlayClock?.lease?{client,lease:s.activePlayClock.lease.id,activeMs:0}:{},...patch});
  const commit=async(a:any)=>{const r=await req('/sessions/'+s.id+'/action',a);assert.equal(r.status,200,JSON.stringify(r));s=r.body.head;return r};
  const motion=async(kind='candidate-motion-open',points?:any[])=>{now+=500;const last=s.movingClock?.transport?.last.ack,l=s.movingClock?.lease,ordinal=(last?.ordinal??0)+1,a={action_id:motionActionId(s.id,ordinal),expected_version:s.version,scene:s.scene,position:points?.at(-1)??s.position,target:'',action:kind,payload:{transport:1,ordinal,previous:last?.token??'',...(kind.endsWith('step')?{lease:l.id,sequence:l.sequence+1,points:points??[]}: {})}},before=s,r=await req('/sessions/'+s.id+'/motion',a);assert.equal(r.status,200,JSON.stringify(r));const patched=applyMotionAck(before,r.body);await get();assert.deepEqual(patched.nativeCrabV1,s.nativeCrabV1);return {a,r}};
  const play=async(kind:string,ms=0)=>{now+=ms;const last=s.activePlayClock?.transport?.last.ack,l=s.activePlayClock?.lease,ordinal=(last?.ordinal??0)+1,a={action_id:activePlayActionId(s.id,ordinal),expected_version:s.version,scene:s.scene,position:s.position,target:'',action:kind,payload:{client,ordinal,previous:last?.token??'',...(kind.endsWith('open')?{}:{lease:l.id,sequence:l.sequence+1,activeMs:ms})}},r=await req('/sessions/'+s.id+'/active-play',a);assert.equal(r.status,200,JSON.stringify(r));await get();return {a,r}};
  await create();const original=structuredClone(s);for(let i=0;i<3;i++){const v=(await req('/sessions/'+s.id+'/life')).body;assert.equal(v.plantUses.basilEnabled,true);assert.equal(v.plantUses.mintEnabled,false);assert.equal(v.animals.schema,1);assert.equal(v.collections.length,0);assert.deepEqual(await get(),original)}cases.push('old GETs pure; basil/B2/old seven animals retained');
  await commit(action('', '',{millisecondsPerMinute:4000},{action:'candidate-clock-enable'}));await motion();assert.ok(s.nativeCrabV1?.frame.visible);assert.equal(s.nativeCrabV1.frame.pose,'stand');
  const frozenCollider=structuredClone(s),lastMotion=s.movingClock.transport.last.ack,ordinal=lastMotion.ordinal+1,colliderGoal={...s.nativeCrabV1.frame.foot};now+=1250;const crossed=await req('/sessions/'+s.id+'/motion',{action_id:motionActionId(s.id,ordinal),expected_version:s.version,scene:s.scene,position:colliderGoal,target:'',action:'candidate-motion-step',payload:{transport:1,ordinal,previous:lastMotion.token,lease:s.movingClock.lease.id,sequence:s.movingClock.lease.sequence+1,points:[colliderGoal]}});assert.deepEqual(crossed,{status:400,body:{error:'INVALID_MOTION_PATH',terminal:true}});assert.deepEqual(await get(),frozenCollider);cases.push('authoritative native ground body blocks a swept movement; no head/time mutation');
  const p=s.position,beforeInvalid=structuredClone(s);for(const a of [action('sample',nativeCrabId,{command:{verb:'sample',frame:{foot:{x:0,y:0}}}}),action('sample',nativeCrabId,undefined,{position:{x:p.x+3,y:p.y}})]){const r=await req('/sessions/'+s.id+'/action',a);assert.equal(r.status,409,JSON.stringify(r));assert.equal(r.body.terminal,true);assert.deepEqual(await get(),beforeInvalid)}cases.push('client pose rejected; position must equal a confirmed checkpoint');
  const sample=action('sample'),observed=await commit(sample);assert.equal(s.nativeCrabV1.sample.quietMs,400);assert.equal(s.nativeCrabV1.sample.version,s.version);assert.equal(waits,1);assert.deepEqual(await req('/sessions/'+s.id+'/action',sample),observed);assert.equal(waits,1);assert.deepEqual(s.items,original.items);assert.equal(s.cash,original.cash);const key=lifeProjectionKey(s);await motion('candidate-motion-step');assert.equal(currentNativeSample(s),undefined);assert.notEqual(lifeProjectionKey(s),key);const stale=await req('/sessions/'+s.id+'/action',action('record'));assert.deepEqual(stale,{status:409,body:{error:'OBSERVATION_STALE',terminal:true}});cases.push('400ms guarded observation; exact replay; a motion version invalidates proof');
  await commit(action('sample'));const proof=structuredClone(s),record=action('record'),runtime=factory().runtime,direct=new AsyncSessionAuthority(server.store,runtime);await direct.prepareAction(owner,s.id,record);assert.deepEqual(await get(),proof);
  const faulty={...server.store,transaction:(work:any)=>server.store.transaction((repo:any)=>work({...repo,addReceipt:async()=>{throw Error('INJECTED_RECEIPT_FAILURE')}}))};await assert.rejects(new AsyncSessionAuthority(faulty,runtime).commitPreparedAction(owner,s.id,record),/INJECTED_RECEIPT_FAILURE/);assert.deepEqual(await get(),proof);const recorded=await direct.commitPreparedAction(owner,s.id,record);s=recorded.head;assert.deepEqual(await req('/sessions/'+s.id+'/action',record),{status:200,body:recorded});assert.ok(s.nativeCrabV1.observation);assert.equal(s.nativeCrabV1.sample,undefined);assert.equal((await req('/sessions/'+s.id+'/life')).body.collections.length,1);cases.push('receipt failure rolls back observation; same prepared ID completes once');
  const firstRecord=s.nativeCrabV1.observation;await play('candidate-active-open');await play('candidate-active-tick',1000);assert.equal(s.nativeCrabV1.frame.phase,'sidewalk');const movingHead=structuredClone(s);assert.deepEqual(await req('/sessions/'+s.id+'/action',action('sample')),{status:409,body:{error:'CRAB_NEEDS_QUIET_MOMENT',terminal:true}});assert.deepEqual(await get(),movingHead);cases.push('moving crab cannot mint a quiet proof, and a failed action preserves foreground lease');let maxHeadBytes=0,maxAckBytes=0;const sizeBefore=JSON.stringify(s).length;for(let i=0;i<120;i++){const r=await play('candidate-active-tick',500);maxHeadBytes=Math.max(maxHeadBytes,JSON.stringify(s).length);maxAckBytes=Math.max(maxAckBytes,JSON.stringify(r.r.body).length)}assert.ok(maxAckBytes<5000);assert.ok(maxHeadBytes-sizeBefore<5000);assert.deepEqual(s.nativeCrabV1.observation,firstRecord);await play('candidate-active-pause');cases.push('120 active compact ACKs: bounded latest confirmation, no append-only crab ledger');
  const travel=action('', 'dock',undefined,{action:'travel-map',payload:undefined});await commit(travel);await motion();const goal=entityAt('dock','ruth')!.approach,w=landWorld(dynamicWorld(s.flags,false),s.landV1),path=findPath(w,'dock',s.position,goal);assert.ok(path.length);for(let i=0;i<path.length;i++)await motion('candidate-motion-step',[path[i]]);assert.ok(Math.hypot(s.position.x-goal.x,s.position.y-goal.y)<1);
  const ref={command:{verb:'brief',ref:crabCommissionRef}};await commit(action('brief','ruth',ref));await commit(action('accept','ruth',{command:{verb:'accept',ref:crabCommissionRef}}));const share=action('share','ruth',{command:{verb:'share',ref:crabCommissionRef}}),twin={...share,action_id:randomUUID()},results=await Promise.all([req('/sessions/'+s.id+'/action',share),req('/sessions/'+s.id+'/action',twin)]);assert.equal(results.filter(r=>r.status===200).length,1,JSON.stringify(results));await get();assert.equal(s.relations.ruth,1);assert.deepEqual(s.items,original.items);assert.equal(s.cash,original.cash);assert.equal((await req('/sessions/'+s.id+'/life')).body.animals.pages.filter((p:any)=>p.ref.id===crabCommissionRef.id).length,1);cases.push('normal travel and authoritative path to Ruth; competing shares grant one relationship point and one page');
  const other=await bootstrap();assert.notEqual((await req('/sessions/'+s.id,undefined,other)).status,200);assert.notEqual((await req('/sessions/'+s.id+'/life',undefined,other)).status,200);cases.push('second normal account cookie cannot read another journey');
  const frozen=structuredClone(s);await server.close();now+=86400000;enabled=false;server=await start();base=server.url+'/'+GAME_UUID+'/api';assert.deepEqual(await get(),frozen);const closed=(await req('/sessions/'+s.id+'/life')).body;assert.equal(closed.animals.pages.filter((p:any)=>p.ref.id===crabCommissionRef.id).length,1);assert.equal(closed.collections.length,1);const closedHead=structuredClone(s);assert.deepEqual(await req('/sessions/'+s.id+'/action',action('sample')),{status:409,body:{error:'NATIVE_CRAB_CLOSED',terminal:true}});assert.deepEqual(await get(),closedHead);cases.push('closed starts restart preserves pinned observation/page, rejects new samples, no offline time');
  assert.equal(models,0);writeFileSync(`../evidence/owner-native-crab-${backend}.json`,JSON.stringify({backend,cases,models,observationWaits:waits,schema,maxHeadBytes,maxAckBytes,productionWrites:0},null,2)+'\n');
 }finally{await server.close();if(pool){await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await pool.end()}rmSync(directory,{recursive:true,force:true})}
});
test('owner native pins, hidden safety, lateral persisted movement, semantic cache and zero-time motion reconciliation',()=>{
 for(const [scene,townMinutes] of [['coast',540],['beach',780],['dock',1140],['coast',1380]] as const){const s:Save={...initial('en',randomUUID()),scene,townMinutes,position:{x:900,y:700},flags:['key','unpacked']};advanceNativeCrab(s,0,true);assert.ok(s.nativeCrabV1?.frame.visible);const before=structuredClone(s.nativeCrabV1),key=lifeProjectionKey(s);advanceNativeCrab(s,1.2,true);const n=s.nativeCrabV1!;assert.equal(n.frame.foot[n.frame.direction==='down'||n.frame.direction==='up'?'y':'x'],before.frame.foot[n.frame.direction==='down'||n.frame.direction==='up'?'y':'x']);assert.ok(n.frame.distance>0);assert.equal(lifeProjectionKey(s),key);assert.deepEqual(nativeCrabFrame(s,s.position).frame,n.frame);assert.ok(validNativeCrabField(n,s.version,townMinutes));assert.equal(validNativeCrabField({...n,pin:{...nativeCrabPin,revision:1}},s.version,townMinutes),false);assert.equal(validNativeCrabField({...n,page:{sourceAction:randomUUID(),minute:townMinutes}},s.version,townMinutes),false);const prior={...s,nativeCrabV1:undefined};assert.ok(!nativeCrabFrame(prior,n.frame.foot).frame.visible||Math.hypot(nativeCrabFrame(prior,n.frame.foot).frame.foot.x-n.frame.foot.x,nativeCrabFrame(prior,n.frame.foot).frame.foot.y-n.frame.foot.y)>0);}
});

test('native foreground supports both existing clock rates, excludes opening/offline time and rejects client-selected budget',()=>{
 for(const rate of [2000,4000] as const){let at=100000;const a=createExplorationAssembly({now:()=>at,defaultRate:rate,crabEnabled:true});const s:any={...initial('en',randomUUID()),scene:'coast',position:{x:1032,y:462},flags:['key','unpacked']};const opened=a.play.apply(s,{action_id:randomUUID(),expected_version:0,scene:s.scene,position:s.position,target:'',action:'candidate-active-open',payload:{client:randomUUID()}});assert.equal(opened.townMinutes,540);assert.ok(opened.nativeCrabV1);const lease=opened.activePlayClock.lease;at+=1500;const tick=a.play.apply(opened,{action_id:randomUUID(),expected_version:0,scene:s.scene,position:s.position,target:'',action:'candidate-active-tick',payload:{client:lease.client,lease:lease.id,sequence:1,activeMs:1500}});assert.ok(tick.nativeCrabV1.frame.distance>0);assert.equal(tick.activePlayClock.remainderMs,1500);at+=86400000;const re=a.play.apply(tick,{action_id:randomUUID(),expected_version:0,scene:s.scene,position:s.position,target:'',action:'candidate-active-open',payload:{client:lease.client}});assert.deepEqual(re.nativeCrabV1.frame,tick.nativeCrabV1.frame);assert.equal(re.townMinutes,tick.townMinutes)}
});
