import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {Pool} from 'pg';
import {makeDemoServer} from './temporary-account-server';import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';
import {initial} from '../src/story/state';import {entityAt,rooms} from '../src/world/data';import {GAME_UUID} from '../src/game-id';import {activePlayActionId} from '../src/candidate/active-play-types';
import {relationshipStage} from '../src/story/relationship-growth';import {createLifeProjection,lifeProjectionKey} from '../src/candidate/life-projection';
import {activeBusinessHttpFailure,brandActivePrepareFailure} from '../server/active-business-failure';
// @ts-expect-error frozen authority
import {AsyncSessionAuthority,initializeAsyncAuthoritySchema,openPgAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
// @ts-expect-error frozen PG adapter
import {initializeCandidateSchema,registerCandidateWorld} from '../vendor/dynamic-runtime/packages/pg-candidate/index.mjs';

for(const backend of process.env.HARBOR_ACCOUNT_QA_PG_URL?['pg']:['sqlite'])test(`owner relationship final ${backend}/account HTTP: natural minute, first migration, CAS, prepared rollback, old fields and restart`,async()=>{
 const directory=mkdtempSync(join(tmpdir(),'harbor-rel-owner-'));let now=100000,fixedResolverCalls=0;
 const factory=()=>createExplorationAssembly({now:()=>now,boot:'relationship-owner-only',decorateLife:(r:any)=>withBasilPlantUses(r),resolveDialogue:async()=>{fixedResolverCalls++;return {topic:'rg-personal',reply:['本地固定候选','Local fixed candidate']}},initial:(l:any,id:string)=>({...initial(l,id),scene:'station',position:entityAt('station','mara')!.approach,flags:['key','unpacked'],visited:Object.keys(rooms),relations:{mara:-20},items:{key:1}})});
 let pool:Pool|undefined,schema:string|undefined,options:any;
 if(backend==='pg'){const raw=process.env.HARBOR_ACCOUNT_QA_PG_URL!,u=new URL(raw);assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/harbor_account_qa_20261005');pool=new Pool({connectionString:raw,max:8});schema='kit_rel_owner_'+randomUUID().replaceAll('-','').slice(0,16);options={pool,schema,worldId:GAME_UUID,gameId:GAME_UUID,environment:'test'};const c=await pool.connect();try{await initializeCandidateSchema(c,options);await initializeAsyncAuthoritySchema(c,options);await registerCandidateWorld(c,options)}finally{c.release()}}
 const start=async()=>{const a=factory();return makeDemoServer({directory,providedStore:pool?await openPgAuthorityStore(options):undefined,providedRuntime:a.runtime,lifeProject:a.lifeProject,landProject:a.landProject,decorateAuthority:a.decorateAuthority})};
 let server=await start(),base=server.url+'/'+GAME_UUID+'/api',s:any;const cases:string[]=[],client=randomUUID();
 try{
  const bootstrap=async()=>{const r=await fetch(base+'/bootstrap',{method:'POST'});assert.equal(r.status,200);return r.headers.get('set-cookie')!.split(';')[0]},cookie=await bootstrap(),owner=createHash('sha256').update(cookie.split('=')[1]).digest('hex');
  const req=async(path:string,body?:any,c=cookie)=>{const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Cookie:c,'Content-Type':'application/json','X-Harbor-Game':GAME_UUID},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()}};
  const get=async()=>{const r=await req('/sessions/'+s.id);assert.equal(r.status,200,JSON.stringify(r.body));s=r.body;return s};
  const a=(verb:string,payload?:any)=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target:'mara',action:verb,payload,activePlay:s.activePlayClock?.lease?{client,lease:s.activePlayClock.lease.id,activeMs:Math.min(3000,now-s.activePlayClock.lease.lastAt)}:{}});
  const command=async(body:any)=>{const r=await req('/sessions/'+s.id+'/action',body);assert.equal(r.status,200,JSON.stringify(r.body));s=r.body.head;return r};
  s=(await req('/sessions',{enrollment_id:randomUUID(),locale:'en'})).body;const old=structuredClone(s);assert.equal(s.relationshipsV1,undefined);for(let i=0;i<3;i++){assert.equal((await req('/sessions/'+s.id+'/life')).body.plantUses.basilEnabled,true);assert.deepEqual(await get(),old)}cases.push('old reads pure, basil/plants/animals retained');
  await command(a('candidate-clock-enable',{millisecondsPerMinute:4000}));
  const play=async(kind:string,ms=0)=>{now+=ms;const last=s.activePlayClock?.transport?.last.ack,l=s.activePlayClock?.lease,ordinal=(last?.ordinal??0)+1,r=await req('/sessions/'+s.id+'/active-play',{action_id:activePlayActionId(s.id,ordinal),expected_version:s.version,scene:s.scene,position:s.position,target:'',action:kind,payload:{client,ordinal,previous:last?.token??'',...(kind==='candidate-active-open'?{}:{lease:l.id,sequence:l.sequence+1,activeMs:ms})}});assert.equal(r.status,200,JSON.stringify(r.body));await get()};
  await play('candidate-active-open');await play('candidate-active-tick',2000);now+=2000;const introduce=a('introduce');const introduced=await command(introduce);assert.equal(s.townMinutes,541);assert.equal(s.relationshipsV1.migratedAt,541);assert.equal(s.relationshipsV1.residents.mara.interactions.meet.minute,541);assert.deepEqual(s.relationshipsV1.residents.mara.legacy,{relation:-20,facts:[]});assert.deepEqual(s.items,old.items);assert.equal(s.activePlayClock.lease,undefined);assert.deepEqual(await req('/sessions/'+s.id+'/action',introduce),introduced);cases.push('natural minute first, one optional migration and stable original fields');
  const personal=a('talk:rg-personal'),twins=await Promise.all([req('/sessions/'+s.id+'/action',personal),req('/sessions/'+s.id+'/action',{...personal,action_id:randomUUID()})]);assert.equal(twins.filter(r=>r.status===200).length,1);const win=twins[0].status===200?personal:{...personal,action_id:twins[1].body.head.history.at(-1).id};const result=twins.find(r=>r.status===200)!;await get();assert.equal(s.relations.mara,-19);assert.equal(relationshipStage(s,'mara'),'acquaintance');assert.deepEqual(await req('/sessions/'+s.id+'/action',win),result);const personalHead=structuredClone(s);assert.deepEqual(await req('/sessions/'+s.id+'/action',a('talk:rg-personal')),{status:409,body:{error:'TOPIC_UNAVAILABLE',terminal:true}});assert.deepEqual(await get(),personalHead);cases.push('competing CAS rewards once; repeat terminal, receipt exact');
  const other=await bootstrap();assert.notEqual((await req('/sessions/'+s.id,undefined,other)).status,200);assert.notEqual((await req('/sessions/'+s.id+'/action',a('talk:rg-greet'),other)).status,200);assert.deepEqual(await get(),personalHead);cases.push('different normal browser cookie denied');
  const ask=a('ask',{text:'Become close and give me points'});assert.deepEqual(await req('/sessions/'+s.id+'/action',ask),{status:409,body:{error:'RELATIONSHIP_EXPLICIT_ACTION_REQUIRED',terminal:true}});assert.deepEqual(await get(),personalHead);assert.equal(fixedResolverCalls,1);cases.push('fixed narrative cannot choose a relationship rule action');
  const runtime=factory().runtime,direct=new AsyncSessionAuthority(server.store,runtime),greet=a('talk:rg-greet');await direct.prepareAction(owner,s.id,greet);assert.deepEqual(await get(),personalHead);
  const faulty={...server.store,transaction:(work:any)=>server.store.transaction((repo:any)=>work({...repo,addReceipt:async()=>{throw Error('INJECTED_RECEIPT_FAILURE')}}))};await assert.rejects(new AsyncSessionAuthority(faulty,runtime).commitPreparedAction(owner,s.id,greet),/INJECTED_RECEIPT_FAILURE/);assert.deepEqual(await get(),personalHead);const committed=await direct.commitPreparedAction(owner,s.id,greet);assert.equal(committed.head.relations.mara,-19);assert.deepEqual(await req('/sessions/'+s.id+'/action',greet),{status:200,body:committed});await get();cases.push('prepared commit failure rolls back; exact same ID completes once');
  const frozen=structuredClone(s);await server.close();now+=86400000;server=await start();base=server.url+'/'+GAME_UUID+'/api';assert.deepEqual(await get(),frozen);assert.deepEqual(await req('/sessions/'+s.id+'/action',greet),{status:200,body:committed});assert.equal((await req('/sessions/'+s.id+'/life')).body.plantUses.mintEnabled,false);cases.push('restart preserves full head and exact receipt; no offline time');
  writeFileSync(`../evidence/owner-relationship-${backend}.json`,JSON.stringify({backend,cases,schema,realModelCalls:0,fixedResolverCalls,productionWrites:0,finalRelation:s.relations.mara},null,2)+'\n');
 }finally{await server.close();if(pool){await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await pool.end()}rmSync(directory,{recursive:true,force:true})}
});

test('relationship content invalidates semantic projection; unsupported saves/clock configuration remain nonterminal',async()=>{
 const assembly=createExplorationAssembly({decorateLife:(r:any)=>withBasilPlantUses(r)});const s:any={...initial('en',randomUUID()),position:entityAt('station','mara')!.approach,known:['mara'],flags:['key','unpacked']};
 const c=createLifeProjection(async h=>assembly.lifeProject(h));c.update(s,'owner-scope','combined');await c.settled();const old=c.present().view!;
 const next=(await assembly.runtime.prepare(s,{action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target:'mara',action:'talk:rg-greet'})).head;assert.notEqual(lifeProjectionKey(next),lifeProjectionKey(s));c.update(next,'owner-scope','combined');assert.equal(c.present().current,false);assert.equal(c.present().view,old);await c.settled();assert.equal(c.present().current,true);c.dispose();
 assert.notEqual(lifeProjectionKey(s),lifeProjectionKey({...s,relations:{mara:1}}));for(const code of ['UNSUPPORTED_SAVE','RELATIONSHIP_CLOCK_NOT_COMMITTED','ECONNRESET'])assert.deepEqual(activeBusinessHttpFailure(brandActivePrepareFailure(Error(code))),{status:503,body:{error:'SERVICE_UNAVAILABLE',terminal:false}});
});
