// @ts-nocheck -- browser orchestration. Real compiled Main/View plus local account HTTP; no injected proof/pose/reward.
import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';import {makeDemoServer} from './temporary-account-server';import {initial} from '../src/story/state';import {GAME_UUID} from '../src/game-id';import {nativeCrabFrame} from '../src/animals/native-crab-game';import {chooseNativePlayerStart} from '../src/animals/native-crab-lanes';import {nativeCrabId} from '../src/animals/native-crab-config';import {rooms} from '../src/world/data';import {findPath} from '../src/engine/world';import {dynamicWorld} from '../src/dynamic-assets/layout';import {landWorld} from '../src/life/land';
import {mkdtempSync,rmSync,readFileSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve,extname} from 'node:path';import {writeFile,mkdir} from 'node:fs/promises';import {chromium} from 'playwright';import assert from 'node:assert/strict';
const directory=mkdtempSync(join(tmpdir(),'crab-real-main-')),out=process.env.NATIVE_CRAB_UI_OUT??'../evidence/native-main-ui';await mkdir(out,{recursive:true});let spec:any,models=0;
const assembly=createExplorationAssembly({crabEnabled:true,resolveDialogue:async()=>{models++;throw Error('QA_MODEL_DISABLED')},decorateLife:(r:any)=>withBasilPlantUses(r),initial:(l:any,id:string)=>({...initial(l,id),...structuredClone(spec),id,version:0,cursor:0,history:[]})});
const server=await makeDemoServer({directory,port:5529,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const report={scope:'compiled actual Main/View/RPGJS + normal loopback temporary account/SQLite; synthetic settled initial scene/minute, then ordinary input and real foreground clock; no pose/proof/reward injection',physicalPhone:'UNVERIFIED',Telegram:'UNVERIFIED',comprehension:'UNVERIFIED',cases:[],errors:[],blockedExternalRequests:0,models:0};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1','--disable-gpu-shader-disk-cache']});let page;
try{
 for(const [width,height,locale] of (process.env.NATIVE_CRAB_UI_ONE?[[390,844,'en']]:[[390,844,'en'],[320,568,'zh'],[1280,800,'en']]))for(const [scene,minute,direction] of (process.env.NATIVE_CRAB_UI_ONE?[['coast',540,'down']]:[['coast',540,'down'],['beach',780,'left'],['dock',1140,'up'],['coast',1380,'right']])){
  spec={scene,townMinutes:minute,flags:['key','unpacked','bag-returned','alternative-route','route-open','market-open'],visited:Object.keys(rooms),known:['ruth'],items:{key:1},position:{x:900,y:700}};
  const f=nativeCrabFrame(spec,spec.position),start=chooseNativePlayerStart(f.frame.foot,direction,f.engine.context.world,scene);assert.ok(start);spec.position=start;
  const label=`${width}-${locale}-${scene}-${direction}`,record={label,scene,minute,width,height,locale,direction,poses:[],snapshots:[],observations:[],result:'RUNNING'};report.cases.push(record);
  const c=await browser.newContext({viewport:{width,height},locale:locale==='zh'?'zh-CN':'en-US',serviceWorkers:'block'});
  await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1'){report.blockedExternalRequests++;return r.abort()}if(u.pathname.includes('/api/'))return r.fulfill({response:await r.fetch({url:server.url+u.pathname+u.search})});const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({status:200,contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
  await c.addInitScript(()=>{window.__name=f=>f});page=await c.newPage();page.on('pageerror',e=>report.errors.push({label,error:String(e)}));page.setDefaultTimeout(18000);await page.goto('http://127.0.0.1:5529/?debug=1');
  const ready=()=>page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await ready();for(let i=0;i<3;i++)await page.locator('.harbor-opening button').click();
  const [journey]=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions')).json();const head=async()=>{const r=await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions/'+journey.id);assert.equal(r.status(),200);return r.json()};
  const words=(zh,en)=>locale==='zh'?zh:en;
  const measure=()=>page.evaluate(id=>{const c=document.querySelector('#rpg').__rpgClient,events=Object.values(c.sceneMap.events()),a=events.find(e=>e.id==='animal-'+id),p=c.getCurrentPlayer();return {actor:a&&{foot:{x:a.x(),y:a.y()},animation:a.animationName(),graphics:a.graphics()},player:{x:p.x(),y:p.y()},period:document.querySelector('.harbor-world').dataset.period,overflow:document.documentElement.scrollWidth>innerWidth+1,loading:!!document.querySelector('.harbor-loading'),error:document.querySelector('.harbor-error')?.textContent}},nativeCrabId);
  const shot=async(name)=>{const m=await measure();assert.equal(m.overflow,false);assert.equal(m.loading,false);assert.ok(m.actor?.graphics.includes('animal-shore-crab-native-c1-v2'),JSON.stringify(m));record.snapshots.push({name,...m});await page.screenshot({path:`${out}/${label}-${name}-platform-layout.png`})};
  // Sample actual native renderer animations while the real Main clock runs.
  const deadline=Date.now()+7000;while(Date.now()<deadline&&record.poses.length<3){const m=await measure();assert.ok(m.actor,JSON.stringify(m));const pose=m.actor.animation.split('-')[0];assert.ok(m.actor.animation.endsWith('-'+direction),JSON.stringify(m));if(!record.poses.includes(pose)){record.poses.push(pose);await shot(pose)}await page.waitForTimeout(70)}assert.deepEqual([...record.poses].sort(),['stand','walkA','walkB'].sort());
  // Open a panel only during a real server-owned quiet stop. Retries consume no item.
  for(let attempt=0;attempt<5;attempt++){
   await page.waitForFunction(id=>{const c=document.querySelector('#rpg').__rpgClient,a=Object.values(c.sceneMap.events()).find(e=>e.id==='animal-'+id);return a?.animationName().startsWith('stand-')&&document.querySelector('.harbor-action.is-ready')},nativeCrabId);
   await page.locator('.harbor-action.is-ready').click();await page.locator('.harbor-panel--entity').waitFor();await page.getByRole('button',{name:words('静静看一会儿','Watch quietly'),exact:true}).waitFor();
   const response=await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/action')),page.getByRole('button',{name:words('静静看一会儿','Watch quietly'),exact:true}).click()]);record.observations.push({attempt,status:response[0].status(),body:await response[0].json()});
   if(response[0].ok())break;assert.equal(response[0].status(),409);await page.keyboard.press('Escape');await page.waitForTimeout(300);
  }
  assert.ok(record.observations.at(-1)?.status===200,JSON.stringify(record.observations.map(v=>({status:v.status,body:v.body}))));let saved=await head();assert.equal(saved.nativeCrabV1.sample.quietMs,400);assert.equal(saved.nativeCrabV1.sample.version,saved.version);assert.equal(saved.nativeCrabV1.sample.frame.direction,direction);
  const frozen=await measure();await page.waitForTimeout(500);assert.deepEqual((await measure()).actor,frozen.actor);const panelTime=saved.townMinutes;assert.equal((await head()).townMinutes,panelTime);await shot('observed');
  await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/action')),page.getByRole('button',{name:words('记下这次观察','Record this observation'),exact:true}).click()]);saved=await head();assert.ok(saved.nativeCrabV1.observation);assert.equal(saved.nativeCrabV1.sample,undefined);assert.equal(saved.cash,25);assert.deepEqual(saved.items,{key:1});
  await page.keyboard.press('Escape');await page.locator('.harbor-header nav').getByRole('button',{name:words('行囊','Bag'),exact:true}).click();await page.getByRole('button',{name:words('发现记录','Records'),exact:true}).click();await page.locator(`[data-life-record="observe:${nativeCrabId}:shore-space"]`).waitFor();await page.locator(`[data-life-record="observe:${nativeCrabId}:shore-space"]`).scrollIntoViewIfNeeded();await shot('collection');
  if(direction==='down'&&width!==1280){
   await page.keyboard.press('Escape');await page.locator('.harbor-header nav').getByRole('button',{name:words('地图','Map'),exact:true}).click();await page.getByRole('button',{name:words('全镇','The bay'),exact:true}).click();await page.locator('[data-place="harbor"]').click();await page.locator('[data-place="dock"]').click();await page.getByRole('button',{name:words('前往这里','Go here'),exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.activeRoom()?.name?.replace(/^map-/,'')==='dock'&&!document.querySelector('.harbor-loading'));await page.waitForTimeout(200);const state=await head(),goal=rooms.dock.entities.find(e=>e.id==='ruth').approach;
   const w=landWorld(dynamicWorld(state.flags,false),state.landV1),bodies=await page.evaluate(()=>Object.values(document.querySelector('#rpg').__rpgClient.sceneMap.events()).filter(e=>e.id.startsWith('person-')&&e.graphics().length).map(e=>({x:e.x()-9,y:e.y()-8,w:18,h:8})));
   w.scenes.dock={...w.scenes.dock,obstacles:[...w.scenes.dock.obstacles,...bodies]};const current=()=>page.evaluate(()=>{const p=document.querySelector('#rpg').__rpgClient.getCurrentPlayer();return {x:p.x(),y:p.y()}}),path=findPath(w,'dock',await current(),goal);assert.ok(path.length);
   for(const q of path)for(let i=0;i<50;i++){const p=await current(),dx=q.x-p.x,dy=q.y-p.y;if(Math.hypot(dx,dy)<3)break;const x=Math.abs(dx)>Math.abs(dy),d=x?dx:dy,key=x?(d>0?'ArrowRight':'ArrowLeft'):(d>0?'ArrowDown':'ArrowUp');await page.keyboard.down(key);await page.waitForTimeout(Math.max(22,Math.min(90,Math.abs(d)/112*1000)));await page.keyboard.up(key);if(i===49)assert.fail('ordinary keyboard path stalled '+JSON.stringify({p,q}))}
   record.keyboardWalkToRuth=true;await page.waitForFunction(()=>document.querySelector('[data-target="ruth"]')?.dataset.near==='true');await page.locator('.harbor-action.is-ready').click();await page.locator('.harbor-panel--entity').waitFor();
   const entry=page.locator('[data-animal-commission="animals:native-quiet-shore"]');
   const press=async(name)=>{await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/action')),entry.getByRole('button',{name,exact:true}).click()]);await page.locator('.harbor-reply').waitFor();for(let i=0;i<8&&await page.locator('.harbor-reply__next button').count();i++){await page.locator('.harbor-reply__next button').click();await page.waitForTimeout(100)}await page.locator('.harbor-reply').waitFor({state:'detached'})};
   await press(words('聊聊动物日常','Ask about animal routines'));await press(words('读过了，接下这份观察约定','I have read it: accept this observation plan'));await press(words('分享观察 · 关系+1一次','Share observations · +1 relationship once'));saved=await head();assert.equal(saved.relations.ruth,1);assert.ok(saved.nativeCrabV1.page);assert.equal(saved.cash,25);assert.deepEqual(saved.items,{key:1});
   await page.screenshot({path:`${out}/${label}-ruth-shared-platform-layout.png`});await page.keyboard.press('Escape');await page.locator('.harbor-header nav').getByRole('button',{name:words('行囊','Bag'),exact:true}).click();await page.getByRole('button',{name:words('发现记录','Records'),exact:true}).click();await page.locator('[data-animal-page="animals:native-quiet-shore"]').waitFor();await page.screenshot({path:`${out}/${label}-knowledge-page-platform-layout.png`});record.normalRuthFlow=true;
  }
  if(process.env.NATIVE_CRAB_UI_JOURNEYS&&width===390&&direction==='down'){
   const click=async(name)=>{const root=['System','Bag'].includes(name),inPanel=await page.locator('.harbor-mainnav').count();await (root?(inPanel?page.locator('.harbor-mainnav'):page.locator('.harbor-header nav')):page).getByRole('button',{name,exact:true}).click()};
   await click('System');await click('My journeys');await page.getByText('Current',{exact:false}).waitFor();await page.waitForTimeout(250);const oldBeforeNew=await head();
   await click('Start a separate new journey');await click('Keep old journeys and start new');await page.locator('.harbor-opening').waitFor();await ready();assert.deepEqual(await head(),oldBeforeNew);
   const journeys=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions')).json();assert.equal(journeys.length,2);const next=journeys.find(j=>j.id!==journey.id);assert.ok(next);const newHead=await(await c.request.get(server.url+'/'+GAME_UUID+'/api/sessions/'+next.id)).json();assert.equal(newHead.nativeCrabV1?.observation,undefined);
   for(let i=0;i<3;i++)await page.locator('.harbor-opening button').click();await click('System');await click('My journeys');await page.getByRole('button',{name:'Continue this journey',exact:true}).click();await page.locator('.harbor-panel--menu').waitFor({state:'detached'});await ready();await page.waitForFunction(()=>document.querySelector('.harbor-app')?.dataset.accountLoading==='false');
   await click('Bag');await click('Records');await page.locator('[data-animal-page="animals:native-quiet-shore"]').waitFor();const restored=await head();assert.deepEqual(restored.nativeCrabV1.observation,oldBeforeNew.nativeCrabV1.observation);assert.deepEqual(restored.nativeCrabV1.page,oldBeforeNew.nativeCrabV1.page);assert.equal(restored.relations.ruth,1);await page.screenshot({path:`${out}/${label}-native-journey-restored-platform-layout.png`});record.newJourneyNativePreservation='PASS';
  }
  const observed=saved.nativeCrabV1.observation;await page.reload();await ready();assert.deepEqual((await head()).nativeCrabV1.observation,observed);record.result='PASS';await c.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2));
 }
 assert.deepEqual(report.errors,[]);assert.equal(models,0);report.models=models;report.result='PASS';
}catch(e){report.result='FAIL';report.failure=String(e);report.failureStack=e.stack;report.rendererAtFailure=page&&!page.isClosed()?await page.evaluate(()=>{const c=document.querySelector('#rpg')?.__rpgClient,p=c?.getCurrentPlayer();return {room:c?.activeRoom()?.name,player:p&&{x:p.x(),y:p.y()}}}):null;if(page&&!page.isClosed()){report.failureText=(await page.locator('body').innerText()).slice(-8000);await page.screenshot({path:out+'/failure-platform-layout.png'})}process.exitCode=1}
finally{await writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await server.close();rmSync(directory,{recursive:true,force:true})}console.log(JSON.stringify({result:report.result,cases:report.cases.length,errors:report.errors,failure:report.failure}));
