import {chromium} from 'playwright';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {Readable} from 'node:stream';
import {execFileSync} from 'node:child_process';
import {randomUUID,createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {initial,applyAction} from '../src/story/state';
import {rooms,entityAt} from '../src/world/data';
import {createRuntime} from '../server/runtime';
import {createExplorationAssembly} from '../server/exploration-assembly';
import {createMovingClock} from '../server/candidate-clock';
import {withCompactMotion} from '../server/candidate-motion-authority';
import {createActivePlayClock,withActivePlayRuntime} from '../server/active-play-clock';
import {withActivePlayAuthority} from '../server/active-play-authority';
import {createApiHandler} from '../server/http';
// @ts-expect-error frozen authority
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const diskGuard=()=>{const row=execFileSync('df',['-k','.'],{encoding:'utf8'}).trim().split('\n').at(-1)!.trim().split(/\s+/);if(Number(row[3])<15728640)throw Error('15GIB_DISK_FLOOR')};diskGuard();
const out=resolve(process.env.QA_ACTIVE_OUT??'../evidence/owner-active-renderer'),dist=resolve('dist'),publicRoot=resolve('public');mkdirSync(out,{recursive:true});
const mime:any={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.tsx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const report:any={scope:'LOCAL candidate real compiled Main/View/RPGJS + isolated SQLite, all external network blocked; synthetic players; no model/media/production/publishing.',rate:4000,rateStatus:'configurable local experiment, not user-selected speed',cases:[],errors:[],blocked:[],modelCalls:0,bundle:readFileSync(resolve(dist,'index.html'),'utf8').match(/src="([^"]+index-[^"]+\.js)"/)?.[1]};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});
try{for(const name of (process.env.QA_ACTIVE_CASES??'320,390,1280,390-slow,390-dialogue,390-tabs,390-battle').split(',')){
 const width=Number(name.split('-')[0]),height=width===320?568:width===390?844:800,slow=name.includes('slow'),battle=name.includes('battle'),dialogue=name.includes('dialogue'),tabs=name.includes('tabs'),deep=width===390&&!battle&&!dialogue&&!tabs,owner='synthetic-'+randomUUID();
 const store=openAsyncSqliteAuthorityStore({path:':memory:',worldId:randomUUID(),gameId:'active-browser',environment:'test'});
 const assembly=createExplorationAssembly({resolveDialogue:async()=>{report.modelCalls++;throw Error('QA_MODEL_CLOSED')},initial:(l:any,id:string)=>{
  if(battle){const s={...initial(l,id),scene:'gym',position:entityAt('gym','idris')!.approach,known:['idris'],flags:['key','unpacked','battle:class:accepted'],visited:Object.keys(rooms)};return {...applyAction(s,{action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target:'idris',action:'battle-start',payload:{encounter:'open-class'}}).head,version:0,cursor:0}}
  if(dialogue)return {...initial(l,id),scene:'station',position:entityAt('station','mara')!.approach,townMinutes:719,known:['mara'],flags:['key','unpacked'],visited:Object.keys(rooms)};
  return {...initial(l,id),scene:'market',position:{x:597,y:145},townMinutes:719,flags:['key','unpacked','bag-returned'],visited:Object.keys(rooms)};
 }}),runtime=assembly.runtime;
 const authority=assembly.decorateAuthority(new AsyncSessionAuthority(store,runtime),store),seed=await authority.create(owner,randomUUID(),'en'),head=()=>authority.get(owner,seed.id),api=createApiHandler({authority,lifeProject:assembly.lifeProject,landProject:assembly.landProject,usage:{status:async()=>({resetAt:0,dialogue:{remaining:0,maximum:0,retryAt:null,pending:0}})}});
 const actions:any[]=[],responses:any[]=[],rejected:any[]=[];let lose=false,offline=false;
 const context=await browser.newContext({viewport:{width,height},locale:'en-US'});
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.hostname!=='127.0.0.1'){report.blocked.push(url.origin+url.pathname);return route.abort()}
  if(url.pathname.includes('/api/')){
   const endpoint=url.pathname.slice(url.pathname.indexOf('/api/'));if(endpoint==='/api/bootstrap')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({mode:'local-authoring-test'})});
   const data=req.postData();if(data)actions.push({endpoint,...req.postDataJSON()});if(offline&&endpoint.endsWith('/active-play'))return route.abort();
   const request:any=Readable.from(data?[Buffer.from(data)]:[]);request.url=endpoint+url.search;request.method=req.method();request.headers=req.headers();let status=200,headers:any={},body=Buffer.alloc(0);const response:any={writeHead:(s:number,h:any)=>{status=s;headers=h},end:(v:any)=>body=Buffer.from(v??'')};
   try{await api(request,response,owner)}catch(e:any){status=400;body=Buffer.from(JSON.stringify({error:e.code??e.message,terminal:true}))}const ack=endpoint.endsWith('/active-play')&&status===200?JSON.parse(body.toString()):undefined;responses.push({endpoint,status,bytes:body.length,action:req.postDataJSON()?.action,actionId:ack?.actionId,minute:ack?.fields?.townMinutes,ackSha:ack?createHash('sha256').update(body).digest('hex'):undefined});if(status>=400)rejected.push({endpoint,status,body:JSON.parse(body.toString())});
   if(lose&&endpoint.endsWith('/active-play')&&req.postDataJSON().action==='candidate-active-tick'){lose=false;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'SERVICE_UNAVAILABLE',terminal:false})})}
   return route.fulfill({status,headers,body});
  }
  const rel='.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname));let file=resolve(dist,rel);if(!file.startsWith(dist+'/'))return route.fulfill({status:404,body:'Missing'});if(!existsSync(file)){file=resolve(publicRoot,rel);if(!file.startsWith(publicRoot+'/')||!existsSync(file))return route.fulfill({status:404,body:'Missing'})}return route.fulfill({status:200,contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)});
 });
 await context.addInitScript((id:string)=>{(window as any).__name=(f:any)=>f;addEventListener('DOMContentLoaded',()=>{window.alteruLocalStorage?.setItem('harbor-muted','1');window.alteruLocalStorage?.setItem('harbor-opening:'+id,'3')})},seed.id);
 await context.addInitScript((ms:number)=>{const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=callback=>ms?window.setTimeout(()=>raf(callback),ms):raf(callback)},slow?1000:0);
 const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>report.errors.push({name,error:String(e)}));
 const ready=()=>page.waitForFunction(()=>!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'),undefined,{timeout:20000});
 await page.goto('http://127.0.0.1:5498/?debug=1&candidate=1&active_clock=1');await ready();await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});
 const pending=()=>page.evaluate(()=>{const s=window.alteruLocalStorage;for(let i=0;i<s.length;i++){const k=s.key(i)!;if(k.includes('harbor-pending-v2:'))return JSON.parse(s.getItem(k)!)}return null});
 const result:any={name,width,height,frameDelayMs:slow?1000:0,paused:[]};
 try{
  if(battle){await page.waitForTimeout(1000);assert.equal(actions.filter(a=>a.endpoint.endsWith('/active-play')).length,0);await page.getByRole('button',{name:/^Strike/}).click();await page.waitForFunction(()=>document.querySelector('.harbor-turn__receipt')?.textContent?.includes('1'));const turn=await head();assert.equal(turn.townMinutes,542);assert.equal(turn.energy,98);await page.locator('.harbor-turn header').getByRole('button',{name:'Pause and return to town',exact:true}).click();await page.waitForTimeout(1300);assert.ok((await head()).activePlayClock?.lease);assert.deepEqual((await head()).turnBattle!.bout,turn.turnBattle!.bout);result.oldTurn={cost:2,energy:98,clockOnlyAfterPause:true};}
  else if(dialogue){await page.waitForTimeout(1000);await page.keyboard.press('e');await page.locator('.harbor-panel').waitFor();await page.waitForTimeout(500);const h=await head();assert.equal(h.activePlayClock?.lease,undefined);await page.waitForTimeout(1800);assert.equal((await head()).townMinutes,h.townMinutes);assert.equal((await head()).activePlayClock!.remainderMs,h.activePlayClock!.remainderMs);result.paused.push('Dialogue');await page.getByRole('button',{name:'Close',exact:true}).click();await page.waitForTimeout(500);assert.ok((await head()).activePlayClock?.lease);result.dialogueResumes=true;}
  else if(tabs){await page.waitForTimeout(1000);const first=await head(),firstClient=first.activePlayClock!.lease!.client;const second=await context.newPage();second.on('pageerror',e=>report.errors.push({name,error:String(e)}));await second.goto('http://127.0.0.1:5498/?debug=1&candidate=1&active_clock=1');await second.waitForFunction(()=>!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await page.waitForTimeout(1800);assert.equal((await head()).activePlayClock!.lease!.client,firstClient);assert.equal(await second.locator('.harbor-loading button').count(),0);await page.getByRole('button',{name:'Bag',exact:true}).click();let h=await head();for(let i=0;i<35&&(!h.activePlayClock?.lease||h.activePlayClock.lease.client===firstClient);i++){await page.waitForTimeout(100);h=await head()}assert.ok(h.activePlayClock?.lease);assert.notEqual(h.activePlayClock.lease.client,firstClient);assert.ok(h.townMinutes!-first.townMinutes!<=2);result.tabs={oneOwner:true,pausedTabHandsOff:true,noDuplicateTime:true};await second.close();}
  else{
   await page.waitForTimeout(4800);let idle=await head();for(let i=0;i<10&&idle.townMinutes!<720;i++){await page.waitForTimeout(200);idle=await head()}assert.ok(idle.townMinutes!>=720,'standing advances');assert.deepEqual(idle.position,seed.position);result.standing={start:719,after:idle.townMinutes,positionUnchanged:true};
   const player=await page.evaluate(()=>{const c=(document.querySelector('#rpg') as any).__rpgClient;(window as any).__qaPlayer=c.getCurrentPlayer();return c.activeRoom().name});assert.equal(player,'market-bazaar');
   const pausePanel=async(label:string)=>{await page.getByRole('button',{name:label,exact:true}).click();await page.waitForTimeout(500);const first=await head();assert.equal(first.activePlayClock?.lease,undefined);await page.waitForTimeout(1700);const last=await head();assert.equal(last.townMinutes,first.townMinutes);assert.equal(last.activePlayClock?.remainderMs,first.activePlayClock?.remainderMs);result.paused.push(label);if(label==='Bag'){diskGuard();await page.screenshot({path:out+`/local-active-candidate-platform-layout-${name}-bag.jpg`,type:'jpeg',quality:70})}await page.getByRole('button',{name:'Close',exact:true}).click();await page.waitForTimeout(300)};
   await pausePanel('Bag');if(deep){await pausePanel('Map');await pausePanel('Menu');
    await page.keyboard.down('ArrowUp');await page.waitForTimeout(slow?3000:1800);await page.keyboard.up('ArrowUp');await page.waitForTimeout(1000);const moved=await head();assert.equal(moved.scene,'bazaar');result.walking={scene:moved.scene,minute:moved.townMinutes,noSeamToll:true};
    await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>!!(window as any).__qaHidden});(window as any).__qaHidden=true;document.dispatchEvent(new Event('visibilitychange'))});await page.waitForTimeout(500);const hidden=await head();await page.waitForTimeout(3400);assert.equal((await head()).townMinutes,hidden.townMinutes);assert.equal((await head()).activePlayClock!.remainderMs,hidden.activePlayClock!.remainderMs);await page.evaluate(()=>{(window as any).__qaHidden=false;document.dispatchEvent(new Event('visibilitychange'))});await page.waitForTimeout(400);assert.equal((await head()).townMinutes,hidden.townMinutes);result.background={paused:true,noCatchup:true};
    lose=true;await page.waitForFunction(()=>!!document.querySelector('.harbor-loading button'),undefined,{timeout:6000});const uncertain=await pending();assert.equal(uncertain.channel,'active-play');const committed=await head();await page.getByRole('button',{name:'Reconnect',exact:true}).click();await ready();await page.waitForTimeout(300);const recovered=await head();const replayAcks=responses.filter(r=>r.actionId===uncertain.action.action_id);assert.equal(replayAcks.length,2);assert.equal(replayAcks[0].ackSha,replayAcks[1].ackSha);assert.ok(recovered.townMinutes!>=committed.townMinutes!);assert.equal(actions.filter(a=>a.action_id===uncertain.action.action_id).length,2);result.lostReply={originalId:uncertain.action.action_id,replayedExactlyOnce:true};
    offline=true;await page.waitForFunction(()=>!!document.querySelector('.harbor-loading button'),undefined,{timeout:6000});const beforeOffline=await head(),responseStart=responses.length;await page.waitForTimeout(3200);offline=false;await page.getByRole('button',{name:'Reconnect',exact:true}).click();await ready();await page.waitForTimeout(300);const afterOffline=await head();const resumed=responses.slice(responseStart).find(r=>r.action==='candidate-active-open'&&r.status===200);assert.equal(resumed?.minute,beforeOffline.townMinutes);assert.ok(afterOffline.townMinutes!>=beforeOffline.townMinutes!);result.offline={noCatchup:true,pendingResolved:!(await pending())};
   }
   const same=await page.evaluate(()=>{const c=(document.querySelector('#rpg') as any).__rpgClient;return {same:c.getCurrentPlayer()===(window as any).__qaPlayer,overflow:document.documentElement.scrollWidth>innerWidth+1}});assert.ok(same.same);assert.equal(same.overflow,false);result.renderer=same;
  }
  diskGuard();await page.screenshot({path:out+`/local-active-candidate-platform-layout-${name}-world.jpg`,type:'jpeg',quality:70});result.maxActiveAckBytes=Math.max(0,...responses.filter(r=>r.endpoint.endsWith('/active-play')).map(r=>r.bytes));result.rejected=rejected;report.cases.push(result);console.log('PASS',JSON.stringify(result));
 }catch(error){diskGuard();await page.screenshot({path:out+`/local-active-candidate-platform-layout-${name}-diagnostic.jpg`,type:'jpeg',quality:65});console.log('DIAGNOSTIC',name,await page.locator('body').innerText(),JSON.stringify({head:await head(),rejected,actions:actions.slice(-7),errors:report.errors}));throw error}
 finally{await context.close();store.close()}
}}finally{writeFileSync(out+'/renderer-report.json',JSON.stringify(report,null,2)+'\n');await browser.close()}
assert.equal(report.errors.length,0);assert.equal(report.modelCalls,0);
