import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';import {initial} from '../src/story/state';import {rooms} from '../src/world/data';import {advanceNativeCrab} from '../src/animals/native-crab-game';import {nativeCrabId} from '../src/animals/native-crab-config';import {crabCommissionRef} from '../server/native-crab-life';
test('current 3b09 source reader/action preserves optional crab pin/page/observation and all previous rules without DB rewind',async()=>{
 const root=process.env.HARBOR_CRAB_ROLLBACK_ROOT;if(!root)throw Error('EXPLICIT_ROLLBACK_ROOT_REQUIRED');const {createExplorationAssembly:legacyFactory}=await import(root+'/server/exploration-assembly.ts'),{withBasilPlantUses:legacyBasil}=await import(root+'/server/plant-basil.ts');
 const old=legacyFactory({decorateLife:(r:any)=>legacyBasil(r)}),next=createExplorationAssembly({crabEnabled:true,decorateLife:(r:any)=>withBasilPlantUses(r)});
 const s:any={...initial('en',randomUUID()),scene:'coast',position:{x:1032,y:462},known:['ruth'],flags:['key','unpacked'],visited:Object.keys(rooms)};advanceNativeCrab(s,0,true);const e={minute:540,sourceAction:randomUUID()};Object.assign(s.nativeCrabV1,{observation:e,brief:e,plan:e,page:e});const pin=structuredClone(s.nativeCrabV1);old.runtime.assertReadable(s);assert.deepEqual(old.runtime.upgrade(structuredClone(s)),s);const r=await old.runtime.prepare(s,{action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target:'home',action:'travel-map'});assert.deepEqual(r.head.nativeCrabV1,pin);assert.equal(old.lifeProject(r.head).plantUses.mintEnabled,false);next.runtime.assertReadable(r.head);assert.equal(next.lifeProject(r.head).collections.filter((c:any)=>c.record.id.includes(nativeCrabId)).length,1);
});
test('closed new starts preserve an accepted crab plan and can complete it; original observation slots remain singular',async()=>{
 let now=100000;const a=createExplorationAssembly({crabEnabled:false,now:()=>now,observeWait:async()=>{now+=400},decorateLife:(r:any)=>withBasilPlantUses(r)});const s:any={...initial('en',randomUUID()),scene:'coast',position:{x:1032,y:462},known:['ruth'],flags:['key','unpacked'],visited:Object.keys(rooms),movingClock:{version:2,millisecondsPerMinute:4000,remainderMs:0,transport:{version:1,last:{digest:'0'.repeat(64),ack:{schema:1,mapVersion:1,ordinal:1,version:1,baseVersion:0,cursor:1,actionId:randomUUID(),token:randomUUID(),fields:{clock:{}}}}}}};advanceNativeCrab(s,0,true);const e={minute:540,sourceAction:randomUUID()};Object.assign(s.nativeCrabV1,{brief:e,plan:e});a.runtime.assertReadable(s);const body=(h:any,verb:string,target=nativeCrabId,payload:any={command:{verb}})=>({action_id:randomUUID(),expected_version:h.version,scene:h.scene,position:h.position,target,action:'animal-life:'+verb,payload,activePlay:{}});
 const watched=(await a.runtime.prepare(s,body(s,'sample'))).head;assert.equal(watched.nativeCrabV1.sample.quietMs,400);const recorded=(await a.runtime.prepare(watched,body(watched,'record'))).head;assert.ok(recorded.nativeCrabV1.observation);const cancelled=(await a.runtime.prepare(recorded,body(recorded,'cancel','animal-notebook',{command:{verb:'cancel',ref:crabCommissionRef}}))).head;assert.ok(cancelled.nativeCrabV1.observation);assert.equal(cancelled.nativeCrabV1.plan,undefined);await assert.rejects(a.runtime.prepare(cancelled,body(cancelled,'sample')),/NATIVE_CRAB_CLOSED/);await assert.rejects(a.runtime.prepare(s,body(s,'accept','ruth',{command:{verb:'accept',ref:{id:'animals:quiet-shore'}}})),/COMMISSION_UNAVAILABLE/);
});
