import test from 'node:test';import assert from 'node:assert/strict';
import {world,worldWithFlags,rooms} from '../src/world/data';import {walkable} from '../src/engine/world';
import {globalPoint,localPoint,pointZone,clusterWalkable,continuousPath,traceZone} from '../src/candidate/continuity';
import {coastBeachWalkable,coastBeachBodies} from '../src/candidate/coast-beach';
import {createMovingClock} from '../server/candidate-clock';import {initial} from '../src/story/state';import {randomUUID} from 'node:crypto';
const w=worldWithFlags(['bridge-fixed']);
test('wrong coast identity no longer blocks visible beach sand; pair states admit identically',()=>{for(const p of [{x:300,y:850},{x:700,y:850},{x:542,y:860},{x:300,y:900}])for(const id of ['coast','beach']){assert.ok(clusterWalkable(w,p,id,{x:p.x,y:p.y-1}),id+JSON.stringify(p));assert.equal(pointZone(p,id,{x:p.x,y:p.y-1}),'beach')}});
test('idle old scene and local coordinates stay untouched; moving identity canonicalizes without coordinate jump',()=>{for(const id of ['coast','beach'])for(const p of [{x:300,y:810},{x:540,y:790}]){assert.equal(pointZone(p,id),id);assert.equal(pointZone(p,id,p),id);assert.deepEqual(globalPoint(id,localPoint(id,p)),p);assert.equal(traceZone(id,p,[]),id)}assert.equal(traceZone('coast',{x:300,y:850},[{x:300,y:851}]),'beach');assert.equal(traceZone('beach',{x:300,y:800},[{x:300,y:798}]),'coast')});
test('shared grounded rocks and signs cannot be bypassed by changing old identity',()=>{for(const o of coastBeachBodies(w)){const p={x:o.x+o.w/2-8,y:o.y+o.h/2-6};for(const id of ['coast','beach'])assert.equal(clusterWalkable(w,p,id),false,id+JSON.stringify(o))}assert.equal(coastBeachWalkable(w,{x:400,y:1280}),false,'beach water');for(const flags of [[],['bridge-fixed']]){const b=worldWithFlags(flags);assert.equal(clusterWalkable(b,globalPoint('path',{x:460,y:300}),'path'),walkable(b,'path',{x:460,y:300}));}assert.equal(clusterWalkable(worldWithFlags([]),globalPoint('path',{x:460,y:300}),'path'),false)});
test('old overlap save inside another member rock can exit monotonically but cannot reenter',()=>{const p={x:810,y:801};assert.ok(walkable(w,'beach',localPoint('beach',p)));assert.equal(coastBeachWalkable(w,p),false);let prev=p;for(let y=800;y>=782;y--){const q={x:p.x,y};assert.ok(coastBeachWalkable(w,q,prev),JSON.stringify(q));prev=q}assert.equal(coastBeachWalkable(w,{x:810,y:784},prev),false)});
test('same and cross-scene navigation sweeps shared domain and cannot route through props',()=>{for(const [from,to] of [['coast','beach'],['coast','coast'],['beach','beach']]){const a={x:300,y:840},b={x:700,y:900},route=continuousPath(w,from,a,to,b);assert.ok(route.length);let prev=a;for(const p of route){const n=Math.max(1,Math.ceil(Math.hypot(p.x-prev.x,p.y-prev.y)));let qprev=prev;for(let i=1;i<=n;i++){const q={x:prev.x+(p.x-prev.x)*i/n,y:prev.y+(p.y-prev.y)*i/n};assert.ok(coastBeachWalkable(w,q,qprev));qprev=q}prev=p}assert.equal(traceZone(from,a,route),'beach')}});
test('authoritative motion agrees, preserves inventory and does not rewrite idle save',()=>{let now=1000;const clock=createMovingClock({now:()=>now,boot:'qa'});for(const id of ['coast','beach']){const p={x:300,y:850};let s={...initial('en',randomUUID()),scene:id,position:localPoint(id,p),flags:['key','unpacked'],visited:['coast','beach']};const original=structuredClone(s);const action=(action:string,position=s.position,payload:any={})=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position,target:'',action,payload});s=clock(s,action('candidate-clock-enable',s.position,{millisecondsPerMinute:2000})).head;assert.equal(s.scene,id);assert.deepEqual(s.position,original.position);s=clock(s,action('candidate-motion-open')).head;const lease=s.movingClock!.lease!;now+=100;const q={x:300,y:851};s=clock(s,action('candidate-motion-step',localPoint('beach',q),{lease:lease.id,sequence:lease.sequence+1,points:[q]})).head;assert.equal(s.scene,'beach');assert.deepEqual(s.position,localPoint('beach',q));assert.deepEqual(s.items,original.items)}});

test('escape never writes a scene whose original local coordinate is invalid',()=>{for(const [id,p,dir] of [['coast',{x:617,y:840},{x:1,y:0}],['beach',{x:810,y:801},{x:0,y:-1}]] as const){let zone=id as string;let prev:{x:number;y:number}=p;for(let i=1;i<=24;i++){const q={x:p.x+dir.x*i,y:p.y+dir.y*i};if(!coastBeachWalkable(w,q,prev))break;zone=pointZone(q,zone,prev);assert.ok(walkable(w,zone,localPoint(zone,q)),zone+JSON.stringify(q));prev=q}}});

test('appended dynamic bodies are shared across the pair',()=>{const b={...w,scenes:{...w.scenes,beach:{...w.scenes.beach,obstacles:[...w.scenes.beach.obstacles,{x:250,y:250,w:18,h:8}]}}};for(const id of ['coast','beach'])assert.equal(clusterWalkable(b,{x:320,y:900},id),false)});
test('sampled old valid saves keep every admitted committed coordinate readable without migration',()=>{for(const id of ['coast','beach'])for(let y=760;y<975;y+=5)for(let x=140;x<965;x+=5){const p={x,y};if(!walkable(w,id,localPoint(id,p)))continue;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const q={x:x+dx,y:y+dy};if(!clusterWalkable(w,q,id,p))continue;const zone=pointZone(q,id,p);assert.ok(walkable(w,zone,localPoint(zone,q)),id+JSON.stringify({p,q,zone}))}}});
