// @ts-nocheck -- compiled Main/View/Pixi; all account IDs and saves are isolated synthetic fixtures.
import {chromium} from 'playwright';import {makeDemoServer} from './temporary-account-server';import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';import {withWildMint} from '../server/wild-mint';import {createReviewedAnimalLife} from '../server/reviewed-animal-life';import pack from '../server/content/reviewed-evening-gull-watch.json';import {initial} from '../src/story/state';import {GAME_UUID} from '../src/game-id';
import {mkdtempSync,readFileSync,existsSync,rmSync} from 'node:fs';import {writeFile,mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const out='../evidence/login-ui-final-v5-00c4';await mkdir(out,{recursive:true});let models=0,server,browser;
const root='/Users/yin/code/games/harbor-animal-ai-owner-aba82cc-20261009/evidence';const loader=readFileSync(root+'/guest-shell-public-20261009.js'),impl=readFileSync(root+'/guest-shell-impl-public-20261009.js');
const directory=mkdtempSync('/tmp/harbor-login-ui-');
const prior=JSON.parse(readFileSync('../evidence/ordinary-local-animal-page.json','utf8')).head;let fixtureMode='normal';
const assembly=createExplorationAssembly({createLife:createReviewedAnimalLife,initial:(locale,id)=>{if(fixtureMode==='page'){const head=structuredClone(prior);delete head.movingClock;delete head.activePlayClock;return {...head,id,locale,version:0,cursor:0,history:[]}}return initial(locale,id)},crabEnabled:true,resolveDialogue:async()=>{models++;throw Error('MODEL_DISABLED')},decorateLife:life=>withWildMint(withBasilPlantUses(life,{enabled:true,newStarts:true}),{enabled:true,newStarts:true})});
const report={scope:'actual compiled Main/View/Pixi + unchanged pinned public guest-shell, isolated SQLite, synthetic local account bridge only for authenticated fixtures. Real login open/cancel has no credentials or account ID injection; every non-loopback network call blocked. Not physical/Telegram or real email verification.',cases:[],errors:[],blocked:[],modelCalls:0,realAuthCalls:0,productionWrites:0};
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const A='710101',B='710102',FULL='710103',EMPTY='710104',PAGE='710105';let api,seedCookie='';
async function call(account,path,body){const r=await fetch(api+path,{method:body===undefined?'GET':'POST',headers:{Cookie:seedCookie,'X-Harbor-Telegram-Id':account,'X-Harbor-Identity-Mode':'temporary-unverified','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const cookie=r.headers.get('set-cookie');if(cookie)seedCookie=cookie.split(';')[0];const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data}
async function seed(account,n){await call(account,'/bootstrap',{});let all=[];for(let i=0;i<n;i++){all.push(await call(account,'/sessions',{enrollment_id:randomUUID(),locale:'en'}));if(i===0)await new Promise(r=>setTimeout(r,5))}return all}
async function context(width,height,locale,id){const c=await browser.newContext({viewport:{width,height},locale:locale==='zh'?'zh-CN':'en-US',serviceWorkers:'block'});const state={apiWrites:[],apiReads:[],hold:false,held:null,release:null,failDirectory:false};
 await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.js'))return r.fulfill({contentType:'text/javascript',body:loader});if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.impl.js'))return r.fulfill({contentType:'text/javascript',body:impl});if(u.hostname!=='127.0.0.1'){report.blocked.push({method:q.method(),path:u.pathname});return r.abort()}
 if(u.pathname.includes('/api/')){const entry={path:u.pathname,account:q.headers()['x-harbor-telegram-id'],method:q.method()};(q.method()==='GET'?state.apiReads:state.apiWrites).push(entry);try{if(state.failDirectory&&u.pathname.endsWith('/sessions')&&q.method()==='GET'){state.failDirectory=false;return r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'SERVICE_UNAVAILABLE'})})}const response=await r.fetch();if(state.hold&&u.pathname.endsWith('/sessions')&&q.method()==='GET'&&entry.account===A){state.hold=false;state.held=true;await new Promise(res=>state.release=res)}return await r.fulfill({response})}catch{return r.abort().catch(()=>{})}}
 const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file))return r.fulfill({status:404,body:'Missing'});return r.fulfill({contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
 await c.addInitScript(({id,locale})=>{window.__name=f=>f;localStorage.setItem('harbor-locale',locale);if(id)window.Aigram={isInAigram:true,telegramId:id,callAigramAPI:()=>Promise.resolve({retcode:0})}},{id,locale});
 const p=await c.newPage();p.setDefaultTimeout(25000);p.on('pageerror',e=>report.errors.push(String(e)));return {c,p,state,tx:(zh,en)=>locale==='zh'?zh:en};
}
async function shot(p,label){await p.evaluate(async()=>{await document.fonts.ready;await Promise.allSettled([...document.images].map(i=>i.decode()));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))});const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,label);await p.screenshot({path:`${out}/${label}.png`});report.cases.push({label,result:'PASS',horizontalOverflow:false});await writeFile(out+'/report.json',JSON.stringify(report,null,2)+'\n')}
async function ready(p){await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-account-switch')&&!document.querySelector('.harbor-journeys')&&!document.querySelector('.harbor-loading'));await p.waitForTimeout(200);while(await p.locator('.harbor-opening button').isVisible())await p.locator('.harbor-opening button').click();await p.waitForTimeout(350)}
function selected(state){return state.apiReads.filter(x=>/\/sessions\/[^/]+$/.test(x.path)).at(-1)?.path.split('/').at(-1)}
try{
 server=await makeDemoServer({directory,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority,accountOnly:true});api=server.url+'/'+GAME_UUID+'/api';
 const old=await seed(A,2),full=await seed(FULL,100);await seed(B,0);await seed(EMPTY,0);fixtureMode='page';const pages=await seed(PAGE,1);fixtureMode='normal';
 browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
 for(const [w,h,locale] of [[320,568,'zh'],[390,844,'en'],[1280,800,'en']]){
  let {c,p,state,tx}=await context(w,h,locale,null);await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:tx('登录并开始','Sign in to start'),exact:true}).waitFor();await p.waitForFunction(()=>typeof window.Aigram?.callAigramAPI==='function');await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await shot(p,`${w}-${locale}-signed-out-platform-layout`);assert.equal(state.apiWrites.length+state.apiReads.length,0);await p.getByRole('button',{name:tx('登录并开始','Sign in to start'),exact:true}).click();await p.locator('#alteru-guest-login').waitFor();await shot(p,`${w}-${locale}-original-login-open`);await p.locator('#alteru-guest-login').getByRole('button',{name:'Close',exact:true}).click();await p.getByRole('alert').waitFor();assert.equal(state.apiWrites.length+state.apiReads.length,0);assert.equal(await p.locator('#rpg').count(),0);await shot(p,`${w}-${locale}-login-cancelled`);await c.close();
  ({c,p,state,tx}=await context(w,h,locale,EMPTY));await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:tx('新游戏','New game'),exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:tx('继续','Continue'),exact:true}).count(),0);assert.ok(!state.apiWrites.some(x=>x.path.endsWith('/sessions')));await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await shot(p,`${w}-${locale}-empty-account`);await c.close();
  ({c,p,state,tx}=await context(w,h,locale,A));await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:tx('继续','Continue'),exact:true}).waitFor();await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});assert.equal(await p.locator('.harbor-entry__actions button').count(),2);assert.equal(await p.locator('.harbor-journeys__list').count(),0);await shot(p,`${w}-${locale}-continue-new`);await p.getByRole('button',{name:tx('继续','Continue'),exact:true}).click();await ready(p);assert.equal(selected(state),(await call(A,'/sessions'))[0].id);await shot(p,`${w}-${locale}-continued-world`);
  await p.locator('.harbor-header nav').getByRole('button',{name:tx('系统','System'),exact:true}).click();await p.getByRole('button',{name:tx('我的旅程','My journeys'),exact:true}).click();await p.locator('.harbor-journeys__list article').first().waitFor();assert.equal(await p.locator('.harbor-journeys__list article').count(),2);await shot(p,`${w}-${locale}-system-journeys`);await c.close();
 }
 // Query-only original-shell identity is not a host transport and cannot bootstrap.
 let {c,p,state,tx}=await context(390,844,'en',null);await p.goto(server.url+'/?telegram_id='+A);await p.waitForFunction(()=>!!window.__alteruPlatformAigramLogged);await p.getByRole('button',{name:'Sign in to start',exact:true}).waitFor();assert.equal(state.apiReads.length+state.apiWrites.length,0);assert.equal(await p.locator('#rpg').count(),0);await shot(p,'390-en-query-only-no-save');await c.close();
 // Explicit new, reloading to entry, latest Continue, System switch and account lifecycle.
 ({c,p,state,tx}=await context(390,844,'en',EMPTY));await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:'New game',exact:true}).click();await ready(p);const created=await call(EMPTY,'/sessions');assert.equal(created.length,1);assert.equal(selected(state),created[0].id);await shot(p,'390-en-explicit-new-world');await p.reload();await p.getByRole('button',{name:'Continue',exact:true}).waitFor();assert.equal(await p.locator('#rpg').count(),0);await p.getByRole('button',{name:'Continue',exact:true}).click();await ready(p);assert.equal((await call(EMPTY,'/sessions'))[0].id,created[0].id);assert.equal(selected(state),created[0].id);await shot(p,'390-en-new-reload-continue');await c.close();
 ({c,p,state,tx}=await context(320,568,'zh',FULL));await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:'继续',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'新游戏',exact:true}).isDisabled(),true);await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await shot(p,'320-zh-full-100-disabled');await p.getByRole('button',{name:'继续',exact:true}).click();await ready(p);await p.locator('.harbor-header nav').getByRole('button',{name:'系统',exact:true}).click();await p.getByRole('button',{name:'我的旅程',exact:true}).click();await p.locator('.harbor-journeys__list article').first().waitFor();assert.equal(await p.locator('.harbor-journeys__list article').count(),100);assert.equal(await p.getByRole('button',{name:'开启独立的新旅程',exact:true}).isDisabled(),true);await shot(p,'320-zh-full-100-system');await p.locator('.harbor-journeys__list article').last().scrollIntoViewIfNeeded();await shot(p,'320-zh-full-100-last-save-reachable');await c.close();
 ({c,p,state,tx}=await context(390,844,'en',A));await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:'Continue',exact:true}).click();await ready(p);await p.locator('.harbor-header nav').getByRole('button',{name:'System',exact:true}).click();await p.getByRole('button',{name:'My journeys',exact:true}).click();await p.locator('.harbor-journeys__list article').first().waitFor();await p.getByRole('button',{name:'Continue this journey',exact:true}).click();await ready(p);assert.equal(selected(state),old[0].id);await shot(p,'390-en-system-switch-world');await p.keyboard.down('ArrowRight');await p.waitForTimeout(900);await p.keyboard.up('ArrowRight');for(let i=0;i<100;i++){const directory=await call(A,'/sessions');if(directory[0].id===old[0].id)break;await p.waitForTimeout(100)}await writeFile(out+'/system-selection-probe.json',JSON.stringify({directory:await call(A,'/sessions'),writes:state.apiWrites,selected:selected(state),currentText:await p.locator('main').innerText()},null,2));assert.equal((await call(A,'/sessions'))[0].id,old[0].id);await p.reload();await p.getByRole('button',{name:'Continue',exact:true}).click();await ready(p);assert.equal(selected(state),(await call(A,'/sessions'))[0].id);assert.equal(selected(state),old[0].id);await shot(p,'390-en-system-selection-becomes-latest');await p.evaluate(()=>{window.Aigram.telegramId=null;window.Aigram.isInAigram=false});await p.getByRole('button',{name:'Sign in to start',exact:true}).waitFor();assert.equal(await p.locator('#rpg').count(),0);await shot(p,'390-en-logout-clears-world');
 state.hold=true;await p.evaluate(id=>{window.Aigram.telegramId=id;window.Aigram.isInAigram=true},A);for(let i=0;i<50&&!state.held;i++)await p.waitForTimeout(20);assert.equal(state.held,true);await p.evaluate(id=>{window.Aigram.telegramId=id;window.Aigram.isInAigram=true},B);await p.getByRole('button',{name:'New game',exact:true}).waitFor();state.release();await p.waitForTimeout(250);assert.equal(await p.getByRole('button',{name:'Continue',exact:true}).count(),0);assert.equal(await p.locator('#rpg').count(),0);assert.equal((await call(B,'/sessions')).length,0);await shot(p,'390-en-late-A-response-stays-B-empty');await c.close();
 ({c,p,state,tx}=await context(390,844,'en',null));await p.goto(server.url+'/?debug=1');await p.locator('#alteru-guest-banner').waitFor();await p.getByRole('button',{name:'Sign in to start',exact:true}).waitFor();await shot(p,'390-en-external-guest-banner');assert.equal(state.apiReads.length+state.apiWrites.length,0);await c.close();

 // Existing reviewed animal page survives account entry and a separate New game.
 for(const [w,h,locale] of [[320,568,'zh'],[1280,800,'en'],[390,844,'en']]){
  ({c,p,state,tx}=await context(w,h,locale,PAGE));await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:tx('继续','Continue'),exact:true}).click();await ready(p);await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});assert.equal(selected(state),pages[0].id);
  const dto=await call(PAGE,'/sessions/'+pages[0].id+'/life');assert.ok(dto.animals.pages.some(x=>x.ref.id===pack.ref.id));
  await p.locator('.harbor-header nav').getByRole('button',{name:tx('行囊','Bag'),exact:true}).click();await p.locator('.harbor-bag > .harbor-subnav').getByRole('button',{name:tx('发现记录','Records'),exact:true}).click();const card=p.locator(`[data-animal-page="${pack.ref.id}"]`);await card.waitFor();await card.scrollIntoViewIfNeeded();assert.equal(await card.locator('p').innerText(),pack.definition.page[locale==='zh'?0:1]);await shot(p,`${w}-${locale}-existing-animal-page-preserved`);
  if(w===390){
   await p.locator('[data-menu-close]').click();await p.locator('.harbor-header nav').getByRole('button',{name:'System',exact:true}).click();await p.getByRole('button',{name:'My journeys',exact:true}).click();await p.getByRole('button',{name:'Start a separate new journey',exact:true}).click();await shot(p,'390-en-new-confirmation');await p.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await call(PAGE,'/sessions')).length,1);
   await p.getByRole('button',{name:'Start a separate new journey',exact:true}).click();const before=await call(PAGE,'/sessions/'+pages[0].id);await p.getByRole('button',{name:'Keep old journeys and start new',exact:true}).click();await ready(p);assert.notEqual(selected(state),pages[0].id);assert.equal((await call(PAGE,'/sessions')).length,2);assert.deepEqual(await call(PAGE,'/sessions/'+pages[0].id),before);await shot(p,'390-en-new-preserves-animal-old-head');
  }await c.close();
 }

 ({c,p,state,tx}=await context(390,844,'en',A));state.failDirectory=true;await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:'Read journeys again',exact:true}).waitFor();await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await shot(p,'390-en-directory-error-retry');assert.ok(!state.apiWrites.some(x=>x.path.endsWith('/sessions')));await p.getByRole('button',{name:'Read journeys again',exact:true}).click();await p.getByRole('button',{name:'Continue',exact:true}).waitFor();assert.equal(await p.locator('#rpg').count(),0);await shot(p,'390-en-directory-retry-success');await c.close();
 assert.equal(models,0);assert.deepEqual(report.errors,[]);assert.ok(!report.blocked.some(x=>/send\/login\/email|email\/code\/login/.test(x.path)));report.result='PASS';
}catch(e){report.result='FAIL';report.failure=String(e);report.failureStack=e?.stack;process.exitCode=1;for(const c of browser?.contexts()??[])for(const p of c.pages())await p.screenshot({path:out+'/failure.png'}).catch(()=>{})}
finally{report.modelCalls=models;await browser?.close();await server?.close();rmSync(directory,{recursive:true,force:true});await writeFile(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({result:report.result,cases:report.cases.length,models,failure:report.failure,errors:report.errors}))}
