import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {initial,applyAction,type Save} from '../src/story/state';
import {rooms,worldWithFlags} from '../src/world/data';
import {walkable} from '../src/engine/world';
import {mapRoute,walkingEntrance,entranceReachable,mapPosition,visiblePlaces} from '../src/world/map-navigation';
import {globalPoint,localPoint} from '../src/candidate/continuity';
import {createRuntime} from '../server/runtime';
// @ts-expect-error existing frozen authority
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const settled=():Save=>({...initial('en',randomUUID()),flags:['key','unpacked'],visited:Object.keys(rooms).filter(id=>!id.startsWith('workshop-annex-'))});
const action=(s:Save,target:string)=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target,action:'travel-map'});
test('first visit uses a genuine portal; quick return requires every intermediate place',()=>{const s=settled();s.visited=['station','beach'];assert.equal(mapRoute(s,'beach').failure,undefined);assert.equal(mapRoute(s,'beach',true).failure,'LOCATION_UNKNOWN');const e=walkingEntrance(s,'cafe');assert.equal(e?.destination,'cafe');assert.deepEqual(e?.approach,rooms.station.entities.find(e=>e.destination==='cafe')?.approach);assert.equal(entranceReachable(s,'cafe'),true);});
test('the current room, unknown room, key and settle gates cannot be bypassed',()=>{const s=initial('en',randomUUID());assert.equal(mapRoute(s,'station').failure,'CURRENT_LOCATION');assert.equal(mapRoute(s,'church').failure,'UNKNOWN_TARGET');assert.equal(mapRoute(s,'home').failure,'KEY_NEEDED');s.visited.push('home','harbor');assert.throws(()=>applyAction(s,action(s,'home')),/KEY_NEEDED/);assert.throws(()=>applyAction(s,action(s,'harbor')),/SETTLE_FIRST/);assert.equal(mapRoute(s,'cafe').failure,undefined);assert.equal(mapRoute(s,'harbor').failure,'SETTLE_FIRST');});
test('annexes are only revealed and routed after the original field note admission',()=>{const s=settled();assert.ok(!visiblePlaces(s).includes('workshop-annex-1'));assert.equal(mapRoute(s,'workshop-annex-1').failure,'UNKNOWN_TARGET');s.fieldNotes={rooms:[{id:'workshop-annex-1',title:['小间','Annex']}]} as Save['fieldNotes'];s.visited.push('workshop-annex-1');assert.deepEqual(mapRoute(s,'workshop-annex-1',true).places,['station','harbor','workshop','workshop-annex-1']);});
test('map anchors consume final portals and current interior projects to its building door',()=>{for(const area of ['station','harbor','market','coast','hill'])for(const e of rooms[area].entities.filter(e=>e.destination&&rooms[e.destination].area===area))assert.deepEqual(mapPosition(e.destination!,rooms[e.destination!].spawn,area),e.at);assert.deepEqual(mapPosition('coast',{x:400,y:500},'coast'),{x:400,y:500});assert.deepEqual(mapPosition('path',rooms.path.spawn,'coast'),{x:1280,y:475});});
test('continuous marketplace walks to a real destination without reintroducing seam travel',()=>{const s=settled();s.scene='market';s.position={x:597,y:180};const e=walkingEntrance(s,'bazaar')!;assert.equal(e.id,'map-walk--bazaar');assert.equal(entranceReachable(s,'bazaar'),true);assert.deepEqual(localPoint('bazaar',globalPoint(s.scene,e.approach)),rooms.bazaar.spawn);});
test('all valid original scene positions and local/global coordinates retain their contract',()=>{for(const r of Object.values(rooms)){const s={...settled(),scene:r.id,position:r.spawn};assert.equal(walkable(worldWithFlags(s.flags),s.scene,s.position),true,r.id);assert.deepEqual(localPoint(r.id,globalPoint(r.id,s.position)),s.position)}});
test('authority quick return commits once, replays, preserves unrelated state and rejects stale or missing-route writes',async()=>{const store=openAsyncSqliteAuthorityStore({path:':memory:',worldId:randomUUID(),gameId:'map-test',environment:'test'});try{const seed=settled(),runtime={...createRuntime(),initial:(_l:any,id:string)=>({...seed,id})},auth=new AsyncSessionAuthority(store,runtime),owner='map-synthetic';const s=await auth.create(owner,randomUUID(),'en'),a=action(s,'cafe'),r=await auth.action(owner,s.id,a);assert.equal(r.head.scene,'cafe');assert.deepEqual(r.head.position,rooms.cafe.spawn);for(const key of ['items','flags','relations','plots','animalsV1','weatherV1','weatherEcologyV1'])assert.deepEqual(r.head[key],s[key],key);assert.deepEqual(await auth.action(owner,s.id,a),r);await assert.rejects(auth.action(owner,s.id,{...a,action_id:randomUUID()}),/VERSION_CONFLICT/);const broken={...s,visited:['station','beach']};assert.throws(()=>applyAction(broken,action(broken,'beach')),/LOCATION_UNKNOWN/)}finally{await store.close()}});
