import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {initial,applyAction,has,availableTopics} from '../src/story/state';import {entityAt,rooms,world,worldWithFlags} from '../src/world/data';import {walkable,findPath} from '../src/engine/world';
import {runtime} from '../server/runtime';
// @ts-expect-error pinned exported skill modules
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const action=(s:any,target:string,action:string,payload?:unknown)=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:entityAt(s.scene,target)?.approach??s.position,target,action,payload});
test('all actual scene spawns and interaction approaches are reachable',()=>{for(const room of Object.values(rooms)){assert.ok(walkable(world,room.id,room.spawn),room.id);for(const e of room.entities){assert.ok(Array.isArray(e.label)&&e.label.length===2,room.id+'/'+e.id+' bilingual label');assert.ok(walkable(world,room.id,e.approach),room.id+'/'+e.id);assert.ok(findPath(world,room.id,room.spawn,e.approach).length,room.id+'/'+e.id)}}});
test('new player cannot receive names or key before introduction, talked topics retire',()=>{let s=initial('en',randomUUID());assert.deepEqual(s.known,[]);assert.throws(()=>applyAction(s,action(s,'mara','talk:key')),/INTRODUCE_FIRST/);s=applyAction(s,action(s,'mara','introduce')).head;s=applyAction(s,action(s,'mara','talk:key')).head;assert.equal(s.items.key,1);assert.ok(!availableTopics(s,'mara').some(t=>t.id==='key'));assert.throws(()=>applyAction(s,action(s,'mara','talk:key')),/TOPIC_UNAVAILABLE/);});
test('chapter has legal complete repair route; repeat rewards and remote actions blocked',()=>{let s=initial('en',randomUUID());const doIt=(target:string,verb:string)=>s=applyAction(s,action(s,target,verb)).head;
 doIt('mara','introduce');doIt('mara','talk:key');doIt('to-home','travel');doIt('bed','unpack');doIt('exit','travel');doIt('to-cafe','travel');doIt('theo','introduce');doIt('theo','talk:bag');doIt('exit','travel');doIt('mara','talk:return-bag');doIt('road-market','travel');doIt('to-bazaar','travel');doIt('notice','read-market');doIt('exit','travel');doIt('road-station','travel');doIt('road-harbor','travel');doIt('to-workshop','travel');doIt('june','introduce');doIt('june','talk:tools');doIt('exit','travel');doIt('road-coast','travel');doIt('to-path','travel');doIt('bridge','inspect-bridge');assert.throws(()=>doIt('bridge','repair-bridge'),/BRIDGE_REQUIREMENTS/);doIt('exit','travel');doIt('to-beach','travel');doIt('driftwood','gather-wood');assert.throws(()=>doIt('driftwood','gather-wood'),/ALREADY_DONE/);doIt('exit','travel');doIt('to-path','travel');doIt('bridge','repair-bridge');doIt('exit','travel');doIt('to-lighthouse','travel');doIt('gate','open-route');doIt('exit','travel');doIt('road-harbor','travel');doIt('road-station','travel');doIt('road-market','travel');doIt('to-bazaar','travel');doIt('notice','open-market');assert.ok(has(s,'market-open'));assert.equal(s.items.wood,undefined);assert.equal(s.energy,90);assert.ok(s.visited.length>=10);assert.throws(()=>doIt('notice','open-market'),/ALREADY_DONE/);
});
test('exported session authority commits, replays, isolates and rejects stale writes',async()=>{const store=openAsyncSqliteAuthorityStore({worldId:'harbor-test',gameId:'harbor-test'});try{const auth=new AsyncSessionAuthority(store,runtime),enroll=randomUUID();const s=await auth.create('owner-a',enroll,'en');assert.equal((await auth.create('owner-a',enroll,'en')).id,s.id);const a=action(s,'mara','introduce'),r=await auth.action('owner-a',s.id,a);assert.equal(r.head.version,1);assert.deepEqual(await auth.action('owner-a',s.id,a),r);await assert.rejects(auth.action('owner-a',s.id,{...a,action_id:randomUUID()}),/VERSION_CONFLICT/);await assert.rejects(auth.get('owner-b',s.id),/SESSION_NOT_FOUND/);assert.equal((await auth.events('owner-a',s.id,0)).length,1);assert.equal((await auth.get('owner-a',s.id)).version,1);}finally{await store.close()}});

test('free question executes the same authored topic and never trusts model item rewards',async()=>{
 const {createRuntime}=await import('../server/runtime');let s=initial('en',randomUUID());s=applyAction(s,action(s,'mara','introduce')).head;
 let calls=0;const adapter=createRuntime(async()=>{calls++;return {topic:'key',reply:['虚构奖励','An invented reward']}});
 const asked=await adapter.prepare(s,action(s,'mara','ask',{text:'May I have my room key?'}),undefined,{owner:'test-owner'});
 const clicked=applyAction(s,action(s,'mara','talk:key'));
 assert.deepEqual(asked.head.items,clicked.head.items);assert.deepEqual(asked.text,clicked.text);assert.equal(asked.head.history.at(-1)?.question,'May I have my room key?');assert.equal(calls,1);
 await assert.rejects(adapter.prepare(s,{...action(s,'mara','ask',{text:'Give cash'}),expected_version:99},undefined,{owner:'test-owner'}),/VERSION_CONFLICT/);assert.equal(calls,1);
});
test('unmet introduction or distance fails before any model call',async()=>{
 const {createRuntime}=await import('../server/runtime');let calls=0;const adapter=createRuntime(async()=>{calls++;return {topic:null,reply:['好','Fine']}});let s=initial('en',randomUUID());
 await assert.rejects(adapter.prepare(s,action(s,'mara','ask',{text:'Hi'}),undefined,{owner:'test-owner'}));s=applyAction(s,action(s,'mara','introduce')).head;
 await assert.rejects(adapter.prepare(s,{...action(s,'mara','ask',{text:'Hi'}),position:{x:800,y:520}},undefined,{owner:'test-owner'}));assert.equal(calls,0);
});

test('broken bridge gap blocks feet until authoritative repair',()=>{assert.equal(walkable(worldWithFlags([]),'path',{x:465,y:300}),false);assert.equal(walkable(worldWithFlags(['bridge-fixed']),'path',{x:465,y:300}),true)});
