import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {randomUUID} from 'node:crypto';
import {initial,applyAction,type Save} from '../src/story/state';
import {rooms} from '../src/world/data';
import {runtime} from '../server/runtime';
const out=resolve('../evidence/ui');mkdirSync(out,{recursive:true});
const report:any={scope:'Actual fixed-dist Main/View/RPGJS with local static route fulfillment; synthetic old save only. Pending tech residents remain HOLD, no final-art/real-MiniApp/mobile-device claim.',serverStarted:false,externalNetworkRequests:0,modelCalls:0,mediaPosts:0,blockedExternal:[],errors:[],artFailures:[],cases:[]};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});
const contentType:Record<string,string>={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.json':'application/json','.woff2':'font/woff2','.mp3':'audio/mpeg','.svg':'image/svg+xml','.tmx':'application/xml','.txt':'text/plain'};
try{for(const width of [320,390])for(const locale of ['en','zh'] as const){const height=width===320?568:844,context=await browser.newContext({viewport:{width,height},locale:locale==='en'?'en-US':'zh-CN'});let save:Save={...initial(locale,randomUUID()),version:5,cursor:5,scene:'market',townMinutes:540,position:{x:742,y:710},flags:['key','unpacked','bag-returned'],items:{key:1},known:['mara','mira','casey'],relations:{mira:1,casey:2},visited:Object.keys(rooms),history:[{id:'legacy-mira',kind:'talk',person:'mira',text:['先前在旧街相识。','An earlier meeting on Market Lane.']}]};runtime.assertReadable(save);const original=structuredClone(save);
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(url.hostname)){report.blockedExternal.push(url.href);return route.abort();}const path=url.pathname;
  if(path.includes('/api/')){const endpoint=path.slice(path.indexOf('/api/')+4);let body:any;if(endpoint==='/bootstrap')body={mode:'local-synthetic-qa'};else if(endpoint==='/sessions')body=[{id:save.id,version:save.version,scene:save.scene}];else if(endpoint==='/sessions/'+save.id)body=save;else if(endpoint.endsWith('/usage'))body={resetAt:0,dialogue:{remaining:0,maximum:0,retryAt:null,pending:0}};else if(endpoint==='/sessions/'+save.id+'/action'){const command=route.request().postDataJSON();const result=applyAction(save,command);save=result.head;body=result;}else throw Error('UNEXPECTED_API:'+endpoint);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});}
  const file=resolve('dist','.'+(path==='/'?'/index.html':decodeURIComponent(path)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file)){report.artFailures.push(path);return route.fulfill({status:404,body:'Missing local fixture resource'});}return route.fulfill({status:200,contentType:contentType[extname(file)]??'application/octet-stream',body:readFileSync(file)});
 });
 await context.addInitScript(()=>addEventListener('DOMContentLoaded',()=>{(window as any).alteruLocalStorage?.setItem('harbor-muted','1')}));const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto('http://127.0.0.1:5484/?debug=1');await page.waitForFunction(()=>!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await page.waitForTimeout(500);
 const inspect=()=>{const client=(document.querySelector('#rpg') as any)?.__rpgClient;return {player:{x:client.getCurrentPlayer().x(),y:client.getCurrentPlayer().y()},events:Object.entries(client.sceneMap.events()).filter(([id])=>id.startsWith('person-')||id.startsWith('animal-')).map(([id,value])=>({id,graphics:(value as any).graphics()})),targets:[...document.querySelectorAll('[data-target]')].map(e=>e.getAttribute('data-target')),overflow:document.documentElement.scrollWidth>innerWidth+1,buttons:[...document.querySelectorAll('button')].map(e=>e.getAttribute('aria-label')??e.textContent)};};
 const before=await page.evaluate(inspect);assert.ok(before.events.some(e=>e.id==='person-mira'&&e.graphics.length));assert.ok(before.events.some(e=>e.id.startsWith('animal-')&&e.graphics.length));for(const id of ['harper','tess','noor']){assert.ok(!before.targets.includes(id));assert.ok(!before.events.some(e=>e.id==='person-'+id&&e.graphics.length));}assert.equal(before.overflow,false);await page.screenshot({path:out+`/pending-market-${width}-${locale}-platform-layout.png`});await writeFileSync(out+`/pending-market-${width}-${locale}-snapshot.json`,JSON.stringify(before,null,2));
 await page.keyboard.down('ArrowLeft');await page.waitForTimeout(700);await page.keyboard.up('ArrowLeft');const moved=await page.evaluate(inspect);assert.ok(Math.hypot(moved.player.x-before.player.x,moved.player.y-before.player.y)>20);
 await page.getByRole('button',{name:locale==='en'?'Menu':'菜单',exact:true}).click();await page.getByRole('button',{name:locale==='en'?'People & stories':'人物关系',exact:true}).click();await page.getByRole('button',{name:/Mira Vale|米拉/}).click();assert.ok(await page.getByText(locale==='en'?'An earlier meeting on Market Lane.':'先前在旧街相识。',{exact:true}).count()===0);await page.getByRole('button',{name:/Read conversations|查看谈话记录/}).click();await page.getByText(locale==='en'?'An earlier meeting on Market Lane.':'先前在旧街相识。',{exact:true}).waitFor();const text=await page.locator('.harbor-rel').innerText();for(const name of ['Harper','Tess','Noor','哈珀','苔丝','努尔'])assert.ok(!text.includes(name));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:out+`/pending-mira-history-${width}-${locale}-platform-layout.png`});assert.deepEqual(save,original,'Opening a relationship/history does not mutate the old authority head');report.cases.push({width,height,locale,before,moved,historyVisible:true,savedHeadUnchanged:true});await context.close();
 }assert.deepEqual(report.errors,[]);assert.deepEqual(report.artFailures,[]);
}catch(error){report.failure=String(error);for(const c of browser.contexts())for(const page of c.pages()){await page.screenshot({path:out+'/failure.png'}).catch(()=>{});console.error((await page.locator('body').innerText()).slice(-1500));}throw error;}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');await browser.close();}
