import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {techNomads,techNomadAdmitted,nomadSchedule,nomadDeferral} from '../src/world/tech-nomads';
import {nomadStoryLeads,validNomadMemory,nomadContext} from '../src/story/tech-nomads';
import {initial,applyAction,availableTopics,type Save,type Action} from '../src/story/state';
import {runtime,createRuntime} from '../server/runtime';
import {dialogueContext} from '../server/dialogue-context';
import {rooms,people,entityAt} from '../src/world/data';
import {npcSheets} from '../src/world/sheets';
import {residentRoutes,residentHere,presentEntity,townMinutes,residentActivity,residentClearOfPlayer,observedActor} from '../src/world/residents';
import {residentGuide,arrivalWarnings} from '../src/story/resident-guide';
import {knownPeople,relationshipStory} from '../src/story/relationships';
import {admitSpatialAction} from '../src/story/binding';
import {questionExamples} from '../src/story/question-examples';
// @ts-expect-error frozen authority: in-process isolated SQLite only, no new service
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';

/** Logic-only synthetic admission. No files are copied, no fake art goes into a build. */
export async function withSyntheticAdmission(run:()=>void|Promise<void>){const original=techNomads.map(p=>structuredClone(p.artAdmission));try{for(const p of techNomads){p.artAdmission.status='accepted';p.artAdmission.missing=[];p.artAdmission.rendererEvidence='SYNTHETIC_LOGIC_TEST_ONLY_NOT_ART_APPROVAL';for(const a of [p.artAdmission.atlas,p.artAdmission.avatar,p.artAdmission.portrait])a.sha256='a'.repeat(64);}await run();}finally{techNomads.forEach((p,i)=>p.artAdmission=original[i]);}}
const command=(s:Save,p:string,action:string):Action=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:entityAt(s.scene,p)!.approach,target:p,action});
const place=(s:Save,p:string,m:number):Save=>{const scene=Object.keys(rooms).find(id=>residentHere({townMinutes:m,flags:s.flags},p,id))!;return {...s,scene,townMinutes:m,position:entityAt(scene,p)!.approach};};
const perform=(s:Save,p:string,verb:string)=>{const a=command(s,p,verb);assert.ok(admitSpatialAction(s,a));return applyAction(s,a).head;};
const completeMinute:Record<string,number>={harper:850,tess:600,noor:1080};
function ready(id:string,locale:'en'|'zh'='en'){const n=techNomads.find(n=>n.id===id)!;let s=place({...initial(locale,randomUUID()),flags:['key','unpacked'],items:{key:1},visited:Object.keys(rooms)},id,completeMinute[id]);s=perform(s,id,'introduce');s=perform(s,id,'talk:nomads-v1-start');s=place(s,n.story.partner,completeMinute[id]);s=perform(s,n.story.partner,'introduce');if(n.story.partnerPrerequisite)s=perform(s,n.story.partner,'talk:life');s=perform(s,n.story.partner,'talk:nomads-v1-'+id+'-consult');return place(s,id,completeMinute[id]);}
const unchanged=(s:Save)=>({cash:s.cash,energy:s.energy,standing:s.standing,items:s.items,plots:s.plots,fernStartedAt:s.fernStartedAt,newsEdition:s.newsEdition,turnBattle:s.turnBattle,animalsV1:s.animalsV1});

test('sealed roles match manifest, paths remain missing and default runtime fails closed without art',async()=>{
 const manifest=readFileSync('doc/qa/tech-nomads-implementation-20261006/frozen-brief/manifest.json');assert.equal(createHash('sha256').update(manifest).digest('hex'),'d08d29af987e21de902906580a96ab7bfe20776b66b24400adb5bef99d3f8bfb');
 const fixed=JSON.parse(readFileSync('doc/qa/tech-nomads-implementation-20261006/frozen-brief/role-manifest.json','utf8'));
 assert.equal(Object.keys(people).length,22);assert.equal(npcSheets.length,19);assert.equal(people.casey.intro[1],'“Casey. I build software. My laptop is back at the room. I want to see whether things can get simpler without adding another app.”');
 for(const p of techNomads){const f=fixed.roles.find((r:any)=>r.id===p.id);assert.deepEqual(p.name,f.name);assert.equal(p.age,f.proposedAge);assert.deepEqual(p.schedule,f.schedule);assert.equal(techNomadAdmitted(p.id),false);assert.equal(p.artAdmission.atlas.path,f.deliverables.atlas.suggestedGameTarget);assert.ok(!npcSheets.some(n=>n.id==='npc-'+p.id));const s=place(initial('en',randomUUID()),p.id,completeMinute[p.id]);assert.equal(presentEntity(s,entityAt(s.scene,p.id)!),false);assert.deepEqual(knownPeople(s),[]);assert.throws(()=>perform(s,p.id,'introduce'),/PERSON_AWAY/);let calls=0;const rt=createRuntime(async()=>{calls++;throw Error('MUST_NOT_CALL_MODEL')});await assert.rejects(rt.prepare({...s,known:[p.id]},{...command(s,p.id,'ask'),payload:{text:'Hello'}}),/PERSON_AWAY/);assert.equal(calls,0);assert.deepEqual(availableTopics({...s,known:[p.id]},p.id),[]);}
});
test('every minute has one half-open schedule; exact activities, night absence and focus boundaries use only game time',()=>{
 for(const p of techNomads)for(let m=0;m<1440;m++){assert.equal(p.schedule.filter(t=>m>=t.start&&m<t.end).length,1);const schedule=nomadSchedule(p.id,{townMinutes:m})!;assert.deepEqual(nomadSchedule(p.id,{townMinutes:m+1440}),schedule);const places=Object.keys(rooms).filter(scene=>residentHere({townMinutes:m},p.id,scene));assert.deepEqual(places,schedule.scene?[schedule.scene]:[]);if(schedule.scene){assert.ok(entityAt(schedule.scene,p.id));assert.deepEqual(residentActivity({townMinutes:m,scene:schedule.scene},p.id),schedule.activity);}}
 for(const [p,a,b,time] of [['harper',480,660,'11:00'],['tess',780,960,'16:00'],['noor',780,900,'15:00']] as const){assert.equal(nomadDeferral(p,{townMinutes:a-1}),undefined);assert.match(nomadDeferral(p,{townMinutes:a})![1],new RegExp(time));assert.ok(nomadDeferral(p,{townMinutes:b-1}));assert.equal(nomadDeferral(p,{townMinutes:b}),undefined);}
});
test('both branches in both locales require visible introductions, actual partner premise and correct place; 60-minute recall never rewards twice',async()=>withSyntheticAdmission(()=>{
 for(const n of techNomads)for(const locale of ['en','zh'] as const)for(const choice of n.story.choices){
  let s=place(initial(locale,randomUUID()),n.id,completeMinute[n.id]);const original=structuredClone(s);assert.deepEqual(availableTopics(s,n.id),[]);assert.deepEqual(nomadStoryLeads(s),[]);s=perform(s,n.id,'introduce');s=perform(s,n.id,'talk:nomads-v1-start');
  const lead=relationshipStory(s).leads.find(l=>l.id===n.story.id)!;assert.deepEqual(lead.people,[n.id]);assert.ok(!lead.next![1].includes(people[n.story.partner].name[1]));assert.throws(()=>perform(s,n.id,'talk:nomads-v1-'+choice.id),/TOPIC_UNAVAILABLE/);
  s=place(s,n.story.partner,completeMinute[n.id]);assert.ok(!availableTopics(s,n.story.partner).some(t=>t.id==='nomads-v1-'+n.id+'-consult'));s=perform(s,n.story.partner,'introduce');if(n.story.partnerPrerequisite){assert.ok(!availableTopics(s,n.story.partner).some(t=>t.id==='nomads-v1-'+n.id+'-consult'));s=perform(s,n.story.partner,'talk:life');}s=perform(s,n.story.partner,'talk:nomads-v1-'+n.id+'-consult');
  s=place(s,n.id,completeMinute[n.id]);const before=structuredClone(s);assert.equal(availableTopics(s,n.id).filter(t=>n.story.choices.some(c=>t.id==='nomads-v1-'+c.id)).length,2);s=perform(s,n.id,'talk:nomads-v1-'+choice.id);assert.equal(s.techNomadsV1!.stories[n.id].choice,choice.id);assert.equal(s.techNomadsV1!.stories[n.id].completedAt,completeMinute[n.id]);assert.deepEqual(unchanged(s),unchanged(before));assert.equal(s.relations[n.id],1);assert.equal(s.relations[n.story.partner],1);assert.ok(validNomadMemory(s));runtime.assertReadable(s);
  for(const c of n.story.choices)assert.throws(()=>perform(s,n.id,'talk:nomads-v1-'+c.id),/TOPIC_UNAVAILABLE/);assert.ok(!availableTopics(s,n.id).some(t=>t.id==='nomads-v1-recall'));const early=place(s,n.id,completeMinute[n.id]+59);assert.throws(()=>perform(early,n.id,'talk:nomads-v1-recall'),/TOPIC_UNAVAILABLE/);s=place(s,n.id,completeMinute[n.id]+60);s=perform(s,n.id,'talk:nomads-v1-recall');assert.deepEqual(s.history.at(-1)!.text,choice.recall);assert.equal(s.relations[n.id],1);assert.equal(s.relations[n.story.partner],1);assert.ok(validNomadMemory(s));assert.throws(()=>perform(s,n.id,'talk:nomads-v1-recall'),/TOPIC_UNAVAILABLE/);
  const model=relationshipStory(s);assert.equal(model.leads.find(l=>l.id===n.story.id)!.state,'done');assert.ok(model.people.find(p=>p.id===n.id)!.stage[1].includes('Shared'));assert.equal(nomadContext(s,n.id)!.news.status,'NO_ADMITTED_TECH_ARTICLE');assert.deepEqual(s.items,original.items);assert.ok(!s.flags.includes('market-open'));assert.match(JSON.stringify(dialogueContext(s,n.id)),/No live\/current news claim/);
 }
}));
test('focus asks return authored boundary before resolver; end-of-work topics reopen and evenings keep life available',async()=>withSyntheticAdmission(async()=>{
 for(const n of techNomads){const focused=n.schedule.find(t=>t.talk.startsWith('defer-until-'))!;let s=place({...initial('en',randomUUID()),known:[n.id],flags:['talk:'+n.id+':routine']},n.id,focused.start);let calls=0;const rt=createRuntime(async()=>{calls++;return {topic:null,reply:['不应调用','Must not call']}});const a={...command(s,n.id,'ask'),payload:{text:'Can we talk about work?'}};const result=await rt.prepare(s,a,undefined,{owner:'synthetic'});assert.equal(calls,0);assert.ok(!result.head.flags.includes('free-dialogue-experienced'));assert.equal(result.head.history.at(-1)!.question,a.payload.text);assert.deepEqual(result.text,nomadDeferral(n.id,s));assert.deepEqual(unchanged(result.head),unchanged(s));assert.equal(result.head.townMinutes,s.townMinutes);assert.deepEqual(availableTopics(s,n.id).map(t=>t.id),['nomads-v1-defer']);assert.equal(residentGuide(s,n.id)!.at,String(focused.end/60).padStart(2,'0')+':00');assert.ok(questionExamples(s,n.id,'en').candidates.length>=2);s=place(s,n.id,focused.end);assert.ok(availableTopics(s,n.id).some(t=>t.id==='nomads-v1-work-1'));s=place(s,n.id,1080);assert.ok(availableTopics(s,n.id).some(t=>t.id==='nomads-v1-start'));assert.ok(!availableTopics(s,n.id).some(t=>t.id.startsWith('nomads-v1-work-')));assert.match(nomadStoryLeads({...s,flags:[...s.flags,'talk:'+n.id+':nomads-v1-start'],townMinutes:1300})[0].next![1],/06:00/);}
 const s=place({...initial('en','guide'),known:['harper'],flags:['talk:harper:routine'],visited:['coast'],scene:'home'},'harper',1010);s.scene='home';assert.equal(arrivalWarnings(s,'coast').length,0);s.visited.push('garden');assert.match(arrivalWarnings({...s,townMinutes:1010},'garden')[0][1],/Coast/);
}));
test('optional memory preserves 13/19-era saves and rejects unknown, inconsistent, future or malformed records',async()=>withSyntheticAdmission(()=>{
 for(const locale of ['en','zh'] as const){const old={...initial(locale,'legacy'),known:['mara','mira','casey'],relations:{mara:3,mira:2,casey:1},flags:['key','unpacked','neighbors2:mira:done'],items:{key:1},history:[{id:'old',kind:'talk',person:'mira',text:['旧记录','Old record']}],animalsV1:{schema:1,individuals:{'harbor-cat-1':{familiarity:1,lastPetMinute:540}}}} as Save;delete old.townMinutes;const before=JSON.stringify(old);runtime.assertReadable(old);assert.equal(runtime.upgrade(old),old);assert.equal(JSON.stringify(old),before);assert.ok(knownPeople(old).includes('mira'));assert.equal('techNomadsV1'in old,false);}
 let s=ready('harper');s=perform(s,'harper','talk:nomads-v1-notice');const good=structuredClone(s);for(const bad of [null,{}, {schema:2,stories:{}},{schema:1,stories:[]},{schema:1,stories:{unknown:{choice:'notice',completedAt:1}}},{schema:1,stories:{harper:{choice:'bad',completedAt:850}}},{schema:1,stories:{harper:{choice:'notice',completedAt:851}}},{schema:1,stories:{harper:{choice:'notice',completedAt:-1}}},{schema:1,stories:{harper:{choice:'notice',completedAt:850,recalledAt:899}}}])assert.throws(()=>runtime.assertReadable({...good,techNomadsV1:bad} as any),/UNSUPPORTED_SAVE/);assert.throws(()=>runtime.assertReadable({...good,known:['harper']}),/UNSUPPORTED_SAVE/);assert.deepEqual(s,good);
}));
test('SQLite authoritative completion: duplicate receipt, competing alternate choice CAS, restart, stale command and owner isolation',async()=>withSyntheticAdmission(async()=>{
 for(const n of techNomads){const dir=mkdtempSync(join(tmpdir(),'nomads-qa-')),cfg={path:join(dir,'qa.sqlite'),worldId:'nomads-v1',gameId:'nomads-v1'};let store=openAsyncSqliteAuthorityStore(cfg);try{const seed=ready(n.id);let auth=new AsyncSessionAuthority(store,{...runtime,initial:(l:any,id:string)=>({...seed,id,locale:l,version:0,cursor:0})});let s=await auth.create('synthetic-A',randomUUID(),'en');const a=command(s,n.id,'talk:nomads-v1-'+n.story.choices[0].id);const replies=await Promise.all([auth.action('synthetic-A',s.id,a),auth.action('synthetic-A',s.id,a)]);assert.deepEqual(replies[0],replies[1]);s=await auth.get('synthetic-A',s.id);assert.equal(s.version,1);assert.equal(s.relations[n.id],1);await assert.rejects(auth.action('synthetic-A',s.id,{...command(s,n.id,'talk:nomads-v1-'+n.story.choices[1].id)}),/TOPIC_UNAVAILABLE/);await assert.rejects(auth.action('synthetic-A',s.id,{...a,action_id:randomUUID()}),/VERSION_CONFLICT/);const head=structuredClone(s);await store.close();store=openAsyncSqliteAuthorityStore(cfg);auth=new AsyncSessionAuthority(store,runtime);assert.deepEqual(await auth.get('synthetic-A',s.id),head);assert.deepEqual(await auth.action('synthetic-A',s.id,a),replies[0]);await assert.rejects(auth.get('synthetic-B',s.id),/SESSION_NOT_FOUND/);assert.deepEqual(await auth.get('synthetic-A',s.id),head);
 const b=await new AsyncSessionAuthority(store,{...runtime,initial:(l:any,id:string)=>({...seed,id,locale:l,version:0,cursor:0})}).create('synthetic-B',randomUUID(),'en');const results=await Promise.allSettled(n.story.choices.map(c=>auth.action('synthetic-B',b.id,command(b,n.id,'talk:nomads-v1-'+c.id))));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);assert.equal((await auth.get('synthetic-B',b.id)).relations[n.id],1);
 }finally{await store.close();rmSync(dir,{recursive:true,force:true});}}
}));

import {dynamicWorld} from '../src/dynamic-assets/layout';
import {walkable,findPath} from '../src/engine/world';
import {acceptedAnimals} from '../src/animals/art';
import {createAnimalRuntime} from '../src/animals/behavior';
import {gameAnimalContext} from '../src/animals/game';
import {profiles} from '../src/animals/config';
import {pointClear,bodyAt,overlaps} from '../src/animals/spatial';

test('future 22 residents: every new patrol, approach and original door remains reachable with dynamic props; overlapping old feet move only the NPC',async()=>withSyntheticAdmission(()=>{
 const times=[359,360,479,480,539,540,659,660,719,720,779,780,839,840,899,900,959,960,1019,1020,1259,1260,1439,1440,1980];let positions=0,paths=0;
 for(const dynamic of [false,true])for(const minutes of times)for(const n of techNomads){const schedule=nomadSchedule(n.id,{townMinutes:minutes})!;if(!schedule.scene)continue;const scene=schedule.scene,base=dynamicWorld(['bag-returned'],dynamic),e=entityAt(scene,n.id)!,others=rooms[scene].entities.filter(o=>o.person&&o.id!==n.id&&presentEntity({townMinutes:minutes,flags:['bag-returned'],scene},o));
  const obstacles=others.map(o=>({x:o.at.x-33,y:o.at.y-8,w:66,h:8})),collision={...base,scenes:{...base.scenes,[scene]:{...base.scenes[scene],obstacles:[...base.scenes[scene].obstacles,...obstacles]}}};
  for(let offset=-24;offset<=24;offset+=4){const foot={x:e.at.x+offset,y:e.at.y};assert.ok(walkable(collision,scene,{x:foot.x-8,y:foot.y-6}),`${n.id}/${scene}/${minutes}/${offset} feet`);assert.ok(findPath(collision,scene,rooms[scene].spawn,{x:foot.x-8,y:foot.y+42}).length,`${n.id}/${scene}/${minutes}/${offset} approach`);paths++;positions++;
   const player={x:foot.x-8,y:foot.y-6},before={...player};const clear=(q:{x:number;y:number})=>walkable(collision,scene,{x:q.x-8,y:q.y-6})&&!others.some(o=>Math.hypot(q.x-o.at.x,q.y-o.at.y)<28);const moved=residentClearOfPlayer(e,foot,player,base.actor,clear);observedActor(e,moved);assert.deepEqual(player,before);assert.ok(!overlaps({x:moved.x-9,y:moved.y-8,w:18,h:8},{...player,...base.actor}),`${n.id} old feet`);
  }
  const full={...base,scenes:{...base.scenes,[scene]:{...base.scenes[scene],obstacles:[...base.scenes[scene].obstacles,...obstacles,{x:e.at.x-33,y:e.at.y-8,w:66,h:8}]}}};for(const target of rooms[scene].entities.filter(e=>e.kind==='portal'||e.id.startsWith('crop-bed-')||e.id==='growing-fern')){assert.ok(findPath(full,scene,rooms[scene].spawn,target.approach).length,`${n.id}/${scene}/${minutes}/${target.id} protected approach`);paths++;}
 }assert.ok(positions>1000);assert.ok(paths>positions);console.log(JSON.stringify({geometryPositions:positions,protectedAndApproachPaths:paths,dynamicWorldBothModes:true}));
}));
test('future 22 residents plus 3 cats/4 gulls simultaneously: bounded paths and protections stay valid at all schedule transitions',async()=>withSyntheticAdmission(()=>{
 let frames=0,residents=0;for(const dynamic of [false,true])for(const minutes of [360,479,480,540,659,660,720,779,780,840,900,960,1020,1259,1260,1980])for(const scene of ['market','coast','dock','courtyard']){
  const s={...initial('en','22-and-animals'),flags:['key','unpacked','bag-returned'],scene,townMinutes:minutes,position:rooms[scene].spawn},ctx=gameAnimalContext(s,s.position,{world:dynamicWorld(s.flags,dynamic)}),r=createAnimalRuntime(acceptedAnimals);residents=Math.max(residents,Object.keys(ctx.people).length);for(let i=0;i<120;i++){const states=r.tick(1/60,ctx);for(const a of states.filter(a=>a.visible)){assert.ok(pointClear(a.foot,a.slot!,profiles[a.species],ctx,states.filter(o=>o.id!==a.id)),`${a.id}/${scene}/${minutes}/${i}`);assert.ok(!Object.values(ctx.people).filter(p=>p.scene===scene).some(p=>overlaps(bodyAt(a.foot,profiles[a.species]),p.body)));frames++;}}
 }assert.equal(residents,22);assert.ok(frames>10000);console.log(JSON.stringify({animalVisibleFrameChecks:frames,maximumAdmittedResidents:residents,cats:3,gulls:4,dynamicWorldBothModes:true}));
}));

 test('activity text never reveals a neighbor name before visible introduction',async()=>withSyntheticAdmission(()=>{
 for(const [id,minutes,person,name] of [['harper',360,'theo','Theo'],['harper',840,'elena','Elena'],['tess',1020,'samira','Samira'],['noor',720,'nell','Nell']] as const){const s=place({...initial('en','knowledge'),known:[id],flags:[`talk:${id}:routine`]},id,minutes);assert.ok(!residentActivity(s,id)![1].includes(name));assert.ok(!JSON.stringify(nomadContext(s,id)!.activity).includes(name));assert.ok(!residentGuide(s,id)!.now[1].includes(name));s.known.push(person);assert.ok(residentActivity(s,id)![1].includes(name));assert.ok(residentGuide(s,id)!.now[1].includes(name));}
 }));
