import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {initial,applyAction,availableTopics,type Save,type Action} from '../src/story/state';
import {crops,plotStatus,cropChoices,plotIds,validPlots} from '../src/story/crops';import {newsRecord,newsMemory} from '../src/story/town-news';import {advanceAwake} from '../src/story/fatigue';
import {rooms,entityAt,world} from '../src/world/data';import {findPath,walkable} from '../src/engine/world';import {residentHere} from '../src/world/residents';import {runtime} from '../server/runtime';
// @ts-expect-error frozen runtime
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const action=(s:Save,target:string,verb:string):Action=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:entityAt(s.scene,target)?.approach??s.position,target,action:verb});
const act=(s:Save,target:string,verb:string)=>applyAction(s,action(s,target,verb)).head;
const placed=(scene='garden'):Save=>({...initial('en',randomUUID()),scene,position:rooms[scene].spawn,flags:['key','unpacked'],items:{key:1},visited:Object.keys(rooms)});
test('new farming targets all have reachable authored physical approaches',()=>{for(const id of [...plotIds,'crop-counter']){const scene=id==='crop-counter'?'grocery':'garden',e=entityAt(scene,id)!;assert.ok(walkable(world,scene,e.approach),id);assert.ok(findPath(world,scene,rooms[scene].spawn,e.approach).length,id)}});
test('three crops: one-time starter, watered growth, dry pause, one harvest and atomic sale/reseed',()=>{
 for(const [id,c] of Object.entries(crops)){
  let s=placed();s=act(s,plotIds[0],'claim-seeds');assert.throws(()=>act(s,plotIds[1],'claim-seeds'),/CROP_ACTION_UNAVAILABLE/);
  s=act(s,plotIds[0],'plant:'+id);assert.equal(plotStatus(s,plotIds[0])!.grown,0);s=act(s,plotIds[0],'water-crop');assert.throws(()=>act(s,plotIds[0],'water-crop'),/CROP_ACTION_UNAVAILABLE/);
  s.townMinutes!+=3000;const dry=plotStatus(s,plotIds[0])!;assert.equal(dry.grown,Math.min(720,c.minutes));
  if(id==='tomato'){assert.equal(dry.needsWater,true);s=act(s,plotIds[0],'water-crop');s.townMinutes!+=720}
  assert.ok(validPlots(s));assert.equal(plotStatus(s,plotIds[0])!.ready,true);s=act(s,plotIds[0],'harvest-crop');assert.equal(s.items['crop-'+id],c.yield);assert.equal(plotStatus(s,plotIds[0]),null);assert.throws(()=>act(s,plotIds[0],'harvest-crop'),/CROP_ACTION_UNAVAILABLE/);
  s.scene='grocery';s.position=rooms.grocery.spawn;s.townMinutes=4860;assert.equal(s.townMinutes%1440,540);const before=s.cash;s=act(s,'crop-counter','sell-crop:'+id);assert.equal(s.cash,before+c.price);assert.equal(s.items['crop-'+id],c.yield-1);s=act(s,'crop-counter','buy-seed:'+id);assert.equal(s.cash,before+c.price-c.cost);assert.equal(s.items['seed-'+id],1);
 }
});
test('closed shop preserves harvest; full purse never consumes it; malformed plots rejected; no offline mutation',()=>{let s=placed('grocery');s.items['crop-radish']=2;s.townMinutes=1300;const original=structuredClone(s);assert.throws(()=>act(s,'crop-counter','sell-crop:radish'),/SHOP_CLOSED/);assert.deepEqual(s,original);s.townMinutes=1980;s.cash=999;assert.throws(()=>act(s,'crop-counter','sell-crop:radish'),/PURSE_FULL/);assert.equal(s.items['crop-radish'],2);assert.throws(()=>runtime.assertReadable({...s,plots:{bad:{crop:'radish',grown:0,updatedAt:0,wetUntil:0}}}));assert.throws(()=>runtime.assertReadable({...s,awakeMinutes:-1}));const copy=structuredClone(s);runtime.assertReadable(s);assert.deepEqual(s,copy)});
test('fatigue follows committed awake minutes; zero energy can travel home, sleep resets without losing crops',()=>{let s=placed();advanceAwake(s,600);assert.equal(s.energy,100);advanceAwake(s,60);assert.equal(s.energy,95);const other={energy:100,awakeMinutes:0};for(let i=0;i<66;i++)advanceAwake(other,10);assert.equal(other.energy,s.energy);s.energy=0;s.awakeMinutes=1200;s=act(s,'home','travel-map');s=act(s,'bed','sleep');assert.equal(s.energy,100);assert.equal(s.awakeMinutes,0);s.awakeMinutes=660;s=act(s,'bed','rest');assert.equal(s.awakeMinutes,300);assert.equal(s.energy,100)});
test('Mara stays through the early errand, owners leave but physical sports do not travel with them',()=>{for(const m of [540,800,1100,1400])assert.equal(residentHere({townMinutes:m,flags:['key','unpacked']},'mara','station'),true);assert.equal(residentHere({townMinutes:800,flags:['bag-returned']},'mara','courtyard'),true);let s=placed('coast');s.known=['ruth','idris'];s.townMinutes=1080;assert.throws(()=>act(s,'ruth','challenge-start:fishing'),/CHALLENGE_UNAVAILABLE/);assert.throws(()=>act(s,'idris','challenge-start:sparring'),/CHALLENGE_UNAVAILABLE/)});
test('news has provenance, fictional branch choice persists, wrong examples cannot award completion or change core economy',()=>{let s=placed();s.known=['dani'];s=act(s,'dani','talk:visitor-news');assert.equal(newsRecord.status,'frozen-local-sample');assert.match(newsRecord.canonicalURL,/^https:\/\/www.anthropic.com\//);s=act(s,'dani','talk:visitor-test');s=act(s,'dani','talk:visitor-reminder');assert.ok(!s.flags.includes('news:checked'));assert.ok(availableTopics(s,'dani').some(t=>t.id==='visitor-hours'));const held=structuredClone(s.items),money=s.cash;s=act(s,'dani','talk:visitor-hours');assert.match(newsMemory(s)![1],/checked/);assert.equal(s.cash,money);assert.deepEqual(s.items,held);assert.throws(()=>act(s,'dani','talk:visitor-needs'),/TOPIC_UNAVAILABLE/);s=act(s,'dani','talk:visitor-recall');assert.match(s.history.at(-1)!.text[1],/checked note/);assert.ok(!availableTopics(s,'dani').some(t=>t.id==='visitor-recall'));});
test('SQLite CAS/duplicate actions/concurrent selling/restart/owner isolation retain gardening and news',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'townlife-')),cfg={path:join(dir,'qa.sqlite'),worldId:'townlife',gameId:'townlife'};let store=openAsyncSqliteAuthorityStore(cfg);
 const rt={...runtime,initial:(locale:any,id:string)=>({...placed('grocery'),id,locale,items:{'crop-radish':2},flags:['key','unpacked','news:heard','news:checked'],plots:{'crop-bed-1':{crop:'tomato',grown:720,updatedAt:540,wetUntil:540}},awakeMinutes:660})};
 try{let auth=new AsyncSessionAuthority(store,rt),s=await auth.create('A',randomUUID(),'en');const a=action(s,'crop-counter','sell-crop:radish');const results=await Promise.allSettled([auth.action('A',s.id,a),auth.action('A',s.id,{...a,action_id:randomUUID()})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const current=await auth.get('A',s.id);assert.equal(current.cash,28);assert.equal(current.items['crop-radish'],1);await auth.action('A',s.id,a);assert.deepEqual(await auth.get('A',s.id),current);await store.close();store=openAsyncSqliteAuthorityStore(cfg);auth=new AsyncSessionAuthority(store,rt);s=await auth.get('A',s.id);assert.equal(s.cash,28);assert.ok(s.flags.includes('news:checked'));assert.equal(s.plots['crop-bed-1'].grown,720);assert.equal(s.awakeMinutes,660);await assert.rejects(auth.get('B',s.id),/SESSION_NOT_FOUND/)}finally{await store.close();rmSync(dir,{recursive:true,force:true})}
});

test('concurrent harvest and lost reply grant one yield, not two',async()=>{const dir=mkdtempSync(join(tmpdir(),'town-harvest-')),store=openAsyncSqliteAuthorityStore({path:join(dir,'q.sqlite'),worldId:'harvest',gameId:'harvest'});try{const rt={...runtime,initial:(locale:any,id:string)=>({...placed(),id,locale,townMinutes:900,plots:{'crop-bed-1':{crop:'radish',grown:0,updatedAt:540,wetUntil:1260}}})};const auth=new AsyncSessionAuthority(store,rt);let s=await auth.create('A',randomUUID(),'en');const a=action(s,'crop-bed-1','harvest-crop');const result=await Promise.allSettled([auth.action('A',s.id,a),auth.action('A',s.id,{...a,action_id:randomUUID()})]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);await auth.action('A',s.id,a);s=await auth.get('A',s.id);assert.equal(s.items['crop-radish'],2);assert.equal(s.plots['crop-bed-1'],undefined);assert.equal(s.energy,98)}finally{await store.close();rmSync(dir,{recursive:true,force:true})}});
