// @ts-nocheck -- Compare existing formal build to current build in isolated actual UI.
import {createExplorationAssembly} from '../server/exploration-assembly';import {withBasilPlantUses} from '../server/plant-basil';import {makeDemoServer} from './temporary-account-server';import {initial} from '../src/story/state';import {rooms} from '../src/world/data';import {pinLegacy} from '../src/life/save';import {ContentRegistry} from '../src/life/registry';import {GAME_UUID} from '../src/game-id';import {chromium} from 'playwright';import {mkdtempSync,readFileSync,existsSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve,extname} from 'node:path';import {mkdir,writeFile,statfs} from 'node:fs/promises';import assert from 'node:assert/strict';
const d=mkdtempSync(join(tmpdir(),'harbor-ui-efficiency-')),reg=new ContentRegistry();
const assembly=createExplorationAssembly({decorateLife:r=>withBasilPlantUses(r),resolveDialogue:async()=>{throw Error('QA_MODEL_DISABLED')},initial:(locale,id)=>{const s=pinLegacy({...initial(locale,id),known:['mara','theo'],visited:Object.keys(rooms),flags:['key','unpacked'],items:{key:1,toolkit:1,wood:2,photo:1,route:1,toolbag:1,fish:1,'packed-snack':2,'seed-basil':2,'crop-basil':3,'seed-radish':1,'crop-radish':2,'seed-tomato':1,'crop-tomato':2}},reg);s.items['life-gift:theo-menu']=1;s.lifeV1.firstRewards=['theo-order-first'];s.lifeV1.collections['gift:life-gift:theo-menu']={id:'gift:life-gift:theo-menu',minute:540,sourceAction:'synthetic-existing-delivery'};return s}});
const server=await makeDemoServer({directory:d,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority}),out=new URL('../../evidence/efficiency/',import.meta.url);await mkdir(out,{recursive:true});
const report={scope:'Actual existing 3b09a9b dist vs UI phase1 dist; same synthetic inventory and legal existing keepsake. Counts cover finding item/place and reaching garden, not walking/planting. Actual full planting/delivery/reward is separately verified.',cases:[],errors:[]};const fs=await statfs('.');assert.ok(fs.bavail*fs.bsize>=15*1024**3);
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});let page;
try{for(const [width,height,locale] of [[320,568,'en'],[390,844,'zh']])for(const version of ['formal','new']){
 const root=resolve(version==='formal'?'/Users/yin/code/games/harbor-relationship-active-owner-release-20261007/source/dist':'dist'),record={width,height,locale,version,clicks:[],scrolls:[],measurements:[]};report.cases.push(record);const tx=(zh,en)=>locale==='zh'?zh:en,c=await browser.newContext({viewport:{width,height},locale:locale==='zh'?'zh-CN':'en-US',serviceWorkers:'block'});
 await c.route('**/*',async r=>{try{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname.includes('/api/'))return r.fulfill({response:await r.fetch({url:server.url+u.pathname+u.search})});const f=resolve(root,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+'/')||!existsSync(f))return r.fulfill({status:404,body:'Missing'});const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.json':'application/json','.woff2':'font/woff2','.ttf':'font/ttf','.tmx':'application/xml','.tsx':'application/xml','.mp3':'audio/mpeg','.wav':'audio/wav'};return r.fulfill({contentType:mime[extname(f)]??'application/octet-stream',body:readFileSync(f)})}catch(e){if(/disposed|closed/.test(String(e)))return;throw e}});
 await c.addInitScript(()=>{window.__name=f=>f});page=await c.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto('http://127.0.0.1:5599/?debug=1');await page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer(),null,{timeout:45000});for(let i=0;i<3;i++)await page.locator('.harbor-opening button').click();await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});
 const click=async(name,scope=page)=>{await scope.getByRole('button',{name,exact:true}).first().click();record.clicks.push(name);await page.waitForTimeout(120)};
 const shot=async(name)=>page.screenshot({path:new URL(`${width}-${locale}-${version}-${name}-platform-layout.png`,out).pathname});
 await click(tx('行囊','Bag'));await page.waitForTimeout(250);await shot('first-bag');
 if(version==='new'){
  const rows=page.locator('[data-bag-item]');record.measurements=await rows.evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {name:e.innerText,width:r.width,height:r.height,font:getComputedStyle(e.querySelector('strong')).fontSize}}));
  await page.getByRole('combobox',{name:tx('物品类型','Item type')}).selectOption('seed');record.clicks.push('select seed category');await page.locator('[data-bag-item="crop:basil@1:seed"]').click();record.clicks.push('select basil seed');await click(tx('查看菜畦地点','Find the garden beds'));await click(tx('前往这里','Go here'));
 }else{
  const seedRow=page.locator('[data-life-batch="crop:basil@1:seed"]'),body=page.locator('.harbor-panel__body');const measure=await seedRow.evaluate(el=>{const b=el.closest('.harbor-panel__body'),r=el.getBoundingClientRect(),br=b.getBoundingClientRect();return {text:el.innerText,font:getComputedStyle(el.querySelector('strong')).fontSize,offset:r.top-br.top+b.scrollTop,viewport:b.clientHeight}});record.scrolls.push({target:'basil seed',...measure,pages:measure.offset/measure.viewport});await seedRow.scrollIntoViewIfNeeded();await shot('seed-found');await page.keyboard.press('Escape');record.clicks.push('close bag');await click(tx('地图','Map'));await click(tx('全镇','The bay'));await page.locator('[data-place="hill"]').click();record.clicks.push('select Hill');await page.locator('[data-place="garden"]').click();record.clicks.push('select Garden');await click(tx('前往这里','Go here'));
 }
 await page.locator('.harbor-backdrop').waitFor({state:'detached'});await page.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.activeRoom()?.name?.replace(/^map-/,'')==='garden');record.seedNavigationClicks=record.clicks.length;await shot('garden-reached');
 record.clicks=[];await click(tx('行囊','Bag'));if(version==='new'){await click(tx('纪念物','Keepsakes'));await page.getByText(tx('第一篮收成的菜单小卡','A menu card for my first delivery')+' ×1',{exact:true}).waitFor()}else{const gift=page.getByText(tx('第一篮收成的菜单小卡','A menu card for my first delivery')+' ×1',{exact:true});const measure=await gift.evaluate(el=>{const b=el.closest('.harbor-panel__body'),r=el.getBoundingClientRect(),br=b.getBoundingClientRect();return {offset:r.top-br.top+b.scrollTop,viewport:b.clientHeight}});record.scrolls.push({target:'earned gift',...measure,pages:measure.offset/measure.viewport});await gift.scrollIntoViewIfNeeded()}
 record.keepsakeClicks=record.clicks.length;await shot('keepsake-found');record.result='pass';await c.unrouteAll({behavior:'wait'});await c.close();
}assert.deepEqual(report.errors,[]);report.result='pass'}catch(e){report.result='failed';report.failure=String(e);if(page&&!page.isClosed()){report.text=(await page.locator('body').innerText()).slice(-4000);await page.screenshot({path:new URL('failure-platform-layout.png',out).pathname})}process.exitCode=1}finally{await writeFile(new URL('report.json',out),JSON.stringify(report,null,2));await browser.close();await server.close();rmSync(d,{recursive:true,force:true})}console.log(JSON.stringify({result:report.result,failure:report.failure,cases:report.cases.length}));
