import test from 'node:test';import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';import {readFileSync} from 'node:fs';import {Pool} from 'pg';
import {initial,type Save,type Action} from '../src/story/state';import {rooms,entityAt} from '../src/world/data';
import {createWeatherState} from '../src/weather/state';import {createExplorationAssembly} from '../server/exploration-assembly';
import {createReviewedAnimalLife} from '../server/reviewed-animal-life';import {withWildMint} from '../server/wild-mint';import {withBasilPlantUses} from '../server/plant-basil';import {mintDefinitionHash} from '../server/plant-uses-rules';
import {activePlayActionId,applyActivePlayAck} from '../src/candidate/active-play-types';import {motionActionId,applyMotionAck} from '../src/candidate/clock-types';
// @ts-expect-error frozen authority
import {initializeAsyncAuthoritySchema,openPgAuthorityStore,AsyncSessionAuthority} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
// @ts-expect-error frozen PG adapter
import {initializeCandidateSchema,registerCandidateWorld} from '../vendor/dynamic-runtime/packages/pg-candidate/index.mjs';

// Read only the actual checked-in public entry's boolean policy. Do not import
// that module, which would open real private config and a production listener.
function publishedPolicy(){const text=readFileSync(new URL('../server/public.ts',import.meta.url),'utf8'),matches=[...text.matchAll(/weather:\{enabled:(true|false),ecology:(true|false)\}/g)];assert.equal(matches.length,1);assert.equal(matches[0][1],'true');assert.equal(matches[0][2],'true');return {enabled:true,ecology:true}}
async function fixture(run:(f:any)=>Promise<void>){
 const raw=process.env.HARBOR_WEATHER_ECOLOGY_QA_PG_URL;if(!raw)throw Error('ISOLATED_ECOLOGY_PG_REQUIRED');const url=new URL(raw);assert.equal(url.hostname,'127.0.0.1');assert.match(url.pathname,/^\/harbor_account_qa_weather_ecology_[a-f0-9]{8}$/);assert.equal(url.username,'harbor_ecology_qa');assert.equal(url.password,'');
 const pool=new Pool({connectionString:raw,max:6}),schema='kit_ecology_qa_'+randomUUID().replaceAll('-','').slice(0,16),opts={pool,schema,worldId:randomUUID(),gameId:'weather-ecology-prepublish-local',environment:'test'};
 let now=100000,models=0;const opened:any[]=[];const c=await pool.connect();try{await initializeCandidateSchema(c,opts);await initializeAsyncAuthoritySchema(c,opts);await registerCandidateWorld(c,opts)}finally{c.release()}
 const build=async(ecology=publishedPolicy().ecology,boot='weather-ecology-qa')=>{const store=await openPgAuthorityStore(opts);opened.push(store);const assembly=createExplorationAssembly({now:()=>now,boot,defaultRate:4000,weather:{...publishedPolicy(),ecology},crabEnabled:true,createLife:createReviewedAnimalLife,decorateLife:(r:any)=>withWildMint(withBasilPlantUses(r,{enabled:true,newStarts:true}),{enabled:true,newStarts:true}),resolveDialogue:async()=>{models++;throw Error('MODELS_CLOSED')},initial:(locale:any,id:string)=>({...initial(locale,id),scene:'home',position:entityAt('home','bed')!.approach,townMinutes:900,weatherV1:createWeatherState(900),flags:['key','unpacked','bag-returned','crop-starter'],visited:Object.keys(rooms),plots:{'crop-bed-1':{crop:'basil',grown:0,updatedAt:900,wetUntil:900}},plantUsesV1:{schema:1,deliveries:0,mint:{node:'harbor-mint-hill-1',definitionHash:mintDefinitionHash,stock:1,recoverAt:1620,leaves:0}}})});return {store,assembly,authority:assembly.decorateAuthority(new AsyncSessionAuthority(store,assembly.runtime),store)}};
 const fingerprint=async()=>{const rows=(await pool.query('select table_name from information_schema.tables where table_schema=$1 order by table_name',[schema])).rows;return Promise.all(rows.map(async({table_name:t})=>{assert.match(t,/^[a-z_]+$/);return {table:t,...(await pool.query(`select count(*)::int as count,md5(coalesce(string_agg(md5(row_to_json(t)::text),'' order by md5(row_to_json(t)::text)),'')) as digest from "${schema}"."${t}" t`)).rows[0]}}))};
 try{await run({build,fingerprint,pool,advance:(ms:number)=>now+=ms,get models(){return models}});assert.equal(models,0)}finally{for(const s of opened)await s.close();await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await pool.end()}
}
const action=(s:Save,verb='rest',target='bed'):Action=>({action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target,action:verb});

test('isolated PG production policy: old58 reads pure; first action current-minute pin; CAS/replay/restart; compatible closed starts',async()=>fixture(async f=>{
 const old=await f.build(false),on=await f.build(),second=await f.build(),owner=randomUUID();const before=await old.authority.create(owner,randomUUID(),'en');assert.equal(before.weatherEcologyV1,undefined);
 const fingerprint=await f.fingerprint();for(let i=0;i<3;i++)assert.deepEqual(await on.authority.get(owner,before.id),before);assert.deepEqual(await f.fingerprint(),fingerprint);
 const one=action(before),two=action(before);const race=await Promise.allSettled([on.authority.action(owner,before.id,one),second.authority.action(owner,before.id,two)]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal(race.filter(r=>r.status==='rejected'&&/VERSION_CONFLICT/.test(String(r.reason))).length,1);
 const winner=race[0].status==='fulfilled'?0:1,receipt=(race[winner] as PromiseFulfilledResult<any>).value;const pinned=await on.authority.get(owner,before.id);assert.equal(pinned.weatherEcologyV1.activatedAt,900);assert.equal(pinned.weatherEcologyV1.settledThrough,1080);assert.equal(pinned.weatherEcologyV1.mintRainUsed,60);assert.equal(pinned.plantUsesV1.mint.recoverAt,1560);assert.equal(pinned.plots['crop-bed-1'].grown,60);assert.deepEqual(pinned.items,before.items);assert.equal(pinned.cash,before.cash);
 const committed=await f.fingerprint();assert.deepEqual(await second.authority.action(owner,before.id,winner?two:one),receipt);await assert.rejects(second.authority.get('foreign-owner',before.id),/SESSION_NOT_FOUND/);assert.deepEqual(await f.fingerprint(),committed);
 const reopened=await f.build(true,'weather-ecology-restart');assert.deepEqual(await reopened.authority.get(owner,before.id),pinned);assert.deepEqual(await reopened.authority.action(owner,before.id,winner?two:one),receipt);assert.deepEqual(await f.fingerprint(),committed);
 const close=await f.build(false,'weather-ecology-closed-starts');const untouched=await close.authority.create(owner,randomUUID(),'en');const unchanged=(await close.authority.action(owner,untouched.id,action(untouched))).head;assert.equal(unchanged.weatherEcologyV1,undefined);assert.equal(unchanged.plantUsesV1.mint.recoverAt,1620);
 const alreadyPinned=await on.authority.create(owner,randomUUID(),'en');const continued=(await close.authority.action(owner,alreadyPinned.id,action(alreadyPinned))).head;assert.equal(continued.weatherEcologyV1.activatedAt,900);assert.equal(continued.plantUsesV1.mint.recoverAt,1560);assert.equal(continued.weatherEcologyV1.mintRainUsed,60);
 const afterClose=(await reopened.authority.action(owner,continued.id,action(continued))).head;assert.equal(afterClose.weatherEcologyV1.activatedAt,900);assert.equal(afterClose.plantUsesV1.mint.recoverAt,1560);assert.equal(afterClose.weatherEcologyV1.mintRainUsed,60);
}));

test('isolated PG production policy: compact idle and combined motion persist exact mint due; no replay/offline/failure credit',async()=>fixture(async f=>{
 // Explicit synthetic ownership, never read from a live account or a save.
 let service=await f.build();const qaOwner=randomUUID();let head:any=await service.authority.create(qaOwner,randomUUID(),'en');const client=randomUUID();
 const clock=(verb='candidate-active-tick',ms=1000)=>{const c=head.activePlayClock,last=c?.transport?.last.ack;return {...action(head,verb,''),action_id:activePlayActionId(head.id,(last?.ordinal??0)+1),payload:{ordinal:(last?.ordinal??0)+1,previous:last?.token??'',client,...(verb==='candidate-active-open'?{}:{lease:c?.lease?.id,sequence:(c?.lease?.sequence??0)+1,activeMs:ms})}}};
 const play=async(a=clock())=>{const ack=await service.authority.activePlay(qaOwner,head.id,a);head=applyActivePlayAck(head,ack);return ack};
 await play(clock('candidate-active-open'));for(let i=0;i<8;i++){f.advance(1000);const a=clock(),ack=await play(a);assert.deepEqual(await service.authority.activePlay(qaOwner,head.id,a),ack)}assert.equal(head.townMinutes,902);assert.equal(head.plantUsesV1.mint.recoverAt,1618);assert.equal((await service.authority.get(qaOwner,head.id)).plantUsesV1.mint.recoverAt,1618);
 await play(clock('candidate-active-pause',0));const paused=structuredClone(head);f.advance(3600000);service=await f.build(true,'weather-ecology-after-offline');await play(clock('candidate-active-open'));assert.deepEqual(head.weatherEcologyV1,paused.weatherEcologyV1);assert.deepEqual(head.plantUsesV1,paused.plantUsesV1);
 const enabled=await service.authority.action(qaOwner,head.id,{...action(head,'candidate-clock-enable',''),payload:{millisecondsPerMinute:4000}});head=enabled.head;await play(clock('candidate-active-open'));
 const move=async(foreground=false)=>{const c=head.movingClock,last=c?.transport?.last.ack,l=head.activePlayClock.lease,a={...action(head,'candidate-motion-open',''),action_id:motionActionId(head.id,(last?.ordinal??0)+1),payload:{transport:1,ordinal:(last?.ordinal??0)+1,previous:last?.token??'',...(c?.lease?{lease:c.lease.id,sequence:c.lease.sequence+1}:{}),points:[],...(foreground?{foreground:{client,lease:l.id,sequence:l.sequence+1,activeMs:2000}}:{})}};const ack=await service.authority.motion(qaOwner,head.id,a);assert.ok(!('items' in ack.fields));head=applyMotionAck(head,ack);assert.deepEqual(await service.authority.motion(qaOwner,head.id,a),ack)};
 await move();for(let i=0;i<4;i++){f.advance(2000);await move(true)}assert.equal(head.townMinutes,904);assert.equal(head.plantUsesV1.mint.recoverAt,1616);assert.deepEqual((await service.authority.get(qaOwner,head.id)).plantUsesV1,head.plantUsesV1);
 const before=await service.authority.get(qaOwner,head.id),bad=action(head,'invalid-action');await assert.rejects(service.authority.action(qaOwner,head.id,bad));assert.deepEqual(await service.authority.get(qaOwner,head.id),before);
}));
