// @ts-nocheck -- actual compiled Main/View/Pixi and isolated synthetic account SQLite.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {readFileSync,existsSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';
import {makeDemoServer} from './temporary-account-server';import {createExplorationAssembly} from '../server/exploration-assembly';import {createReviewedAnimalLife} from '../server/reviewed-animal-life';import {withWildMint} from '../server/wild-mint';import {withBasilPlantUses} from '../server/plant-basil';import {initial} from '../src/story/state';import {rooms,people,entityAt} from '../src/world/data';import {weatherAt} from '../src/weather/state';import {GAME_UUID} from '../src/game-id';
const out=resolve(process.env.HARBOR_WEATHER_UI_DIR??'../evidence/weather-ui');await mkdir(out,{recursive:true});const dir=mkdtempSync('/tmp/harbor-weather-ui-');
const shell='/Users/yin/code/games/harbor-animal-ai-owner-aba82cc-20261009/evidence',loader=readFileSync(shell+'/guest-shell-public-20261009.js'),impl=readFileSync(shell+'/guest-shell-impl-public-20261009.js');
let spec:any,api,cookie='',modelCalls=0;
const assembly=createExplorationAssembly({weather:{enabled:true},crabEnabled:true,createLife:createReviewedAnimalLife,resolveDialogue:async()=>{modelCalls++;throw Error('MODEL_CLOSED')},decorateLife:life=>withWildMint(withBasilPlantUses(life,{enabled:true,newStarts:true}),{enabled:true,newStarts:true}),initial:(locale,id)=>({...initial(locale,id),townMinutes:spec.minute,scene:spec.scene,position:spec.scene==='home'?entityAt('home','bed').approach:rooms[spec.scene].spawn,flags:['key','unpacked','bag-returned','garden-agreed','alternative-route','crop-starter'],known:Object.keys(people),visited:Object.keys(rooms),plots:{'crop-bed-1':{crop:'basil',grown:0,updatedAt:spec.minute,wetUntil:spec.minute}}})});
const server=await makeDemoServer({directory:dir,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority,accountOnly:true});api=server.url+'/'+GAME_UUID+'/api';
async function call(account,path,body){const r=await fetch(api+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,'X-Harbor-Telegram-Id':account,'X-Harbor-Identity-Mode':'temporary-unverified','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data}
const report={scope:'compiled candidate Main/View/RPGJS+unchanged pinned guest shell, isolated SQLite synthetic accounts; all non-loopback requests blocked except fulfilled pinned public shell. Platform-layout shots hide only the unchanged shared guest banner. Not physical/Telegram or production verification.',cases:[],errors:[],missing:[],blocked:[],modelCalls:0,productionWrites:0,realAuthCalls:0};
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg','.wav':'audio/wav'};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
let specs=[];for(const [width,height] of [[320,568],[390,844],[1280,800]])for(const [minute,scene,quality] of [[540,'market','full'],[720,'market','full'],[900,'garden','full'],[1620,'market','full'],[900,'home','full'],[900,'garden','low'],[1620,'market','low']])specs.push({width,height,minute,scene,quality,locale:'en'});
specs.push({width:320,height:568,minute:1620,scene:'garden',quality:'full',locale:'zh'},{width:320,height:568,minute:900,scene:'home',quality:'low',locale:'zh'});
if(process.env.HARBOR_WEATHER_UI_CASE)specs=specs.filter(s=>`${s.width}-${s.locale}-${s.scene}-${s.minute}-${s.quality}`===process.env.HARBOR_WEATHER_UI_CASE);
async function snap(page,label){await page.screenshot({path:out+'/'+label+'.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,label+' overflow')}
async function ready(p){await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));while(await p.locator('.harbor-opening button').isVisible())await p.locator('.harbor-opening button').click();await p.waitForTimeout(300)}
async function metrics(p){return p.evaluate(async()=>{const c=document.querySelector('#rpg').__rpgClient;const p=c.getCurrentPlayer(),r=document.querySelector('.harbor-weather'),obj=document.querySelector('.harbor-objective').getBoundingClientRect(),controls=document.querySelector('.harbor-controls').getBoundingClientRect(),location=document.querySelector('.harbor-location').getBoundingClientRect();let hero;function visit(n){if(n.texture?.source?.label?.includes('/hero.png'))hero=n;for(const k of n.children??[])visit(k)}visit(c.canvasApp.stage);const b=hero.getBounds(),rpg=document.querySelector('#rpg').getBoundingClientRect(),sx=rpg.width/parseFloat(c.width()),sy=rpg.height/parseFloat(c.height());let times=[],last=performance.now();await new Promise(resolve=>{let i=0;const tick=t=>{times.push(t-last);last=t;if(++i>=25)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});times=times.slice(1).sort((a,b)=>a-b);return {kind:document.querySelector('.harbor-world').dataset.weatherKind,particleCount:r?.querySelectorAll('i').length??0,outdoorLayer:!!r,pointerEvents:r&&getComputedStyle(r).pointerEvents,locationText:document.querySelector('.harbor-location').textContent,locationBottom:location.bottom,objectiveTop:obj.top,headGap:rpg.y+(b.y+b.height*14/128)*sy-obj.bottom,footGap:controls.top-(rpg.y+(b.y+b.height*122/128)*sy),frameMedianMs:times[Math.floor(times.length/2)],frameP95Ms:times[Math.floor(times.length*.95)],position:{x:p.x(),y:p.y()},nativeRoom:c.activeRoom().name}})}
try{for(let index=0;index<specs.length;index++){
 spec=specs[index];const account=String(720000+index),label=`${spec.width}-${spec.locale}-${spec.scene}-${spec.minute}-${spec.quality}`;await call(account,'/bootstrap',{});const seed=await call(account,'/sessions',{enrollment_id:randomUUID(),locale:spec.locale}),head=()=>call(account,'/sessions/'+seed.id);
 const context=await browser.newContext({viewport:{width:spec.width,height:spec.height},locale:spec.locale==='zh'?'zh-CN':'en-US',serviceWorkers:'block',...(process.env.HARBOR_WEATHER_UI_CASE?{recordVideo:{dir:out+'/video',size:{width:spec.width,height:spec.height}}}:{})});
 await context.addInitScript(({account,locale,quality,id})=>{window.__name=f=>f;window.Aigram={isInAigram:true,telegramId:account,callAigramAPI:()=>Promise.resolve({retcode:0})};addEventListener('DOMContentLoaded',()=>{for(const [key,value] of [['harbor-locale',locale],['harbor-muted','1'],['harbor-weather-quality',quality],['harbor-opening:'+id,'3']])if(window.alteruLocalStorage.getItem(key)===null)window.alteruLocalStorage.setItem(key,value)});window.__rainCount=0;window.__rainMax=0;const start=AudioBufferSourceNode.prototype.start,stop=AudioBufferSourceNode.prototype.stop;AudioBufferSourceNode.prototype.start=function(...args){if(this.loop){this.__weatherQA=true;window.__rainCount++;window.__rainMax=Math.max(window.__rainMax,window.__rainCount)}return start.apply(this,args)};AudioBufferSourceNode.prototype.stop=function(...args){if(this.__weatherQA){this.__weatherQA=false;window.__rainCount--}return stop.apply(this,args)}},{account,locale:spec.locale,quality:spec.quality,id:seed.id});
 await context.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.js'))return r.fulfill({contentType:'text/javascript',body:loader});if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.impl.js'))return r.fulfill({contentType:'text/javascript',body:impl});if(u.hostname!=='127.0.0.1'){report.blocked.push(u.origin+u.pathname);return r.abort()}
 if(u.pathname.includes('/api/'))return r.continue();const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file)){report.missing.push(u.pathname);return r.fulfill({status:404,body:'Missing'})}return r.fulfill({contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
 const p=await context.newPage();p.setDefaultTimeout(25000);p.on('pageerror',e=>report.errors.push({label,error:String(e)}));
 try{await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:spec.locale==='zh'?'继续':'Continue',exact:true}).click();await ready(p);await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});const m=await metrics(p);assert.equal(m.kind,weatherAt(spec.minute));assert.equal(m.particleCount,rooms[spec.scene].outdoor&&m.kind==='light-rain'?(spec.quality==='low'?4:12):0);assert.equal(m.outdoorLayer,rooms[spec.scene].outdoor);assert.ok(m.headGap>=10&&m.footGap>=10,label+' actor safe');assert.ok(m.objectiveTop>=m.locationBottom-1,label+' HUD overlap');if(m.outdoorLayer)assert.equal(m.pointerEvents,'none');await snap(p,label);const result={...spec,label,metrics:m};
 if(spec.width===390&&spec.scene==='garden'&&spec.quality==='full'){
  await p.keyboard.down('ArrowLeft');await p.waitForTimeout(700);await p.keyboard.up('ArrowLeft');await p.waitForTimeout(300);const moved=await metrics(p);assert.notDeepEqual(moved.position,m.position);result.keyboardMoved=true;
  const stick=await p.locator('.harbor-stick').boundingBox(),beforeStick=(await metrics(p)).position;await p.mouse.move(stick.x+stick.width/2,stick.y+stick.height/2);await p.mouse.down();await p.mouse.move(stick.x+stick.width/2+28,stick.y+stick.height/2);await p.waitForTimeout(500);await p.mouse.up();await p.waitForTimeout(300);const afterStick=(await metrics(p)).position;assert.ok(afterStick.x>beforeStick.x);result.joystickMovedAndStopped=true;
  await p.locator('.harbor-header nav').getByRole('button',{name:'System',exact:true}).click();await p.getByRole('button',{name:'Settings',exact:true}).click();await p.getByRole('button',{name:'Enable sound',exact:true}).click();await p.getByRole('button',{name:'Weather effects: Standard',exact:true}).click();assert.equal(await p.locator('.harbor-weather i').count(),4);await snap(p,label+'-settings');const paused=await head();await p.waitForTimeout(1500);assert.equal((await head()).townMinutes,paused.townMinutes);assert.equal((await head()).plots['crop-bed-1'].grown,paused.plots['crop-bed-1'].grown);assert.equal(await p.evaluate(()=>window.__rainCount),0);await p.getByRole('button',{name:'Close',exact:true}).click();await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>window.__rainCount),1);
  await p.getByRole('button',{name:'Bag',exact:true}).click();await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>window.__rainCount),0);assert.equal(await p.locator('.harbor-weather').getAttribute('data-weather-paused'),'true');await snap(p,label+'-bag');await p.getByRole('button',{name:'Close',exact:true}).click();await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>window.__rainCount),1);
  const active=await head();await p.waitForTimeout(5000);const grown=await head();assert.ok(grown.townMinutes>active.townMinutes);assert.equal(grown.plots['crop-bed-1'].grown-active.plots['crop-bed-1'].grown,grown.townMinutes-active.townMinutes);result.actualForegroundRainGrowth=true;
  await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>!!window.__qaHidden});window.__qaHidden=true;document.dispatchEvent(new Event('visibilitychange'))});await p.waitForTimeout(300);const hidden=await head();assert.equal(await p.evaluate(()=>window.__rainCount),0);await p.waitForTimeout(4300);assert.equal((await head()).townMinutes,hidden.townMinutes);assert.deepEqual((await head()).weatherV1,hidden.weatherV1);await p.evaluate(()=>{window.__qaHidden=false;document.dispatchEvent(new Event('visibilitychange'))});await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>window.__rainCount),1);assert.equal(await p.evaluate(()=>window.__rainMax),1);result.rainVoice={singleLoop:true,mutedPanelBackgroundStops:true};result.backgroundNoCatchup=true;result.qualityChangedRulesUnchanged=true;
  await p.emulateMedia({reducedMotion:'reduce'});const anim=await p.locator('.harbor-weather i').first().evaluate(e=>getComputedStyle(e).animationName);assert.equal(anim,'none');await snap(p,label+'-reduced');result.reducedMotion=true;
  await p.locator('.harbor-header nav').getByRole('button',{name:'System',exact:true}).click();await p.waitForTimeout(300);const old=await head();await p.reload();await p.getByRole('button',{name:'Continue',exact:true}).click();await ready(p);assert.equal((await head()).weatherV1.kind,old.weatherV1.kind);assert.equal(await p.locator('.harbor-weather').getAttribute('data-weather-quality'),'low');result.reloadKeepsKindAndPreference=true;
  await p.locator('.harbor-header nav').getByRole('button',{name:'System',exact:true}).click();await p.getByRole('button',{name:'Controls & help',exact:true}).click();assert.ok((await p.locator('.harbor-panel').innerText()).includes('It does not count as watering by hand'));await snap(p,label+'-help');result.rainHelpExplainsFiniteAndNoManualCredit=true;
 }
 if(spec.width===390&&spec.scene==='home'){
  await p.keyboard.press('e');await p.locator('.harbor-panel').waitFor();const before=await head();await p.getByRole('button',{name:'Nap for three hours',exact:true}).click();await p.waitForTimeout(300);const n=await head();assert.equal(n.plots['crop-bed-1'].grown,60);assert.equal(n.townMinutes,before.townMinutes+180);assert.equal(await p.locator('.harbor-weather').count(),0);await snap(p,label+'-rest');result.sleepSettlesRainOutdoorsWhileIndoors=true;
 }
 report.cases.push(result);console.log('PASS',label);writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');
 }catch(error){await snap(p,label+'-FAIL').catch(()=>{});writeFileSync(out+'/failed.json',JSON.stringify({label,error:String(error),body:(await p.locator('body').innerText()).slice(0,4000),head:await head()},null,2));throw error}finally{await context.close()}
 }assert.equal(report.errors.length,0);assert.equal(report.missing.length,0);assert.equal(modelCalls,0);report.modelCalls=modelCalls;report.status='PASS';
}catch(error){report.status='FAIL';report.failure=String(error);throw error}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');await browser.close();await server.close();rmSync(dir,{recursive:true,force:true})}
