// @ts-nocheck -- real compiled Main/Pixi, isolated synthetic accounts, no production identity.
import {globalPoint,localPoint} from '../src/candidate/continuity';
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {readFileSync,existsSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';
import {makeDemoServer} from './temporary-account-server';import {createExplorationAssembly} from '../server/exploration-assembly';
import {createReviewedAnimalLife} from '../server/reviewed-animal-life';import {withWildMint} from '../server/wild-mint';import {withBasilPlantUses} from '../server/plant-basil';
import {initial} from '../src/story/state';import {rooms,people,entityAt} from '../src/world/data';import {mintNode} from '../src/life/plant-uses';import {mintDefinitionHash} from '../server/plant-uses-rules';
import {acceptedAnimals} from '../src/animals/art';import {weatherAnimalSlot} from '../src/weather/animal-shelter';import {createWeatherState} from '../src/weather/state';import {createWeatherEcology} from '../src/weather/ecology';import {GAME_UUID} from '../src/game-id';
const out=resolve(process.env.HARBOR_ECOLOGY_UI_DIR??'../evidence/ui/round1');await mkdir(out,{recursive:true});const dir=mkdtempSync('/tmp/harbor-weather-ecology-ui-');
const pinnedShell='/Users/yin/code/games/harbor-animal-ai-owner-aba82cc-20261009/evidence',loader=readFileSync(pinnedShell+'/guest-shell-public-20261009.js'),impl=readFileSync(pinnedShell+'/guest-shell-impl-public-20261009.js');
let spec:any,api,cookie='',modelCalls=0;
const assembly=createExplorationAssembly({weather:{enabled:true,ecology:true},crabEnabled:true,createLife:createReviewedAnimalLife,resolveDialogue:async()=>{modelCalls++;throw Error('MODEL_CLOSED')},decorateLife:life=>withWildMint(withBasilPlantUses(life,{enabled:true}),{enabled:true}),initial:(locale,id)=>({...initial(locale,id),townMinutes:900,scene:spec.scene,position:spec.position,flags:['key','unpacked','bag-returned','garden-agreed','alternative-route'],known:Object.keys(people),visited:Object.keys(rooms),plantUsesV1:{schema:1,deliveries:0,mint:{node:mintNode.id,definitionHash:mintDefinitionHash,stock:1,recoverAt:1620,leaves:0}}})});
const server=await makeDemoServer({directory:dir,providedRuntime:assembly.runtime,lifeProject:assembly.lifeProject,landProject:assembly.landProject,decorateAuthority:assembly.decorateAuthority,accountOnly:true});api=server.url+'/'+GAME_UUID+'/api';
async function call(account,path,body){const r=await fetch(api+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,'X-Harbor-Telegram-Id':account,'X-Harbor-Identity-Mode':'temporary-unverified','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data}
const report={scope:'compiled independent candidate Main/View/RPGJS, local synthetic account SQLite; pinned unchanged shell; all external calls blocked. No production, physical phone, Telegram, true login or comprehension evidence.',cases:[],pageErrors:[],missing:[],blocked:[],modelCalls:0,productionWrites:0};
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg','.wav':'audio/wav'};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader','--disk-cache-size=1','--media-cache-size=1']});
let specs=[];for(const [width,height] of [[320,568],[390,844]]){
 for(const [scene,cat] of [['station','harbor-cat-1'],['market','harbor-cat-2'],['courtyard','harbor-cat-3']]){const foot=weatherAnimalSlot(acceptedAnimals.find(a=>a.id===cat),{townMinutes:900,weatherV1:createWeatherState(900),weatherEcologyV1:createWeatherEcology(900)}).shelter.point;specs.push({width,height,type:'cat',scene,cat,foot,position:{x:foot.x-8,y:scene==='market'?foot.y-60:foot.y+48},locale:'en'})}
 specs.push({width,height,type:'mint',scene:'hill',position:mintNode.approach,locale:width===320?'zh':'en'});
 specs.push({width,height,type:'resident',scene:'market',position:entityAt('market','dani').approach,locale:width===320?'zh':'en'});
}
if(process.env.HARBOR_ECOLOGY_UI_CASE)specs=specs.filter(s=>`${s.width}-${s.type}-${s.scene}`===process.env.HARBOR_ECOLOGY_UI_CASE);
async function snap(p,label){await p.waitForFunction(()=>[...document.images].every(image=>image.complete&&image.naturalWidth>0));await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await p.screenshot({path:out+'/'+label+'-platform-layout.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'horizontal overflow')}
async function ready(p){await p.waitForFunction(()=>document.querySelector('#rpg')?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'));while(await p.locator('.harbor-opening button').isVisible())await p.locator('.harbor-opening button').click();await p.waitForTimeout(300)}
function actor(p,id){return p.evaluate(id=>{const c=document.querySelector('#rpg').__rpgClient,e=Object.values(c.sceneMap.events()).find(e=>e.id.endsWith(id));return e?{id:e.id,x:e.x(),y:e.y(),pose:e.animationName(),graphics:e.graphics()}:null},id)}
try{for(let index=0;index<specs.length;index++){
 spec=specs[index];const account=String(731000+index),label=`${spec.width}-${spec.type}-${spec.scene}`,result={...spec,label};await call(account,'/bootstrap',{});const seed=await call(account,'/sessions',{enrollment_id:randomUUID(),locale:spec.locale}),head=()=>call(account,'/sessions/'+seed.id);
 const c=await browser.newContext({viewport:{width:spec.width,height:spec.height},locale:spec.locale==='zh'?'zh-CN':'en-US',serviceWorkers:'block',recordVideo:{dir:out+'/video',size:{width:spec.width,height:spec.height}}});
 await c.addInitScript(({account,locale,id})=>{window.__name=f=>f;window.Aigram={isInAigram:true,telegramId:account,callAigramAPI:()=>Promise.resolve({retcode:0})};addEventListener('DOMContentLoaded',()=>{for(const [k,v] of [['harbor-locale',locale],['harbor-muted','1'],['harbor-opening:'+id,'3']])window.alteruLocalStorage.setItem(k,v)})},{account,locale:spec.locale,id:seed.id});
 await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.js'))return r.fulfill({contentType:'text/javascript',body:loader});if(u.hostname==='images.aiwaves.tech'&&u.pathname.endsWith('/guest-shell.impl.js'))return r.fulfill({contentType:'text/javascript',body:impl});if(u.hostname!=='127.0.0.1'){report.blocked.push(u.origin+u.pathname);return r.abort()}if(u.pathname.includes('/api/'))return r.continue();const file=resolve('dist','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(resolve('dist')+'/')||!existsSync(file)){report.missing.push(u.pathname);return r.fulfill({status:404,body:'Missing'})}return r.fulfill({contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)})});
 const p=await c.newPage();p.setDefaultTimeout(25000);p.on('pageerror',e=>report.pageErrors.push({label,error:String(e)}));
 try{await p.goto(server.url+'/?debug=1');await p.getByRole('button',{name:spec.locale==='zh'?'继续':'Continue',exact:true}).click();await ready(p);await p.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});assert.equal(await p.locator('.harbor-world').getAttribute('data-weather-kind'),'light-rain');await snap(p,label+'-initial');
 if(spec.type==='cat'){
  const id='animal-'+spec.cat;result.initial=await actor(p,id);assert.ok(result.initial?.graphics.length);
  await p.evaluate(id=>{window.__ecoTrace=[];window.__ecoTracing=true;const frame=()=>{if(!window.__ecoTracing)return;const c=document.querySelector('#rpg').__rpgClient,e=Object.values(c.sceneMap.events()).find(e=>e.id.endsWith(id));if(e)window.__ecoTrace.push({at:performance.now(),x:e.x(),y:e.y(),pose:e.animationName()});requestAnimationFrame(frame)};requestAnimationFrame(frame)},id);
  await p.waitForFunction(({id,foot})=>{const c=document.querySelector('#rpg').__rpgClient,e=Object.values(c.sceneMap.events()).find(e=>e.id.endsWith(id));return e&&Math.hypot(e.x()-foot.x,e.y()-foot.y)<2},{id,foot:globalPoint(spec.scene,spec.foot)},{timeout:45000});await p.waitForTimeout(300);result.final=await actor(p,id);result.finalLogical=localPoint(spec.scene,result.final);await snap(p,label+'-sheltered');
  const trace=await p.evaluate(()=>{window.__ecoTracing=false;return window.__ecoTrace});writeFileSync(out+'/'+label+'-rAF.json',JSON.stringify(trace));assert.ok(trace.length>100);assert.ok(new Set(trace.map(s=>s.pose)).size>=3,'actual A/stand/B');result.traceSamples=trace.length;result.poses=[...new Set(trace.map(s=>s.pose))];
  if(spec.scene==='market'){const dani=await actor(p,'person-dani');await p.waitForTimeout(1100);assert.deepEqual(await actor(p,'person-dani'),dani);result.rainStopsDistantDaniStroll=true}
  await p.keyboard.press('e');await p.locator('[data-cat-rain]').waitFor();assert.ok((await p.locator('[data-cat-rain]').innerText()).includes('existing records'));assert.equal(await p.getByRole('button',{name:'Watch quietly',exact:true}).count(),0);await snap(p,label+'-rain-panel');result.rainCannotMasqueradeAsSunObservation=true;if(spec.width===390){const beforePet=await head();const receipt=p.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/action'));await p.getByRole('button',{name:'Pet gently',exact:true}).click();assert.equal((await receipt).status(),200);const pet=await head();assert.equal(pet.animalsV1.individuals[spec.cat].familiarity,1);assert.deepEqual(pet.items,beforePet.items);assert.equal(pet.cash,beforePet.cash);await snap(p,label+'-ordinary-pet');result.realLocalPetReceiptNoExtraReward=true}await p.getByRole('button',{name:'Close',exact:true}).click();
  await p.getByRole('button',{name:'Bag',exact:true}).click();const pause=await actor(p,id);await p.waitForTimeout(1200);assert.deepEqual(await actor(p,id),pause);await snap(p,label+'-paused');result.panelFreezesCat=true;
  const h=await head();assert.ok(h.weatherEcologyV1);assert.equal(h.plantUsesV1.mint.recoverAt,1620-h.weatherEcologyV1.mintRainUsed);result.committedMintDue=h.plantUsesV1.mint.recoverAt;
 }
 if(spec.type==='mint'){
  await p.keyboard.press('e');await p.locator('[data-wild-mint]').waitFor();const text=await p.locator('[data-wild-mint]').innerText();assert.ok(text.includes('60'));assert.ok(spec.locale==='en'?text.includes('no extra leaves'):text.includes('不会额外送叶'));await snap(p,label+'-panel');result.panelText=text;
  const h=await head();await p.waitForTimeout(1200);assert.equal((await head()).plantUsesV1.mint.recoverAt,h.plantUsesV1.mint.recoverAt);result.panelDoesNotGrowMint=true;
 }
 if(spec.type==='resident'){
  await p.keyboard.press('e');await p.locator('.harbor-panel').waitFor();const text=await p.locator('.harbor-dialogue').innerText();assert.ok(spec.locale==='en'?text.includes('page dry'):text.includes('这一页湿了'));await snap(p,label+'-panel');result.panelText=text;
 }
 report.cases.push(result);writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log('PASS',label);
 }catch(error){await snap(p,label+'-FAIL').catch(()=>{});writeFileSync(out+'/'+label+'-FAIL.json',JSON.stringify({error:String(error),body:(await p.locator('body').innerText()).slice(0,3500),actor:spec.cat?await actor(p,'animal-'+spec.cat):null},null,2));throw error}finally{await c.close()}
 }assert.equal(report.pageErrors.length,0);assert.equal(report.missing.length,0);assert.equal(modelCalls,0);report.status='PASS';
}catch(error){report.status='FAIL';report.failure=String(error);throw error}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await server.close();rmSync(dir,{recursive:true,force:true})}
