import {chromium} from 'playwright';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {Readable} from 'node:stream';
import {execFileSync} from 'node:child_process';
const diskGuard=()=>{const row=execFileSync('df',['-k','.'],{encoding:'utf8'}).trim().split('\n').at(-1)!.trim().split(/\s+/);if(Number(row[3])<15729664)throw Error('15GIB_DISK_FLOOR');};
diskGuard();
import {randomUUID,createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {initial,applyAction} from '../src/story/state';
import {rooms,entityAt} from '../src/world/data';
import {createRuntime} from '../server/runtime';
import {createMovingClock} from '../server/candidate-clock';
import {withCompactMotion} from '../server/candidate-motion-authority';
import {createApiHandler} from '../server/http';
import {AsyncSessionAuthority,openAsyncSqliteAuthorityStore} from '../vendor/dynamic-runtime/packages/authority-session/async.mjs';
const out=resolve('_qa/ui/compact-motion'),dist=resolve('dist'),publicRoot=resolve('public');mkdirSync(out,{recursive:true});
const mime:any={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.svg':'image/svg+xml','.tmx':'application/xml','.tsx':'application/xml','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const codeFiles=['src/candidate/clock-types.ts','src/candidate/use-moving-clock.ts','src/candidate/render-adapter.ts','src/candidate/motion-trace.ts','src/engine/distance-motion.ts','src/engine/rpg-space.ts','src/engine/elapsed-motion.ts','src/story/client.ts','server/candidate-clock.ts','server/candidate-motion-authority.ts','server/http.ts','server/runtime.ts','server/candidate-preview.ts'];
const codeDigest=createHash('sha256');for(const path of codeFiles)codeDigest.update(path+'\n').update(readFileSync(path));
const report:any={codeDigest:codeDigest.digest('hex'),codeFiles,rendererBundle:readFileSync(resolve(dist,'index.html'),'utf8').match(/src="([^"]+index-[^"]+\.js)"/)?.[1],scope:'LOCAL candidate, real Main/View/RPGJS, synthetic isolated SQLite authority; every external request blocked. Not Telegram or a physical phone. No publishing, models, media, production or player operations.',cases:[],errors:[],blocked:[],modelCalls:0};
const browser=await chromium.launch({headless:true,executablePath:'/Users/yin/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',args:['--use-angle=swiftshader']});
try{for(const width of (process.env.QA_WIDTHS??'320,390,1280').split(',').map(Number)){
 const height=width===320?568:width===390?844:800,rate=width===390?4000:2000,locale=width===390?'zh':'en',owner='synthetic-'+randomUUID();
 const store=openAsyncSqliteAuthorityStore({path:':memory:',worldId:randomUUID(),gameId:'moving-local-candidate',environment:'test'});
 const motion=createMovingClock(),base=createRuntime(async()=>{report.modelCalls++;throw Error('QA_MODEL_CLOSED')},undefined,motion);
 const motionRuntime={...base,initial:(l:any,id:string)=>{if(process.env.QA_BATTLE){const s={...initial(l,id),scene:'gym',position:entityAt('gym','idris')!.approach,known:['idris'],flags:['key','unpacked','battle:class:accepted'],visited:Object.keys(rooms)};return {...applyAction(s,{action_id:randomUUID(),expected_version:s.version,scene:s.scene,position:s.position,target:'idris',action:'battle-start',payload:{encounter:'open-class'}}).head,version:0,cursor:0}}return {...initial(l,id),version:0,scene:'market',position:{x:597,y:145},townMinutes:718,flags:['key','unpacked','bag-returned'],visited:Object.keys(rooms)}}};
 const authority=withCompactMotion(new AsyncSessionAuthority(store,motionRuntime),store,motionRuntime,motion);
 const seed=await authority.create(owner,randomUUID(),locale),head=()=>authority.get(owner,seed.id),api=createApiHandler({authority,usage:{status:async()=>({resetAt:0,dialogue:{remaining:0,maximum:0,retryAt:null,pending:0}})},noteMedia:{}}),actions:any[]=[],rejected:any[]=[],responses:any[]=[];let dropAfterCommit=false,offline=false;
 const context=await browser.newContext({viewport:{width,height},locale:locale==='en'?'en-US':'zh-CN'});
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.hostname!=='127.0.0.1'){report.blocked.push(url.origin+url.pathname);return route.abort()}
  if(url.pathname.includes('/api/')){const endpoint=url.pathname.slice(url.pathname.indexOf('/api/'));if(endpoint==='/api/bootstrap')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({mode:'local-authoring-test'})});const data=req.postData();if(endpoint.endsWith('/action')||endpoint.endsWith('/motion'))actions.push({...req.postDataJSON(),channel:endpoint.endsWith('/motion')?'motion':'action'});if(endpoint.endsWith('/motion')&&offline)return route.abort();const request:any=Readable.from(data?[Buffer.from(data)]:[]);request.url=endpoint+url.search;request.method=req.method();request.headers=req.headers();let status=200,headers:any={},body=Buffer.alloc(0);const response:any={writeHead:(s:number,h:any)=>{status=s;headers=h},end:(v:any)=>body=Buffer.from(v??'')};try{await api(request,response,owner)}catch(e:any){status=400;body=Buffer.from(JSON.stringify({error:e.code??e.message,terminal:true}));rejected.push({endpoint,error:e.code??e.message})}if(endpoint.endsWith('/motion')){responses.push({status,bytes:body.length});if(dropAfterCommit&&req.postDataJSON().action==='candidate-motion-step'){dropAfterCommit=false;return route.fulfill({status:408,contentType:'application/json',body:JSON.stringify({error:'GATEWAY_RESPONSE_TIMEOUT'})})}}return route.fulfill({status,headers,body})}
  const relative='.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname));let file=resolve(dist,relative);if(!file.startsWith(dist+'/'))return route.fulfill({status:404,body:'Missing local resource'});if(!existsSync(file)){file=resolve(publicRoot,relative);if(!file.startsWith(publicRoot+'/')||!existsSync(file))return route.fulfill({status:404,body:'Missing local resource'})}return route.fulfill({status:200,contentType:mime[extname(file)]??'application/octet-stream',body:readFileSync(file)});
 });
 await context.addInitScript((id:string)=>{(window as any).__name=(f:any)=>f;addEventListener('DOMContentLoaded',()=>{window.alteruLocalStorage?.setItem('harbor-muted','1');window.alteruLocalStorage?.setItem('harbor-opening:'+id,'3')})},seed.id);
 await context.addInitScript((ms:number)=>{const raf=requestAnimationFrame.bind(window);(window as any).__qaFrameMs=ms;window.requestAnimationFrame=callback=>{const delay=(window as any).__qaFrameMs;return delay?window.setTimeout(()=>raf(callback),delay):raf(callback)}},Number(process.env.QA_FRAME_MS??0));
 const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>report.errors.push(String(e)));
 await page.goto(`http://127.0.0.1:5498/?debug=1&candidate=1&clock=${rate}`);
 await page.waitForFunction(()=>!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'),undefined,{timeout:20000}).catch(async e=>{diskGuard();await page.screenshot({path:out+'/diagnostic-'+width+'.png'});console.log('DIAGNOSTIC',await page.locator('body').innerText(),report.errors);throw e});
 for(let i=0;i<3&&await page.locator('.harbor-opening button').count();i++)await page.locator('.harbor-opening button').click();
 if(process.env.QA_BATTLE){await page.waitForTimeout(600);assert.equal(actions.filter(a=>a.channel==='motion').length,0);await page.getByRole('button',{name:locale==='en'?/^Strike/:/^出招/}).click();await page.waitForFunction(()=>document.querySelector('.harbor-turn__receipt')?.textContent?.includes('1'));const played=await head();assert.equal(played.townMinutes,542);assert.equal(played.energy,98);assert.equal(played.turnBattle!.bout.round,1);assert.equal(actions.filter(a=>a.channel==='motion').length,0);await page.locator('.harbor-turn header').getByRole('button',{name:locale==='en'?'Pause and return to town':'暂停并返回小镇',exact:true}).click();await page.waitForTimeout(1100);const paused=await head();assert.equal(paused.turnBattle!.phase,'paused');assert.ok(paused.movingClock?.lease);assert.deepEqual(paused.turnBattle!.bout,played.turnBattle!.bout);assert.equal(paused.townMinutes,542);await page.reload();await page.waitForFunction(()=>!document.querySelector('.harbor-loading')&&!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer());await page.waitForTimeout(700);const restored=await head();assert.deepEqual(restored.turnBattle,paused.turnBattle);assert.equal(restored.townMinutes,542);report.cases.push({width,height,mode:'old-locked-bout-then-paused',turnCost:2,energyAfter:98,clockAdmittedOnlyAfterPause:true,reloadPreserved:true,modelCalls:report.modelCalls,rejected});assert.equal(rejected.length,0);console.log('PASS BATTLE',JSON.stringify(report.cases.at(-1)));await context.close();await store.close();continue;}
 await page.waitForTimeout(1300);assert.ok((await head()).movingClock?.lease,'server clock initialized');
 await page.evaluate(()=>{(window as any).__qaPlayer=(document.querySelector('#rpg') as any).__rpgClient.getCurrentPlayer()});
 const inspect=()=>page.evaluate(()=>{const c=(document.querySelector('#rpg') as any).__rpgClient,p=c.getCurrentPlayer();const nodes:any[]=[];const visit=(n:any)=>{nodes.push(n);for(const k of n.children??[])visit(k)};visit(c.canvasApp.stage);const view=nodes.find(n=>'toWorld' in n&&'clamp' in n);return {viewport:view&&{x:view.x,y:view.y,scale:view.scale.x,tl:view.toWorld(0,0),br:view.toWorld(Number(c.width()),Number(c.height()))},textures:nodes.filter(n=>n.texture?.source?.label?.includes('hero')||n.texture?.source?.label?.includes('bazaar-base')).map(n=>({label:n.texture.source.label,bounds:n.getBounds(),visible:n.visible,renderable:n.renderable})),map:c.activeRoom().name,x:p.x(),y:p.y(),samePlayer:p===(window as any).__qaPlayer,label:document.querySelector('.harbor-location')?.textContent,overflow:document.documentElement.scrollWidth>innerWidth+1,graphics:p.graphics(),events:Object.entries(c.sceneMap.events()).filter(([id])=>id.includes('person-')).map(([id,v]:any)=>({id,x:v.x(),y:v.y(),graphics:v.graphics()}))}});
 const before=await inspect();diskGuard();await page.screenshot({path:out+`/local-compact-candidate-platform-layout-${width}-${Number(process.env.QA_FRAME_MS??0)?'slow':'normal'}-market.png`});
 await page.keyboard.down('ArrowUp');await page.waitForTimeout(1250);for(let i=0;i<6&&(await head()).scene!=='bazaar';i++)await page.waitForTimeout(250);await page.keyboard.up('ArrowUp');await page.waitForTimeout(650);
 const north=await head(),after=await inspect();const firstDistance=685-(north.scene==='bazaar'?north.position.y:north.position.y+540);if(Number(process.env.QA_FRAME_MS??0)>=150)assert.ok(firstDistance>80,'slow real rAF uses elapsed, not legacy 40ms cap');assert.equal(north.scene,'bazaar','normal keyboard crosses continuously');assert.equal(after.map,'market-bazaar');assert.equal(after.samePlayer,true);assert.equal(after.overflow,false);assert.ok(after.textures.length>=2,'real floor and hero sprites draw');
 diskGuard();await page.screenshot({path:out+`/local-compact-candidate-platform-layout-${width}-${Number(process.env.QA_FRAME_MS??0)?'slow':'normal'}-bazaar.png`});
 await page.getByRole('button',{name:locale==='en'?'Bag':'行囊',exact:true}).click();await page.waitForTimeout(700);const paused=await head();await page.waitForTimeout(2400);assert.equal((await head()).townMinutes,paused.townMinutes,'reading freezes minutes');await page.getByRole('button',{name:locale==='en'?'Close':'关闭',exact:true}).click();await page.waitForTimeout(650);
 await page.getByRole('button',{name:locale==='en'?'Map':'地图',exact:true}).click();await page.getByRole('button',{name:locale==='en'?'The bay':'全镇',exact:true}).click();await page.locator('[data-place="station"]').click();assert.ok((await page.locator('.harbor-map-destination').innerText()).includes(locale==='en'?'10 game minutes':'10游戏分钟'),'declared quick trip minutes');await page.waitForTimeout(700);const mapPaused=await head();await page.waitForTimeout(1400);assert.equal((await head()).townMinutes,mapPaused.townMinutes,'reading map freezes minutes');await page.getByRole('button',{name:locale==='en'?'Close':'关闭',exact:true}).click();await page.waitForTimeout(650);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>!!(window as any).__qaHidden});(window as any).__qaHidden=true});const background=await head();await page.waitForTimeout(3400);assert.equal((await head()).townMinutes,background.townMinutes,'simulated hidden document never catches up');await page.evaluate(()=>{(window as any).__qaHidden=false});await page.waitForTimeout(1200);assert.equal((await head()).townMinutes,background.townMinutes);assert.equal(await page.locator('.harbor-loading').count(),0,'foreground resumes with authority position');
 await page.keyboard.down('ArrowDown');await page.waitForTimeout(1250);for(let i=0;i<6&&(await head()).scene!=='market';i++)await page.waitForTimeout(250);await page.keyboard.up('ArrowDown');await page.waitForTimeout(650);const returned=await head();assert.equal(returned.scene,'market');assert.ok(returned.townMinutes-seed.townMinutes<=4,'no 20min seam toll');
 const roundTrip=async()=>{await page.keyboard.down('ArrowUp');await page.waitForTimeout(1250);await page.keyboard.up('ArrowUp');await page.waitForTimeout(550);await page.keyboard.down('ArrowDown');await page.waitForTimeout(1250);await page.keyboard.up('ArrowDown');await page.waitForTimeout(550)};await roundTrip();let threshold=await head(),extraTrips=0;while(rate===2000&&threshold.townMinutes<720&&extraTrips<4){await roundTrip();extraTrips++;threshold=await head()}if(rate===2000){assert.ok(threshold.townMinutes>=720,'normal movement reaches noon');await page.waitForFunction(()=>{const c=(document.querySelector('#rpg') as any).__rpgClient;return c.sceneMap.events()['market--person-samira']?.graphics().length===0},undefined,{timeout:3000})}const scheduled=await inspect();if(rate===2000)assert.equal(scheduled.events.find(e=>e.id==='market--person-samira')?.graphics.length,0,'same renderer withdraws morning resident at noon');await page.setViewportSize({width:width+40,height});await page.waitForTimeout(150);const resized=await inspect();assert.equal(resized.overflow,false);assert.equal(resized.samePlayer,true);await page.setViewportSize({width,height});await page.waitForTimeout(150);const committed=await head();await page.reload();await page.waitForFunction(()=>!!(document.querySelector('#rpg') as any)?.__rpgClient?.getCurrentPlayer()&&!document.querySelector('.harbor-loading'),undefined,{timeout:20000}).catch(async e=>{diskGuard();await page.screenshot({path:out+'/diagnostic-'+width+'.png'});console.log('DIAGNOSTIC',await page.locator('body').innerText(),report.errors);throw e});await page.waitForTimeout(800);const restored=await head();assert.equal(restored.townMinutes,committed.townMinutes);assert.deepEqual(restored.position,committed.position);
 const notice=entityAt('bazaar','notice')!;await page.getByRole('button',{name:locale==='en'?'Walk toward the next stop':'带我到下一处入口',exact:true}).click();let arrived=await head();for(let i=0;i<100&&(arrived.scene!=='bazaar'||Math.hypot(arrived.position.x-notice.approach.x,arrived.position.y-notice.approach.y)>4);i++){await page.waitForTimeout(200);arrived=await head()}assert.equal(arrived.scene,'bazaar');assert.ok(Math.hypot(arrived.position.x-notice.approach.x,arrived.position.y-notice.approach.y)<=4,'objective arrow reaches actual notice instead of removed portal');

 // Transport loss AFTER the atomic commit keeps exactly one pending and repeats its original identity.
 dropAfterCommit=true;await page.keyboard.down('ArrowDown');await page.waitForFunction(()=>!!document.querySelector('.harbor-loading button'),undefined,{timeout:6000});await page.keyboard.up('ArrowDown');const committedLost=await head();const pending=await page.evaluate(()=>{const storage=window.alteruLocalStorage;for(let i=0;i<storage.length;i++){const key=storage.key(i)!;if(key.includes('harbor-pending-v2:'))return JSON.parse(storage.getItem(key)!)}return null});assert.equal(pending?.channel,'motion');await page.getByRole('button',{name:locale==='en'?'Reconnect':'重新连接',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.harbor-loading'),undefined,{timeout:15000});await page.waitForTimeout(900);const recovered=await head();assert.equal(recovered.townMinutes,committedLost.townMinutes);assert.deepEqual(recovered.position,committedLost.position);assert.ok(actions.filter(a=>a.action_id===pending.action.action_id).length===2,'same ID replay, no duplicate clock');
 // Offline BEFORE commit expires unverifiable prediction and restores authoritative state; no offline catch-up.
 const offlineBefore=await head();offline=true;await page.keyboard.down('ArrowDown');await page.waitForFunction(()=>!!document.querySelector('.harbor-loading button'),undefined,{timeout:6000});await page.keyboard.up('ArrowDown');await page.waitForTimeout(3200);offline=false;await page.getByRole('button',{name:locale==='en'?'Reconnect':'重新连接',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.harbor-loading'),undefined,{timeout:15000});await page.waitForTimeout(900);const offlineAfter=await head();assert.equal(offlineAfter.townMinutes,offlineBefore.townMinutes);assert.deepEqual(offlineAfter.position,offlineBefore.position);assert.equal(await page.evaluate(()=>{const s=window.alteruLocalStorage;for(let i=0;i<s.length;i++)if(s.key(i)?.includes('harbor-pending-v2:'))return true;return false}),false);
 const expectedNetworkErrors=rejected.filter(r=>r.error==='MOTION_EXPIRED');assert.equal(rejected.length,expectedNetworkErrors.length);assert.equal(expectedNetworkErrors.length,1);
 report.cases.push({width,height,locale,rate,before,after,initial:seed.townMinutes,crossed:{scene:north.scene,minute:north.townMinutes},returned:{scene:returned.scene,minute:returned.townMinutes,position:returned.position},reloadMinute:restored.townMinutes,thresholdMinute:threshold.townMinutes,mapPause:true,simulatedBackgroundPause:true,objectiveReached:{scene:arrived.scene,position:arrived.position,target:notice.approach},compact:{frameDelayMs:Number(process.env.QA_FRAME_MS??0),firstDistance,maxAckBytes:Math.max(...responses.map(r=>r.bytes)),lostResponseSameId:true,lostResponseMode:'HTTP408_after_atomic_commit',offlineExpiredRestored:true},resize:{width:width+40,overflow:resized.overflow,samePlayer:resized.samePlayer},residentAtThreshold:scheduled.events.find(e=>e.id==='market--person-samira'),actions:actions.length,rejected,ordinaryTravelRequests:actions.filter(a=>a.action==='travel').length});console.log('PASS',width,JSON.stringify(report.cases.at(-1)));await context.close();await store.close();
}}finally{writeFileSync(out+`/renderer-report${process.env.QA_REPORT_SUFFIX??''}.json`,JSON.stringify(report,null,2)+'\n');await browser.close()}
assert.equal(report.errors.length,0);assert.equal(report.modelCalls,0);
