/** Explicit QA runner. Private cookie state stays outside this repository. No model calls. */
import assert from 'node:assert/strict';import {readFile,writeFile,mkdir,lstat} from 'node:fs/promises';import {createHash,randomUUID} from 'node:crypto';
import {entityAt,rooms} from '../src/world/data';
import slots from '../src/dynamic-assets/slots.json';
// @ts-expect-error byte contract
import {createHarborDynamicReader} from '../src/dynamic-assets/browser-reader.mjs';
const root=process.env.HARBOR_B_QA_PRIVATE;if(!root||!root.startsWith('/private/tmp/harbor-dynamic-b-'))throw Error('PRIVATE_QA_PATH_REQUIRED');await mkdir(root,{recursive:true,mode:0o700});if((await lstat(root)).mode&0o077)throw Error('PRIVATE_QA_MODE');
const file=root+'/sessions.json',base='https://game.aiwaves.tech/e78df027-7ef4-4d49-82eb-ea91f03d9fb3';
let state:any;try{state=JSON.parse(await readFile(file,'utf8'))}catch(e:any){if(e.code!=='ENOENT')throw e;state={startedAt:Date.now(),players:[{},{}],results:[]}}
const persist=()=>writeFile(file,JSON.stringify(state),{mode:0o600});
async function request(player:any,path:string,body?:any){const r=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:'https://game.aiwaves.tech','X-Harbor-Dynamic-Assets':'1',...(player.cookie?{Cookie:player.cookie}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(30000)});const data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]}}
if(process.argv[2]==='create'){
 for(const player of state.players){if(!player.cookie){const r=await request(player,'/bootstrap',{});assert.equal(r.status,200);player.cookie=r.cookie;player.enrollment='asset-b-qa-'+randomUUID();await persist()};if(!player.id){const r=await request(player,'/sessions',{enrollment_id:player.enrollment,locale:'en'});assert.equal(r.status,200);assert.equal(r.data.version,0);assert.equal(r.data.dynamicAssetRooms,undefined);player.id=r.data.id;player.createdAt=Date.now();await persist()}}
 const enabledAt=Date.now();const document={enabledAt,entries:state.players.map((p:any)=>({owner:p.cookie.split('=')[1].split('.')[0],sessionId:p.id,enrollment:p.enrollment,createdAt:p.createdAt,expiresAt:enabledAt+86400000}))};await writeFile(root+'/asset-qa-allowlist.json',JSON.stringify(document),{mode:0o600});console.log(JSON.stringify({created:2,provisionalOnly:true,activationMustResetEnabledAt:true,startsAt:null,endsAt:null,privateFileReady:true}));
}else if(process.argv[2]==='verify'){
 const player=state.players[0],other=state.players[1];assert.ok(player.id&&other.id);let head=(await request(player,'/sessions/'+player.id)).data;assert.ok(head.dynamicAssetRooms.includes('home'));
 async function action(target:string,action:string){if(!player.pending){player.pending={action_id:randomUUID(),expected_version:head.version,scene:head.scene,position:entityAt(head.scene,target)!.approach,target,action};await persist()};const r=await request(player,'/sessions/'+player.id+'/action',player.pending);assert.equal(r.status,200,JSON.stringify(r.data));player.pending=null;await persist();head=(await request(player,'/sessions/'+player.id)).data}
 async function go(destination:string){const queue=[{scene:head.scene,path:[] as string[]}],seen=new Set([head.scene]);let path:string[]|undefined;while(queue.length){const n=queue.shift()!;if(n.scene===destination){path=n.path;break}for(const e of rooms[n.scene].entities){if(e.kind==='portal'&&e.destination&&!seen.has(e.destination)&&!e.destination.startsWith('workshop-annex-')){seen.add(e.destination);queue.push({scene:e.destination,path:[...n.path,e.id]})}}}assert.ok(path);for(const id of path!)await action(id,'travel')}
 if(!head.known.includes('mara')){await go('station');await action('mara','introduce')};if(!head.flags.includes('key')){await go('station');await action('mara','talk:key')}
 await go('home');if(!head.flags.includes('unpacked'))await action('bed','unpack');
 for(const room of ['home','cafe','garden']){
  if(room==='garden'&&!head.flags.includes('garden-agreed')){if(!head.flags.includes('bridge-seen')){await go('path');await action('bridge','inspect-bridge')}await go('courtyard');if(!head.known.includes('elena'))await action('elena','introduce');if(!head.flags.includes('talk:elena:quiet'))await action('elena','talk:quiet');if(!head.flags.includes('garden-agreed'))await action('elena','talk:hours')}
  await go(room);const prefix='/sessions/'+player.id+'/assets/'+room+'/';const before=head;
  const [a,b]=await Promise.all([request(player,prefix+'prepare',{}),request(player,prefix+'prepare',{})]);assert.equal(a.status,200,JSON.stringify(a.data));assert.equal(b.status,200);assert.equal(a.data.attachment.grantHash,b.data.attachment.grantHash);
  const pack=await request(player,prefix+'package');assert.equal(pack.status,200);assert.deepEqual(pack.data,a.data);const updated=(await request(player,'/sessions/'+player.id)).data;assert.equal(updated.version,before.version);assert.equal(updated.cursor,before.cursor);assert.ok(updated.roomAssetAttachments.some((x:any)=>x.grantHash===a.data.attachment.grantHash));
  assert.equal((await request(other,prefix+'prepare',{})).status,403);assert.equal((await request(other,prefix+'package')).status,403);
  const calls:string[]=[];let offline=false;const reader=await createHarborDynamicReader({attachment:a.data.attachment,wire:a.data.package,baseUrl:()=>base+'/api'+prefix,baseURI:base+'/',fetchImpl:async(url:string,init:any)=>{calls.push(url.split('/').at(-1)!);if(offline)throw Error('QA_TRANSPORT_OUTAGE');return fetch(url,{...init,headers:{...init.headers,Origin:'https://game.aiwaves.tech',Cookie:player.cookie}})}});
  const resolved=await reader.resolve();assert.equal(resolved.remoteAuthorizationConfirmed,true);const hash=createHash('sha256').update(resolved.files[0].bytes).digest('hex');assert.equal(hash,slots.find(s=>s.scene===room)!.imageHash);assert.equal(a.data.package.grant.pins[0].revision,2);assert.deepEqual(calls,['check','manifest','blob','check']);offline=true;const safe=await reader.resolve();assert.equal(safe.mode,'offline-template');assert.deepEqual(safe.files,resolved.files);
  state.results=state.results.filter((r:any)=>r.room!==room);state.results.push({room,grantHash:a.data.attachment.grantHash,packageHash:a.data.attachment.packageHash,imageHash:hash,revision:2,source:'real-remote-inventory',remoteAuthorizationConfirmed:true,exactPairOnOutage:true,wrongOwnerDenied:true,storyVersionUnchanged:true});player.packages??={};player.packages[room]=a.data;await persist();
 }
 console.log(JSON.stringify({verifiedRooms:state.results,platformAccountsVerified:false,modelCalls:0}));
}else throw Error('EXPLICIT_CREATE_OR_VERIFY_REQUIRED');
