import {useState,useEffect} from 'react';import {chooseJourney,type JourneyChoice,loadNoteImage} from '../story/client';import type {Save} from '../story/state';import {rooms,tx,type Locale} from '../world/data';
export function JourneyEntry({choice,locale,onReady}:{choice:JourneyChoice;locale:Locale;onReady:(s:Save)=>void}){
 const [confirm,setConfirm]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 const run=async(option:Parameters<typeof chooseJourney>[1])=>{setBusy(true);setError(false);try{onReady(await chooseJourney(locale,option))}catch{setError(true)}finally{setBusy(false)}};
 return <section className="harbor-journey-choices"><h2>{tx(['选择你的旅程','Choose your journey'],locale)}</h2><p>{tx(choice.browserClaimed?['原旅程已归入账号。登录那个账号即可继续，也可以另开一段只属于这个浏览器的旅程。','Your previous journey belongs to an account now. Sign in to that account to continue, or start a separate journey on this browser.']:['每段旅程会独立保留。','Each journey stays separate.'],locale)}</p>
 {choice.journeys.map(j=><button key={j.id} disabled={busy} onClick={()=>void run({kind:'existing',id:j.id})}>{tx(['继续','Continue'],locale)} · {rooms[j.scene]?tx(rooms[j.scene].title,locale):j.scene}</button>)}
 {choice.legacy.map(j=><article key={j.id}><p>{tx(['这个浏览器还有一段旅程：','A journey on this browser:'],locale)} {rooms[j.scene]?tx(rooms[j.scene].title,locale):j.scene}</p>{confirm===j.id?<><p>{tx(['确认这是你的进度，并把它归入当前账号？其他旅程会保留。','Is this your progress? Add it to this account? Your other journeys will remain.'],locale)}</p><button disabled={busy} onClick={()=>void run({kind:'claim',id:j.id,confirmed:true})}>{tx(['确认归入当前账号','Yes, add to this account'],locale)}</button><button disabled={busy} onClick={()=>setConfirm(null)}>{tx(['取消','Cancel'],locale)}</button></>:<button disabled={busy} onClick={()=>setConfirm(j.id)}>{tx(['查看归入选项','Review adding this journey'],locale)}</button>}</article>)}
 <button disabled={busy} onClick={()=>void run({kind:'new'})}>{tx(['开启独立的新旅程','Start a separate new journey'],locale)}</button>{error&&<p role="alert">{tx(['暂未完成，你的进度仍然保留。','That did not finish. Your progress has been kept.'],locale)}</p>}</section>;
}
export function NoteImage({id,room,alt}:{id:string;room:string;alt:string}){const [url,setUrl]=useState<string>();useEffect(()=>{let live=true,owned:string|undefined;void loadNoteImage(id,room).then(u=>{if(!live)URL.revokeObjectURL(u);else{owned=u;setUrl(u)}}).catch(()=>{});return()=>{live=false;if(owned)URL.revokeObjectURL(owned)}},[id,room]);return url?<img src={url} alt={alt}/>:<span role="status">{alt}</span>}
