/** One bounded mixer. Media is generated by AlterU; no provider URL in runtime. */
export class SummerAudio{
 private context?:AudioContext;
 private master?:GainNode;
 private buffers=new Map<string,AudioBuffer>();
 private active=new Set<{source:AudioBufferSourceNode;gain:GainNode}>();
 private current='';
 private effects=0;
 private effectLoads=new Map<string,Promise<AudioBuffer>>();
 private effectTimes=new Map<string,number>();
 private desired='town-a';
 private muted=false;
 private timer=0;
 private generation=0;
 private next=0;
 constructor(){
  document.addEventListener('visibilitychange',()=>{if(!this.context)return;if(document.hidden)void this.context.suspend();else if(!this.muted)void this.context.resume().catch(()=>{})});
 }
 unlock(){
  if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.master.gain.value=this.muted?0:.22;this.master.connect(this.context.destination)}
  if(!this.muted)void this.context.resume().then(()=>this.change()).catch(()=>{});
 }
 setMuted(muted:boolean){this.muted=muted;if(this.master&&this.context){this.master.gain.cancelScheduledValues(this.context.currentTime);this.master.gain.setTargetAtTime(muted?0:.22,this.context.currentTime,.08)}if(!muted)this.unlock()}
 setArea(area:string){this.desired=area==='practice'?'practice':area==='coast'||area==='harbor'?'coast':area==='hill'?'hill':'town-a';if(this.context)void this.change()}
 effect(key:'step'|'door'|'hit'|'progress'){
  const context=this.context;if(!context||this.muted||document.hidden||this.effects>=4)return;
  const now=performance.now();if(now-(this.effectTimes.get(key)??-1000)<(key==='step'?230:90))return;this.effectTimes.set(key,now);
  let load=this.effectLoads.get(key);if(!load){load=fetch('./audio/'+key+'.mp3').then(r=>{if(!r.ok)throw Error('SFX_LOAD');return r.arrayBuffer()}).then(b=>context.decodeAudioData(b));this.effectLoads.set(key,load)}
  void load.then(buffer=>{if(this.effects>=4||this.muted||document.hidden)return;const voice=context.createBufferSource(),gain=context.createGain();voice.buffer=buffer;gain.gain.value=key==='step'?.22:key==='hit'?.45:.7;voice.connect(gain);gain.connect(this.master!);this.effects++;voice.onended=()=>{this.effects--;voice.disconnect();gain.disconnect()};voice.start()}).catch(()=>this.effectLoads.delete(key));
 }
 private async change(){
  const context=this.context!;if(!context||this.current===this.desired)return;
  const key=this.desired,token=++this.generation;this.current=key;
  try{
   let buffer=this.buffers.get(key);
   if(!buffer){const response=await fetch('./audio/'+key+'.mp3');if(!response.ok)throw Error('AUDIO_LOAD');buffer=await context.decodeAudioData(await response.arrayBuffer());this.buffers.set(key,buffer)}
   if(token!==this.generation)return;
   clearTimeout(this.timer);
   for(const voice of this.active){voice.gain.gain.cancelScheduledValues(context.currentTime);voice.gain.gain.setTargetAtTime(0,context.currentTime,.2);voice.source.stop(context.currentTime+.8)}
   this.next=context.currentTime+.02;
   const schedule=()=>{
    if(token!==this.generation)return;
    if(this.next-context.currentTime<3){
     const source=context.createBufferSource(),gain=context.createGain();source.buffer=buffer!;source.connect(gain);gain.connect(this.master!);
     const start=Math.max(context.currentTime,this.next),duration=buffer!.duration,overlap=Math.min(2,duration/5);
     gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(1,start+overlap);
     gain.gain.setValueAtTime(1,start+duration-overlap);gain.gain.linearRampToValueAtTime(0,start+duration);
     const voice={source,gain};this.active.add(voice);source.onended=()=>{source.disconnect();gain.disconnect();this.active.delete(voice)};
     source.start(start);this.next=start+duration-overlap;
    }
    this.timer=window.setTimeout(schedule,1000);
   };schedule();
  }catch{if(token===this.generation)this.current=''}
 }
}
export const summerAudio=new SummerAudio();
