import {cartridge} from './story/cartridge';
import {description} from './story/descriptions';
import {BayMap} from './ui/Map';
import {nextObjectiveEntrance} from './story/navigation';
import {summerAudio} from './audio';
import {Fishing} from './ui/Fishing';
import {useEffect,useRef,useState} from 'react';import {createRoot} from 'react-dom/client';
import {View,type WorldHandle} from './world/View';import {rooms,people,tx,entityLabel,type Locale,type Entity,type Words} from './world/data';import {has,objective,availableTopics,items,type Save} from './story/state';import {connect,send,checkpoint,readUsage,ensureNoteImage,noteImageUrl,type NoteMedia,type Usage} from './story/client';import {Icon} from './ui/icons';import {Joystick} from './ui/Joystick';import {Combat} from './ui/Combat';import './style.css';
const actionLabels:Record<string,Words>={'unpack':['放下行李','Put your bag down'],'rest':['歇一会儿','Rest a while'],'repair-terrace':['检查灯的接线','Check the lantern wiring'],'inspect-bridge':['查看损坏的地方','Inspect the damage'],'repair-bridge':['用工具和两块木板修桥','Repair with tools and two planks'],'gather-wood':['拾取结实的木板','Gather sound timber'],'open-route':['安排海岸通行','Set up coast access'],'read-market':['读集市告示','Read the market notice'],'open-market':['告诉大家路线准备好了','Share the good news'],'assemble-map':['拼合旧路线图','Put the route map together'],'inspect-garden':['读门上的便条','Read the note'],'notes-observe':['仔细查看','Take a close look'],'read-weather':['翻看记录本','Read the logbook']};
const errors:Record<string,Words>={NOTES_SOURCE_NEEDED:['先亲眼查看小桥，并向琼借到工具，再聊这条线索。','Inspect the bridge and borrow June’s tools before following this lead.'],NOTES_READ_FIRST:['先读完上一处的两条观察，线索才能接着走。','Read both observations in the last place before following the next lead.'],NOTES_COMPLETE:['这次的两处线索已经全部找到。随时可以回去翻看。','You have found both places in this trail. You can revisit your notes any time.'],MODEL_DRAFT_INVALID:['这个线索还没能指向可靠的去处。你仍可继续在小镇探索，稍后再问。','This lead has not pointed to a reliable place yet. Keep exploring town and ask again later.'],NOTES_REVIEW_REJECTED:['琼还需要核对这条线索。先逛逛小镇，稍后再问。','June still needs to check this lead. Explore town and ask again later.'],AI_ROOM_DAILY_LIMIT:['今天已经问过不少新线索了。先去看看已经发现的地方吧。','You have asked for today’s new leads. Visit the places you have already discovered.'],AI_DIALOGUE_DAILY_LIMIT:['今天的自由提问次数用完了。仍可以继续探索和已有话题，菜单里可查看恢复时间。','You have used today’s free questions. Keep exploring and using the existing topics; the menu shows when questions reset.'],AI_COOLDOWN:['先歇一小会儿再提问吧。问题已经保留。','Please wait a moment before asking again. Your question is saved.'],AI_REQUEST_IN_PROGRESS:['上一句还在等待答复，请稍等。','Your previous question is still waiting for a reply.'],MODEL_CALL_PENDING_OR_INTERRUPTED:['正在确认上一句的结果。请重新读取进度后继续，避免重复提问。','Your previous reply is still being checked. Reload progress before trying again.'],DIALOGUE_INVALID:['这次没能得到清楚的答复。可以换一种问法，或选择现有话题。','That reply was not clear enough. Try another question, or choose a topic.'],MODEL_CALL_FAILED:['暂时没能得到答复。你的问题还在，可以再试。','No reply arrived this time. Your question is still here if you want to retry.'],MODEL_HTTP_ERROR:['暂时没能得到答复。稍后再试，现有话题仍可继续。','A reply is unavailable just now. Try later, or keep using the available topics.'],KEY_NEEDED:['先向玛拉领取钥匙。','Ask Mara for your key first.'],SETTLE_FIRST:['先把行李放到租屋里，再出远门。','Put your bag down in your room before heading farther out.'],TOO_FAR:['再靠近一点。','Move a little closer.'],NOT_ENOUGH_CASH:['现金不够，可以先去接免费饮用水。','Not enough cash. The drinking water is free.'],BRIDGE_REQUIREMENTS:['需要借来的工具和两块结实的木板。','You need borrowed tools and two sound planks.'],REST_NEEDED:['有点累了，回家免费休息一下。','You’re tired. Rest at home for free.'],ROUTE_NOT_READY:['先修好桥、找到公共绕行路，或取得住户的借道同意。','Repair the bridge, find the public trail, or agree access with the resident first.'],ALREADY_DONE:['这件事已经完成，记录里可以回看。','That is already done. You can revisit it in your journal.'],TOPIC_UNAVAILABLE:['这个话题已经聊过了，可以查看谈话记录。','You’ve already covered that. Read it in your conversation history.'],VERSION_CONFLICT:['进度已更新，正在重新读取。','Your progress changed. Reloading it now.'],CHALLENGE_ACTIVE:['先完成或退出当前练习。','Finish or leave the current practice first.']};
function localeInitial():Locale{const choice=window.alteruLocalStorage.getItem('harbor-locale');return choice==='en'||choice==='zh'?choice:navigator.language.toLowerCase().startsWith('zh')?'zh':'en'}
function App(){
 const [locale,setLocale]=useState<Locale>(localeInitial),[save,setSave]=useState<Save|null>(null),[near,setNear]=useState<Entity|null>(null),[panel,setPanel]=useState<'none'|'entity'|'bag'|'map'|'menu'|'journal'>('none'),[target,setTarget]=useState<Entity|null>(null),[message,setMessage]=useState<Words|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<Words|null>(null),[choicesReady,setChoicesReady]=useState(true),[portrait,setPortrait]=useState<string|null>(null),[muted,setMuted]=useState(()=>window.alteruLocalStorage.getItem('harbor-muted')==='1');
 const [repair,setRepair]=useState([0,0,0]),[mapPieces,setMapPieces]=useState([2,0,3,1]),[selectedPiece,setSelectedPiece]=useState<number|null>(null),[free,setFree]=useState('');
 const [introPage,setIntroPage]=useState(0),[introClosed,setIntroClosed]=useState(false);
 const [worldReady,setWorldReady]=useState(false);
 const [noteMedia,setNoteMedia]=useState<NoteMedia|null>(null);
 useEffect(()=>{setNoteMedia(null);if(!save?.scene.startsWith('workshop-annex-'))return;let live=true;setNoteMedia({status:'preparing',room:save.scene});void ensureNoteImage(save.id,save.scene).then(r=>{if(live)setNoteMedia(r)}).catch(()=>{if(live)setNoteMedia({status:'interrupted',room:save.scene})});return()=>{live=false}},[save?.id,save?.scene]);
 const [usage,setUsage]=useState<Usage|null>(null);
 useEffect(()=>{if(panel==='menu')void readUsage().then(setUsage).catch(()=>setUsage(null))},[panel]);
 useEffect(()=>{setFree(target?.person?window.alteruLocalStorage.getItem('harbor-draft-'+target.person)??'':'')},[target?.person]);
 const handle=useRef<WorldHandle|null>(null),position=useRef({x:0,y:0}),latest=useRef({save,busy,panel,worldReady});latest.current={save,busy,panel,worldReady};
 useEffect(()=>{summerAudio.setMuted(muted)},[muted]);
 useEffect(()=>{if(save)summerAudio.setArea(save.activeChallenge&&['sparring','footwork','endurance'].includes(save.activeChallenge.kind)?'practice':rooms[save.scene].area)},[save?.scene,save?.activeChallenge?.kind]);
 useEffect(()=>{const play=()=>summerAudio.unlock();window.addEventListener('pointerdown',play,{once:true});window.addEventListener('keydown',play,{once:true});return()=>{window.removeEventListener('pointerdown',play);window.removeEventListener('keydown',play)}},[]);
 const load=()=>{setBusy(true);setError(null);void connect(locale).then(s=>{setSave(s);position.current=s.position}).catch(()=>setError(['暂时没能读到进度，请重试。','Your progress could not be loaded. Please retry.'])).finally(()=>setBusy(false))};
 useEffect(()=>{load();const t=setInterval(()=>{const {save,busy,panel,worldReady}=latest.current;if(save&&worldReady&&!busy&&panel==='none')void checkpoint(save,position.current).catch(()=>{})},5000);return()=>clearInterval(t)},[]);
 useEffect(()=>{
  if(!message){setChoicesReady(true);return}
  setChoicesReady(false);
  const length=tx(message,locale).length;
  const delay=Math.min(4200,Math.max(1000,length*(locale==='zh'?42:18)));
  const timer=setTimeout(()=>setChoicesReady(true),delay);
  return()=>clearTimeout(timer);
 },[message,locale]);
 const act=async(action:string,e:Entity|null=target,payload?:unknown,targetId?:string)=>{
  if(!save||busy)return;setBusy(true);setError(null);
  try{const r=await send(save,{action_id:crypto.randomUUID(),expected_version:save.version,scene:save.scene,position:position.current,target:targetId??e?.id??'',action,payload});if(r.head.scene!==save.scene){setWorldReady(false);summerAudio.effect('door')}else if(r.head.flags.length>save.flags.length)summerAudio.effect('progress');setSave(r.head);position.current=r.head.position;
   if(action==='travel'||action==='travel-map'){setPanel('none');setTarget(null);setMessage(null);setNear(null)}else{setMessage(r.text);if(action==='introduce'||action.startsWith('talk:'))setPanel('entity')}
   return true;
  }catch(err:any){setError(errors[err.message]??['暂时没能完成，请重试读取进度。','That could not be completed. Reload your progress to retry.']);if(err.message==='VERSION_CONFLICT')load();return false}finally{setBusy(false)}
 };
 const interact=()=>{if(!near||!save||busy)return;setTarget(near);setPanel('entity');setError(null);setMessage(null);if(near.person&&!save.known.includes(near.person))void act('introduce',near)};
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.key.toLowerCase()==='e'&&panel==='none'&&!save?.activeChallenge){e.preventDefault();interact()}if(e.key==='Escape'&&!save?.activeChallenge){setPanel('none');setPortrait(null)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[near,save,busy,panel]);
 const close=()=>{setPanel('none');setMessage(null);setError(null);setTarget(null)};
 const startChallenge=(kind:string)=>void act('challenge-start:'+kind);
 const choose=(id:string)=>{if(id==='repair-terrace')startChallenge('repair');else if(id==='assemble-map')startChallenge('map');else void act(id)};
 const ask=async()=>{if(!free.trim()||!target||!save||busy)return;const question=free.trim();const done=await act('ask',target,{text:question,locale});if(done){setFree('');if(target.person)window.alteruLocalStorage.removeItem('harbor-draft-'+target.person)}};
 if(!save)return <main className="harbor-entry"><img className="harbor-entry__art" src="./poster.png" alt=""/><small>A SUMMER IN HARBOR</small><h1>{tx(['海湾新生活','A Summer in Harbor'],locale)}</h1><p>{tx(['一只旅行包。一个陌生小镇。一个属于你的夏天。','One bag. An unfamiliar town. A summer of your own.'],locale)}</p><p>{busy?tx(['正在抵达…','Arriving…'],locale):error&&tx(error,locale)}</p>{!busy&&<button onClick={load}>{tx(['重新连接','Reconnect'],locale)}</button>}</main>;
 const fieldRoom=save.fieldNotes?.rooms.find(r=>r.id===save.scene);const fieldObservation=fieldRoom?.observations[['observation-a','observation-b'].indexOf(target?.id??'')];
 const fieldTitles=Object.fromEntries((save.fieldNotes?.rooms??[]).map(r=>[r.id,r.title]));
 const showIntro=save.version===0&&!introClosed;
 const who=target?.person,knownName=who?tx(save.known.includes(who)?people[who].name:people[who].unknown,locale):target?tx(fieldTitles[target.destination??'']??entityLabel(target,save.flags),locale):'';const challenge=save.activeChallenge;
 const panelTitle={none:'',entity:knownName,bag:tx(['行囊','Your bag'],locale),map:tx(['海湾地图','Around the bay'],locale),menu:tx(['歇一会儿','Take a moment'],locale),journal:tx(['旅行手记','Your journal'],locale)}[panel];
 return <main className="harbor-app"><header className="harbor-header"><div className="harbor-heading"><small>{tx(['第一个夏天','YOUR FIRST SUMMER'],locale)}</small><h1>{tx(['海湾新生活','A Summer in Harbor'],locale)}</h1></div><nav>{(['map','bag','menu'] as const).map(p=><button key={p} aria-label={tx(p==='map'?['地图','Map']:p==='bag'?['行囊','Bag']:['菜单','Menu'],locale)} onClick={()=>setPanel(p)}><Icon name={p}/></button>)}<button aria-label={tx(muted?['开启声音','Enable sound']:['关闭声音','Mute'],locale)} onClick={()=>{setMuted(!muted);window.alteruLocalStorage.setItem('harbor-muted',muted?'0':'1')}}><Icon name={muted?'mute':'sound'}/></button></nav></header>
 <div className="harbor-location"><span>{tx(fieldTitles[save.scene]??rooms[save.scene].title,locale)}</span><small>{tx(rooms[save.scene].outdoor?['室外','OUTDOORS']:['室内','INDOORS'],locale)}</small></div><View titles={fieldTitles} flags={[...save.flags,...(save.fieldNotes?.rooms??[]).map(r=>r.id)]} scene={save.scene} start={save.position} locale={locale} paused={panel!=='none'||busy||!!challenge||showIntro} onNear={setNear} onRenderReady={setWorldReady} onPosition={p=>position.current=p} handle={handle}/><aside className="harbor-objective"><div><span>{tx(['眼前的事','A place to start'],locale)}</span>{tx(objective(save),locale)}</div>{nextObjectiveEntrance(save)&&<button aria-label={tx(['带我到下一处入口','Walk toward the next stop'],locale)} onClick={()=>{const next=nextObjectiveEntrance(save);if(next)handle.current?.approach(next)}}><Icon name="arrow"/></button>}</aside>
 {!challenge&&!showIntro&&panel==='none'&&<div className="harbor-controls"><Joystick label={tx(['移动','Move'],locale)} onMove={(x,y)=>handle.current?.move(x,y)}/><button className={'harbor-action '+(near?'is-ready':'')} disabled={!near||busy} onPointerDown={interact}><span>{near?tx(near.person?(save.known.includes(near.person)?people[near.person].name:people[near.person].unknown):fieldTitles[near.destination??'']??entityLabel(near,save.flags),locale):tx(['四处走走','Take a look around'],locale)}</span><strong>{tx(near?.kind==='portal'?['前往','Go']:near?['互动','Interact']:['靠近后互动','Move closer'],locale)}</strong>{near&&<Icon name={near.kind==='person'?'chat':'arrow'}/>}</button></div>}
 {panel!=='none'&&!challenge&&<div className="harbor-backdrop" onClick={close}><section className={'harbor-panel harbor-panel--'+panel} onClick={e=>e.stopPropagation()} aria-label={panelTitle}><header><div><small>{panel==='entity'?tx(fieldTitles[save.scene]??rooms[save.scene].title,locale):'A SUMMER IN HARBOR'}</small><h2>{panelTitle}</h2></div><button aria-label={tx(['关闭','Close'],locale)} onClick={close}><Icon name="close"/></button></header>
 <div className="harbor-panel__body">
 {panel==='entity'&&target&&<>{who&&<button className="harbor-portrait" aria-label={tx(['放大人物肖像','Enlarge portrait'],locale)} onClick={()=>setPortrait(who)}><img src={`./art/${who}-root-v2.png`} alt={knownName}/></button>}{message?<p className="harbor-dialogue" onClick={()=>setChoicesReady(true)}>{tx(message,locale)}</p>:<p className="harbor-dialogue">{tx(fieldObservation?.read?fieldObservation.text:fieldRoom?.detail??description(save,target),locale)}</p>}
 {fieldRoom&&noteMedia&&<div className="harbor-note-image">{noteMedia.status==='ready'?<button onClick={()=>setPortrait('note:'+save.scene)}><img src={noteImageUrl(save.id,save.scene)} alt={tx(fieldRoom.title,locale)}/><span>{tx(['放大查看细节','View the details'],locale)}</span></button>:<p>{tx(noteMedia.status==='interrupted'||noteMedia.status==='failed'?['细节图片暂时未能显现，不影响继续查看线索。','The detail picture is unavailable for now. You can keep reading the clues.']:['眼前的细节正在慢慢显现，可以先查看线索。','The details are taking shape. You can read the clues now.'],locale)}</p>}</div>}{busy&&<p role="status">{tx(['稍等片刻，正在理清这条线索…','One moment, following the thread…'],locale)}</p>}{choicesReady&&!busy&&<div className="harbor-choices">{target.kind==='portal'?<button className="harbor-primary" onClick={()=>void act('travel')}>{tx(['前往','Go to'],locale)} {tx(fieldTitles[target.destination??'']??entityLabel(target,save.flags),locale)}<Icon name="arrow"/></button>:who?<>{availableTopics(save,who).map(t=><button key={t.id} onClick={()=>void act('talk:'+t.id)}>{tx(t.label,locale)}<Icon name="arrow"/></button>)}{who==='june'&&has(save,'bridge-seen')&&save.items.toolkit&&(save.fieldNotes?.depth??0)<2&&<button onClick={()=>void act('notes-generate')}>{tx(['顺着已有线索，再找一个地方看看','Follow these clues to another place'],locale)}</button>}{who==='idris'&&<><button className="harbor-primary" onClick={()=>startChallenge('sparring')}>{tx(['开始友好切磋','Start a friendly spar'],locale)}</button><button onClick={()=>startChallenge('footwork')}>{tx(['开始走位练习','Start footwork practice'],locale)}</button><button onClick={()=>startChallenge('endurance')}>{tx(['练习坚持二十秒','Try a twenty-second round'],locale)}</button></>}{who==='ruth'&&<button onClick={()=>startChallenge('fishing')}>{tx(['拿起鱼竿','Pick up the rod'],locale)}</button>}</>:(target.actions??[]).filter(id=>(id!=='notes-observe'||!fieldObservation?.read)&&(id!=='open-market'||has(save,'market-known')&&has(save,'route-open'))&&(id!=='repair-bridge'||has(save,'bridge-seen'))&&(id==='rest'||!has(save,id)&&!(id==='unpack'&&has(save,'unpacked'))&&!(id==='repair-terrace'&&has(save,'terrace-fixed'))&&!(id==='assemble-map'&&has(save,'alternative-route')))).map(id=><button key={id} onClick={()=>choose(id)}>{tx(id==='notes-observe'&&fieldObservation?fieldObservation.label:actionLabels[id]??[id,id],locale)}<Icon name="arrow"/></button>)}</div>}
 {who&&choicesReady&&<><form className="harbor-input" onSubmit={e=>{e.preventDefault();ask()}}><input aria-label={tx(['自由询问','Ask a question'],locale)} placeholder={tx(['也可以自己问一句…','Ask in your own words…'],locale)} value={free} disabled={busy} onChange={e=>{setFree(e.target.value);if(who)window.alteruLocalStorage.setItem('harbor-draft-'+who,e.target.value)}} maxLength={400}/><button disabled={!free.trim()||busy} type="submit" aria-label={tx(['发送','Send'],locale)}><Icon name="arrow"/></button></form><button className="harbor-link" onClick={()=>setPanel('journal')}>{tx(['查看谈话记录','Conversation history'],locale)}</button></>}</>}
 {panel==='bag'&&<><div className="harbor-stats"><span>{tx(['体力','Energy'],locale)} {save.energy}/100</span><span>${save.cash}</span><span>{tx(['口碑','Reputation'],locale)} {save.standing}</span></div>{(['tools','objects','notes'] as const).map((kind,i)=><section key={kind}><h3>{tx([['工具','物件','笔记'][i],['Tools','Objects','Notes'][i]],locale)}</h3>{Object.entries(save.items).filter(([id,n])=>n>0&&items[id]?.kind===kind).map(([id,n])=><article className="harbor-item" key={id}><strong>{tx(items[id].name,locale)} {n>1?'×'+n:''}</strong><p>{tx(items[id].description,locale)}</p>{['photo','route'].includes(id)&&<button onClick={()=>setPortrait('asset:'+(id==='photo'?'bridge-photo':'trail-map-closeup'))}>{tx(['放大查看','View closely'],locale)}</button>}</article>)}</section>)}{!Object.keys(save.items).length&&<p>{tx(['暂时只有随身行李。先找到住处吧。','Just your luggage for now. Let’s find your room.'],locale)}</p>}</>}
 {panel==='journal'&&<>{save.history.length?save.history.slice().reverse().map(h=><article className="harbor-item" key={h.id}><small>{h.person?tx(people[h.person].name,locale):tx(['旅途中的事','Along the way'],locale)}</small>{h.question&&<p className="harbor-question">{h.question}</p>}<p>{tx(h.text,locale)}</p></article>):<p>{tx(['旅程刚刚开始。','Your summer has just begun.'],locale)}</p>}</>}
 {panel==='map'&&<BayMap save={save} locale={locale} busy={busy} onTravel={id=>void act('travel-map',null,undefined,id)}/>}
 {panel==='menu'&&<div className="harbor-choices">{usage&&<p className="harbor-usage">{tx(['今天还可以自由提问 '+usage.dialogue.remaining+' 次。','You have '+usage.dialogue.remaining+' free questions left today.'],locale)}{usage.room&&<><br/>{tx(['今天还可以追寻 '+usage.room.remaining+' 条新线索。','You can follow '+usage.room.remaining+' new leads today.'],locale)}</>}<br/><small>{tx(['恢复时间：','Resets: '],locale)}{new Date(usage.resetAt).toLocaleString(locale==='zh'?'zh-CN':'en-US')}</small></p>}<button onClick={()=>setPanel('journal')}>{tx(['旅行手记','Your journal'],locale)}<Icon name="arrow"/></button><button onClick={()=>{const l=locale==='en'?'zh':'en';setLocale(l);window.alteruLocalStorage.setItem('harbor-locale',l)}}>English / 中文 · {locale.toUpperCase()}</button><button onClick={()=>{setMuted(!muted);window.alteruLocalStorage.setItem('harbor-muted',muted?'0':'1')}}>{tx(muted?['开启声音','Enable sound']:['关闭声音','Mute'],locale)}</button><button onClick={()=>{close();load()}}>{tx(['重新读取进度','Reload progress'],locale)}</button><p>{tx(['移动：方向键 / WASD。互动：E。切磋：J 出手，K 闪避。','Move: arrows / WASD. Interact: E. Practice: J to strike, K to dodge.'],locale)}</p></div>}
 {busy&&<p className="harbor-status" role="status">{tx(['稍等一下…','One moment…'],locale)}</p>}{error&&<p className="harbor-error" role="alert">{tx(error,locale)}</p>}</div></section></div>}
 {showIntro&&<div className="harbor-backdrop"><section className="harbor-panel harbor-opening"><header><div><small>{tx(['序章 · 刚刚抵达','PROLOGUE · JUST ARRIVED'],locale)}</small><h2>{tx(introPage===0?['这一个夏天，慢一点','A slower kind of summer']:['先找到落脚的地方','First, find your room'],locale)}</h2></div></header><div className="harbor-panel__body"><p>{cartridge(locale).opening.blocks[introPage].text}</p><button className="harbor-primary" onClick={()=>introPage===0?setIntroPage(1):setIntroClosed(true)}>{tx(introPage===0?['继续','Continue']:['走过去打个招呼','Go and say hello'],locale)}<Icon name="arrow"/></button></div></section></div>}
 {challenge&&<div className="harbor-backdrop"><div className="harbor-challenge">{['sparring','footwork','endurance'].includes(challenge.kind)?<Combat key={challenge.id} kind={challenge.kind} locale={locale} onFinish={runs=>void act('challenge-finish',null,{runs},challenge.id)} onLeave={()=>void act('challenge-finish',null,{withdraw:true},challenge.id)}/>:challenge.kind==='fishing'?<Fishing key={challenge.id} locale={locale} onFinish={fishing=>void act('challenge-finish',null,{fishing},challenge.id)} onLeave={()=>void act('challenge-finish',null,{withdraw:true},challenge.id)}/>:<section className="harbor-panel"><header><h2>{tx(challenge.kind==='repair'?['让露台亮起来','Light up the terrace']:challenge.kind==='map'?['连接旧路线','Join the old route']:['码头垂钓','Fishing at the pier'],locale)}</h2><button onClick={()=>void act('challenge-finish',null,{withdraw:true},challenge.id)}>{tx(['退出','Leave'],locale)}</button></header><div className="harbor-panel__body">{challenge.kind==='repair'?<><p>{tx(['接头旁的刻痕提示顺序：一短、三短、两短。点选接头调整位置。','Marks beside the sockets show the order: one notch, three, then two. Tap a connector to adjust it.'],locale)}</p><img className="harbor-repair-photo" src="./art/repair-closeup-dark.png" alt={tx(['灯的三个接头','The lantern’s three connectors'],locale)}/><div className="harbor-repair">{repair.map((n,i)=><button key={i} onClick={()=>setRepair(repair.map((v,j)=>i===j?(v+1)%4:v))} aria-label={tx(['转动接头','Turn connector'],locale)+' '+(i+1)}><svg viewBox="0 0 60 60" aria-hidden="true"><circle cx="30" cy="30" r="23"/><path d="M30 30V11" transform={`rotate(${n*90} 30 30)`}/></svg><span>{n||'—'}</span></button>)}</div><button className="harbor-primary" disabled={JSON.stringify(repair)!=='[1,3,2]'||busy} onClick={()=>void act('challenge-finish',null,{solution:repair},challenge.id)}>{tx(['接通灯','Connect the lantern'],locale)}</button></>:challenge.kind==='map'?<><p>{tx(['从山坡到海边，先点一块，再点另一块交换位置。','From the hill to the sea. Tap two pieces to swap them.'],locale)}</p><div className="harbor-puzzle">{mapPieces.map((n,i)=><button aria-label={tx(['选择地图碎片','Select map piece'],locale)+' '+(i+1)} style={{backgroundImage:'url(./art/trail-map-closeup.png)',backgroundPosition:`${n%2*100}% ${Math.floor(n/2)*100}%`}} className={i===selectedPiece?'is-selected':''} key={i} onClick={()=>{if(selectedPiece===null)setSelectedPiece(i);else{const p=[...mapPieces];[p[i],p[selectedPiece]]=[p[selectedPiece],p[i]];setMapPieces(p);setSelectedPiece(null)}}}><span>{tx([['山坡','转弯','小桥','海岸'][n],['Hill','Bend','Bridge','Coast'][n]],locale)}</span></button>)}</div><button className="harbor-primary" disabled={JSON.stringify(mapPieces)!=='[0,1,2,3]'||busy} onClick={()=>void act('challenge-finish',null,{solution:mapPieces},challenge.id)}>{tx(['收好路线图','Keep the map'],locale)}</button></>:<p>{tx(['这项活动暂时无法打开，请返回后再试。','This activity could not open. Go back and try again.'],locale)}</p>}{error&&<p className="harbor-error">{tx(error,locale)}</p>}</div></section>}</div></div>}
 {portrait&&<div className="harbor-backdrop harbor-portrait-full" onClick={()=>setPortrait(null)}><button aria-label={tx(['关闭放大图','Close enlarged portrait'],locale)}><Icon name="close"/></button><img src={portrait.startsWith('note:')?noteImageUrl(save.id,portrait.slice(5)):portrait.startsWith('asset:')?`./art/${portrait.slice(6)}.png`:`./art/${portrait}-root-v2.png`} alt={portrait.startsWith('asset:')||portrait.startsWith('note:')?tx(['资料特写','Document detail'],locale):tx(people[portrait].name,locale)}/></div>}
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
